### ISSUE TITLE
Json Query-All fails on MacOS 

### ISSUE THREAD

**Issue by jeff-hykin** [NixOS/nixpkgs#101094]
**Describe the bug**
Running `nix-env -qa --json` fails on MacOS for at least some commits

**To Reproduce**

```
# this fails
nix-env -qa --json -f https://github.com/NixOS/nixpkgs-channels/archive/e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz > ~/testJson.json

# this succeeds (different hash)
nix-env -qa --json -f https://github.com/NixOS/nixpkgs-channels/archive/8414d8386b9a6b855b291fb3f01a4e3b04c08bbb.tar.gz > ~/testJson.json           
```
run `nix-env -qa --json`

**Expected behavior**
No error

**Screenshots**
![Screen Shot 2020-10-19 at 3 01 09 PM](https://user-images.githubusercontent.com/17692058/96505646-0cea5480-121c-11eb-9fc7-7bb6cfd77a9c.png)
```
error: while evaluating 'assertValidity' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/stdenv/generic/check-meta.nix:247:20, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/stdenv/generic/make-derivation.nix:278:18:
while evaluating 'checkValidity' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/stdenv/generic/check-meta.nix:228:19, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/stdenv/generic/check-meta.nix:248:18:
while evaluating anonymous function at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/stdenv/generic/check-meta.nix:41:56, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/stdenv/generic/check-meta.nix:231:13:
while evaluating 'toList' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/lists.nix:283:12, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/stdenv/generic/check-meta.nix:42:71:
while evaluating the attribute 'meta.license' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/os-specific/linux/bcc/default.nix:71:5:
while evaluating the attribute 'linux_4_4' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/top-level/all-packages.nix:16727:3:
while evaluating 'callPackageWith' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:117:35, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/top-level/all-packages.nix:16727:15:
while evaluating 'makeOverridable' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:67:24, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:121:8:
while evaluating anonymous function at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/os-specific/linux/kernel/linux-4.4.nix:1:1, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:69:16:
while evaluating 'buildLinux' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/top-level/all-packages.nix:17107:16, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/os-specific/linux/kernel/linux-4.4.nix:3:1:
while evaluating 'callPackageWith' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:117:35, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/top-level/all-packages.nix:17107:23:
while evaluating 'makeOverridable' at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:67:24, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:121:8:
while evaluating anonymous function at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/os-specific/linux/kernel/generic.nix:1:1, called from /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/lib/customisation.nix:69:16:
assertion (stdenv).isLinux failed at /nix/store/01xs0fxs60lm7gwm83n0vkgbyv2ikf48-e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz/pkgs/os-specific/linux/kernel/generic.nix:56:1
```

**Additional context**
- Adding the keep-going option `-k` doesn't help

**Notify maintainers**
@vcunat  I'm not sure who maintains `nix-env` 

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(jeffhykin): `""`
 - channels(root): `"nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
     # unknown
# a list of nixos modules affected by the problem
module:
     # unknown
```

**Comment by jeff-hykin** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/68206

**Comment by marsam** [comment]
It's already fixed in unstable and 20.09. The error mentioned it's because you are pointing to the reprecated repository `nixpkgs-channels` https://github.com/NixOS/nixpkgs/issues/99257

**Comment by jeff-hykin** [comment]
Thanks @marsam, what's the alternative URL?

**Comment by vcunat** [comment]
The main repo contains the same branches, only (sometimes) differently named, as explained in the title post of that issue.

**Comment by jeff-hykin** [comment]
Okay @vcunat , I read the Issue and the related discourse thread, but I'm still not sure what you mean.

Changing the `-f` url to (what I believe is) the updated format still fails with the same error
```
nix-env -qa --json -f https://github.com/NixOS/nixpkgs/archive/e005a487992c6ebf6f2ae2d22f1770f3ed2952cf.tar.gz > ~/Desktop/testJson.json 
```

**Comment by vcunat** [comment]
Well... a misunderstanding of some kind.

It doesn't matter how you get the commit.  If it's the same commit, so you'll still get the same files and the same error.  It's an old commit (I see author and commit dates from April).  And yes, the expressions in that commit were apparently broken &ndash; but they were fixed later so I can't see what else to do about it here.

**Comment by jeff-hykin** [comment]
I'm a bit confused at what's going on general.

If 
- every package was represented by a json file (just using a format I'm more familiar with)
- and there was cli tool that downloaded the .tar.gz and extracted those package-json files (different packages for different queries)
- if one package was malformed (corrupted json) 

Couldn't the cli tool still get the info for all the packages that didn't have a problem?

Wouldn't the corrupt package infor be corrupt for everyone?


I don't understand how serialized package information could be parsed for one OS but not another OS

**Comment by vcunat** [comment]
The information differs per platform; for example, the trace comes through a package for Linux kernel which isn't available (`-qa`) for darwin.  And the information isn't "stored"... you execute the *.nix files with some settings (a Turing-complete language) and generate JSON from the resulting `*.drv` files (essentially).

> Couldn't the cli tool still get the info for all the packages that didn't have a problem?

That actually might be a bug in the `--json` mode, at a quick look at least.  Without `--json` the packages with assertions and throws are intentionally skipped.  The tool lives in https://github.com/nixos/nix

**Comment by jeff-hykin** [comment]
Okay that information helps me get a better understanding, I'm still confused on a few things though

> The information differs per platform

The package name/version/available-platforms is different on different platforms? I don't quite follow your trace example. If nix-env or the nix interpreter using a substitute trace package for darwin, can't I just point nix-env to the newest/fixed substitute package while it parses the packages available in the `-f` commit? 


> information isn't "stored"... you execute the *.nix files

Okay, but what could they possibly need to execute to tell me their package name, version, description, and available platforms? That should just be static information since it doesn't change with platform.

> generate JSON from the resulting *.drv files (essentially).

So the entire .drv has to be built just to get the package name?

**Comment by jeff-hykin** [comment]
@vcunat 

Since it's only the json option that fails, and all I need right now is the pname of the package, is there some other way I can get the pname? (A way without the --json option)

**Comment by vcunat** [comment]
> The package name/version/available-platforms/description is different on different platforms? I don't quite follow your trace example. If nix-env or the nix interpreter depends on a substitute trace package for darwin, can't I just point nix-env to the newest/fixed substitute package while it parses the packages available in the `-f` commit?

Depends, technically it certainly can differ.  And we do have cases like
```nix
{
  qt5 =        if stdenv.hostPlatform.isDarwin then qt512 else qt515;
}
```
or more extreme (where the source is too ugly to show here)
```
$ nix eval -f . libiconv.name
"glibc-iconv-2.32"

$ nix eval -f . libiconv.name --argstr system x86_64-darwin
"libiconv-osx-10.12.6"
```
and you ran into a case that was even considered a bug in the expression.

If an evaluation failure doesn't happen too often (on too many commits), I'd suggest you just skip those commits, at least for now.  Generally it happens sometimes that we get commits in nixpkgs master that are broken in some way.

> So the entire .drv has to be built just to get the package name?

Generally no.  Laziness is certainly attempted, but `--json` gives you much more information than the name, so that increases the chance to encounter some error.

I don't know nix-instantiate codebase at all.

> Since it's only the json option that fails, and all I need right now is the pname of the package, is there some other way I can get the pname? (A way without the --json option)

I'm not aware of a way suitable for you.  (Other than `nix-env -qa --json` which might be OK anyway, as explained above.)  Actually I'm personally opposed to using `name` that doesn't parse "correctly" by `builtins.parseDrvName` (typically starting `version` by `"unstable"`, maybe I've missed some other weird style).

**Comment by jeff-hykin** [comment]
@vcunat Thanks, this information is really helpful and changes my understanding. For #93327, I can probably skip some, and better yet, I can probably fill in the gaps using pname information and `nix search` from commits before/after to deduce when there are problems with a name. However, I can't afford to miss much because the whole point of #93327 is to catalog niche specific versions of niche tools (the kinds of tools that would have poorly formatted versions).

However, your info presents a bigger problem: so just to confirm, @vcunat you're telling me that `nix-env -qa` on one machine can return different results on another machine?

**Comment by jeff-hykin** [comment]
Since other people could benefit from this (and its off topic), I created [a discourse post](https://discourse.nixos.org/t/clarification-on-package-names-and-versions/9819) for this convo if you want to continue there.
