### ISSUE TITLE
Steam doesn't detect Xbox controllers when already running

### ISSUE THREAD

**Issue by andreisergiu98** [NixOS/nixpkgs#101281]
**Describe the bug**
I'm trying to get Steam big picture to work with [xow](https://github.com/medusalix/xow), xbox wireless adapter and a couple of xbox controllers. But if Steam is already running and I turn on my controllers, they successfully connect to the dongle, but steam doesn't detect them. If i first turn on the controllers, and then i start Steam, it recognizes them and they work fine.

xow:
```
  boot.kernelModules = [ "uinput" ];
  environment.systemPackages = [ pkgs.xow ];
  services.udev.packages = [ pkgs.xow ];
  
  systemd.services."xow" = {
    enable = true;
    description = "Xbox One Wireless Dongle Driver";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type="idle";
      ExecStart="${pkgs.xow}/bin/xow";
      DynamicUser = true;
      Restart="on-success";
    };
  };
```
I couldn't use the service file provided by the package because it would never start. I read somewhere that systemd is picky with symlinks, so i defined it myself, now it's starting fine. I also had to blacklist `mt76x2u` else xow would crash.

Steam:
```
  hardware.opengl = {
    enable = true;
    driSupport32Bit = true;
    extraPackages32 = with pkgs.pkgsi686Linux; [ libva ];
  };

  nixpkgs.config.allowBroken = true;
  hardware.steam-hardware.enable = true;
  hardware.pulseaudio.support32Bit = config.hardware.pulseaudio.enable;
  environment.systemPackages = with pkgs; [ 
    unstable.steam
  ];
```

**To Reproduce**
1. Make sure xow is running fine
2. Start Steam
2. Turn on steam controllers
3. Try to see if they work (they dont)

**Additional context**
I think xow is working fine. I tried the latest version (0.5) and the last commit, importing udev rules from the package and adding them to services.udev.extraRules. 
```
Oct 21 21:37:16 olaphis systemd[1]: Started Xbox One Wireless Dongle Driver.
Oct 21 21:37:21 olaphis xow[775]: 2020-10-21 21:37:21 INFO  - xow 0.5 ©Severin v. W.
Oct 21 21:37:21 olaphis xow[775]: 2020-10-21 21:37:21 INFO  - Waiting for device...
Oct 21 21:37:22 olaphis xow[775]: 2020-10-21 21:37:22 INFO  - Wireless address: 62:45:bd:03:0e:49
Oct 21 21:37:22 olaphis xow[775]: 2020-10-21 21:37:22 INFO  - Dongle initialized
Oct 21 21:37:53 olaphis xow[775]: 2020-10-21 21:37:53 INFO  - Controller '1' connected
Oct 21 21:37:53 olaphis xow[775]: 2020-10-21 21:37:53 INFO  - Device announced, product id: 02dd
Oct 21 21:37:53 olaphis xow[775]: 2020-10-21 21:37:53 INFO  - Serial number: 03980059953545
Oct 21 21:37:55 olaphis xow[775]: 2020-10-21 21:37:55 INFO  - Battery level: 2
```

I also tried adding my user to the `input` group.
It doesn't matter if steam is running in big picture or not, i also tried steam native, still not working.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.70, NixOS, 20.03.3129.d3784204ba1 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3129.d3784204ba1, nixos-unstable-21.03pre246543.24c9b05ac53"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Edit:
Steam won't detect controllers even when using the wire. And also i tested the controllers with `jstest` and `evtest` and they work as expected. So i'm pretty sure the issue must be with steam.

**Comment by MetaDark** [comment]
This might be an upstream problem with `xow`, have you tried using it on a non NixOS system?

I also maintain `xpadneo` and I don't have this problem with Steam. Maybe try to test if it's still an issue on your system with xpadneo?
```nix
{
  hardware.xpadneo.enable = true;
}
```

**Comment by MetaDark** [comment]
You might also want to try enabling xow using the NixOS module:
```
services.hardware.xow.enable = true;
```

**Comment by andreisergiu98** [comment]
> This might be an upstream problem with xow, have you tried using it on a non NixOS system?

Yes, i have another system with Arch and it's working fine there. Steam detects controller connections even when it's already running.

> You might also want to try enabling xow using the NixOS module instead of writing a custom service:

That's what i tried at first, but xow wouldn't start, the service was hanging in an `inactive (dead)` state. And I think it might be because when importing the service from the package, nix is creating a symlink to the service and it might cause some issues.

Also I did some more tests with xow and controllers are working fine, `jstest`, `evtest`, this website https://gamepad-tester.com everywhere it works as expected, even Stardew Valley is able to detect them, but not Steam (well unless i restart it with controllers connected, then they are detected and working).

> I also maintain xpadneo (a kernel driver for Xbox controllers) and I don't have this problem with Steam. Maybe try to test if there's still a problem on your system with xpadneo?

It's really weird, I am able to pair them, xpadneo detects them, but they are totally unresponsive, everywhere. I uninstalled xow, and removed the wireless dongle when i tested this.

Since xow it's working fine in browser with https://gamepad-tester.com and with some games, then udev rules should be fine , right? 
I would say it's an upstream issue with Steam, but it's working fine on Arch, so there might be some issues with some libs?

**Comment by jansol** [comment]
The xow NixOS module is fixed now. The problem was that NixOS specifically bypasses the Install section of service files and the module wasn't setting WantedBy for the service explicitly.

**Comment by bryanasdev000** [comment]
I am wih something similar here, I am using the gamepad via USB , before the config `hardware.steam-hardware.enable = true;` all software detected the control, and I was able to play without problems except for steam, which prevented me from using the big picture, after enabling this option I have the same behavior as steam for all applications, if I plug in the control it does not work until the next reboot.

Any suggestions on where to debug to understand why this behavior?

Dmesg and lsusb look ok.

**Comment by mixedCase** [comment]
Having a similar issue, since I'm not using xow or anything but kernel drivers: Steam isn't able to detect a hotplugged Xbox one wired controller. It works perfectly fine if I plug it in before starting Steam.

I can also confirm this behavior works on Arch.

**Comment by aanderse** [comment]
@mixedCase that's my situation too 😞

**Comment by mmahut** [comment]
I guess no news on this? :(

**Comment by Artturin** [comment]
i'll take a look, probably something to do with udev rules. i dont have a xbox controller though, only a steam controller

**Comment by aanderse** [comment]
This problem sufficiently annoys me at this point that if there are any instructions I can follow to provide information I'm happy to do so. Thanks for offering to look.

I am currently in possession of 2 xbox controllers, several controllers that show up as xbox controllers, and some controllers that don't show up as xbox controllers. I have this issue with all these controllers to the best of my recollection.

**Comment by Artturin** [comment]
the steam udev rules are almost the same as on other distros, though arch does https://github.com/archlinux/svntogit-community/blob/f2c9f122aecbd65f8808a02707e690c483703d73/trunk/PKGBUILD#L33

i'll try borrowing a xbox controller. does this happen with only the xbox one or does it happen with 360 too

**Comment by Artturin** [comment]
sadly i can't find a xbox one controller.

the udev rules provided by the steam package are the same as on other distros, maybe it has something to do with our other udev rules.

may also have something to do with bubblewrap

**Comment by lightdiscord** [comment]
It seems to be related to linux user_namespaces which to my understanding remaps the id of the sender of udev events (from 0 to a big number) leading udev to ignore these messages if it's not zero.

Running `udevadm -d monitor` directly on my system and under `steam-run` (running as root and as a normal user) led me to believe this ([here is the output of each command where under steam-run as normal user each event is ignored](https://github.com/NixOS/nixpkgs/files/7170530/outputs.txt)).

This issue may need to be fixed with bubblewrap, I don't think something can be done here.
Unfortunately I don't have a solution :sweat_smile: 

PS : I don't know if fixing this issue will make everything work, I'll try to do a minimal program to see if controller hot-plug works under a steam-run run as root which don't ignore udev messages.

**Comment by Artturin** [comment]
> It seems to be related to linux user_namespaces which to my understanding remaps the id of the sender of udev events (from 0 to a big number) leading udev to ignore these messages if it's not zero.

these look related
https://github.com/NixOS/nixpkgs/issues/116361
https://github.com/NixOS/nixpkgs/pull/138969

**Comment by Artturin** [comment]
I merged https://github.com/NixOS/nixpkgs/pull/138969

someone who has this issue please look into using the patched systemd with the steam fhsenv

**Comment by mixedCase** [comment]
@Artturin I've just tested on latest NixOS unstable. A hotplugged Xbox One controller was successfully detected by Steam Big Picture. Thank you!

**Comment by Artturin** [comment]
> @Artturin I've just tested on latest NixOS unstable. A hotplugged Xbox One controller was successfully detected by Steam Big Picture. Thank you!

i haven't done anything that would have fixed this

**Comment by mixedCase** [comment]
@Artturin Well that is exceptionally weird! Because it's definitely working for me, looks like an unrelated PR fixed it?

This is straight out of my terminal, after starting Steam with no controller, disconnecting and connecting again:

```
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/mixedcase/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 2.24 seconds
BuildCompleteAppOverviewChange: 727
RegisterForAppOverview 1: 16ms
RegisterForAppOverview 2: 16ms
Local Device Found
  type: 045e 02ea
  path: sdl://0
  serial_number:  - 0
  Manufacturer:
  Product:      Xbox One Wireless Controller
  Release:      301
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Controller 0 connected, configuring it now...
Installing breakpad exception handler for appid(steam)/version(1631912732)
Controller has an Invalid or missing unit serial number, setting to '45e-2ea-462a818'
Opted-in Controller Mask for AppId 413080: 0
!! Controller 0 attributes:
  Type: 32
  ProductID: 746
  Serial: 45e-2ea-462a818
  Capabilities: 001803ff
  Firmware Version: 0
  Firmware Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
  Bootloader Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
Loaded Config for Local Selection Path for App ID 413090, Controller 0: /home/mixedcase/.local/share/Steam/steamapps/workshop/content/241100/1689651975/1007024772344596662_legacy.bin
[413090]Non-Steam Controller Configs Enabled: 1
Loaded Config for Local Selection Path for App ID 413090, Controller 0: /home/mixedcase/.local/share/Steam/steamapps/workshop/content/241100/1557881022/956347096063773104_legacy.bin
Could not load local selection (), local override (/home/mixedcase/.local/share/Steam//controller_config/basicui_gamepad.vdf), or user path (/home/mixedcase/.local/share/Steam/userdata/73574424/config/controller_configs/basicui_gamepad.vdf), checking last resort path: /home/mixedcase/.local/share/Steam//controller_base/basicui_gamepad.vdf
Loaded Config for Last Resort Path for App ID 769, Controller 0: /home/mixedcase/.local/share/Steam//controller_base/basicui_gamepad.vdf
BYieldingQueryAccountsRegisteredToController
Controller device closed after hid_read failure
Controller 0 disconnected
Local Device Found
  type: 045e 02ea
  path: sdl://1
  serial_number:  - 0
  Manufacturer:
  Product:      Xbox One Wireless Controller
  Release:      301
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Controller 0 connected, configuring it now...
Controller has an Invalid or missing unit serial number, setting to '45e-2ea-462a818'
!! Controller 0 attributes:
  Type: 32
  ProductID: 746
  Serial: 45e-2ea-462a818
  Capabilities: 001803ff
  Firmware Version: 0
  Firmware Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
  Bootloader Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
Loaded Config for Local Selection Path for App ID 413090, Controller 0: /home/mixedcase/.local/share/Steam/steamapps/workshop/content/241100/1689651975/1007024772344596662_legacy.bin
Loaded Config for Local Selection Path for App ID 413090, Controller 0: /home/mixedcase/.local/share/Steam/steamapps/workshop/content/241100/1557881022/956347096063773104_legacy.bin
```

**Comment by baracoder** [comment]
This must be a change to how steam recognizes controllers. The program from @lightdiscord  https://gist.github.com/lightdiscord/6c004a106a0a2fc9751ec28208d8fa5c
still does not show events when started within `steam-run`

There is still something odd: My joystick Logitech X52 HOTAS is recognized as a gamepad, while when I run steam packages on flatpak, it works properly. I don't know what they do differently in the flatpak version to get it working. Maybe using libgudev or a flatpak specific version of udev in the runtime packages?

I have tested adding patched systemd to the fhs of steam, but this did not change anything (maybe some other udev library version was shadowing it)

**Comment by Oro** [comment]
I still have this issue, with both an xbox 360 controller with the wireless adapter as well with an 8Bitdo SN30+ in both wired and wireless mode.

Starting steam with any of these already connected works, but if one gets connected after starting steam (or worse - shortly disconnects while playing) it will not be reconnected until a Steam restart.

However, with a Steam Controller hotplugging works just fine!

This happens with Steam Big Picture mode (and also in games, but I guess Big Picture mode is more readily reproducable).   
I assume I am doing something wrong as others have it fixed, is this really no longer an issue for others? Happy for any pointers and to assist in debugging.

(my config is at https://git.sr.ht/~oro/nixos-configuration/tree/41257548899925a5afcc00d3ab18e0646d994cb0/hosts/OroPC/configuration.nix in case it is needed, i am currently on `22.11pre384129.e0169d7a9d3 (Raccoon)`)

**Comment by bjornfor** [comment]
>I assume I am doing something wrong as others have it fixed, is this really no longer an issue for others?

I have the same issue, with PS5 DualSense controllers.

I debugged a bit during the christmas holiday, based on some info in either this issue or some other... By applying a patch (linked from the issue) I was able to see udev starting to detect hotplugging the controller in the Steam FHS env (it didn't detect these events by default), but still Steam wouldn't pick up the hotplugged controller.

**Comment by bjornfor** [comment]
> I debugged a bit during the christmas holiday, based on some info in either this issue or some other... By applying a patch (linked from the issue) I was able to see udev starting to detect hotplugging the controller in the Steam FHS env (it didn't detect these events by default), but still Steam wouldn't pick up the hotplugged controller.

I found my experimental config snippet from back then:

```nix
  nixpkgs.overlays = [
    (final: prev:
      let
        systemdPatched = prev.systemd.overrideAttrs (oldAttrs: {
          patches = (oldAttrs.patches or []) ++ [
            "${pkgs.path}/pkgs/applications/blockchains/ledger-live-desktop/systemd.patch"
          ];
        });
      in
      {
        # This change makes `udevadm monitor` emit events inside `steam-run
        # bash`. The bug can be observed *without* this patch by running
        # `SYSTEMD_LOG_LEVEL=debug udevadm monitor` inside `steam-run bash` and
        # observing the "sd-device-monitor: Sender uid=N, message ignored"
        # messsage. However, it doesn't make *steam* detect devices
        # dynamically.
        steam = prev.steam.override {
          extraPkgs = pkgs: [ systemdPatched ];
          extraLibraries = pkgs: [ systemdPatched ];
        };
      })
  ];
  systemd.services.systemd-udevd.serviceConfig.Environment = [
    "SYSTEMD_LOG_LEVEL=debug"
  ];
```

AFAIR, I was worried that steam itself didn't use the patched libudev, but I'm pretty sure I looked up the process map and found it had (only) loaded the patched libudev, so I'm not sure what's going on. Didn't look at it since.

**Comment by aanderse** [comment]
If anyone just wants to throw money at this problem I highly suggest the [Logitech F710 Wireless Gamepad](https://www.logitechg.com/en-ca/products/gamepads/f710-wireless-gamepad.940-000117.html) to solve it. The real win with this gamepad is that it **always** shows up as connected to your PC, even when it is powered off. It achieves this by coming with a usb dongle that shows up effectively as a wired joystick regardless if the gamepad is being used or not. Perfect solution for this problem... I have 3.

I'll mention a potential con, though: Make sure you have good line of sight between the usb dongle and the gamepad (don't worry, it comes with a ~1m usb extension cable to allow good line of sight) and aren't too far away (3-4 m I would guess) or else the signal is really spotty. In my last setup I used this through the wall and it absolutely wouldn't work for any serious gaming, but now I have the pc in the same room as the gamepads with direct line of sight and it is perfect.

But yeah... a real solution would be better and still appreciated by me. Just thought I'd post this in case anyone could benefit from it. :man_shrugging:

**Comment by baracoder** [comment]
Another alternative is to use [steam via flatpak](https://flathub.org/apps/details/com.valvesoftware.Steam):
in the config:
```
services.flatpak.enable = true;
```
then install and run it:
```
flatpak install flathub com.valvesoftware.Steam
flatpak run com.valvesoftware.Steam
```
 I didn't have any issues since doing it since flatpak was updated to >= 1.12

**Comment by SkyLeite** [comment]
I still have this issue on Nix's version of steam using nixos-unstable. Enabling xpadneo did not fix it either.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/182851 may have fixed this

https://nixpk.gs/pr-tracker.html?pr=182851

**Comment by varris1** [comment]
Seems like #182851 didn't fix it. I see that it is in nixos-unstable and it seems like Steam still displays the same issue with my DualSense controller. I need to restart Steam before it detects it

**Comment by Slabity** [comment]
I am having this issue on every controller I have:

- Steam Controller
- Nintendo Switch Pro Controller
- PS3 Controller
- Gulikit King Kong Pro 2 Controller in all 4 modes (Switch, XInput, DInput, Android/iOS)
- USB adapters for NES, SNES, and Gamecube controllers

It occurs when using both Bluetooth and USB, so I am 90% certain it has nothing to do with which controller you are using. The behavior is the same for all of them; when I connect any USB/Bluetooth controller it is not recognized or noticed by Steam if it is already running, but only when Steam is starting up while the controller is currently plugged in.

Here's some information on what happens when I use the Gulikit controller (XInput mode via bluetooth):

**Controller connected and Steam is _not_ started**

```
$ dmesg
...
[363720.677883] microsoft 0005:045E:02E0.000C: unknown main item tag 0x0
[363720.677966] input: GuliKit Controller XW as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/input/input32
[363720.678062] microsoft 0005:045E:02E0.000C: input,hidraw7: BLUETOOTH HID v9.03 Gamepad [GuliKit Controller XW] on 68:54:5a:ac:2b:13
```

```
$ sudo udevadm -d monitor
...
KERNEL[363724.973049] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
UDEV  [363724.974532] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
KERNEL[363728.445758] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C (hid)
KERNEL[363728.445859] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/power_supply/hid-98:b6:ea:32:74:f4-battery/wakeup52 (wakeup)
KERNEL[363728.445872] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/power_supply/hid-98:b6:ea:32:74:f4-battery/hwmon7 (hwmon)
KERNEL[363728.445917] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/input/input32 (input)
KERNEL[363728.445952] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/input/input32/js0 (input)
KERNEL[363728.445971] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/input/input32/event20 (input)
KERNEL[363728.445998] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/hidraw/hidraw7 (hidraw)
KERNEL[363728.446014] bind     /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C (hid)
UDEV  [363728.447121] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C (hid)
UDEV  [363728.448687] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/input/input32 (input)
UDEV  [363728.449815] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/input/input32/js0 (input)
UDEV  [363728.451757] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/hidraw/hidraw7 (hidraw)
UDEV  [363728.482819] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/input/input32/event20 (input)
UDEV  [363728.488595] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/power_supply/hid-98:b6:ea:32:74:f4-battery/wakeup52 (wakeup)
UDEV  [363728.501209] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/power_supply/hid-98:b6:ea:32:74:f4-battery/hwmon7 (hwmon)
UDEV  [363728.502009] bind     /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C (hid)
KERNEL[363728.534099] change   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
UDEV  [363728.559894] change   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000C/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
```

At this point, `/dev/input/event20` and `/dev/input/js0` are now created

**Now I start Steam**

```
$ dmesg
...
[363827.881577] input: Microsoft X-Box 360 pad 0 as /devices/virtual/input/input33
```

And `udevadm -d monitor` reports:

```
$ sudo udevadm -d monitor
...
KERNEL[363835.651845] add      /devices/virtual/input/input33 (input)
KERNEL[363835.651869] add      /devices/virtual/input/input33/js1 (input)
KERNEL[363835.651881] add      /devices/virtual/input/input33/event21 (input)
UDEV  [363835.653024] add      /devices/virtual/input/input33 (input)
UDEV  [363835.653484] add      /devices/virtual/input/input33/js1 (input)
UDEV  [363835.677034] add      /devices/virtual/input/input33/event21 (input)
```

And now `/dev/input/event21` and `/dev/input/js1` are created (???)

**Disconnected the controller with Steam running**

Nothing new in `dmesg`

```
$ sudo udevadm -d monitor
...
KERNEL[364507.177236] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery/hwmon7 (hwmon)
KERNEL[364507.177254] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery/wakeup52 (wakeup)
KERNEL[364507.177268] change   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
KERNEL[364507.177280] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
UDEV  [364507.178551] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery/hwmon7 (hwmon)
UDEV  [364507.178613] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery/wakeup52 (wakeup)
UDEV  [364507.179353] change   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
UDEV  [364507.179860] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
KERNEL[364507.187814] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/input/input35/js0 (input)
UDEV  [364507.188543] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/input/input35/js0 (input)
KERNEL[364507.194806] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/input/input35/event20 (input)
UDEV  [364507.195655] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/input/input35/event20 (input)
KERNEL[364507.207811] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/input/input35 (input)
KERNEL[364507.207829] remove   /devices/virtual/input/input36/js1 (input)
KERNEL[364507.207840] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/hidraw/hidraw7 (hidraw)
KERNEL[364507.207852] unbind   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E (hid)
KERNEL[364507.207867] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E (hid)
UDEV  [364507.208195] remove   /devices/virtual/input/input36/js1 (input)
UDEV  [364507.208617] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/input/input35 (input)
UDEV  [364507.209279] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E/hidraw/hidraw7 (hidraw)
UDEV  [364507.209817] unbind   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E (hid)
UDEV  [364507.210254] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:045E:02E0.000E (hid)
KERNEL[364507.215785] remove   /devices/virtual/input/input36/event21 (input)
UDEV  [364507.216008] remove   /devices/virtual/input/input36/event21 (input)
KERNEL[364507.228815] remove   /devices/virtual/input/input36 (input)
UDEV  [364507.229118] remove   /devices/virtual/input/input36 (input)
KERNEL[364507.429801] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512 (bluetooth)
UDEV  [364507.430495] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512 (bluetooth)
KERNEL[364509.098712] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
UDEV  [364509.099597] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
KERNEL[364539.727804] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
UDEV  [364539.728903] remove   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
```

**I reconnect the controller with Steam running***

```
$ dmesg
...
[365515.320324] microsoft 0005:045E:02E0.000F: unknown main item tag 0x0
[365515.320403] input: GuliKit Controller XW as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/input/input37
[365515.320516] microsoft 0005:045E:02E0.000F: input,hidraw7: BLUETOOTH HID v9.03 Gamepad [GuliKit Controller XW] on 68:54:5a:ac:2b:13
```

```
$ sudo udevadm -d monitor
...
KERNEL[365520.331721] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
UDEV  [365520.333178] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256 (bluetooth)
KERNEL[365523.127068] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F (hid)
KERNEL[365523.127161] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/power_supply/hid-98:b6:ea:32:74:f4-battery/wakeup52 (wakeup)
KERNEL[365523.127176] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/power_supply/hid-98:b6:ea:32:74:f4-battery/hwmon7 (hwmon)
KERNEL[365523.127209] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/input/input37 (input)
KERNEL[365523.127247] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/input/input37/js0 (input)
KERNEL[365523.127273] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/input/input37/event20 (input)
KERNEL[365523.127311] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/hidraw/hidraw7 (hidraw)
KERNEL[365523.127330] bind     /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F (hid)
UDEV  [365523.128214] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F (hid)
UDEV  [365523.130020] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/input/input37 (input)
UDEV  [365523.131215] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/input/input37/js0 (input)
UDEV  [365523.132879] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/hidraw/hidraw7 (hidraw)
UDEV  [365523.163729] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/input/input37/event20 (input)
UDEV  [365523.169949] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/power_supply/hid-98:b6:ea:32:74:f4-battery/wakeup52 (wakeup)
UDEV  [365523.180099] add      /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/power_supply/hid-98:b6:ea:32:74:f4-battery/hwmon7 (hwmon)
UDEV  [365523.180809] bind     /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F (hid)
KERNEL[365523.199187] change   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
UDEV  [365523.222483] change   /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.000F/power_supply/hid-98:b6:ea:32:74:f4-battery (power_supply)
```

And `/dev/input/event20` and `/dev/input/js0` is back

**TL;DR** - So it looks like Steam will normally start up and find the controller and then it will create the virtual input devices `event21` and `js1`. However, it won't create these devices when they are connected after Steam is already running. The question I have is why this happens and what can be done to fix it. It looks to be a NixOS specific issue as the problem doesn't appear to be on other Linux distributions like Arch (just reading off of what's in this thread, I haven't tried myself).

If anyone wants me to try anything and test it on a fair variety of USB/Bluetooth controllers please let me know.

**Comment by SkyLeite** [comment]
This seems related: https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/11

**Comment by Oro** [comment]
Just as an added datapoint: The Steam Controller is actually one that does not exhibit this issue for me, at least not when wirelessly connected with the Dongle that came with it. 

If I connect it via cable then it is the same as usual, only recognized when restarting steam. Also if connected via dongle and I replug the dongle, the controller only gets recognized when restarting steam. But if the dongle stays put and I shutdown the controller (by holding the Steam button for a few seconds) and start it again it works just fine with steam running. I guess it might be similar to the controller described in https://github.com/NixOS/nixpkgs/issues/101281#issuecomment-1166650649

**Comment by zhaofengli** [comment]
> There is still something odd: My joystick Logitech X52 HOTAS is recognized as a gamepad, while when I run steam packages on flatpak, it works properly. I don't know what they do differently in the flatpak version to get it working. Maybe using libgudev or a flatpak specific version of udev in the runtime packages?

I was surprised as well, and a little bit of digging reveals that SDL2 [automatically detects](https://github.com/libsdl-org/SDL/commit/8e2746cfb6e1f1a1da5088241a1440fd2535e321) being inside flatpak and disables the unreliable udev-based discovery. And disabling it manually [actually worked](https://imgur.com/a/b0n6qW8)! I opened #189961 to fix this.

**Comment by varris1** [comment]
Can confirm that it fixed the issue for me. Good job in discovering this

**Comment by aanderse** [comment]
This is resolved for me now as well. Thank you all! :heart:
