### ISSUE TITLE
Cinnamon crashes and breaks when launching "Virtual keyboard"

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#101881]
**Describe the bug**
When cinnamon is started either via gdm or `exec cinnamon-session-cinnameon` in a `.xinitrc`. 
+ Sometimes the desktop icons do load
+ Always a window spawns telling me that I'm in fallback mode
+ no taskbar, no window decorations (hence I think no compositor & window manager)

**To Reproduce**
Here I'm kind of unsure: I deleted all nemo and cinnamon folder in $HOME, .config and .local/share. Still this occurs on all of my machines.
IIRC this first happen when accidentally starting a "virtual keyboard" app

1. Start cinnamon
2. Start "Virtual keyboard"
3. Some cinnamon components crash instantly, the and the behavior is reproducible on further attempts of starting cinnamon

**Expected behavior**
Cinnamon starts and is usable

**Additional context**
Booting into an old generation did not fix this, however, I'm quite unsure what could be the cause of it. This is some log which I could create by running cinnamon from a `.xinitrc`. I'm not sure whether this is related to the issue or not.

relevant `.xinitrc`:
```
exec cinnamon-launcher --debug
```
Output captured (the log is over 2000 lines long, this is from the very end and might be the issue):

```
(nemo-desktop:7615): GLib-CRITICAL **: 22:40:05.139: g_strstr_len: assertion 'haystack != NULL' failed
** Message: 22:40:05.139: nemo-desktop: session is not cinnamon (checked XDG_SESSION_DESKTOP,DESKTOP_SESSION environment variables.) Applying default behavior
cinnamon-session[7339]: DEBUG(+): t+0.70044s: CsmAutostartApp: (pid:7619) done (status:0)
Cjs-Message: 22:40:05.212: JS LOG: About to start Cinnamon
Cjs-Message: 22:40:05.262: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 48 ms
Cjs-Message: 22:40:05.269: JS LOG: [LookingGlass/info] loading user theme: /run/current-system/sw/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
Cjs-Message: 22:40:05.282: JS LOG: [LookingGlass/info] added icon directory: /run/current-system/sw/share/themes/Mint-Y-Dark/cinnamon

(cinnamon:7561): Cjs-WARNING **: 22:40:05.283: Some code accessed the property 'BackgroundManager' on the module 'backgroundManager'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested)
cinnamon-session[7339]: DEBUG(+): t+1.18960s: CsmXsmpServer: ice_io_error_handler (0x12ad0e0)
cinnamon-session[7339]: DEBUG(+): t+1.18965s: CsmXSMPClient: IceProcessMessagesIOError on '0x13143b0 [cinnamon 10b8bc0d0be326c08e160383480453759900000073390000]'
cinnamon-session[7339]: DEBUG(+): t+1.18968s: CsmManager: disconnect client
cinnamon-session[7339]: DEBUG(+): t+1.18969s: CsmManager: disconnect client: /org/gnome/SessionManager/Client23
cinnamon-session[7339]: DEBUG(+): t+1.18970s: CsmXSMPClient: getting restart style
cinnamon-session[7339]: DEBUG(+): t+1.18971s: CsmManager: autorestart not set, not restarting application
cinnamon-session[7339]: DEBUG(+): t+1.18972s: CsmStore: Unreffing object: 0x13143b0
cinnamon-session[7339]: DEBUG(+): t+1.18973s: CsmManager: Client removed: /org/gnome/SessionManager/Client23
cinnamon-session[7339]: DEBUG(+): t+1.18983s: CsmManager: disconnect client
cinnamon-session[7339]: DEBUG(+): t+1.18985s: CsmManager: disconnect client: /org/gnome/SessionManager/Client23
cinnamon-session[7339]: DEBUG(+): t+1.18986s: CsmXSMPClient: getting restart style
cinnamon-session[7339]: DEBUG(+): t+1.18987s: CsmManager: autorestart not set, not restarting application
cinnamon-session[7339]: DEBUG(+): t+1.18988s: CsmClient: disposing /org/gnome/SessionManager/Client23
cinnamon-session[7339]: DEBUG(+): t+1.18989s: CsmXSMPClient: xsmp_finalize (0x13143b0 [cinnamon 10b8bc0d0be326c08e160383480453759900000073390000])
Traceback (most recent call last):
  File "/nix/store/jqxihmciar0jcp0bavmnl2w2gvbpliwn-cinnamon-common-4.6.1/bin/.cinnamon-launcher-wrapped", line 72, in <module>
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/os.py", line 568, in execvp
    _execvpe(file, args)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/os.py", line 610, in _execvpe
    raise last_exc
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/os.py", line 601, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
(II) AIGLX: Suspending AIGLX clients for VT switch
cinnamon-session[7339]: DEBUG(+): t+5.41061s: Starting app: /org/gnome/SessionManager/App2
cinnamon-session[7339]: DEBUG(+): t+5.41068s: CsmAutostartApp: starting cinnamon-screensaver.desktop: command=cinnamon-screensaver startup-id=10b8bc0d0be326c08e160383480454203300000073390001
cinnamon-session[7339]: GLib-DEBUG(+): t+5.41077s: posix_spawn avoided (fd close requested)
cinnamon-session[7339]: DEBUG(+): t+5.41238s: CsmAutostartApp: started pid:7669
cinnamon-session[7339]: WARNING: t+5.71344s: Detected that screensaver has appeared on the bus
```

**Notify maintainers**
@mkg20001 @worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.11, NixOS, 20.09beta538.0cfe5377e89 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1469.13d0c311e3a, nixos-unstable-21.03pre244932.84d74ae9c9c"`
 - channels(wucke13): `"nixos-unstable-21.03pre246062.420f89ceb26, nixpkgs-unstable-19.09pre170896.6e5caa3f8ac, nixos-unstable-small-19.03pre161392.50bb0afa7ce"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment]
I will say that it does start in lightdm. IIRC upstream uses slick greeter and lightdm, so maybe it's just broken for that dm.

**Comment by wucke13** [comment]
@worldofpeace it is broken when started on `.xinitrc` as well, and it used to work in gdm just a day a go as well. Thinking more of the problem, what else can break the startup of cinnamon if all of these are empty/removed:

+ `.cinnamon`
+ `.config/autostart`
+ `.config/cinnamon-session`
+ `.config/nemo`
+ `.local/share/cinnamon/`
+ `.local/share/nemo`

? There must be something in my $HOME which alters the startup procedure of cinnamon to break (otherwise it wouldn't work for you?!) but what can it be?

**Comment by mkg20001** [comment]
```
dconf load / << EOF
[org/cinnamon/desktop/a11y/applications]
screen-keyboard-enabled=false
screen-reader-enabled=false
EOF
```

**Comment by mkg20001** [comment]
@worldofpeace 

Which package provides gio for `Notifiy`? We'd need to add that to buildInputs then the error should be fixed

**Comment by worldofpeace** [comment]
That is `libnotify`. Be sure to on the source code to always run a `rg gi.repository` to see what namespaces are imported. From there you track where those typelibs come from to determine the dependencies that belong in `buildInputs`

**Comment by 1ctinus** [comment]
Any updates on this?

**Comment by mkg20001** [comment]
It would need to be tested if the issue still persists.

**Comment by wucke13** [comment]
The bug is still persistent.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16, NixOS, 20.09.4058.22612485a46 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `"nixos-20.09.4058.22612485a46, nixos-unstable-21.05pre285574.8e4fe32876c"`
 - channels(wucke13): `"nixos-unstable-21.03pre246062.420f89ceb26, nixpkgs-unstable-19.09pre170896.6e5caa3f8ac, nixos-unstable-small-19.03pre161392.50bb0afa7ce"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by wucke13** [comment]
The bug is still present in 21.05:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.4, NixOS, 21.05.20210601.5237039 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.05.641.5237039cc1e, nixos-unstable-21.11pre292748.6933d068c5d"`
 - channels(wucke13): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by mkg20001** [comment]
The main problem I have is that I have no idea where to even start debugging the segfault, as it seems to be part of native code

**Comment by wucke13** [comment]
Any chances upstream has some idea? Not sure how to get in touch with them without making it seem like "We have a problem and you shall fix it".

**Comment by baronleonardo** [comment]
I ran `strace cinnamon-screensaver` and I found that it is missing `caribou`, just install it and the bug will disappear.
I think this package is a must or we have a security-issue here

**Comment by bobby285271** [comment]
I can confirm installing caribou fixes the issue. I haven't really looked into it yet, the related line is likely at
https://github.com/linuxmint/cinnamon/blob/5.4.10/js/ui/virtualKeyboard.js#L268

And I managed to SIGSEGV gjs-console (cjs-console) in a `nix-shell -p cinnamon.cjs -p gnome.caribou` shell with:

```js
const Caribou = imports.gi.Caribou;
new Caribou.KeyboardModel({ keyboard_type: 'tablet' });
```
I search for the output `Failed to load keyboard file tablet/us: Could not find layout file for us`, and found this https://github.com/GNOME/caribou/blob/master/libcaribou/xml-deserializer.vala#L33

So I do `XDG_DATA_DIRS=$(nix-build -A gnome.caribou)/share:$XDG_DATA_DIRS` and the SIGSEGV is gone together.
