### ISSUE TITLE
incorrect hostname --fqdn

### ISSUE THREAD

**Issue by shdpl** [NixOS/nixpkgs#10183]
I'm not sure whether it's a bug of nixos, but i noticed unusual situation about my configuration.

This is invalid ( i think ) behavior

``` nix
{
  networking = { 
    hostName = "hostname";
    domain = "domain.tld";
  };
}
```

``` bash
# hostname --short
hostname
# hostname --domain
(none)
```

After small change results are correct

``` nix
{
  networking = { 
    hostName = "hostname";
    domain = "domain.tld";
    search = [ "domain.tld" ];
  };
}
```

``` bash
# hostname --short
hostname
# hostname --domain
domain.tld
```

Nothing huge, but if one needs hostname correct --fqdn solution is not totally obvious.

**Comment by davidak** [comment]
still the case for NixOS 15.09.1012.9fe0c23, the workaround don't work.

because of this i have problems with postfix.

**Comment by peti** [comment]
This is a well-known problem caused by the fact that  NixOS won't record the host name as an alias for "127.0.0.1" in `/etc/hosts`.

**Comment by ttuegel** [comment]
> This is a well-known problem caused by the fact that NixOS won't record the host name as an alias for "127.0.0.1" in /etc/hosts.

Is this simply an oversight that could be corrected with a quick PR, or was this done by design?

**Comment by peti** [comment]
I volunteered to make a fix and then I never did it. :disappointed:  The whole story is at https://github.com/NixOS/nixpkgs/issues/1248.

**Comment by yegortimoshenko** [comment]
```
[chronos@yegatool:~]$ hostname --fqdn
yegatool
```

@Mic92 This seems to be resolved, and seems to be a duplicate of #1248. Since you've closed the latter, could you also close this one?

**Comment by florianjacob** [comment]
I can reproduce that this now works on master (but is still broken on 17.09)
```
> hostname --fqdn
host.domain.tld
> hostname
host
> hostname --short
host
>  hostname --domain
host.domain.tld
```

**Comment by peti** [comment]
@yegortimoshenko, according to the very example you cited, this issue is *not* resolved because `hostname --fqdn` still doesn't work even though a domain name is configured.

**Comment by yegortimoshenko** [comment]
@peti Oh, I don't have domain set:

```
[chronos@yegatool:~]$ hostname --domain

```

@florianjacob tested it with a domain and it seems to be fixed. I assume this is fallout from #1248.

**Comment by srhb** [comment]
Which commit is supposed to fix this? With domain set, the issue persists for me.

**Comment by mbrgm** [comment]
Same problem as @srhb ... any fixes?

**Comment by florianjacob** [comment]
I can confirm that this is currently broken again in stable 18.03.

**Comment by azazel75** [comment]
It's broken also on unstable

**Comment by Mic92** [comment]
I would rather they nscd because it caches result. myhostname loads its information from the operating system and is stateless itself: https://github.com/systemd/systemd/blob/master/src/nss-myhostname/nss-myhostname.c#L88

**Comment by alyssais** [comment]
I had this problem consistently, but removing `myhostname` from nsswitch.conf fixed it for me.

**Comment by alyssais** [comment]
Related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=756224

**Comment by toraritte** [comment]
@alyssais Is your setup public on github? 

I tried to remove `myhostname` using the NixOS option `system.nssHosts`, but it is an additive operation only. Or did you just replace the read-only `nsswitch.conf` with the right options?

I was looking at the [systemd-resolved options](https://nixos.org/nixos/options.html#services.resolved) as well, but couldn't get it to work. Even a pointer to a post would help.

**Comment by alyssais** [comment]
On Mon, Apr 29, 2019 at 03:34:53PM -0700, Attila Gulyas wrote:
> @alyssais Is your setup public on github?

Not on GitHub, but it is public.

Here's the relevant commit:

https://edef.eu/~qyliss/nixlib/commit/7ac2a71fc41ebc3ebe565b5f773c151b1994fec2.html

**Comment by toraritte** [comment]
Thank you @alyssais ! Tried all possible combination, even reinstalled the whole system and started from a clean config, but in the end it was @davidak's [`extraHosts` workaround](https://github.com/davidak/nixos-config/blob/d1fcef16470c567245fcb480c55f980b59bfc208/binary/configuration.nix#L32-L35) that worked for me [from his comment to #1248](https://github.com/NixOS/nixpkgs/issues/1248#issuecomment-233192217). Others have mentioned this as well, but his config has a line for `::1` and that seems to be crucial, no clue why.

**Comment by prolineserver** [comment]
The suggested workarounds didn't fully work out for me. In order to get kerberos authentication with GSSAPIAuthentication and a krb5.keytab working, the order in the hosts file seems to be important: the fqdn needs to be first, neither hostname nor localhost. Otherwise I'll get an `No key table entry found matching host/localhost@`. I finally ended up with
```
{ config, pkgs, lib, ... }:
{
    networking.hosts =
    {
      "127.0.1.1" = lib.mkForce [ "${hostName}.${domain}" "${hostName}"];
      "::1" = lib.mkForce ["${hostName}.${domain}" "${hostName}" "localhost"];
    };
}
```

**Comment by flokli** [comment]
@Mic92 After your writings about `myhostname`, I assume `hostname --fqdn` / ssh with kerberos both just do use nss?

In that case, what do they exactly do, and why does this fail with myhostname in nsswitch.conf?

**Comment by blitz** [comment]
@primeos just pointed me here via #87633. This is issue really causes subtle issues. I only noticed this was the problem when my email client failed to send an email, because it failed to send a FQDN...

**Comment by blitz** [comment]
I've written a small integration test, if someone feels like experimenting:

https://github.com/blitz/nixpkgs/commit/efd537c925c468b8e676419a54855d01ee56aebb

**Comment by primeos** [comment]
Oh, I completely forgot to close this issue. With #76542 this should finally be resolved :)
