### ISSUE TITLE
unstable channel hasn't updated for 14+ days

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#11097]
https://github.com/nixos/nixpkgs-channels has been stuck at 7ae05edcdd14f6ace83ead9bf0d114e97c89a83a for two weeks. According to https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents, kde4 tests fail, but there might be other reasons why the channel is blocked.

**Comment by vcunat** [comment]
Yes, there's a build error in kgamma:
> Unknown CMake command "check_include_files".

Maybe some cmake update on staging or something...

**Comment by wizeman** [comment]
Sounds like exactly the same problem that @aszlig fixed in conky: 880eba6481d112b934325f1e60033ffd3c6c3f53

**Comment by pSub** [comment]
Yes, that sounds exactly like that problem. However I have no idea how to fix it properly.

@ttuegel You do most of the kde stuff, do you have a idea?

**Comment by ttuegel** [comment]
For kgamma, check for a patch upstream. CMake doesn't keep backwards compatibility between versions, so you can't just upgrade it globally. You will need an upstream patch for kgamma to fix it properly. If there is no upstream patch, I guess your options are to use an older CMake for kgamma or drop kgamma as unmaintained upstream.

**Comment by vcunat** [comment]
Fixed a channel blocker in 48409bd3. No other failures are visible ATM http://hydra.nixos.org/build/28002207#tabs-constituents

**Comment by vcunat** [comment]
So, kde4 test succeed for me now on x86_64-linux. I decided to switch to cmake-2.8 for all kde4 components, as that seemed easiest with kde4 stuff not really maintained upstream anymore.

**Comment by vcunat** [comment]
@lethalman: what is your estimate about status of gnome-3.18 in nixpkgs? When switch the default?

Now I see that gnome-maps-3.16 also has [problems with newer glib](http://hydra.nixos.org/build/28002102/nixlog/17/tail-reload) and there are no more 3.16 releases of that one. Maybe 3.16 will become nontrivial to keep alive.

**Comment by domenkozar** [comment]
`gnome3.gnome-maps` has been removed by @lethalman , but main hydra machine still fails to run tests because of:

```
mv: error writing '/nix/store/sdsnyczpgyrf801z33g043igch461gk3-xsession': No space left on device
<3>note: build failure may have been caused by lack of free disk space
<3>builder for ‘/nix/store/n24r2qi5h74c1j8h2cilx23zaz1phbpp-xsession.drv’ failed with exit code 1
```

cc @rbvermaa @edolstra

**Comment by domenkozar** [comment]
Currently hydra doesn't pickup nixos tests, so they're in queue for a few days.

**Comment by peti** [comment]
It appears that https://hydra.nixos.org/build/28408697 succeeded. Now all we need is a channel update!

**Comment by domenkozar** [comment]
here it is \o/
