### ISSUE TITLE
download files in firefox/thunderbird: no default application to open them

### ISSUE THREAD

**Issue by fkz** [NixOS/nixpkgs#11355]
For example, if I download a .pdf file or want to open a .pdf attachment out of thunderbird, no application is available per default. I have to browse the executables and set it to something like /run/current-system/sw/bin/evince the first time I want to open a .pdf attachement (similarly with firefox). Ideally, the default applications should somehow be configurable from nix.

**Comment by vcunat** [comment]
IMHO it seems like Mozilla's apps don't follow XDG specs (or not exactly), as we do install `*.desktop` files, and other apps do know how to find these, e.g. thunar shows a good `open with` suggestion list when I click a PDF file.

**Comment by Mathnerd314** [comment]
[Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=694870) uses a [Gnome API](https://developer.gnome.org/gio/stable/GAppInfo.html). I have Gnome installed and it seems to work OK (not great, it seems to default to using gnome applications instead of kde, even when I'm running kde). Maybe it uses a cache which is created by gnome-shell.

**Comment by fkz** [comment]
I use KDE5 currently, there it doesn't work. (when no gnome is installed there are also no gnome applications offered obviously). I have no idea how to fix this.

**Comment by Profpatsch** [comment]
(triage) Is this still a problem?

**Comment by vcunat** [comment]
I believe it hasn't changed, though I may've missed something during the last two months.

**Comment by DamienCassou** [comment]
Profpatsch <notifications@github.com> writes:

> Is this still a problem?

it is!

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by cumber** [comment]
This is still a problem. I use Thunderbird with xmonad as my window manager (without gnome installed); I can't even open web links in emails without manually finding the path to my browser in the store.

**Comment by johnramsden** [comment]
Is there a solution for this? Or a workaround? I can't open any links in Thunderbird and it's fairly irritating.

**Comment by vcunat** [comment]
I worked around by choosing the application once (for each file type) and it remembered.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by Spass1966** [comment]
This is still an issue.

**Comment by michaelpj** [comment]
Hmm, I thought I fixed this at least partially in https://github.com/NixOS/nixpkgs/pull/44866. There's definitely something non-standard going on in there since `xdg-open` does the right thing already.

**Comment by Spass1966** [comment]
@michaelpj I spoke too soon. After today's update everything works correctly for me. Also fixed Telegram Desktop's habit of opening my non-default browser.

**Comment by con-f-use** [comment]
It's not stale, still happens!

**Comment by DrymarchonShaun** [comment]
Seemingly still happens -- for what it's worth, I've noticed when clicking "show in folder" on a download and then right clicking on it in nemo and selecting "open with -> Other application" only some random wine entries show up.

**Comment by DrymarchonShaun** [comment]
Another thing of note - if i go into Settings -> General -> "What should Firefox do with other files?" and set it to "Ask whether to open or save files" the proper application shows up, and says it's the default.

**Comment by DrymarchonShaun** [comment]
@mweinelt @lovesegfault I'm not sure if y'all are aware of this issue's existence given how old it is, also not sure if this falls under your purview? If it doesn't, do you have any idea who might be able to shine some light on it?

**Comment by DrymarchonShaun** [comment]
Ok, further update to this - I usually run hyprland, which is where I'm seeing this issue, but I was curious and added gnome to my NixOS config temporarily just to test - if I instead of entering hyprland, enter gnome, this issue is gone and everything works as intended. Also, likely of note - with gnome still enabled in my config, but entering hyprland as usual, the issue *still* exists.

**Comment by din14970** [comment]
I can open attachments like pdf in thunderbird, but if I attempt to download them thunderbird crashes with a core dump. I'm on Nixos-unstable with thunderbird version 115.13.0. Not sure if this is related to the original issue, but it came up on Google. Anyone else face this issue?
