### ISSUE TITLE
tensorflow 2.4 depends on h5py 2.10 but is packaged with h5py 3.2

### ISSUE THREAD

**Issue by sekunho** [NixOS/nixpkgs#124599]
**Describe the bug**
h5py 3 is incompatible with tensorflow 2.4 (see [here](https://github.com/tensorflow/tensorflow/issues/44467)).

**To Reproduce**
1. Load model
2. Run script
3. Encounter error

```
# Error when loading model
model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Expected behavior**
It's supposed to be packaged with h5py 2.10 to avoid the bug.

**Notify maintainers**

@jyp @abbradar

**Comment by danieldk** [comment]
The general issue is that we cannot have multiple versions of Python packages in nixpkgs (since multiple versions may end up in the interpreter path). I think this is best resolved by updating to Tensorflow 2.5.0.

**Comment by CMCDragonkai** [comment]
Can we either:

1. Upgrade TF to 2.5, and backport that to 21.05 release
2. Downgrade h5py to version 2, and backport that to 21.05 release

At the moment TF on 21.05 release is broken  due not keras model loading.

**Comment by hsek** [comment]
But the restriction of being unable to have multiple versions for Python packages when nix supports it is a bit inconvenient, and unreliable. Since problems like this can appear in the future where a dependency has to be pinned to a specific version, but isn't. I don't really know how things are under the hood though. I'm fairly new to using nix for packaging things.

**Comment by CMCDragonkai** [comment]
Upgrading to 2.5 TF is probably the best way. Hoping to look into this later.

**Comment by CMCDragonkai** [comment]
The 2.5 MR was merged by accident, this is still not resolved.
