### ISSUE TITLE
tdesktop takes 30s to show the main window with pipewire

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#128514]
**Describe the bug**

When running `telegram-desktop`, it takes 30s to show the main window. No CPU/network usage during the blocking time.

**To Reproduce**
1. Checkout nixpkgs at 88226ea038e538e09c272a7c56ba73c3f5eed57f (tdesktop 2.9.0, pipewire 0.3.33)
2. `nix-build . -A tdesktop`
3. `./result/bin/telegram-desktop`

Start log:
```
(.telegram-desktop-wrapped:2936815): lib_base-WARNING **: 22:52:38.528: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
lib_base-Message: 22:52:38.529: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
lib_base-Message: 22:52:38.529: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.

(.telegram-desktop-wrapped:2936815): Telegram-WARNING **: 22:52:38.530: Application was built without embedded fonts, this may lead to font issues.
```
It's block here until 22:53:08 (seems exact 30s), then a timeout is printed, and the main window is now shown. (The last three `error` lines are not related since they also appear under pulseaudio)
```
AL lib: (EE) ALCpulseCapture_connectStream: Stream did not get ready: Timeout
error: : cannot open
error: : cannot open
error: : cannot open
```

**Expected behavior**
Show the main window immediately when running the application.

**Additional context**

Note that I'm on PC with microphone support but without microphone plugged. Not sure if it's related.

~~Is it related to pulseaudio?~~
Yes. The issue only exists for pipewire with pulse emulation. It shows the main window in 2s for pulseaudio.

I'm using pipewire without pulseaudio. Here's my configuration:
```nix
{
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };
}
```

**Notify maintainers**

@primeos @abbradar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.42, NixOS, 21.11.20210618.33d42ad (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/store/6zl4j413gbg98slcqkhhyi5fnw8ri8ra-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- tdesktop
# a list of nixos modules affected by the problem
module:
```

**Comment by jansol** [comment]
The configuration snippet you posted ENABLES pulseaudio emulation in pipewire. There was indeed an issue like this in the pulse emulation but it was fixed over half a year ago. FWIW telegram-desktop opens its window in ~2s here.

**Comment by primeos** [comment]
@oxalica X11 or Wayland? On Wayland it could be https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start and there was also a Telegram-Desktop bug once (the Wayland support isn't quite there yet).

**Comment by oxalica** [comment]
> X11 or Wayland?

X11 with KDE.
```
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
```

**Comment by oxalica** [comment]
I tried pulseaudio without pipewire, and the issue is gone. So it is clearly related to pipewire's pulse emulation. I just updated the title and description.

**Comment by oxalica** [comment]
> is this still a thing?

Yes. It's still reproduced on current `nixos-unstable` 88226ea038e538e09c272a7c56ba73c3f5eed57f 

Note that I'm on PC with microphone support but without microphone plugged. Not sure if it's related.

**Comment by jansol** [comment]
Can you get some logs from pipewire, pipewire-media-session and pipewire-pulse from, when this happens? They should show up in `journalctl --user`.

**Comment by oxalica** [comment]
I found an issue of tdesktop which says it's a bug of pipewire: https://github.com/telegramdesktop/tdesktop/issues/16240
But it doesn't have any details.

**Comment by oxalica** [comment]
It's fixed in current `nixos-unstable` with pipewire 0.3.34 and tdesktop 2.9.3
