### ISSUE TITLE
Telegram client (tdesktop) shows most text in monospace

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#129733]
**Describe the bug**
After a `nixos-rebuild` and booting into the resulting new system, Telegram showed most UI and content text in some monospace font. Previously such text wasn't in monospace. Some other fonts seem also different, e.g. a serif italic proportional font where Telegram used to have sans italic proportional font.

**To Reproduce**
1. be on nixpkgs-unstable
2. launch `telegram-desktop`

or:
1. be in a checkout of `nixpkgs` `master` (currently f29159e2e8f5484eb64d82b9dcb8e15f205f781c)
2. `nix run -f . tdesktop -c telegram-desktop`

**Expected behavior**
Only text intended to represent code or similar stuff should be shown in monospace, other text in a proportional font.

**Screenshots**
How it looked in `/nix/store/1d709yyhi0x54nrmsy4czwrbzsb9blc6-nixos-system-nixos-21.11pre300226.20887e4bbfd/sw/bin/telegram-desktop` a.k.a. `/nix/store/js89hmvfpki2v2b2fdyfkpyzakfkaj0l-telegram-desktop-2.8.4/bin/telegram-desktop`:

![Bildschirmfoto von 2021-07-09 10-49-16](https://user-images.githubusercontent.com/97746/125052611-71985880-e0a4-11eb-9d35-c1d767838ae2.png)

How it looks in `/nix/store/rn54rx0aa1r2mvak88ffibb3xidn75fn-nixos-system-nixos-21.11pre300903.00c86ad1463/sw/bin/telegram-desktop` a.k.a. `/nix/store/fyw97fawn0zy31gxyvgiamiz7bgqkxma-telegram-desktop-2.8.4/bin/telegram-desktop`:

![Bildschirmfoto von 2021-07-09 10-50-56](https://user-images.githubusercontent.com/97746/125052655-7f4dde00-e0a4-11eb-972f-b973a45594a6.png)

**Additional context**
Manually launching the new Telegram version `/nix/store/fyw97fawn0zy31gxyvgiamiz7bgqkxma-telegram-desktop-2.8.4/bin/telegram-desktop` from a system bootet into the old NixOS generation `/nix/store/1d709yyhi0x54nrmsy4czwrbzsb9blc6-nixos-system-nixos-21.11pre300226.20887e4bbfd` has the same effect.

**Notify maintainers**

@primeos @abbradar

**Metadata**
Output of `nix-shell -p nix-info --run "nix-info -m"`:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.47, NixOS, 21.11pre300903.00c86ad1463 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre300903.00c86ad1463, nixos-unstable-21.03pre257780.e9158eca70a"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- tdesktop
# a list of nixos modules affected by the problem
module:
```

**Comment by jansol** [comment]
There are some upstream issues for telegram-desktop about its font handling. It hardcodes Open Sans (`opensans-ttf`) and there is no way to change it. Previously it would fall back to the system sans-serif font if Open Sans is not present, seems like it no longer does that. This could be related to the recent fontconfig update, I remember seeing another issue here that mentioned it.

**Comment by andresilva** [comment]
This is fixed with #129675.

**Comment by Kranzes** [comment]
Hopefully this can get into unstable ASAP.

**Comment by Hentioe** [comment]
I ran into a similar problem and found that the default font had not effective after some inspection. I don’t know if the upgrade of fontconfig can fix this?

My font configuration:

```nix
fonts = {
  enableDefaultFonts = true;
  fonts = with pkgs; [
    noto-fonts
    noto-fonts-cjk
    noto-fonts-extra
    noto-fonts-emoji
    noto-fonts-emoji-blob-bin
  ];

  fontconfig = {
    defaultFonts = {
      serif = [ "Noto Serif" ];
      sansSerif = [ "Noto Sans CJK SC"];
      monospace = [ "Noto Sans Mono CJK SC" ];
    };
  };
};
```

The results of the `fc-match` command:

```zsh
➜  ~ fc-match serif   
NotoSerif-Regular.ttf: "Noto Serif" "Regular"
➜  ~ fc-match sans-serif
NotoSans-Regular.ttf: "Noto Sans" "Regular"
➜  ~ fc-match monospace 
Hack-Regular.ttf: "Hack" "Regular"
```

**Comment by neonfuz** [comment]
I'm working on a package right now that's having the same issue. This package is a wrapped appimage, I just rebased against master and the issue is still here so I don't think the fontconfig change fixed it?

this is the package btw:
https://github.com/neonfuz/nixpkgs/blob/slippi-bin/pkgs/misc/emulators/slippi-bin/default.nix

**Comment by Kranzes** [comment]
Just wanted to add that this bug isn't only with tdesktop, this bug has even appeared inside the game Garry's Mod which im running through Steam 😆

**Comment by andresilva** [comment]
> I'm working on a package right now that's having the same issue. This package is a wrapped appimage, I just rebased against master and the issue is still here so I don't think the fontconfig change fixed it?
> 
> this is the package btw:
> https://github.com/neonfuz/nixpkgs/blob/slippi-bin/pkgs/misc/emulators/slippi-bin/default.nix

Master doesn't contain the fontconfig update that I linked, it was merged into staging. I assume that all bugs related to fonts across different apps that people are reporting are all related to the fontconfig upgrade and hopefully are all solved with #129675. I have only personally tested that it fixed the Telegram monospace problem since that's the app I was having a problem with.

**Comment by Artturin** [comment]
https://nixpk.gs/pr-tracker.html?pr=129675

**Comment by Kranzes** [comment]
This should take at least a week...

**Comment by Artturin** [comment]
Use a working nixos-unstable rev 

clone nixpkgs to ~/nixpkgs
```
git checkout 7229e6d646c
sudo nixos-rebuild switch -I nixpkgs=$HOME/nixpkgs
```

**Comment by das-g** [comment]
After hours of building I can confirm that the problem was indeed introduced by 9852c9e5b66f33c912b52bbf1e4e1369353ecc50. `tdesktop` built from 9852c9e5b66f33c912b52bbf1e4e1369353ecc50 is affected by the issue while `tdesktop` build from its only parent commit c9cc001679617321b64641cbfcf969fc749a8295 isn't affected.

**Comment by Artturin** [comment]
https://nixpk.gs/pr-tracker.html?pr=129675
is now in nixos-unstable
