### ISSUE TITLE
Last change in openSSH disables every public key type except DSA 

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#13393]
I've run into a problem which is the result a [bug](https://anongit.mindrot.org/openssh.git/commit/?id=ed08510d38) in openSSH (which will be fixed in 7.2), commit a7b7ac8bfb948f05c8956f8de23d806fb7686438 and the fact the `openssh.service.extraConfig` is prepended to `sshd_config`. So `PubkeyAcceptedKeyTypes +ssh-dss` effectively disables every public key type except DSA and I can't login via ssh anymore.
I think we should really deal with this `Match` problem either as proposed in #12265 or #1610.

**Comment by edolstra** [comment]
I've pushed a fix to order the default config before anything else. Can you check if that fixes the problem for you?

**Comment by rnhmjoj** [comment]
If this moves the configuration to the bottom of the file it should work. I'm building a vm to test it anyway.

**Comment by rnhmjoj** [comment]
Yes, it does. Thank you.

**Comment by l0b0** [comment]
It looks like this is still an issue. I had to add

```
Host *
    HostKeyAlgorithms rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-ed25519
```

to ~/.ssh/config as [suggested by a recent conversation](https://superuser.com/a/1485062/2259) to make IDEA able to talk to a Vagrant box.
