### ISSUE TITLE
(luksroot.nix) Add an option to request a pin when unlocking FIDO2 authenticator

### ISSUE THREAD

**Issue by smkuehnhold** [NixOS/nixpkgs#141824]
### Describe the bug
The NixOS module for LUKS partitions currently uses [this line](https://github.com/NixOS/nixpkgs/blob/61d49535d870c7f777f3b09ead65afec40c8e4a6/nixos/modules/system/boot/luksroot.nix#L434) when unlocking a FIDO2 authenticator. This clearly works for the majority of cases, but unfortunately some authenticators _require_ a separate pin for unlocking (e.g. yubikey 5). Acquiring this pin before unlocking can be as easy as adding the `-P` or `--pin` flag after `fido2luks open`. Therefore I am requesting that this option be added to the module.

### Steps To Reproduce
1. Configure your LUKS partition as outlined in the [NixOS manual ](https://nixos.org/manual/nixos/stable/#sec-luks-file-systems-fido2)(except adding -P after `command` for every `fido2luks [command]` and typing in the appropriate pin).
2. Reboot and enter the salt value if one has been configured.
3. Receive the following error:
```
Authentication Error { cause: FidoError(

This operating requires a PIN but none was provided.) }
No FIDO2 key found, falling back to normal open procedure.
```

### Expected behavior
I expect there to be an option to require this pin in my NixOS configuration. Perhaps it could be named something like `boot.initrd.luks.devices.<name>.fido2.requiresPin`?

**Comment by peterwilli** [comment]
> ### Describe the bug
> 
> The NixOS module for LUKS partitions currently uses [this line](https://github.com/NixOS/nixpkgs/blob/61d49535d870c7f777f3b09ead65afec40c8e4a6/nixos/modules/system/boot/luksroot.nix#L434) when unlocking a FIDO2 authenticator. This clearly works for the majority of cases, but unfortunately some authenticators _require_ a separate pin for unlocking (e.g. yubikey 5). Acquiring this pin before unlocking can be as easy as adding the `-P` or `--pin` flag after `fido2luks open`. Therefore I am requesting that this option be added to the module.
> ### Steps To Reproduce
> 
>     1. Configure your LUKS partition as outlined in the [NixOS manual ](https://nixos.org/manual/nixos/stable/#sec-luks-file-systems-fido2)(except adding -P after `command` for every `fido2luks [command]` and typing in the appropriate pin).
> 
>     2. Reboot and enter the salt value if one has been configured.
> 
>     3. Receive the following error:
> 
> 
> ```
> Authentication Error { cause: FidoError(
> 
> This operating requires a PIN but none was provided.) }
> No FIDO2 key found, falling back to normal open procedure.
> ```
> 
> ### Expected behavior
> 
> I expect there to be an option to require this pin in my NixOS configuration. Perhaps it could be named something like `boot.initrd.luks.devices.<name>.fido2.requiresPin`?

Hi there. I faced the same problem (and thought of the same solution).
I posted the fix here: https://github.com/peterwilli/nixpkgs/tree/fido2luks-requires-pin

However, I can't get my YubiKey 5 NFC to be recognized at boot. Using `fido2luks` in my running desktop to add a key works fine, for some reason.

I think that maybe it has to do that I had to use the unstable fido2luks to get it recognized in the running desktop. I'll start fiddling with that.

In the meantime, can others chip in and try it out? Also let me know if it's good for making a PR.

**Comment by peterwilli** [comment]
Just by talking about it in my previous comment, I managed to figure out I needed the unstable fido2luks, I managed to do that by downloading https://github.com/NixOS/nixpkgs/commit/5ebb1dca9bb as zip and copy the `master` fido2luks to that commit, and adding my requires-pin branch on top of it.

However, it still doesn't work! It turns out you don't have a tty on initrd. I have to update my branch to use `read` or something. See https://github.com/shimunn/fido2luks/issues/14#issuecomment-680178277 for more info on that matter.

**Comment by peterwilli** [comment]
I fixed it and got it running with my YubiKey 5 NFC. Anyone who wants to try it out for verification: https://github.com/NixOS/nixpkgs/pull/143981

**Comment by jmbaur** [comment]
In #149241, the device PIN is stored under `/crypt-ramfs/passphrase`, which can then be reused by other luks devices if `boot.initrd.luks.reusePassphrases` is true.

**Comment by peterwilli** [comment]
> PR #149241 solves this same problem, however in #149241, the device PIN is stored under `/crypt-ramfs/passphrase`, which can then be reused by other LUKS devices if `boot.initrd.luks.reusePassphrases` is true.

I like your solution in where you use RamFS since it's sort of the same thing as what I do but reusable for next LUKS devices. I guess the answer as to which PR will be the best is if the ability to reuse a pin/passphrase weighs up to the guarantee a key will only be read once by one process at a time.

In any case it's cool to see how other people tackle this problem!

**Comment by Occhioverde** [comment]
Hi all!

Just for information, since the last reply to this issue is almost a year old: is a solution to this problem still being worked on?

I would really like to add my SoloKey as a LUKS key, but the presence of the PIN seems to be a dealbreaker…

**Comment by smkuehnhold** [comment]
@Occhioverde

PR #149241 contains the most recent work regarding this feature request that I personally am aware of. Unfortunately, it doesn't seem like it has been updated very recently,  so I went ahead and dropped a similar message.

I probably can't help with any implementation, but this is definitely something I am still interested in.
