### ISSUE TITLE
libc: purity problems with `/bin/sh` used to implement `system(3)`

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#1424]
http://hydra.nixos.org/build/7380540/nixlog/1/raw

Symptom: SIGSEGV

Failed workarounds: build fails on Hydra, i.e. on NixOS with chroot builds. 

Problem: build set LD_LIBRARY_PATH including glibc-2.18 /lib/. The make command used system() which called /bin/sh. /bin/sh is taken from something that existed at the beginning of the large build batch (either system or nix.conf). So it is linked against glibc-2.17. There seems to be some clash here...

This shows that system() impurity can bite us even under the ideal conditions: NixOS with chroot builds. Is it _now_ a good idea to patch glibc?

**Comment by edolstra** [comment]
Having thought about it a bit, I think the least intrusive/ugly solution is to have system() and popen() look for `sh` in `$PATH`, but only if we're in a Nix build. So basically to apply patch [1], but conditional at runtime on some environment variable like `$NIX_STORE`. This variable would have to be added to `sysdeps/generic/unsecvars.h` to prevent problems with setuid binaries. This approach would get rid of the dependency on /bin/sh in Nix builds, while circumventing the cyclic dependency between glibc and bash.

We would have to do something similar for gawk [2].

[1] https://gitorious.org/guix/guix/source/5d4fd2671aaadc5b0b7e0c331fa5e2a1d7e5c4d8:distro/packages/patches/glibc-bootstrap-system.patch
[2] https://gitorious.org/guix/guix/source/5d4fd2671aaadc5b0b7e0c331fa5e2a1d7e5c4d8:distro/packages/patches/gawk-shell.patch

**Comment by wmertens** [comment]
@edolstra so during a build it calls `sh` and otherwise `/bin/sh`? Won't
that give purity problems outside builds (as well as hard-to-debug issues
when a different `sh` ends up in the path)?

If not `/bin/sh`, how do we get the full path to sh in glibc?

**Comment by edolstra** [comment]
Yes, so this would only change behaviour during builds.

**Comment by wmertens** [comment]
I don't know, somehow using sh from PATH seems more troublesome than
creating a glibc+bash package (an approach that might also work on Darwin's
libSystem).

I was also thinking that it wouldn't solve
https://github.com/NixOS/nixpkgs/issues/2835 but that's just a matter of
running patchShebangs.

So basically I can't come up with any real objections :)

**Comment by wmertens** [comment]
Please read https://github.com/NixOS/nixpkgs/pull/4998#issuecomment-71816223 and comment here or there.

**Comment by copumpkin** [comment]
I have another approach to the glibc problem (that I was considering implementing for libSystem on darwin):

1. Patch your libc to not mention /bin/sh ,but instead to call a function (or just look at an external symbol) to find out what shell to use, and allow undefined symbols during linkage. Call this package `rawLibc` or something like it.
2. Have bash depend on `rawLibc`, but patch it to define the missing symbol for the shell, pointing to itself.
3. Make a wrapper package around `rawLibc` that depends on bash as well, and also defines the missing symbol to point at the bash in question. It then re-exports libc + the extra symbol and pretends to be a complete libc. On darwin, we have explicit re-exports of symbols, and on linux the glibc so can just be a linker script that points to `rawLibc` and the little shim that defines the symbol.

**Comment by Profpatsch** [comment]
(triage) this looks like a bigger design problem, has a solution been found in the meantime?

**Comment by Ericson2314** [comment]
I might have a general solution with https://github.com/NixOS/nix/issues/1080

**Comment by shlevy** [comment]
@Ericson2314 https://github.com/NixOS/nixpkgs/pull/4998 already did basically your suggestion there, except all in one output instead of multiple outputs.

**Comment by Ericson2314** [comment]
@shlevy yes in this case they are equivalent and I wish that had happened.

**Comment by gilligan** [comment]
What is the status with this? Is this still unsolved?

**Comment by 7c6f434c** [comment]
Well, our glibc still includes a reference to `/bin/sh`

I dunno, maybe builds should be allowed to override parts of the chroot environment with store paths?

**Comment by 7c6f434c** [comment]
Well, this issue will probably still bite us ubt rarely.

One more option, I guess: sandbox could use a `/bin/sh` being a statically linked binary delegating to the `sh` mentioned in `$NIX_BIN_SH`, with build-time `stdenv`'s `sh` as the default. As it would be used only in the build sandbox, horrible setuid secuity issues with this approach are moot. And then `stdenv.mkDerivation` could make sure that `stdenv.shell` is used just by setting a variable.

**Comment by bjornfor** [comment]
> Well, this issue will probably still bite us but rarely.

For non-NixOS users, I think more than rarely.

At least it was annoying for me a year ago when I tried to run Nix-built programs with LD_LIBRARY_PATH wrappers and saw system() calls to Ubuntu's /bin/sh. The program crashed. (I don't remember if or how I fixed it.)

**Comment by 7c6f434c** [comment]
>> Well, this issue will probably still bite us but rarely.
>For non-NixOS users, I think more than rarely.

Well, this issue is only distinct from all the other `/bin/sh` purity discussions by being a problem even during a sandboxed build. Runtime problems often (but not always) are fixable with some namespace-based tricks like FHS envs.

**Comment by wmertens** [comment]
I think this is still a problem, and upon rereading, the glibc+bash/dash approach that @shlevy was working on still seems the best.

**Comment by shlevy** [comment]
@wmertens See https://github.com/NixOS/nixpkgs/pull/4998

**Comment by wmertens** [comment]
Oh wow forgot all about that discussion. It seems like we don't have a resolution everybody likes?

Currently afaict the impurity still exists, especially when sandboxing is not available. The proposed solutions are combining glibc and sh in a single package, or using sandboxing features (not always available).

**Comment by shlevy** [comment]
Another option would be to have a separate dynamic library that reexports everything in glibc + points to bash and link everything to that.

**Comment by rnhmjoj** [comment]
Did anything happen during the last decade? It seems the libcs are still using `/bin/sh` to implement `system()`.
Can't we simply follow [what Guix does](https://codeberg.org/guix/guix/src/branch/master/gnu/packages/base.scm#L1005) and replace /bin/sh with a statically-linked bash?

**Comment by domenkozar** [comment]
Note that [even Nix itself ships statically linked busybox](https://github.com/search?q=repo%3ANixOS%2Fnix%20sandbox%20shell&type=code) `/bin/sh` to execute builds due to madness in NixOS, I've noticed this when recently implementing a fix in [snix](https://github.com/cachix/snix/pull/2).
