### ISSUE TITLE
Can't build wkhtmltopdf since upgraded to 16.03 channel

### ISSUE THREAD

**Issue by dsferruzza** [NixOS/nixpkgs#14422]
## Issue description

Hi!

- I tried to upgrade NixOS to the `16.03` channel
- I got an error while building `wkhtmltopdf`
- I removed `wkhtmltopdf` from my package list to finish the upgrade
- I finished the upgrade and rebooted
- I still can't build `wkhtmltopdf` and get the following error:

```
building path(s) ‘/nix/store/fyg8qkyflj5wsidzbkwz34kijhfdw58k-wkhtmltopdf-0.12.2.4’
unpacking sources
unpacking source archive /nix/store/jk6nqx2jyv3f16bg38kmpwqcg0svr787-wkhtmltopdf
source root is wkhtmltopdf
patching sources
applying patch /nix/store/2b3ar6qspk9y65ml2df5bjzypyb970nj-makefix.patch
patching file src/image/image.pro
patching file src/pdf/pdf.pro
configuring
building
make flags: SHELL=/nix/store/w6rc026a5kw9zyvvapqq6li157ckvwq7-bash-4.3-p42/bin/bash
cd src/lib/ && /nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/bin/qmake /tmp/nix-build-wkhtmltopdf-0.12.2.4.drv-0/wkhtmltopdf/src/lib/lib.pro INSTALLBASE=/nix/store/fyg8qkyflj5wsidzbkwz34kijhfdw58k-wkhtmltopdf-0.12.2.4 -o Makefile
cd src/lib/ && make -f Makefile
make[1]: Entering directory '/tmp/nix-build-wkhtmltopdf-0.12.2.4.drv-0/wkhtmltopdf/src/lib'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT4_STATICPLUGIN_TEXTCODECS -DVERSION=0.12.2.4 -DFULL_VERSION=0.12.2.4 -DBUILDING_DLL -DQT_NODLL -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_XMLPATTERNS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/share/qt-4.8.7/mkspecs/linux-g++ -I. -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtCore -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtNetwork -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtGui -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtXmlPatterns -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtSvg -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtWebKit -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include -I../../include -I. -o loadsettings.o ../lib/loadsettings.cc
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT4_STATICPLUGIN_TEXTCODECS -DVERSION=0.12.2.4 -DFULL_VERSION=0.12.2.4 -DBUILDING_DLL -DQT_NODLL -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_XMLPATTERNS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/share/qt-4.8.7/mkspecs/linux-g++ -I. -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtCore -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtNetwork -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtGui -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtXmlPatterns -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtSvg -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include/QtWebKit -I/nix/store/rr5gf9daz1vfx7z7xsbz0az8685w475a-qt-mod-4.8.6/include -I../../include -I. -o multipageloader.o ../lib/multipageloader.cc
In file included from ../lib/multipageloader_p.hh:24:0,
                 from ../lib/multipageloader.cc:22:
../lib/multipageloader.hh:30:20: fatal error: QWebPage: No such file or directory
compilation terminated.
Makefile:385: recipe for target 'multipageloader.o' failed
make[1]: *** [multipageloader.o] Error 1
make[1]: Leaving directory '/tmp/nix-build-wkhtmltopdf-0.12.2.4.drv-0/wkhtmltopdf/src/lib'
Makefile:41: recipe for target 'sub-src-lib-make_default-ordered' failed
make: *** [sub-src-lib-make_default-ordered] Error 2
builder for ‘/nix/store/8yhw5sa5nyj0i09kdyyqypxb8v89w65v-wkhtmltopdf-0.12.2.4.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/fnfgc47cpw0p6zrqmsci5wsy7axg124l-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/wslr5dy1v0afrks2r0l6h9gpxsmnvz4w-nixos-system-nixos-hosting-16.03.498.f8a5d1e.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/wslr5dy1v0afrks2r0l6h9gpxsmnvz4w-nixos-system-nixos-hosting-16.03.498.f8a5d1e.drv’ failed
```

I believe the maintainer of the `wkhtmltopdf` package is @jb55 ; do you have any idea I could try to solve this?

### Steps to reproduce

I believe you just need to build `wkhtmltopdf` from the `16.03` channel.

## Technical details

* System: NixOS `16.03.498.f8a5d1e (Emu)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `16.03.498.f8a5d1e`

**Comment by jb55** [comment]
Looks like some qt deps couldn't be found. I'll look into this today.

**Comment by jb55** [comment]
You can cherry pick the fix onto your local release from here: https://github.com/jb55/nixpkgs/commit/56ff791a543d887db21daf36f0837736818109ce

I'm going to send a PR to nixpkgs tomorrow after some testing.

**Comment by jb55** [comment]
Should be fixed on `release-16.03` now

**Comment by dsferruzza** [comment]
The fix has been released today and works!
Thanks a lot!

**Comment by dsferruzza** [comment]
I might have talked too fast: `wkhtmltopdf` now compiles but it seems to fail when it needs to use SSL/TLS (either accessing a web page or one of its resources through HTTPS).

```
# nixos-version
16.03.581.e409886 (Emu)
# wkhtmltopdf -V
wkhtmltopdf 0.12.3.2 (with patched qt)
```

This works (only HTTP):
```
# wkhtmltopdf http://php.net test.pdf
Loading pages (1/6)
libpng warning: iCCP: known incorrect sRGB profile           ] 52%
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

But this doesn't:
```
# wkhtmltopdf https://github.com test.pdf
Loading pages (1/6)
QSslSocket: cannot call unresolved function TLSv1_client_method10%
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
Error: Failed loading page https://github.com (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: UnknownNetworkError
```

Any idea of what could be wrong?

**Comment by jb55** [comment]
yeah I think I know what's wrong: http://stackoverflow.com/a/10846849/10486

will update in a bit

**Comment by dsferruzza** [comment]
Hi @jb55 !

Any news on this?
I still have the error on `16.03.759.b10f61b` :(

**Comment by jb55** [comment]
working on it now :+1:

**Comment by jb55** [comment]
I have a fix here: https://github.com/NixOS/nixpkgs/pull/15443

**Comment by dsferruzza** [comment]
Cool :)

I saw it was merged into `master`. Does this mean it won't be available in the next `16.03` release? (#14521 was merged into `release-16.03`.)

**Comment by dsferruzza** [comment]
@jb55 did you see the previous message? is there a way to include this fix in `16.03`?

**Comment by jb55** [comment]
@dsferruzza I'll open a PR soon

**Comment by jb55** [comment]
@dsferruzza done: #16373

**Comment by dsferruzza** [comment]
Nice! Thanks a lot!
