### ISSUE TITLE
yarn sets $NODE env variable to the node version from nix which breaks some usages

### ISSUE THREAD

**Issue by ahmedelgabri** [NixOS/nixpkgs#145634]
### Describe the bug
`nixpkgs.yarn` (or `nixpkgs.nodePackages.yarn`) sets `$NODE` to a specific node version, which will it error out when used in a project that has strict engine requirements inside `package.json`

### Steps To Reproduce

I created a simple repo to be able to reproduce this issue https://github.com/ahmedelgabri/nix-yarn-issue

1. make sure to install `nixpkgs.yarn` & `nixpkgs.fnm` (or `nvm`)
2. Clone the repo
3. Run `fnm use --install-if-missing` to install the version from `.nvmrc` file
4. Validate that you get the correct version `node -v` & `which node` should point to the `node` coming from `fnm`
5. Run `yarn start`, it shouldn't run & you will get this error

```shell
error nix-yarn-issue@1.0.0: The engine "node" is incompatible with this module. Expected version ">= 16". Got "14.18.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

6. Run this command

```shell
yarn env | grep -E "\"(NODE|npm_node_execpath|npm_config_user_agent)\""
```

The output should look like this

```shell
"NODE": "/nix/store/d37aprv8pxqpslag1yq6n0q2q0fnpqwg-nodejs-14.18.1/bin/node",
"npm_node_execpath": "/nix/store/d37aprv8pxqpslag1yq6n0q2q0fnpqwg-nodejs-14.18.1/bin/node",
"npm_config_user_agent": "yarn/1.22.17 npm/? node/v14.18.1 darwin x64",
```

The problem is that `nix` sets the `NODE` environment variable to the `nix` node executable, which then `yarn` picks up and sets [`npm_node_execpath`](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/util/execute-lifecycle-script.js#L80) to the same value.

I tried to search the repo to find where exactly this is happening but I couldn't really find it.

Overriding `NODE` is not the solution because this doesn't affect `npm_config_user_agent` & will still error out. 

So doing this doesn't work

```shell
export NODE=$(which node) yarn start
```

It will result in the same error here 

```shell
error nix-yarn-issue@1.0.0: The engine "node" is incompatible with this module. Expected version ">= 16". Got "14.18.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

because the output looks like this

```shell
"NODE": "/Users/ahmed/.fnm/node-versions/v16.13.0/installation/bin/node",
"npm_node_execpath": "/Users/ahmed/.fnm/node-versions/v16.13.0/installation/bin/node",
"npm_config_user_agent": "yarn/1.22.17 npm/? node/v14.18.1 darwin x64", # this is not correct still
```

This problem doesn't happen if `yarn` is installed using `homebrew` or directly `curl -o- -L https://yarnpkg.com/install.sh | bash`.

This is the result when using `yarn` which is installed using `homebrew` 

```shell
"NODE": "/Users/ahmed/.fnm/node-versions/v16.13.0/installation/bin/node",
"npm_node_execpath": "/Users/ahmed/.fnm/node-versions/v16.13.0/installation/bin/node",
"npm_config_user_agent": "yarn/1.22.17 npm/? node/v16.13.0 darwin x64",
```

### Expected behavior

That `yarn` works correctly & switch `NODE`, `npm_node_execpath` & `npm_config_user_agent` when the node version is changed.

### Notify maintainers

@DamienCassou (_sorry if you are not the maintainer but I couldn't mention anyone from the [maintainer list](https://github.com/NixOS/nixpkgs/blob/c5ed8beb478a8ca035f033f659b60c89500a3034/pkgs/development/tools/yarn/default.nix#L27)_)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.1.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(ahmed): `"darwin, nixpkgs-21.05pre286546.2cca79be09c"`
 - nixpkgs: `/nix/store/vpgzs19895khmlgjryi4y9w7cd2br1m5-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by DamienCassou** [comment]
I have no clue about this issue, I'm sorry.

/cc @offlinehacker @screendriver

**Comment by Artturin** [comment]
```
nix why-depends ".#yarn" ".#nodejs" --all
/nix/store/yg5c88hv8p37rd1nm2s7ly6hp8jq9byh-yarn-1.22.17
└───libexec/yarn/bin/yarn.js: …#!/nix/store/rdagrwgmq8n9jcs5iq5xpcxcxnh0lcc7-nodejs-14.18.1/bin/node../* esl…
    libexec/yarn/bin/yarnpkg: …#!/nix/store/rdagrwgmq8n9jcs5iq5xpcxcxnh0lcc7-nodejs-14.18.1/bin/node.require…
    libexec/yarn/lib/cli.js: …#!/nix/store/rdagrwgmq8n9jcs5iq5xpcxcxnh0lcc7-nodejs-14.18.1/bin/node.module.…
    → /nix/store/rdagrwgmq8n9jcs5iq5xpcxcxnh0lcc7-nodejs-14.18.1
```
there's a nodejs14 shebang in those
```
#!/nix/store/rdagrwgmq8n9jcs5iq5xpcxcxnh0lcc7-nodejs-14.18.1/bin/node
```

**Comment by ahmedelgabri** [comment]
@Artturin any clue how can this be changed? looking at the derivation it seems like _something_ happens at the build phase because the install phase is a simple symlinking https://github.com/NixOS/nixpkgs/blob/5715d5b507362b1d9c87317d874e47e33b0eabd6/pkgs/development/tools/yarn/default.nix

**Comment by samuela** [comment]
I'm seeing the exact same issue using the `nodejs-16_x` and `yarn` packages as of c11d08f02390aab49e7c22e6d0ea9b176394d961. I have the following in my `package.json`:
```
  "engines": {
    "node": ">=16"
  },
```
But I'm seeing the following when trying to run yarn:
```
[nix-shell:~/dev/cuddlefish/next]$ node --version
v16.13.0

[nix-shell:~/dev/cuddlefish/next]$ yarn run dev
yarn run v1.22.17
error next@: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.18.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
which is obviously a contradiction. I have no idea where 14.18.1 is coming from besides the fact that it is the current `nodejs` version for the nixpkgs commit I'm on.

**Comment by samuela** [comment]
Any known workaround for this?

**Comment by ahmedelgabri** [comment]
@samuela override doesn't solve the problem if you work with different projects & everyone requires a different node version this will still break.

**Comment by samuela** [comment]
Totally, it's just a hack for the time being. I'd still like to see this resolved properly as well!

**Comment by thall** [comment]
With overlay:
```
nixpkgs.overlays = [(
  self: super: {
    yarn = super.yarn.override {
      nodejs = pkgs.nodejs-16_x;
    };
  }
)];
```

**Comment by ahmedelgabri** [comment]
@thall This doesn't solve the problem. Because now `yarn` will not work with any project that's using an older version 

https://github.com/NixOS/nixpkgs/issues/145634#issuecomment-973978780

The reason why the shebang should stay the same is this, `yarn` will work as expected in any project & picking up the project version correctly.

**Comment by Scoder12** [comment]
The override works for `pkgs.yarn` but not `pkgs.nodePackages.yarn`.

**Comment by thall** [comment]
> @thall This doesn't solve the problem. Because now `yarn` will not work with any project that's using an older version
> 
> [#145634 (comment)](https://github.com/NixOS/nixpkgs/issues/145634#issuecomment-973978780)

@ahmedelgabri  Yes, I know that, its not a solution, just a workaround that I wanted to share.

**Comment by j-a-m-l** [comment]
I've also this problem, @ahmedelgabri, and I've fixed it in a `shell.nix` to have a reproducible local environment for each project:

New project:
```nix
{ pkgs ? import <nixpkgs> {
  overlays = [(
    self: super: {
	  yarn = super.yarn.override {
	    nodejs = pkgs.nodejs-18_x;
	  };
    }
  )];
} }:
  pkgs.mkShell {
    nativeBuildInputs = with pkgs; [
      nodejs-18_x
      yarn
    ];
    buildInputs = [ ];
}
```

Other, older, project, does not need the overlay:
```nix
{ pkgs ? import <nixpkgs> { } }:
  pkgs.mkShell {
    nativeBuildInputs = with pkgs; [
      nodejs-16_x
      yarn
    ];
    buildInputs = [ ];
}
```

**Comment by tennox** [comment]
> The override works for `pkgs.yarn` but not `pkgs.nodePackages.yarn`.

To resolve this (also useful for e.g. `nodePackages.pnpm`) it can be achieved by overlaying the default `nodejs` package:
```nix
overlays = [ (self: super: {
    nodejs = pkgs.nodejs-16_x;
}) ]
```

which is then used to [build `nodePackages`](https://github.com/NixOS/nixpkgs/blob/5466ae6f3fed81b585d206419137ae955040b4f5/pkgs/development/node-packages/composition.nix#L5), so `nixpkgs.nodePackages.pnpm` will be using that version of nodejs:
```
$ pnpm node --version
v16.17.1
```

**Comment by kagworld** [comment]
seems to be using the wrong version
```
$ yarn node -v
yarn node v1.22.18
v14.20.1
...

```
workaround
```
$ node `which yarn` node -v
yarn node v1.22.18
v18.9.1
```

**Comment by davidpfarrell** [comment]
I was in the process of creating a new issue but luckily discovered this so I'll share my thoughts/findings here:

---

The [decision](https://github.com/NixOS/nixpkgs/commit/7fd0d020a559780d881ca46de336ab4a789c9f0f#diff-54a0c0fa5bfc62ede90d1e4b9e7e10226650ec9ae2587fdea489a4cc3d7c6745R17) to symlink `yarn` to `bin/yarn.js` instead of `bin/yarn` makes it impossible invoke yarn directly using a custom node version.

The [official yarn package](https://github.com/yarnpkg/yarn/tree/master/bin) has `yarn` as a shell script and `yarn.js` as a node script

_bin/yarn_
```bash
#!/bin/sh
```

_bin/yarn.js_
```bash
#!/usr/bin/env node
```

Additionally, `yarn.js` will use whichever `node` version is first on the path.

HOWEVER, after being nixified, the `#!` expressions become hard-coded and we lose the dynamic nature of the original:

_fresh install of yarn_
```bash
$ nix-shell -p yarn

$ which yarn
/nix/store/xblz3z89rsnfmmj1zyji3n3v2rvrp2m4-yarn-1.22.19/bin/yarn
```

_check path-installed commands_
```shell
$ ls -l `dirname \`which yarn\``

total 0
lrwxr-xr-x 1 root nixbld 27 Dec 31  1969 yarn -> ../libexec/yarn/bin/yarn.js
lrwxr-xr-x 1 root nixbld 27 Dec 31  1969 yarnpkg -> ../libexec/yarn/bin/yarn.js
```

_check #! settings of installed commands_
```shell
$ head -1 `dirname \`realpath \\\`which yarn\\\`\``/yarn{,.js}

==> /nix/store/xblz3z89rsnfmmj1zyji3n3v2rvrp2m4-yarn-1.22.19/libexec/yarn/bin/yarn <==
#!/nix/store/ka6rabx4lz7m3habrjhh8hvbgxbz8r98-bash-5.2-p15/bin/sh

==> /nix/store/xblz3z89rsnfmmj1zyji3n3v2rvrp2m4-yarn-1.22.19/libexec/yarn/bin/yarn.js <==
#!/nix/store/kvlngvm6agicknyj02m93zbql3g39kw2-nodejs-18.15.0/bin/node
```

So when `yarn.js` is invoked directly, it will ALWAYS use whichever version of node is hard-coded in the `#!`.

However, if we could invoke the yarn shell script, it will check the path for which node version to use.

My recommended fix:

Modify the nix pkg installation steps to symlink `yarn` to the `yarn` shell script and not the `yarn.js` node script.

Additionally, I think hard-coding the #! in the `yarn.js` script is a bit of a bug, but not sure if there's a configuration option in the nixpkg to skip the fixup for that script?

**Comment by Denperidge** [comment]
Adding that the bug is still affecting things in NixOS 24.05 sadly

**Comment by ahmedelgabri** [comment]
I think I will close the issue because, at the time I opened this, I was new to Nix and was a bit more used to things installed globally with Homebrew and stuff… 

3 years later I don't think this is a bug, because things like nix shell or flakes devShells are better to manage project dependencies locally and not in a global way. and this is how I work now, I don't install anything globally. 

Any project I'm working on either has `shell.nix` or `flake.nix` which is automatically loaded with `direnv` and will use `yarn` with the same node version I use with nix like what @j-a-m-l or @thall suggested above.
