### ISSUE TITLE
atom: broken dependencies with nixpkgs-master

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#14660]
## Issue description
After a `nixos-rebuild switch -I nixpkgs=~/dev/nixpkgs`, Atom no longer works and complains with the following error message:
```
/nix/store/r7pij9zh7jpnqkavwrv11ymww99jb33n-atom-1.6.2/share/atom/atom: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
```
Note that running `nixos-rebuild switch` again the current version of `nixos-unstable-small` works just fine. (which is https://nixos.org/releases/nixos/unstable-small/nixos-16.09pre80416.9d0e57b//nixexprs.tar.xz)
This does not seem to be related to Atom itself, since it has not changed.

### Steps to reproduce
- Checkout master (I am at 18a6403c5964b90abbfe33d18472c2ebed31eb90)
- `nixos-rebuild switch -I nixpkgs=~/dev/nixpkgs`
- Run Atom

## Technical details

* System: 16.09.git.18a6403 (Flounder)
* Nix version: nix-env (Nix) 1.12pre4523_3b81b26
* Nixpkgs version: "16.09pre80416.9d0e57b"

**Comment by abbradar** [comment]
I've fixed it as part of #14658: https://github.com/NixOS/nixpkgs/pull/14658/commits/d7a23ee50a676f0a2412eb8cd3339cc945f209c8

**Comment by vcunat** [comment]
Can someone confirm it really works again? (I don't use it, so I'm not a good judge of that.)

**Comment by abbradar** [comment]
FWIW I'm not using it too and tested that I "fixed" it by running and observing window with "Getting started" or something like that.

**Comment by vcunat** [comment]
OK, well, let anyone reopen in case the/some problems persist.

**Comment by NeQuissimus** [comment]
I am still not sure I understand why it broke in the first place... Could you explain this to me? :D
I mean, I see that you now changed the way the path is searched. But how did it break, considering the Atom derivation had not changed from what I can tell?

I am happy if it works again, I would just like to understand why :) Thanks!

**Comment by abbradar** [comment]
Post-multiple-outputs `buildEnv` by default links binary outputs, not library ones. That is, if you have package `foo` split into `foo.bin` and `foo.lib` (all libraries residing in latter), `buildEnv` wouldn't link `.lib` by default. This could have been fixed by adding `extraOutputsToInstall` argument for `buildEnv` but I instead removed `buildEnv` and used `makeLibraryPath` function (which does the right thing without another derivation).

**Comment by NeQuissimus** [comment]
I see, thanks :)

**Comment by vcunat** [comment]
Hmm, maybe that default isn't a good one. I focused on `systemPackages` at that time, but majority of call sites will have a different nature, it seems.

**Comment by abbradar** [comment]
From a brief look, `buildEnv` is used

1) In various wrappers to bring together things -- that's mostly `bin` outputs, occasionally non-splitted things like plugins.
2) To link libraries like in this case -- arguably this is an improper use and it should be done with `makeLibraryPath` instead (but cannot always be done this way, I think).
3) Misc cases -- for example, I want both `lib` and `bin` outputs in `buildFHSEnv`.
4) To, well, bring programs together.

So I think the current choice is okay but I don't have any numbers.

**Comment by vcunat** [comment]
I see you dropped `buildEnv` for that use case... but it should be enough to just pass it `extraOutputsToInstall` in similar cases.

**Comment by abbradar** [comment]
Well, I think that this use case is just invalid unless it's not used for `LD_LIBRARY_PATH` or `patchelf` but for something else which takes only one path. `makeLibraryPath` should also skip the cost of creating this environment altogether.

**Comment by vcunat** [comment]
Agreed.
