### ISSUE TITLE
Sublime Text needs libcurl dependency

### ISSUE THREAD

**Issue by dbeckwith** [NixOS/nixpkgs#146635]
### Describe the bug
See sublimehq/sublime_text#5022. This also affects Sublime Merge.

### Steps To Reproduce
1. Launch Sublime Text in the terminal with `sublime_text`
2. Observe warnings about failure to load from `libcurl.so`

### Expected behavior
Editor should launch without warnings

### Notify maintainers

@jtojnar @wmertens @demin-dmitriy @zimbatm @zookatron

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.77, NixOS, 21.05.4051.9e86f5f7a19 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.4051.9e86f5f7a19, nixos-unstable-21.11pre329341.9e70e9f732f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- sublime4
- sublime-merge
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
Right, noticed the same thing with Sublime Merge.

**Comment by dbeckwith** [comment]
Yes, Sublime Merge has the same issue. Will update the bug to reflect that.

**Comment by dbeckwith** [comment]
I suppose because of https://github.com/sublimehq/sublime_text/issues/5022#issuecomment-962722422 this is actually pretty low-priority. The warnings are annoying but I guess they only relate to checking for updates which isn't really relevant in NixOS.

**Comment by r-burns** [comment]
Is it possible to disable the auto update feature entirely? Seems appropriate when it's running from an immutable store path.

**Comment by dbeckwith** [comment]
Sublime does not _auto-update_, it just checks for updates and shows a notification. You can disable the update check notification with a [user preference](https://stackoverflow.com/a/35269421). However, this doesn't appear to stop it from attempting to load libcurl on startup. In order to do that it would probably require a feature request for Sublime to only load libcurl on demand when it actually goes to check for updates (if update checks aren't disabled).

**Comment by zookatron** [comment]
I have fixed this issue in the Sublime Merge application: https://github.com/NixOS/nixpkgs/pull/146934 I do not use Sublime Text version 4 so I have not had a chance to investigate the issue there yet but the solution is likely the same.

**Comment by zookatron** [comment]
I have fixed this issue in Sublime Text version 4 as well: https://github.com/NixOS/nixpkgs/pull/150471 Once this pull request is merged we should be able to close this issue.

**Comment by dbeckwith** [comment]
Thanks @zookatron!

**Comment by dbeckwith** [comment]
Also, just FYI, the [sublime devs said](https://github.com/sublimehq/sublime_text/issues/5022#issuecomment-974990436) curl is used for license validity checks and crash reporting as well as update checks.

**Comment by blakat360** [comment]
This is still an issue when running nix on manjaro.

I  have this flake::

``` nix
{
  description = "Terminal dev environment";

  inputs = { nixpkgs.url = "github:nixos/nixpkgs/nixos-21.11"; };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in {
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = with pkgs; [
          sublime4
	  curl
        ];
      };
    };
}

```

and this flake.lock

```
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1659446231,
        "narHash": "sha256-hekabNdTdgR/iLsgce5TGWmfIDZ86qjPhxDg/8TlzhE=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "eabc38219184cc3e04a974fe31857d8e0eac098d",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-21.11",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

running subl lol gives you the errors

**Comment by dbeckwith** [comment]
@blakat360 This issue was fixed in b1239b8d486135eb0696743578fbadc052235e72 which is in NixOS 22.05, but you seem to be using an earlier version (21.11). You'll need to upgrade to get this fix. I don't think including `curl` in the shell `buildInputs` will properly make it available to the sublime package.

**Comment by blakat360** [comment]
@dbeckwith that fixed it - serves me right for copy-pastaing a flake template off the web
