### ISSUE TITLE
rustc fail to build on Darwin

### ISSUE THREAD

**Issue by sirn** [NixOS/nixpkgs#15031]
## Issue description

The `rustc` package fails to build on Darwin with failures when it tries to test networking:

```
failures:
    sys::ext::net::test::basic
    sys::ext::net::test::iter
    sys::ext::net::test::test_connect_unix_datagram
    sys::ext::net::test::test_read_timeout
    sys::ext::net::test::test_read_with_timeout
    sys::ext::net::test::test_unix_datagram
    sys::ext::net::test::test_unix_datagram_recv
    sys::ext::net::test::test_unnamed_unix_datagram
    sys::ext::net::test::timeouts
    sys::ext::net::test::try_clone

test result: FAILED. 729 passed; 10 failed; 2 ignored; 0 measured
 
/private/var/folders/6g/7z1n53nn73s_ypxy9ypyy6yw0000gn/T/nix-build-rustc-2016-03-22-g6cc502c.drv-0/rust-6cc502c/mk/tests.mk:447: recipe for target 'tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-std.ok' failed
make: *** [tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-std.ok] Error 101
builder for ‘/nix/store/aa08ynri31iyaz93721y2qxihjwwq1li-rustc-2016-03-22-g6cc502c.drv’ failed with exit code 2
error: build of ‘/nix/store/aa08ynri31iyaz93721y2qxihjwwq1li-rustc-2016-03-22-g6cc502c.drv’ failed
```

### Steps to reproduce

1. Be on Mac OS X.
2. `nix-env -i rustc`

## Technical details

* System: Mac OS X 10.11.4
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre81657.9445bb2

**Comment by retrry** [comment]
You should try to update channel and install rust then. Channel just updated with rustc binaries. Build succeeds on Hydra: https://hydra.nixos.org/job/nixpkgs/trunk/rustc.x86_64-darwin.

I saw those test failures too, but somehow they disappeared for me so I have no idea what is happening :)

**Comment by matthewbauer** [comment]
@sirn I think this is fixed and can be closed, correct?

**Comment by sirn** [comment]
Hi, I haven't tried lately. I'll test later today (since Rust take a really long time to build on my machine.)

**Comment by sirn** [comment]
Sorry, just noticed the binary is already available. This works for me now. Closing. Thanks!

**Comment by acowley** [comment]
Unfortunately, the `rustc` and `cargo` bootstrapping setups don't work on `darwin`. It is hopefully a simple matter of splicing out the calls to `patchelf`, but I still see the above mentioned errors when building on darwin, so I won't open a PR as I can't actually build `rustc`.

Can anyone suggest why this at some point worked on hydra when it doesn't work locally for @sirn or I?
