### ISSUE TITLE
XFCE is slow and missing icons in current unstable channel

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#15174]
## Issue description

Since updating to 16.09pre82105.7465bcd (Flounder), XFCE takes an additional 10 seconds to initialize and become responsive from the login screen. Additionally, icon paths seem to be missing:
![screenshot - 05022016 - 01 50 55 pm](https://cloud.githubusercontent.com/assets/106511/14967782/0b619dee-106e-11e6-8283-f3030f3b63d5.png)

The slow startup is more annoying than the missing icons, although not having the battery indicator is a bit of a problem.

### Steps to reproduce

`nixos-rebuild switch --upgrade` in the unstable channel

```
  services.xserver = {
    enable = true;
    videoDrivers = [ "nvidia" ];
    };
    desktopManager.xterm.enable = false;
    desktopManager.xfce.enable = true;
  };
```

This same behavior happens on 2 independent laptops that I have both running NixOS.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

16.09pre82105.7465bcd (Flounder)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"16.09pre82105.7465bcd"

**Comment by andrewrk** [comment]
cc @edolstra @AndersonTorres

**Comment by vcunat** [comment]
I haven't noticed slow startup, but the icons are most likely due to splitting packages into multiple outputs (I've had this for many months now).

**Comment by wizeman** [comment]
FWIW, besides the missing icons I'm also experiencing a noticeably slower startup, just like @andrewrk.

**Comment by abbradar** [comment]
I've fixed DeaDBeeF's (it's a GTK3 application) icon in https://github.com/NixOS/nixpkgs/commit/f396fa8cb24dee446b00c9434401d1ad9c7eb4bb. Maybe it's related?

**Comment by andrewrk** [comment]
I'm not sure if this is related, but it appears that auto mounting my phone has stopped working too.

I have this in my config:

```
  services = {
    ntp.enable = true;
    locate.enable = true;
    dbus.enable = true;
    udisks2.enable = true;
    udev.packages = [ pkgs.libmtp ];
  };
```

Previously I could open thunar, plug in my android via USB, enable file transfer, and then copy files with thunar.

**Comment by vcunat** [comment]
Most likely you need
```nix
let # to fix highlighting
  udev.packages = [ pkgs.libmtp.out ];
```

**Comment by abbradar** [comment]
We may want to pick needed outputs in `udev.packages` instead. I'll make a patch later.

**Comment by andrewrk** [comment]
I tried `pkgs.libmtp.out`, did a rebuild switch, rebooted, and got the same behavior. No device listed in thunar.

**Comment by abbradar** [comment]
Interesting, it looks like its rules are in `.bin`. Try `libmtp.bin` -- we also may need to document properly where should udev rules reside.

**Comment by andrewrk** [comment]
`libmtp.bin` did it, thanks.

It's a bit concerning that nix doesn't catch errors like this, if you simply type something wrong it silently fails instead of complaining when you try to rebuild.

**Comment by abbradar** [comment]
We had a proposition recently to add "checked path" builtin, like `builtins.checkPath libmtp "lib/udev/rules.d"` and some syntactic sugar to make this easier. The idea is to check if the path does really exist in derivation before building something that depends on it. It would require changes both in Nix the daemon and Nix the language, though, and also an extension for `.drv` format (as I imagine). Don't expect it soon ;_;.

**Comment by vcunat** [comment]
IMO you can't have such functionality as standard language builtin, at least not without nasty consequences.

**Comment by abbradar** [comment]
I've noticed that `xfce4-display-settings` dialog box (opens when you attach a monitor) doesn't have any icons now. May be related.

**Comment by abbradar** [comment]
@andrewrk This particular problem has been fixed in cd5dd9f82e141a4d7f570bf483ee5e278b188480.

**Comment by andrewrk** [comment]
Great! Now all we have to do is wait for the new unstable to build successfully in Hydra.

**Comment by andrewrk** [comment]
I just updated to 16.09pre83796.d541e0d (Flounder) which includes cd5dd9f and it has the same problem.

**Comment by andrewrk** [comment]
Also, look at how broken pavucontrol is: 
![screenshot_2016-05-18_11-26-31](https://cloud.githubusercontent.com/assets/106511/15370348/72c83fb8-1ceb-11e6-85cb-001918aa7a09.png)

**Comment by boobiesinc** [comment]
tested: 16.09.git.f8177f7M (Flounder)
(I didn't wait for a hydra :P took 38 hours of compilation total)

This seems mostly fixed, except, what you see here:
![iconvirtualbox_nixos2_19_05_2016_22_42_03](https://cloud.githubusercontent.com/assets/19384416/15407560/2ccf3820-1e14-11e6-9f33-c4830b2dfe50.png)
![iconvirtualbox_nixos2_19_05_2016_22_41_40](https://cloud.githubusercontent.com/assets/19384416/15407564/2d2c0618-1e14-11e6-8474-3021e159b09d.png)
![iconvirtualbox_nixos2_19_05_2016_22_41_28](https://cloud.githubusercontent.com/assets/19384416/15407565/2d2c84bc-1e14-11e6-918f-8005d1647ed2.png)
![iconvirtualbox_nixos2_19_05_2016_22_41_10](https://cloud.githubusercontent.com/assets/19384416/15407562/2ced9450-1e14-11e6-8c61-38adbbfb7268.png)
![iconsvirtualbox_nixos2_19_05_2016_22_39_20](https://cloud.githubusercontent.com/assets/19384416/15407563/2d18c1de-1e14-11e6-8562-83988b271894.png)


aaaaand, this show-stopper for me https://github.com/NixOS/nixpkgs/issues/15474


see, pavu seems okay, @andrewrk :
![pavuvirtualbox_nixos2_19_05_2016_22_53_30](https://cloud.githubusercontent.com/assets/19384416/15407642/a3d9570c-1e14-11e6-861f-0c04641ab7be.png)

**Comment by andrewrk** [comment]
UI is completely missing in obs, I think this problem has to maybe do with qt or gtk or something.

![screenshot_2016-05-19_13-43-44](https://cloud.githubusercontent.com/assets/106511/15409014/c59790e0-1dc7-11e6-9088-b9f4653fe470.png)

**Comment by andrewrk** [comment]
Some programs are completely unusable.

**Comment by andrewrk** [comment]
```
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
```

**Comment by andrewrk** [comment]
pavucontrol gives many messages like this:

```
(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:9:37: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:10:37: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:11:31: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:12:39: The style property GtkButton:default-outside-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:13:30: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:14:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:15:31: The style property GtkWidget:interior-focus is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:16:40: The style property GtkButtonBox:child-internal-pad-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:17:40: The style property GtkButtonBox:child-internal-pad-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:18:36: The style property GtkButtonBox:child-min-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:19:35: The style property GtkButtonBox:child-min-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:20:36: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:21:38: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:22:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:26:33: The style property GtkMenu:horizontal-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:27:31: The style property GtkMenu:vertical-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:28:30: The style property GtkNotebook:initial-gap is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:29:30: The style property GtkNotebook:tab-overlap is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:30:27: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:31:47: The style property GtkProgressBar:min-horizontal-bar-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:32:44: The style property GtkProgressBar:min-vertical-bar-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:33:28: The style property GtkRange:slider-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:34:28: The style property GtkRange:stepper-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:35:31: The style property GtkRange:stepper-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:36:29: The style property GtkRange:trough-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:37:37: The style property GtkRange:trough-under-steppers is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:38:29: The style property GtkScale:value-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:41:37: The style property GtkScrollbar:min-slider-length is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:43:48: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:44:31: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:49:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:50:30: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:51:31: The style property GtkWidget:interior-focus is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:52:27: The style property GtkWidget:link-color is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:53:35: The style property GtkWidget:visited-link-color is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:94:13: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:95:13: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:95:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:100:13: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:101:21: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:105:21: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:113:27: The :prelight pseudo-class is deprecated. Use :hover instead.

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:123:30: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:179:30: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:180:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:31712): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:214:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.
```

**Comment by boobiesinc** [comment]
For me, this is the only message that I get
```
$ pavucontrol 

** (pavucontrol:1045): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```

**Comment by andrewrk** [comment]
I just updated to 16.09pre83955.cc41cb3 (Flounder) and this is still not fixed.

During the slow login time the hard drive light is blinking rapidly. Perhaps an icon/ui directory is specified incorrectly and it is searching for the files but never finds them.

**Comment by andrewrk** [comment]
Updated to 16.09pre84456.b7c38c7 (Flounder), problem still exists.

**Comment by andrewrk** [comment]
Updated to 16.09pre84513.2661511 (Flounder), problem still exists.

Why am I the only person who cares about this? Maybe I should go fix it myself.

**Comment by abbradar** [comment]
@andrewrk Strange thing is -- I don't observe any problems. I don't use XFCE's panel or desktop, but I set my themes through XFCE control panel (I use Adwaita from GNOME3) and everything looks and works fine.

**Comment by andrewrk** [comment]
@abbradar what does your pavucontrol look like? or network manager?
![screenshot_2016-06-01_14-23-36](https://cloud.githubusercontent.com/assets/106511/15726229/875dcb18-2804-11e6-83ac-2cb80debde85.png)

Can I see your /etc/nixos/configuration.nix?

**Comment by abbradar** [comment]
[Full screenshot](https://i.imgur.com/S0BeCl7.png). Notice taffybar as panel and xmonad as window manager, but otherwise it's managed by `xfce4-session`. Also there is a fallback icon instead of a proper "lock channels" one in pavucontrol but it doesn't seem related to this issue (was like this from the beginning of times I think).

[My configuration, desktop-specific part](https://github.com/abbradar/dotfiles/blob/master/nixos-book/configuration.nix)
[My configuration, common part](https://github.com/abbradar/dotfiles/blob/master/configuration-common.nix)

**Comment by andrewrk** [comment]
Thanks this is helpful. And what is your nixos-version?

**Comment by abbradar** [comment]
16.09.git.4ee615b (Flounder), but essentially it's b835f3e26202c0670103a1d622edbb438bae5fe1

**Comment by andrewrk** [comment]
@abbradar you just have xfce installed; you're not using `services.xserver.desktopManager.xfce.enable = true;` so I think this is why our environments are different.

**Comment by abbradar** [comment]
https://github.com/abbradar/dotfiles/blob/master/nixos-book/configuration.nix#L339

**Comment by andrewrk** [comment]
Oops, I forgot you linked to two configs. My mistake.

**Comment by abbradar** [comment]
FWIW I also load `xfce + xmonad` session.

And right now, when I rebooted to check that for you, I got Firefox unthemed! Possibly linked, investigating... pavucontrol and brothers work fine though.

**Comment by abbradar** [comment]
@andrewrk Do you have GTK2 applications themed? It appears I've lost all theming for them...

**Comment by joelmo** [comment]
I tried this config in a vm and things seem fine, startup time is normal:

```
{ config, lib, pkgs, ... }:

{
  imports = [ <nixos/tests/common/user-account.nix> ]; 
 
  services.xserver = {
    enable = true;
    desktopManager.xterm.enable = false;
    desktopManager.xfce.enable = true;
  };
}
```
![snapshot2](https://cloud.githubusercontent.com/assets/336631/15727441/bf3a347a-2856-11e6-9810-e35781e709a2.png)

**Comment by abbradar** [comment]
Fixed my problem -- I should have chosen not `xfce + xmonad` but `xfce` session to have XMonad started by `xfce4-session` (I usually do that but I forgot now). Otherwise all applications that are started via xmonad do not inherit Xfce's GTK theme.

**Comment by andrewrk** [comment]
Maybe I'll skim down to a more minimal system, and then do a git bisect in nixpkgs to figure out the first commit that went wrong.

**Comment by abbradar** [comment]
Have you tried moving `.xfce`, `.config` and `.local` somewhere and test if it helps? Or just create a new temporary user.

**Comment by andrewrk** [comment]
I tried creating  a new temporary user, and here's what happened:

 * The slowness from login time to desktop is gone.
 * Applications menu icon is still missing.
 * I added the power manager applet to the panel and that icon is still missing.
 * I opened pavucontrol and it looked correct.
 * I then opened the appearance settings window and clicking any of the options in the style tab cause pavucontrol to look bad like my earlier screenshots.

**Comment by joelmo** [comment]
@andrewrk do you use the setting services.xserver.layout?

**Comment by FRidh** [comment]
and now my pavucontrol is also messed up. I am using KDE5/Plasma. Because it suddenly got slow again I removed a bunch of dot files and that got it working again. But since then pavucontrol looks as @andrewrk showed, except for having Breeze icons.

**Comment by andrewrk** [comment]
I am extremely pleased to report that after updating to 16.09pre87524.2ef1c6b (Flounder) this issue is now fixed!
