### ISSUE TITLE
unknown hash algorithm ‘sha512’ when --upgrade to 16.03

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#15349]
## Issue description

Just
nix-channel --add "https://nixos.org/channels/nixos-16.03/" nixos
and trying to
nixos-rebuild dry-build --upgrade
It says
error: unknown hash algorithm ‘sha512’, at /nix/store/w4kmgqafriggn0xrb8xsgpm42y8nykrv-nixos-16.03.733.74139a6/nixos/pkgs/build-support/fetchurl/default.nix:101:3

### Steps to reproduce

Set up a new channel, then --upgrade

## Technical details

\# nixos-version 
15.09.1245.6edbeb8 (Dingo)
\# nix-env --version
nix-env (Nix) 1.10

Should i return to 15.09 and install something?

**Comment by groxxda** [comment]
I'm no expert but you can try following [this](https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_Nixpkgs) guide.

I think [this package](https://hydra.nixos.org/build/35197081) should work

**Comment by edolstra** [comment]
Try any `nixos-rebuild` action other than `dry-build`. It should fetch a version of Nix capable of understanding `sha512` first.

**Comment by domenkozar** [comment]
Huh, I thought I pushed a check for sha512 support.

**Comment by domenkozar** [comment]
We should probably just bump the required version to 1.11 for nixpkgs.

**Comment by comonoid** [comment]
> Try any nixos-rebuild action other than dry-build.
> It should fetch a version of Nix capable of understanding sha512 first.

Yes, it fetched it. But it can't install it for the same reason...

**Comment by comonoid** [comment]
> We should probably just bump the required version to 1.11 for nixpkgs.

I'm sorry, but how? All i tried, nix-install-package says "invalid package contents"
For example,
nix-install-package --non-interactive --url https://hydra.nixos.org/build/33406637/nix/pkg/nix-1.11.2-x86_64-linux.nixpkg
(web server says 404 at this links)
What i am doing wrong?...

**Comment by comonoid** [comment]
Here i got proper links —
http://hydra.nixos.org/job/nix/master/build.x86_64-linux/all
Still the same thing — unknown hash algorithm ‘sha512’

**Comment by edolstra** [comment]
Do you have Firefox in your configuration? That's the only package in 16.03 that currently uses a sha-512 hash. Maybe we should revert that to sha-1/256.

**Comment by comonoid** [comment]
> Do you have Firefox in your configuration?

Yes i do (did). VERY THANKS!
"nixos-rebuild build" is fine without firefox (i install it later) —
Installation finished. No error reported.
Now rebooting... ;-)

**Comment by comonoid** [comment]
All that you adviced me works fine
But all i did by myself caused my system to break ;-)
Now most of commands (nix-env, nix-collect-garbage and nixos-rebuild [...] --upgrade) return
error: creating statement: table ValidPaths has no column named ultimate
Oh... It happened after i installed from hydra.nixos.org/build/34883313
How can i uninstall it (so the system would install some proper nix)?...
\# nixos-version
16.03.733.74139a6 (Emu)
\# nix-env --version
error: creating statement: table ValidPaths has no column named ultimate
\# nix --version
nix (Nix) 1.12pre4591_c879a20

**Comment by edolstra** [comment]
What does `cat /nix/var/nix/db/schema` say?

**Comment by comonoid** [comment]
\# cat /nix/var/nix/db/schema
7

**Comment by edolstra** [comment]
Maybe you can just boot into an older configuration?

**Comment by comonoid** [comment]
There are no older configs because i was an idiot ;-(
I rebooted from "CD", nix-install did some (little) work and told the same (table ValidPaths has no column named ultimate) before the "Installation finished. No error reported."

**Comment by vcunat** [comment]
Hmm, I wonder what policy to use on master for sha512, e.g. see https://github.com/NixOS/nixpkgs/pull/15048#issuecomment-218992645 I suspect that using it in core packages at this point might unnecessarily complicate upgrading.
