### ISSUE TITLE
PulseAudio sound does not work in Electron apps

### ISSUE THREAD

**Issue by alyaeanyx** [NixOS/nixpkgs#158474]
### Describe the bug
Sound does not seem to work in Electron apps (for instance Element and FreeTube) with PulseAudio. The rest of the application works fine, but when they should normally play sound, the application stays mute and also doesn't show up in pavucontrol.

### Steps To Reproduce
1. Install a NixOS system with FreeTube and `sound.enable = true` and `hardware.pulseaudio.enable = true;`
2. Open FreeTube and try to play a video with sound

### Expected behavior
There should be sound

### Logs
This is the stdout of FreeTube when I try to play a video with sound:
```console
ALSA lib pcm.c:2576:(snd_pcm_open_conf) Unknown field libs
[1137736:0207/144459.635623:ERROR:alsa_util.cc(204)] PcmOpen: default,Invalid argument
ALSA lib pcm.c:2576:(snd_pcm_open_conf) Unknown field libs
[1137736:0207/144459.635699:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,Invalid argument
```

### Additional context
The problem occurs on nixos-unstable. I've tried to `git bisect` the bug, but I got stuck because `nixos-rebuild` had to build too many packages from scratch. So far, I've narrowed it down to bb141a865f62f9b1b00a954225c0c3eb7a500e43 (last known good commit) to a45818989adb69966bbaa992b9b0d1c743d4726e (first known bad commit).

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
alexandra@thermidor ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixos"`
 - channels(alexandra): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Obikawa** [comment]
I can confirm this. I also lost sound in LBRY 2 or 3 days ago.

Also, I am using Pipewire with Pulse compatibility.

**Comment by aopom** [comment]
On nixos unstable, I'm getting the same issue just running `amixer`, which is an ALSA tool:
```
$ amixer
ALSA lib control.c:1464:(snd_ctl_open_conf) Unknown field libs
amixer: Mixer attach default error: Invalid argument
```
ping @fps @L-as @AndersonTorres as you maintain some ALSA parts

**Comment by L-as** [comment]
This should already be fixed, but I think it's in staging. Can't remember PR number.

**Comment by L-as** [comment]
https://github.com/NixOS/nixpkgs/pull/157631

I think you can just close this.

**Comment by alyaeanyx** [comment]
Yep, thanks!

**Comment by Obikawa** [comment]
Did sound return to your applications, @alyaeanyx ?

LBRY still does not output sound on `master` branch.

**Comment by L-as** [comment]
That's because it's in staging.
