### ISSUE TITLE
kalendar: Icon theme "breeze" not found.

### ISSUE THREAD

**Issue by anthr76** [NixOS/nixpkgs#170352]
### Describe the bug

kalendar fails to launch.

### Steps To Reproduce
1. `nix-shell -p kalendar` on unstable

### Expected behavior
The application starts

### Additional context

```
QML debugging is enabled. Only use this in a safe environment.
Icon theme "breeze" not found.
Icon theme "breeze" not found.
fish: Job 1, 'kalendar' terminated by signal SIGSEGV (Address boundary error)
```

Also do we really need QML debugging?

### Notify maintainers

@SuperSandro2000 
@hqurve 
@chuangzhu

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(anthonyjrabbito): `"latest-22.05pre369988.1ffba9f2f68, nixos-21.11.337114.9887f024766"`
 - nixpkgs: `/nix/store/vixwi1vkcmhfj2lcc1x5mjf70jdsgrgk-source`
```

**Comment by hqurve** [comment]
Likely, the missing breeze icons is a red herring for the segmentation fault. You may have ran an older version of kalendar and the qmlcache needs to be updated (this should have been fixed according to one of the developers on the matrix channel). As stated here https://github.com/NixOS/nixpkgs/pull/153084 you could try delete ~/.cache/KDE/kalendar. If this works and everything looks normal, great!

If icons are missing or it still doesnt work, could you try adding breeze-icons to your system packages? I am not too sure if icons should be wrapped into the executable...

Also, what are you currently using? A desktop environment eg kde or gnome, or just a wm?

**Comment by anthr76** [comment]
So for whatever reason this doesn't actually work 

```
nix-shell -I 'https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz' -p kalendar 
```

Though installing it through my flake like I did before did so I installed `kalendar` `libsForQt5.breeze-icons` from unstable.

That definitely gets me further but I still can't launch for a DB issue now.

<details>

```shell
kalendar
QML debugging is enabled. Only use this in a safe environment.
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
akonadi.collectionattributetable
Error    : Table 'akonadi.collectionattributetable' doesn't exist in engine
status   : Operation failed
akonadi.collectionmimetyperelation
Error    : Table 'akonadi.collectionmimetyperelation' doesn't exist in engine
status   : Operation failed
akonadi.collectionpimitemrelation
Error    : Table 'akonadi.collectionpimitemrelation' doesn't exist in engine
status   : Operation failed
akonadi.collectiontable
Error    : Table 'akonadi.collectiontable' doesn't exist in engine
status   : Operation failed
akonadi.flagtable
Error    : Table 'akonadi.flagtable' doesn't exist in engine
status   : Operation failed
akonadi.mimetypetable
Error    : Table 'akonadi.mimetypetable' doesn't exist in engine
status   : Operation failed
akonadi.parttable
Error    : Table 'akonadi.parttable' doesn't exist in engine
status   : Operation failed
akonadi.parttypetable
Error    : Table 'akonadi.parttypetable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemflagrelation
Error    : Table 'akonadi.pimitemflagrelation' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtable
Error    : Table 'akonadi.pimitemtable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtagrelation
Error    : Table 'akonadi.pimitemtagrelation' doesn't exist in engine
status   : Operation failed
akonadi.relationtable
Error    : Table 'akonadi.relationtable' doesn't exist in engine
status   : Operation failed
akonadi.relationtypetable
Error    : Table 'akonadi.relationtypetable' doesn't exist in engine
status   : Operation failed
akonadi.resourcetable
Error    : Table 'akonadi.resourcetable' doesn't exist in engine
status   : Operation failed
akonadi.schemaversiontable
Error    : Table 'akonadi.schemaversiontable' doesn't exist in engine
status   : Operation failed
akonadi.tagattributetable
Error    : Table 'akonadi.tagattributetable' doesn't exist in engine
status   : Operation failed
akonadi.tagremoteidresourcerelationtable
Error    : Table 'akonadi.tagremoteidresourcerelationtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtable
Error    : Table 'akonadi.tagtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtypetable
Error    : Table 'akonadi.tagtypetable' doesn't exist in engine
status   : Operation failed

Repairing tables
akonadi.collectionattributetable
Error    : Table 'akonadi.collectionattributetable' doesn't exist in engine
status   : Operation failed
akonadi.collectionmimetyperelation
Error    : Table 'akonadi.collectionmimetyperelation' doesn't exist in engine
status   : Operation failed
akonadi.collectionpimitemrelation
Error    : Table 'akonadi.collectionpimitemrelation' doesn't exist in engine
status   : Operation failed
akonadi.collectiontable
Error    : Table 'akonadi.collectiontable' doesn't exist in engine
status   : Operation failed
akonadi.flagtable
Error    : Table 'akonadi.flagtable' doesn't exist in engine
status   : Operation failed
akonadi.mimetypetable
Error    : Table 'akonadi.mimetypetable' doesn't exist in engine
status   : Operation failed
akonadi.parttable
Error    : Table 'akonadi.parttable' doesn't exist in engine
status   : Operation failed
akonadi.parttypetable
Error    : Table 'akonadi.parttypetable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemflagrelation
Error    : Table 'akonadi.pimitemflagrelation' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtable
Error    : Table 'akonadi.pimitemtable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtagrelation
Error    : Table 'akonadi.pimitemtagrelation' doesn't exist in engine
status   : Operation failed
akonadi.relationtable
Error    : Table 'akonadi.relationtable' doesn't exist in engine
status   : Operation failed
akonadi.relationtypetable
Error    : Table 'akonadi.relationtypetable' doesn't exist in engine
status   : Operation failed
akonadi.resourcetable
Error    : Table 'akonadi.resourcetable' doesn't exist in engine
status   : Operation failed
akonadi.schemaversiontable
Error    : Table 'akonadi.schemaversiontable' doesn't exist in engine
status   : Operation failed
akonadi.tagattributetable
Error    : Table 'akonadi.tagattributetable' doesn't exist in engine
status   : Operation failed
akonadi.tagremoteidresourcerelationtable
Error    : Table 'akonadi.tagremoteidresourcerelationtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtable
Error    : Table 'akonadi.tagtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtypetable
Error    : Table 'akonadi.tagtypetable' doesn't exist in engine
status   : Operation failed
org.kde.pim.akonadiserver: Running DB initializer
org.kde.pim.akonadiserver: "\nSql error: Table 'akonadi.schemaversiontable' doesn't exist in engine QMYSQL: Unable to execute query\nQuery: ALTER TABLE SchemaVersionTable ADD COLUMN version INTEGER NOT NULL DEFAULT 0"
org.kde.pim.akonadiserver: Unable to initialize database.
org.kde.pim.akonadiserver: Shutting down AkonadiServer...
org.kde.pim.akonadicontrol: Application '/nix/store/p7wg7411qy61y914xw3qj0rhg73g236g-akonadi-21.12.3/bin/akonadiserver' exited normally...
org.kde.pim.akonadicore: Could not start/stop Akonadi!
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
akonadi.collectionattributetable
Error    : Table 'akonadi.collectionattributetable' doesn't exist in engine
status   : Operation failed
akonadi.collectionmimetyperelation
Error    : Table 'akonadi.collectionmimetyperelation' doesn't exist in engine
status   : Operation failed
akonadi.collectionpimitemrelation
Error    : Table 'akonadi.collectionpimitemrelation' doesn't exist in engine
status   : Operation failed
akonadi.collectiontable
Error    : Table 'akonadi.collectiontable' doesn't exist in engine
status   : Operation failed
akonadi.flagtable
Error    : Table 'akonadi.flagtable' doesn't exist in engine
status   : Operation failed
akonadi.mimetypetable
Error    : Table 'akonadi.mimetypetable' doesn't exist in engine
status   : Operation failed
akonadi.parttable
Error    : Table 'akonadi.parttable' doesn't exist in engine
status   : Operation failed
akonadi.parttypetable
Error    : Table 'akonadi.parttypetable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemflagrelation
Error    : Table 'akonadi.pimitemflagrelation' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtable
Error    : Table 'akonadi.pimitemtable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtagrelation
Error    : Table 'akonadi.pimitemtagrelation' doesn't exist in engine
status   : Operation failed
akonadi.relationtable
Error    : Table 'akonadi.relationtable' doesn't exist in engine
status   : Operation failed
akonadi.relationtypetable
Error    : Table 'akonadi.relationtypetable' doesn't exist in engine
status   : Operation failed
akonadi.resourcetable
Error    : Table 'akonadi.resourcetable' doesn't exist in engine
status   : Operation failed
akonadi.schemaversiontable
Error    : Table 'akonadi.schemaversiontable' doesn't exist in engine
status   : Operation failed
akonadi.tagattributetable
Error    : Table 'akonadi.tagattributetable' doesn't exist in engine
status   : Operation failed
akonadi.tagremoteidresourcerelationtable
Error    : Table 'akonadi.tagremoteidresourcerelationtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtable
Error    : Table 'akonadi.tagtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtypetable
Error    : Table 'akonadi.tagtypetable' doesn't exist in engine
status   : Operation failed

Repairing tables
akonadi.collectionattributetable
Error    : Table 'akonadi.collectionattributetable' doesn't exist in engine
status   : Operation failed
akonadi.collectionmimetyperelation
Error    : Table 'akonadi.collectionmimetyperelation' doesn't exist in engine
status   : Operation failed
akonadi.collectionpimitemrelation
Error    : Table 'akonadi.collectionpimitemrelation' doesn't exist in engine
status   : Operation failed
akonadi.collectiontable
Error    : Table 'akonadi.collectiontable' doesn't exist in engine
status   : Operation failed
akonadi.flagtable
Error    : Table 'akonadi.flagtable' doesn't exist in engine
status   : Operation failed
akonadi.mimetypetable
Error    : Table 'akonadi.mimetypetable' doesn't exist in engine
status   : Operation failed
akonadi.parttable
Error    : Table 'akonadi.parttable' doesn't exist in engine
status   : Operation failed
akonadi.parttypetable
Error    : Table 'akonadi.parttypetable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemflagrelation
Error    : Table 'akonadi.pimitemflagrelation' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtable
Error    : Table 'akonadi.pimitemtable' doesn't exist in engine
status   : Operation failed
akonadi.pimitemtagrelation
Error    : Table 'akonadi.pimitemtagrelation' doesn't exist in engine
status   : Operation failed
akonadi.relationtable
Error    : Table 'akonadi.relationtable' doesn't exist in engine
status   : Operation failed
akonadi.relationtypetable
Error    : Table 'akonadi.relationtypetable' doesn't exist in engine
status   : Operation failed
akonadi.resourcetable
Error    : Table 'akonadi.resourcetable' doesn't exist in engine
status   : Operation failed
akonadi.schemaversiontable
Error    : Table 'akonadi.schemaversiontable' doesn't exist in engine
status   : Operation failed
akonadi.tagattributetable
Error    : Table 'akonadi.tagattributetable' doesn't exist in engine
status   : Operation failed
akonadi.tagremoteidresourcerelationtable
Error    : Table 'akonadi.tagremoteidresourcerelationtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtable
Error    : Table 'akonadi.tagtable' doesn't exist in engine
status   : Operation failed
akonadi.tagtypetable
Error    : Table 'akonadi.tagtypetable' doesn't exist in engine
status   : Operation failed
org.kde.pim.akonadiserver: Running DB initializer
org.kde.pim.akonadiserver: "\nSql error: Table 'akonadi.schemaversiontable' doesn't exist in engine QMYSQL: Unable to execute query\nQuery: ALTER TABLE SchemaVersionTable ADD COLUMN version INTEGER NOT NULL DEFAULT 0"
org.kde.pim.akonadiserver: Unable to initialize database.
fish: Job 1, 'kalendar' terminated by signal SIGSEGV (Address boundary error)
```

</details>

I'm running sway a very minimal setup. I did wipe `~/.cache/KDE`

**Comment by hqurve** [comment]
Could it perhaps be a mismatch between unstable and stable? (I noticed that you have two different channels). I'm grasping as straws, I dont really know whats happening

**Comment by hqurve** [comment]
How far have you ever set up kalendar or anything which depends on akonadi on your system?

**Comment by anthr76** [comment]
I have yet to run anything KDE on the system it's a two week old system.

**Comment by anthr76** [comment]
```

~~> /nix/store/z29x8c3a9q3vnh39r9m9jyi96jxsph0d-akonadi-22.04.0/bin/akonadictl status                                  breeze-icons kalendar
Akonadi Control: stopped
Akonadi Server: stopped
Akonadi Server Search Support: available (Remote Search)
Available Agent Types: akonadi_knut_resource

anthonyjrabbito@rs2

->>                                                                                                                    breeze-icons kalendar

anthonyjrabbito@rs2

->> /nix/store/z29x8c3a9q3vnh39r9m9jyi96jxsph0d-akonadi-22.04.0/bin/akonadictl start                                   breeze-icons kalendar
org.kde.pim.akonadictl: Starting Akonadi Server...
Error: unable to execute binary akonadi_control

anthonyjrabbito@rs2

~~> /nix/store/z29x8c3a9q3vnh39r9m9jyi96jxsph0d-akonadi-22.04.0/bin/akonadi_control --help                             breeze-icons kalendar
Usage: /nix/store/z29x8c3a9q3vnh39r9m9jyi96jxsph0d-akonadi-22.04.0/bin/akonadi_control [options]
Akonadi Control Process
Do not run this manually, use 'akonadictl' instead to start/stop Akonadi.

Options:
  -h, --help         Displays help on commandline options.
  --help-all         Displays help including Qt specific options.
  -v, --version      Displays version information.
  --instance <name>  Namespace for starting multiple Akonadi instances in the
                     same user session
  --verbose          Make Akonadi very chatty
  ```

**Comment by anthr76** [comment]
Given that error above I was able to deduct akonadi was more to blame here. `rm -rf ~/.local/share/akonad` fixed it. Not having breeze-icon-themes in my shell didn't cause Kalendar to crash this time. So i'm going to close this issue, but this is definitely flakely and will need to be fixed somehow.
