### ISSUE TITLE
systemd initrd doesn't restore backlight levels

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixpkgs#178345]
With `boot.initrd.systemd.enable = true;`, my screen's brightness is reset to 100% on reboot. `systemd-backlight@leds:tpacpi::kbd_backlight.service` starts up but `systemd-backlight@backlight:amdgpu_bl0.service` doesn't. Not sure how to debug this. I'm on a thinkpad T14s.

**Clarification**: the issue is not that the brightness level is 100% in the initrd, but that it *stays* 100% after booting. In other words `systemd-backlight` *never* starts.

**Comment by ncfavier** [comment]
That didn't do it.

**Comment by ncfavier** [comment]
Interestingly I'm getting these errors in the log:

```
ACPI: video: Video Device [VGA] (multi-head: yes  rom: no  post: no)
input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:17/LNXVIDEO:00/input/input16
Serial bus multi instantiate pseudo device driver INT3515:00: error -ENXIO: IRQ index 1 not found
Serial bus multi instantiate pseudo device driver INT3515:00: error -ENXIO: Error requesting irq at index 1: -6
```

which points me to https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1893624 with a similar issue.

This looks like a hardware-specific problem so I'll close.

**Comment by NickCao** [comment]
This does not look like a hardware-specific or even driver issue. On my machine `systemd-backlight@backlight:intel_backlight.service` is not even active, but manually starting it works. In short there is a udev rule shipped by systemd in `/run/current-system/sw/lib/udev/rules.d/99-systemd.rules` saying
```
SUBSYSTEM=="backlight", TAG+="systemd", IMPORT{builtin}="path_id", ENV{SYSTEMD_WANTS}+="systemd-backlight@backlight:$name.service"
```
And it should bring these units up.

**Comment by NickCao** [comment]
Setting
```nix
{
  boot.initrd.systemd.additionalUpstreamUnits = [ "systemd-backlight@.service" ];
  boot.initrd.services.udev.packages = [ config.systemd.package ];
}
```
do brings the unit up, but now it fails with `Failed to locate executable /nix/store/...-systemd-stage-1-251.3/lib/systemd/systemd-backlight: No such file or directory`, like a missing store path in the initrd.

**Comment by ncfavier** [comment]
> Setting
> 
> ```nix
> {
>   boot.initrd.systemd.additionalUpstreamUnits = [ "systemd-backlight@.service" ];
>   boot.initrd.services.udev.packages = [ config.systemd.package ];
> }
> ```
> 
> do brings the unit up, but now it fails with `Failed to locate executable /nix/store/...-systemd-stage-1-251.3/lib/systemd/systemd-backlight: No such file or directory`, like a missing store path in the initrd.

Doesn't do anything for me, even after adding `boot.initrd.systemd.storePaths = [ "${config.boot.initrd.systemd.package}/lib/systemd/systemd-backlight" ];`. I still see the IRQ error I mentioned above, which is why I'm pretty sure it's a hardware issue in my case.

Also, adding `boot.initrd.services.udev.packages = [ config.systemd.package ];` somehow delays the vconsole setup until after the LUKS decryption, so I have to type in my passphrase in QWERTY.

**Comment by NickCao** [comment]
I'm curious about the behavior change of systemd/udev when systemd stage 1 is in use, I thought the `systemd-backlight@.service` ought to be activated after switching root, not even relevant to the initrd, however the reality is quite the opposite.

**Comment by lheckemann** [comment]
> I'm also not sure if/how systemd passes this state into the initramfs though, so this may fundamentally not work?

I still don't know how it's supposed to work at all --- restoring backlight levels implies knowing what they previously were, and that can only be determined from the root filesystem. I suppose it could also be stored in an EFI variable, but I don't think that it is.

So the reason it doesn't work is that it doesn't know what level it should restore to.

**Comment by NickCao** [comment]
`/var` is obviously `requiredForBoot`, thus it should be mounted in initrd, in that way it is *possible* to restore backlight in the initrd, but considering `/vat` is actually mounted under `/sysroot/var`, this won't work in practice. So I believe the correct way is to restore backlight after switching root.

**Comment by lheckemann** [comment]
> it is _possible_ to restore backlight in the initrd

but not really useful, especially considering that one of the main uses for seeing what the initramfs is doing is seeing an encryption passphrase prompt (and if the filesystem hasn't been decrypted yet, it's not possible...)

**Comment by ncfavier** [comment]
To be clear, I don't think the goal should be to restore backlight levels *in the initrd*. At least that's not what this issue is about. The goal is the restore backlight levels *at all*, which currently doesn't happen for me.

**Comment by NickCao** [comment]
My guess was a bit off, but indeed it was udev db leaked from initrd to the udevd after switching root. Now that the referenced issue is fixed and released upstream, we can safely enable `initrd-udevadm-cleanup-db.service`, and the udev rules will be properly reevaluated after switching root.

**Comment by lheckemann** [comment]
Oooooh. Yeah I was completely missing the point, sorry!

**Comment by ncfavier** [comment]
This keeps getting weirder: while https://github.com/NixOS/nixpkgs/pull/185116 fixes the issue for me, I can also fix it another way: by removing `amdgpu` from `boot.initrd.kernelModules` (for example, by not importing the `lenovo-thinkpad-t14s-amd-gen1` module from nixos-hardware). I'm pretty sure I had tried that in June and it did not fix the issue at the time, but now it does.

Also, not including `amdgpu` in the initrd modules fixes *another* issue: about a second after the passphrase prompt appears, the screen seems to "reset", and the framebuffer gets scrolled up a few lines while the prompt stays in the same place:

<details>
<summary>Screenshot</summary>

![](https://f.monade.li/haMmES.png)
</details>

Here's the [`systemd-analyze plot`](https://f.monade.li/Csmaui.svg) where you can see that "about a second after the passphrase prompt appears" seems to line up with the moment `sys-devices-pci0000:00-0000:00:08.1-0000:06:00.0-backlight-amdgpu_bl0.device` is detected/initialised/started (?).

This is all regardless of whether `initrd-udevadm-cleanup-db.service` is included.
