### ISSUE TITLE
nilfs-utils: nilfs_cleanerd not running due to 'error while loading shared libraries: libnilfs.so.0

### ISSUE THREAD

**Issue by mikael-andersson** [NixOS/nixpkgs#18169]
## Issue description
It seems my NILFS is not garbage collected. The other day I was not able to boot up my NixOS due to a full disk.

[root@nixos:/home/mikael]# nilfs_cleanerd /dev/mapper/cryptroot
nilfs_cleanerd: error while loading shared libraries: libnilfs.so.0:
cannot open shared object file: No such file or directory

If I set LD_LIBRARY_PATH, I am however able to start nilfs_cleanerd as
root.

### Steps to reproduce
1. Install nilfs-utils
2. Verify that nilfs_cleanerd is not running by ps aux | grep nilfs

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.03.1171.9cb194c (Emu)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.03.1171.9cb194c"

**Comment by dezgeg** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/commit/8fe93051f66b548e184455798388c77672a38608.

**Comment by mikael-andersson** [comment]
I actually solved it myself last night. :)

I think it is a bit strange that no one else has came across this 
problem before.

Thanks,

Mikael


2016-09-01 00:51 skrev Tuomas Tynkkynen:

**Comment by mikael-andersson** [comment]
I realize that my title with "nilfs_cleanerd not running" was a bit ambiguous. The thing is, I am now able to start nilfs_cleanerd and do not get any library dependency problems. However, it still does not start at boot. Should I open a new issue for it or should it be solved as part of this issue?

**Comment by mikael-andersson** [comment]
I am closing this and open a new one with a more correct issue title.
