### ISSUE TITLE
lutris: overwatch 2 - Nvidia X Error: Overflow with BadValue (MIT-SHM).

### ISSUE THREAD

**Issue by imsofi** [NixOS/nixpkgs#195126]
### Describe the bug
After this PR: #194668 and running Overwatch 2 with `caffe-7.18` (as required by the game), it crashes with a death loop of 
```
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0044), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 004c), starting debugger...
...
```

This continues until the computer hardlocks. Unsure of what causes it however.

<details>
<summary>Log file</summary>

```
lutris-wrapper: /home/sofi/.local/share/lutris/runners/wine/caffe-7.18-x86_64/bin/wine
Started initial process 332 from /home/sofi/.local/share/lutris/runners/wine/caffe-7.18-x86_64/bin/wine winecfg.exe
Start monitoring process.
fsync: warning: a previous shm file /wine-200d3f2f-fsync was not properly removed
fsync: up and running.
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0044), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 004c), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 00b0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 00b8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 00f8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0100), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 00f0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 00e8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0140), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0138), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0150), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0148), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0178), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0158), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0180), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0208), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0220), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0250), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0210), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 01d0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0290), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0278), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0230), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0258), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 01a0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 01b8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0198), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 02d0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0330), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0328), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0298), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0228), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0430), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0240), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0378), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 01a8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0358), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0318), starting debugger...
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0320), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0490), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0440), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0398), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0350), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0480), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 01c0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0380), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0218), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0368), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0640), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0638), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0650), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 03e8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0248), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0170), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0340), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 03d8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0408), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0508), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0728), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 07d0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 03c0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 02a0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0898), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0448), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0660), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 07a8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0518), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0560), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 08d8), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0758), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0978), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0568), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0418), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 09c0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 02f0), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0558), starting debugger...
Maximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0a68), starting debugger...
Maximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0360), starting debugger...
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0598), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0400), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0580), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0af0), starting debugger...
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0990), starting debugger...
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0670), starting debugger...
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0a30), starting debugger...
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0888), starting debugger...
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 0868), starting debugger...
wine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 000000007B013B68 (thread 08f0), starting debugger...
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedwine: Call from 000000007B013B68 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
```
</details>

### Steps To Reproduce

1. Install the [https://lutris.net/games/battlenet/](https://lutris.net/games/battlenet/) inside lutris. (or the overwatch 2 one. Its the same + shader caches).
2. Follow the changes needed as by [https://gist.github.com/ryleu/aaef41c71dddd612c6bcf118c7870149](https://gist.github.com/ryleu/aaef41c71dddd612c6bcf118c7870149) (in short, downloading `caffe-7.18` for anti-cheat support and enabling it in lutris)
3. Attempt to use the `caffe-7.18` library.

### Expected behavior
Launching correctly.

### Notify maintainers

CC: @jonringer @Madouura

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
% nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.11-zen1, NixOS, 22.11 (Raccoon), 22.11.20221002.59d2991`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by imsofi** [comment]
Should state, this is not a problem with the PR, as without it, `caffe-7.18` simply crashes with the error of missing the `libunwind.so.8` library.

Further info on the machine is that it runs an `nvidia` gpu.

**Comment by imsofi** [comment]
Looking into this more, it seems to be an issue of `caffe` itself. It also shows up on Manjaro and Arch following various reports under different discord servers.

Going to keep this open while a solution for this shows up.

**Comment by imsofi** [comment]
Found some comments talking about ICD, nvidia, and vulkan about this. This may be a driver issue of nvidia.

> I know very little about it but one thing I do know it some people  need to also set the ICD loader to use the nvidia.json

https://github.com/NixOS/nixpkgs/pull/157907#issuecomment-1042342710

**Comment by imsofi** [comment]
> Found some comments talking about ICD, nvidia, and vulkan about this. This may be a driver issue of nvidia.
> 
> > I know very little about it but one thing I do know it some people  need to also set the ICD loader to use the nvidia.json
> 
> Steam related issue about ICD/Nvidia/Vulkan: [#157907 (comment)](https://github.com/NixOS/nixpkgs/pull/157907#issuecomment-1042342710)

This might be wrong however, it seems to correctly fetch the vulkan ICD, at least from my understanding.

**Comment by imsofi** [comment]
Running with the default wine-staging included in nix, i get
```console
Start monitoring process.
gamemodeauto: 
ntlm_auth: /home/sofi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/1wn862qvv09ivc0mfzv2zhx8zqwfx3q9-samba-4.15.9/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/sofi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/1wn862qvv09ivc0mfzv2zhx8zqwfx3q9-samba-4.15.9/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/sofi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/1wn862qvv09ivc0mfzv2zhx8zqwfx3q9-samba-4.15.9/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/sofi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/1wn862qvv09ivc0mfzv2zhx8zqwfx3q9-samba-4.15.9/lib/samba/libcommon-auth-samba4.so)
[1008/230127.995:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
ntlm_auth: /home/sofi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/1wn862qvv09ivc0mfzv2zhx8zqwfx3q9-samba-4.15.9/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/sofi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/1wn862qvv09ivc0mfzv2zhx8zqwfx3q9-samba-4.15.9/lib/samba/libcommon-auth-samba4.so)
[1008/230128.684:ERROR:dxva_video_decode_accelerator_win.cc(1397)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: Module not found. (0x7E)
[1008/230128.685:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x180
  Serial number of failed request:  3992
  Current serial number in output stream:  4002
Initial process has exited (return code: 0)
Monitored process exited.
Exit with return code 0
2022-10-08 23:01:51,519: Game still running (state: running)
2022-10-08 23:01:51,519: Stopping Blizzard Battle.net (wine)
```

Same also happens with `wine-tkg-staging-fsync-git-7.18.r4`.

This however seems common, and why `caffe-7.18` gets recommended. https://www.reddit.com/r/linux_gaming/comments/xvms2v/overwatch_2_how_to_help/ir24fxu/

**Comment by Kid0h** [comment]
I'm experiencing the same problem.

**Comment by imsofi** [comment]
Sadly `caffe-7.18` still seems to produce `shell32.dll.SHGetDesktopFolder` errors. But i speculate this to be an issue of caffe, rather than an issue of NixOS.

Heard some have success with `wine-tkg-7.18` directly. So `caffe-7.18` may not be needed to run Overwatch 2.

**Comment by imsofi** [comment]
Annoyingly, seems there are still a set of issues. Launcher however now starts and runs, but game does not.

This is getting increasingly hard to debug, as i feel like i am hitting wine, compiling, and fhsenv issues. I think the best strategy is waiting for more general support for Wine and Overwatch 2 and try again then.

**Comment by imsofi** [comment]
> I'm experiencing the same problem.

@Kid0h What is your hardware, output of `nix-shell -p nix-info --run "nix-info -m"`, and could you also post the error message that happens?

**Comment by imsofi** [comment]
Yeah i have yet to figure out what the explorer.exe explosion stems from. I have also hit the issue when trying to run wine-ge from nix-gaming. https://github.com/fufexan/nix-gaming/issues/27

There is also an issue of `MIT-SHM` from wine staging here. Untested if normal wine is affected by this as well, as Blizzard does not launch on it. Would love input from someone with more experience with debugging Wine.

**Comment by Kid0h** [comment]
btw, the explorer.exe explosion isn't present just with OW2, you can't really launch anything with Caffe (or wine-tkg-staging, same thing).

**Comment by imsofi** [comment]
Yeah, no that is a Wine issue. Hence why this issue is now about the Overflow with Lutris and Wine-Staging Which is a issue of how the fhsenv is set up. Sadly hard to give a good statement for a PR about this still, seeing how the game does not launch due to Wine related issues :/

**Comment by jonringer** [comment]
`MIT-SHM` issue for steam was solved by https://github.com/NixOS/nixpkgs/commit/721ea006a841176e6045b479e2d44ed2b47ed3d0 , we should probably do something similar or just make unsharing of PID namespace default to false as most use cases of `buildFHSUserEnv` for nixpkgs to make an application work, rather than try to isolate it using different kernel namespaces. "hardened" applications may choose to opt-in, but then we are getting to a discussion of usability vs security

**Comment by Kid0h** [comment]
I think I have a path we can explore, basically this problem only occurs in `wine-tkg-staging` (not just `wine-staging`) **AND** it starts only in `wine-tkg-staging` **v7.7** - that means that somewhere in the commits between v7.6 and v.7.7 there is a change that causes this issue (in Caffe it's after 7.7, so it might be on a slightly different commit or something).

**Comment by LunNova** [comment]
The SHM issues were also occuring for me with the default lutris wine version, AMD GPU/CPU.

I opened #198384 to add the unshare = false options for lutris, but it looks like it does not completely resolve this issue, only part of it.

**Comment by imsofi** [comment]
Yeah this looks pretty much like my WIP patch. And working with upstream `wine-tkg` I have also now solved the `shell32.dll.SHGetDesktopFolder` which came from a faulty `fshack` patch not reading the sandbox correctly (or at least that is my understanding from it, see https://github.com/Frogging-Family/wine-tkg-git/issues/874#issuecomment-1279958668 for a better explanation).
