### ISSUE TITLE
Firefox fails to load cursors on Wayland

### ISSUE THREAD

**Issue by jordanisaacs** [NixOS/nixpkgs#207339]
### Describe the bug

Firefox fails to load cursors on v108. The following message is recieved for all cursor types:

```
Gdk-Message: 17:51:21.641: Unable to load left_ptr from the cursor theme
```

It seems to be because Firefox has stopped profile icons (either `~/.icons` or `~/.local/share/icons`). Some people on [reddit](https://old.reddit.com/r/swaywm/comments/zasy6c/cursor_theme_stopped_working_in_firefox_with_a/) fixed it by symlinking to `/usr/share/icons` but I tried that it didn't work so I am guessing there needs to be a nix specific workaround to fix this. I am running dwl (not sway) but it seems to be a wayland issue.

### Steps To Reproduce

Run firefox v108 on wayland with `MOZ_ENABLE_WAYLAND=1`.

### Expected behavior

Cursors are loaded.

### Additional context

The issues fixes if you run it on XWayland `GDK_BACKEND=x11 MOZ_ENABLE_WAYLAND=0`.

**Comment by bobby285271** [comment]
Likely https://gitlab.gnome.org/GNOME/gtk/-/issues/5365.

**Comment by jordanisaacs** [comment]
Fix also seems to be coming in gtk 3.26 released earlier today so that is promising.

**Comment by dmizelle** [comment]
If you are running KDE, I was running into this until I set a default cursor theme. I set it in the KDE settings panel as I was being lazy, but there may be a way to set it via home-manager.

**Comment by jordanisaacs** [comment]
I figured out what was wrong on my end. I had the default icon theme set in ~/{xdg_data_home}/.icons along with the cursor files linked there. But the cursor files were not in my {xdg_data_dirs}. The regression seems to be that it doesn't load cursor files from {xdg_data_home} (or .icons) anymore. But still reads the default icon theme name. Thus, I fixed it by making sure the cursor files were also linked into xdg_data_dirs. I'll keep this for other people to find though.

**Comment by WizardUli** [comment]
I do not use or have any of `~/.icons`, `~/.config/icons`, ~/.local/share/icons` and I do not care about cursor theme at all and still have this problem.

@jordanisaacs Could you provide a specifc example what should go to the _XDG_DATA_DIRS_ and how you achieve it please? (Is there a convenient NixOS/home-manager for that? Or do you use something like `environment.loginShellInit`.) Thanks.

**Comment by WizardUli** [comment]
Just adding
```nix
{
  gtk = {
    enable = true;
    theme = {
      package = pkgs.gnome.gnome-themes-extra;
      name = "Adwaita-dark";
    };
  };
}
```
to _home-manager_ fixed it for me.

**Comment by grxnola** [comment]
When will the update that patches this go from staging to the 21.11 branch?

**Comment by jtojnar** [comment]
@grxnola It won’t unless someone explicitly backports it.

**Comment by foosinn** [comment]
Is there a fix without home manager

**Comment by jtojnar** [comment]
Installing the cursor theme with `environment.systemPackages` and selecting imperatively in `gnome-tweaks` should still work.

**Comment by foosinn** [comment]
yes it did :tada:

**Comment by foosinn** [comment]
@thall: for me it was solved by removed manual gsettings commands and just setting it once via gui.

**Comment by PanAeon** [comment]
Running firefox as `XDG_DATA_DIRS=~/.local/share firefox` fixed the issue for me 
![image](https://user-images.githubusercontent.com/686076/226609110-bda6d818-aa5c-4bb1-b526-ee6b4ffc1b83.png)

**Comment by tnc1394** [comment]
For those experiencing this after switching to and from Plasma (in my case back to sway), I managed to fix it by running
`dconf reset /org/gnome/desktop/interface/cursor-theme`

I found the solution here: https://discourse.nixos.org/t/gnome-broke-after-trying-plasma/16019

**Comment by jktjkt** [comment]
I'm on Plasma-desktop with Wayland and fractional scaling. Some random Googling suggested running `dconf write /org/gnome/desktop/interface/cursor-theme "'Breeze_Snow'"`, but that did not help because the actual config writeout failed. Apparently, this needs a D-Bus service, and that one was not available:
```console-session
$ nix-shell -p dconf
$ dconf write /org/gnome/desktop/interface/cursor-theme "'Breeze_Snow'"
error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

I had to set `programs.dconf.enable = true;` in my `/etc/nixos/configuration.nix`; once that has been done, plasma's `systemsettings` set a correct value for me, and the the already-running Firefox picked a correct icon theme dynamically. Now I (finally) see my mouse pointer in Firefox again, yay.

**Comment by kidonng** [comment]
I encountered similiar issues with Chrome/Electron/WebKitGTK apps (cursor fall back to some kind of default X cursors instead of using DE theme). The solution I found (before discovering this issue) is to symlink the cursor theme to one of the icons location (`~/.icons`, `~/.local/share/icons`, whatever) as `default`.

A more NixOS way is to add this to `users.users.<name>.packages`:

```nix
      (runCommandLocal "breeze-cursors-fix" {} ''
        dir=$out/share/icons
        mkdir -p $dir
        ln -s ${breeze-qt5}/share/icons/breeze_cursors $dir/default
      '')
```

(Swap Breeze with any theme you prefer)

**Comment by Schweber** [comment]
@kidonng this is rejected by nix with `error: undefined variable 'runCommandLocal'`. Should this be added to configuration.nix or is this meant for home-manager?

**Comment by kidonng** [comment]
> @kidonng this is rejected by nix with `error: undefined variable 'runCommandLocal'`. Should this be added to configuration.nix or is this meant for home-manager?

It's one of the [trivial builders](https://ryantm.github.io/nixpkgs/builders/trivial-builders/#trivial-builder-runCommandLocal) in Nixpkgs, I have edited my comment to make it clear to call it with `pkgs.runConmandLocal`.

As long as the output is in `$XCURSOR_PATH`, it doesn't matter how you install the package (system, user, profile, home-manager, etc.)

**Comment by Schweber** [comment]
@kidonng Thank you, that solves it for me :+1:

**Comment by Schweber** [comment]
I looked into the [home-manager module](https://github.com/nix-community/home-manager/blob/master/modules/config/home-cursor.nix) and it has all these compatibility options in mind.

This should set the correct cursor in all use cases:

```
    home-manager.users.username.home.pointerCursor = {
          gtk.enable = true;
          x11.enable = true;
          package = pkgs.bibata-cursors;
          name = "Bibata-Modern-Amber";
          size = 28;
        };
```

It solved all cursor issues for me (i had 2 distinct ones - mozilla and wayland desktop).

**Comment by donottellmetonottellyou** [comment]
> I looked into the [home-manager module](https://github.com/nix-community/home-manager/blob/master/modules/config/home-cursor.nix) and it has all these compatibility options in mind.
> 
> This should set the correct cursor in all use cases:
> 
> ```
>     home-manager.users.username.home.pointerCursor = {
>           gtk.enable = true;
>           x11.enable = true;
>           package = pkgs.bibata-cursors;
>           name = "Bibata-Modern-Amber";
>           size = 28;
>         };
> ```
> 
> It solved all cursor issues for me (i had 2 distinct ones - mozilla and wayland desktop).

This did not work at all for me, maybe because I installed firefox using programs.firefox.enable?

> I encountered similiar issues with Chrome/Electron/WebKitGTK apps (cursor fall back to some kind of default X cursors instead of using DE theme). The solution I found (before discovering this issue) is to symlink the cursor theme to one of the `$XCURSOR_PATH` as `default`.
> 
> A more NixOS way is to add this package (e.g. `users.users.<name>.packages`):
> 
> ```nix
>       (pkgs.runCommandLocal "breeze-cursors-fix" {} ''
>         dir=$out/share/icons
>         mkdir -p $dir
>         ln -s ${breeze-qt5}/share/icons/breeze_cursors $dir/default
>       '')
> ```
> 
> (Swap Breeze with any theme you prefer)

I changed `breeze-qt5` to `kdePackages.breeze` (I am using Plasma 6) and added this to `environment.systemPackages`, and it seems to have fixed the cursor issue with other programs such as Steam, but not for Firefox. It is super annoying because not only does Firefox not respect my theme, it enlarges the cursor.
