### ISSUE TITLE
Latest ansible fails to run with "unsupported locale setting"

### ISSUE THREAD

**Issue by ingon** [NixOS/nixpkgs#223151]
### Describe the bug
Running latest ansible results in the following error:
```
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
```

### Steps To Reproduce
```
$ nix-shell -p ansible

[nix-shell:~]$ ansible --version
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
```

### Expected behavior
Running older package version produces the correct behavior:
```
$ nix-shell -p ansible_2_13

[nix-shell:~]$ ansible --version
ansible [core 2.13.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/mj1nqkhh69ydmc2fmzivfxwkk9vylw6f-python3.10-ansible-core-2.13.6/lib/python3.10/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/mj1nqkhh69ydmc2fmzivfxwkk9vylw6f-python3.10-ansible-core-2.13.6/bin/ansible
  python version = 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

### Notify maintainers
@mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/4l09rh46bvvp84d8xm879zrqkix4cyy1-nix-info
copying path '/nix/store/4l09rh46bvvp84d8xm879zrqkix4cyy1-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.102-1-MANJARO, Manjaro Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by IndeedNotJames** [comment]
ansible-core requires the locale have UTF-8 encoding since 2.14.0

Excerpt from the 2.14.0 release notes[^1]
> ansible - At startup the filesystem encoding and locale are checked to verify they are UTF-8. If not, the process exits with an error reporting the errant encoding.

Can you share the output of executing `locale` in a shell, please?
You probably just have to fix your system language to a UTF-8 variant.
Or just run ansible using `LANG=C.UTF-8 ansible`

[^1]: https://github.com/ansible/ansible/blob/7bb078bd740fba8ad43cc69e18fc8aeb4719180a/changelogs/CHANGELOG-v2.14.rst#id11

**Comment by ingon** [comment]
Thanks for digging this out.

In a bare (e.g. non-nix) shell: 
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

In nix-shell: 
```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

Trying out your suggestion: 
```
$ LANG=C.UTF-8 ansible
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
```

I wonder if the quotes in some of the values are confusing it, looking at resetting the locale info.

**Comment by ingon** [comment]
Also to note, I do have `ansible` installed natively (e.g. through manjaro/arch package manager), and it shows:
```
$ ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```
And this is why I found strange that the same cannot run in `nix-shell` (and thought it could be nix's fault)

I have a little breakthrough tho, it seems it runs fine with: 
```
[nix-shell:~]$ LC_ALL=C.UTF-8 ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/w0h7rbxxrvs2s51xh1sfd0z1bys6rcfv-python3.10-ansible-core-2.14.2/lib/python3.10/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/w0h7rbxxrvs2s51xh1sfd0z1bys6rcfv-python3.10-ansible-core-2.14.2/bin/ansible
  python version = 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0] (/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by casty8** [comment]
I'm facing the same issue, did you find the solution @ingon ?

**Comment by Trufax** [comment]
i have the same issue ? Is there any better solution than setting LC_ALL, it messes with other programs so i dont really want to do that.

**Comment by benmotyka** [comment]
export LC_ALL="C.UTF-8" helped me on Arch Linux

**Comment by FMG-sarahjabado** [comment]
Running the command `locale-gen "en_US.UTF-8"` appeared to have resolved the issue for me, my issue was presenting in the same way as what @ingon showed when he ran the `locale` command back on the 26th of March.

**Comment by envy** [comment]
I fixed this issue by adding `glibcLocales` to my shell.nix

**Comment by Jarmos-san** [comment]
While investigating and attempting to fix a similar concern I had, I stumbled across [this comment](https://github.com/ansible/ansible/issues/78283#issuecomment-1188345809) which states:

> The `python` docker image you are using ships with the `C.UTF-8` locale but not `en_US.UTF-8` locale. Currently ansible-test effectively requires `en_US.UTF-8` by exporting that via the `LC_ALL` environment variable.

I know the solution which worked for me might not be related to `nix` at all but since this thread shows up high up on the Google SERP, I'm going to share it. So, adding the following line to my `~/.zshrc` (or `~/.bashrc` file in case you use Bash) and then reloading the shell fixed it for me:

```zsh
# Add the line to ~/.zshrc
export LC_ALL=en_US.UTF-8
```

And then run:
```console
$ source ~/.zshrc
$ ansible --version
ansible [core 2.16.4]
  config file = None
  configured module search path = ['/home/space/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/linuxbrew/.linuxbrew/Cellar/ansible/9.3.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /home/space/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/linuxbrew/.linuxbrew/bin/ansible
  python version = 3.12.2 (main, Feb  6 2024, 20:19:44) [GCC 11.4.0] (/home/linuxbrew/.linuxbrew/Cellar/ansible/9.3.0/libexec/bin/python)
  jinja version = 3.1.3
  libyaml = True

**Comment by Trufax** [comment]
This fix works but everyone must be clear this affects the whole system. It can have side effects on other applications as well so use it with caution.

**Comment by Foosec** [comment]
This is still an issue, reading into this LC_ALL nowadays should typically go unset, maybe ansible should look at different locale settings like LANG instead? As for a temp fix that doesn't mess with other things, just create an alias for ansible that sets LC_ALL before running ansible.

**Comment by Timoniche** [comment]
LANGUAGE = "C.UTF-8"
        LANG="C.UTF-8"
        LC_COLLATE="C.UTF-8"
        LC_CTYPE="C.UTF-8"
        LC_MONETARY="C.UTF-8"
        LC_NUMERIC="C.UTF-8"
        LC_TIME="C.UTF-8"
        LC_MESSAGES="C.UTF-8"
        LC_ALL="C.UTF-8"
        
        helped me

**Comment by abhisekp** [comment]
> ```
>     LANGUAGE = "C.UTF-8"
>     LANG="C.UTF-8"
>     LC_COLLATE="C.UTF-8"
>     LC_CTYPE="C.UTF-8"
>     LC_MONETARY="C.UTF-8"
>     LC_NUMERIC="C.UTF-8"
>     LC_TIME="C.UTF-8"
>     LC_MESSAGES="C.UTF-8"
>     LC_ALL="C.UTF-8"
>     
>     helped me
> ```

This works while running Ansible under WSL

**Comment by fulafisken** [comment]
I once had this issue on an archlinux machine, it had somehow not generated the locale-files properly in an update. Running the command locale-gen solved the problem for me in this case.

**Comment by drzymalanet** [comment]
I've had this issue with vs code ansible plugin with conjunction to **ansible-lint**. The solution for me was to change this in the plugin config:
```
"ansible.validation.lint.path": "LC_ALL=C.UTF-8 ansible-lint"
```

**Comment by marcelomrwin** [comment]
`LC_ALL="C.UTF-8" ansible-playbook ...`

Fixed the issue. Don't need to change anything.

**Comment by trim21** [comment]
another solution is to point env `LOCALE_ARCHIVE` to host locale archive location

**Comment by ingon** [comment]
> This fix works but everyone must be clear this affects the whole system. It can have side effects on other applications as well so use it with caution.

I should call out that my flake where I put `LC_ALL="C.UTF-8"` was specific for a project that used `ansible` at the time (activated via `direnv`). I've moved to provisioning my servers via `nix`/`colmena` since, so I'm no longer using `ansible` in any capacity.

**Comment by ultinous-kszegi** [comment]
@marcelomrwin 
> `LC_ALL="C.UTF-8" ansible-playbook ...`
> 
> Fixed the issue. Don't need to change anything.

IMO things **do** need to change
 As @Foosec written:
> This is still an issue, reading into this LC_ALL nowadays should typically go unset, maybe ansible should look at different locale settings like LANG instead?

A non-contrived example: as a non-native English speaker, who works mostly in English (as many people in IT), I set my locale to an English variant, but there is no way in flaming hell that my `LC_MEASUREMENT` will be set to a non-SI locale, or that my LC_TIME will be set to some non hierarchically descending, illogically ordered format.
Or god forbid that my `LC_MONETARY` is set to one that defaults to Euro. Long story short, no `en_` locale variant is acceptable for me, neither is some unspecific like `C.UTF-8` - both creates a crap desktop experience on GUI.
Come on, it's 2025 soon, different `LC_` variables are decades old...
`LC_LOCALE` overrides each and every one of those.
Setting `LC_ALL`doesn't "fix everything", it just makes ansible happy. For no obvious reason.

Checking that locale supports UTF-8 doesn't equal to checking that you have an uniform locale setting, for **all** locale variable, **and** that it happens to be an UTF-8 one

**Comment by gempir** [comment]
On Arch: 

```
sudo pacman -S glibc-locales
```
