### ISSUE TITLE
Liferea 1.14.1 through 1.14.3 (release-22.11) hangs, crashes on startup

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#223128]
### Describe the bug

Upstream issue: [Liferea 1.14.1 crash when refreshing feeds.](https://github.com/lwindolf/liferea/issues/1212)

### Steps To Reproduce
1. Upgrade to latest Liferea on release-22.11
2. Run Liferea

### Notify maintainers

@romildo (maintainer) @ryantm (1.14.1 upgrade)

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.103, NixOS, 22.11 (Raccoon), 22.11.3299.9ef6e7727f4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vbgl** [comment]
Fixed by #222944?

**Comment by romildo** [comment]
v1.14.2 is buggy too: https://github.com/lwindolf/liferea/issues/1214

v1.14.3 has been released, but is also buggy: https://github.com/lwindolf/liferea/issues/1217

**Comment by romildo** [comment]
https://github.com/NixOS/nixpkgs/pull/223586 seems to work for me.

**Comment by l0b0** [comment]
Oh yeah, still broken. It takes a bit longer to segfault on 1.14.2, that's all.

**Comment by romildo** [comment]
Is this still an issue?

**Comment by l0b0** [comment]
1.14.5 seems to be stable, closing.
