### ISSUE TITLE
nixpkgs stack uses different hpack than upstream binary release

### ISSUE THREAD

**Issue by googleson78** [NixOS/nixpkgs#223390]
### Describe the bug
The `stack` that's currently in nixpkgs uses `hpack-0.35.2`, the official stack binary release uses `hpack-0.35.1`

For more details, I think the core issue is basically the same as https://github.com/NixOS/nixpkgs/issues/84820.

I think the fix is to change the version of `hpack` which the `stack` in nixpkgs is built with from `0.35.2` (which is the version of the `hpack` package in nixpkgs) to `0.35.1`.

### Notify maintainers

@cdepillabout @expipiplus1 @maralorn @sternenseemann

**Comment by googleson78** [comment]
It would also be great to have some automation to make sure this doesn't regress. I guess that would involve downloading an official matching version stack binary and checking what the `hpack` version is there (via `-v`), if there is no better way to get the upstream hpack version.

**Comment by sternenseemann** [comment]
In what way does this issue present? Supposedly stack has become more resistant to this problem: https://github.com/commercialhaskell/stack/issues/5210

It seems ridiculous that we'd have to track what stack binaries ship for all eternity.

**Comment by googleson78** [comment]
The concrete issue is that 

0. I get stack from `nixpkgs`
1. My colleagues get stack from the official bindist
2. I add new source files
3. I run `stack build`
4. The `.cabal` file gets regenerated to include the newer files, but also potentially other changes happen, because my hpack version is different (at the very least, the hpack version comment changes)
5. I commit the `.cabal` file, as recommended by the issue you linked
6. Now my colleague pulls in my changes, they use an official stack release with a different hpack version, so they get arbitrary issues, depending on the different `hpack` version. At the very least they get some weird mismatch, or the file doesn't get regenerated, etc.

> It seems ridiculous that we'd have to track what stack binaries ship for all eternity.

I don't really understand this - for dev facing tools, isn't it expected that `nixpkgs` would track the official releases? Otherwise this introduces reproducibility issues between getting your tools from `nixpkgs` and from official releases, hence I am now arbitrarily going to get breakage if I choose to use NixOS when collaborating with non-NixOS users (or I have to potentially apply some workarounds to be able to use official releases because official releases don't always work on NixOS).

**Comment by maralorn** [comment]
But the real problem here is not an incompatibility between stack and hpack versions. It is like with very many tools, that you using another hpack version than your coworkers does not work.

I am uncertain what the best solution for that is. But in general nixpkgs downgrading software because other distribution methods are not as fast is a bit unsatisfying.

Additionally, I find it mighty confusing, that the stack binaries are not build with hpack version from stackage. Using the hpack version from stackage LTS, which we do, is the most blessing one can generally achieve for a package version.

So all of this is me shouting like a five year old: “Not our fault!” The question is what to do about it.

Have you considered using an older nixpkgs version which uses the right hpack version?

Apparently the whole process is super sensitive to the hpack version, so if we downgrade hpack now we probably annoy other people.

If there is no better solution maybe we need to supply different hpack versions and stack with different hpack versions and the user can choose?

**Comment by googleson78** [comment]
> But in general nixpkgs downgrading software because other distribution methods are not as fast is a bit unsatisfying.

I agree

> Additionally, I find it mighty confusing, that the stack binaries are not build with hpack version from stackage.

I agree

> If there is no better solution maybe we need to supply different hpack versions and stack with different hpack versions and the user can choose?

I would guess that if you bless the version that the official stack bindist ships, nobody would complain, except maybe a single instance of other nixpkgs stack users, after which it should be fine? I guess a more principled approach would be to instead live with this for now and wait until stack bindists bump hpack version, at which point start tracking the hpack version provided with bindists. 

> So all of this is me shouting like a five year old: “Not our fault!” The question is what to do about it.

> Have you considered using an older nixpkgs version which uses the right hpack version?

Of course I can work (and actively am working) around this. And also I do not expect that miraculously software from nixpkgs will be bug for bug compatible with official bindists. But this feels like a relatively simple(perhaps? I do not know how easy it is to have an additional `hpack` version in nixpkgs) change to make, which results in actual observable incompatibility being reduced.

**Comment by cdepillabout** [comment]
Currently `master` / `haskell-updates` provides stack-2.9.1 as the top-level `stack` attribute (even though the latest release of `stack` is 2.9.3), and it uses hpack-0.35.2.

Upstream `stack` uses the following hpack versions:

- stack-2.9.1: hpack-0.35.0
- stack-2.9.3: hpack-0.35.1

I've just pushed cbc30e4bbc3 in https://github.com/NixOS/nixpkgs/pull/223827, which drops `stack`'s hpack dependency to 0.35.0, in-line with upstream `stack`.  This should make sure people getting `stack` from Nixpkgs use a compatible `hpack` version with people that get stack from upstream.

I'm going to keep this issue open in case anyone is able to send a PR implementing some sort of test in Nixpkgs that upstream stack and our stack use the same hpack version.

**Comment by maralorn** [comment]
Just so I understand this right: If someone's team uses “stack-2.9.3: hpack-0.35.1” but they themselves get our “stack-2.9.1: hpack-0.35.0” do they still have this problem?

**Comment by googleson78** [comment]
Thanks @cdepillabout and sorry for not getting back to this earlier. I'll still have in mind trying to write a test for this.

> Just so I understand this right: If someone's team uses “stack-2.9.3: hpack-0.35.1” but they themselves get our “stack-2.9.1: hpack-0.35.0” do they still have this problem?

It did somehow become an issue for my workplace, because this causes the original issue but in reverse - I was using a newer hpack(from nix) and someone was using the older one, causing some kind of issues for the other person. However, I currently can't dig out the exact complaints.

**Comment by cdepillabout** [comment]
> If someone's team uses “stack-2.9.3: hpack-0.35.1” but they themselves get our “stack-2.9.1: hpack-0.35.0” do they still have this problem?

My understanding is that this is correct.  If you're using `stack` + `hpack` in a team setting, you have to make sure everyone uses the same version of `stack`, compiled with the same version of `hpack`.  (Although it might be the case that you only have to make sure the `hpack` version is the same, you don't all necessarily have to use the same version of `stack`.)

**Comment by cdepillabout** [comment]
I fixed the underlying problem in cbc30e4bbc341.  But we don't have any assurance that the same problem won't crop up again the next time Stack releases a new version.

I was leaving this issue open so that hopefully someone would send a PR adding some sort of test that the hpack version used by Stack in Nixpkgs is the same as the hpack version used by the upstream Stack release.

Although I don't have a good idea of how to write this test in such a way that we won't have to manually bump a version/URL/hash every time there is a new release of Stack, which is quite annoying.  It is the git-annex problem all over again.

**Comment by cdepillabout** [comment]
I implemented the check for the upstream stack/hpack version in #243798
