### ISSUE TITLE
nixos/systemd-boot: exit status 1 nixos-rebuild fails

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#223579]
### Describe the bug
Getting an error in bootctl status step

### Steps To Reproduce
1. `nixos-rebuild boot`

### Expected behavior
Can rebuild NixOS

### Logs
```
building Nix...
building the system configuration...
Traceback (most recent call last):
  File "/nix/store/q46474x4pl7fql374rr2yg8abi998p6j-systemd-boot", line 337, in <module>
    main()
  File "/nix/store/q46474x4pl7fql374rr2yg8abi998p6j-systemd-boot", line 262, in main
    installed_out = subprocess.check_output(["/nix/store/33pkg1f1ad2wh2rkl2c48hf8kfxcjgw5-systemd-253.1/bin/bootctl", "--esp-path=/boot/efi", "status"], universal_newlines=True)
  File "/nix/store/syz2y6j53y5hpzbs7l0965zwxshi8iyl-python3-3.10.10/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/syz2y6j53y5hpzbs7l0965zwxshi8iyl-python3-3.10.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/33pkg1f1ad2wh2rkl2c48hf8kfxcjgw5-systemd-253.1/bin/bootctl', '--esp-path=/boot/efi', 'status']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
```

### Notify maintainers

@flokli @Kloenk @Mic92 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05pre468444.4bb072f0a8b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(aroun): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

EDIT: here is the log for `bootctl --esp-path=/boot/efi status --no-pager; echo $?`:
<details>
<summary>Fold/Unfold</summary>
<br>

```
System:
      Firmware: UEFI 2.60 (Lenovo 0.4165)
 Firmware Arch: x64
   Secure Boot: disabled (disabled)
  TPM2 Support: no
  Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 253.1
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/ae38c970-6a8c-47a0-8c7a-205f035aa9ea
         File: └─/EFI/systemd/systemd-bootx64.efi

Random Seed:
 System Token: set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot/efi (/dev/disk/by-partuuid/ae38c970-6a8c-47a0-8c7a-205f035aa9ea)
         File: ├─/EFI/systemd/systemd-bootx64.efi (systemd-boot 253.1)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0002
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/ae38c970-6a8c-47a0-8c7a-205f035aa9ea
         File: └─/EFI/systemd/systemd-bootx64.efi

        Title: ubuntu
           ID: 0x0001
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/f28ced3e-6d45-494d-ab58-fa2cad9566d4
         File: └─/EFI/ubuntu/shimx64.efi

        Title: Windows Boot Manager
           ID: 0x0000
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/cd2822d3-637a-7242-b14f-f90108494e3e
         File: └─/EFI/Microsoft/Boot/bootmgfw.efi

        Title: VeraCrypt BootLoader (DcsBoot)
           ID: 0xDC5B
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/804ca91a-a521-465c-bbcd-119bbd578214
         File: └─/EFI/VeraCrypt/DcsBoot.efi

Boot Loader Entries:
        $BOOT: /boot/efi (/dev/disk/by-partuuid/ae38c970-6a8c-47a0-8c7a-205f035aa9ea)
        token: nixos

Default Boot Loader Entry:
         type: Boot Loader Specification Type #1 (.conf)
        title: NixOS (Generation 489 NixOS 23.05pre468444.4bb072f0a8b, Linux Kernel 6.1.21, Built on 2023-03-29)
           id: nixos-generation-489.conf
       source: /boot/efi//loader/entries/nixos-generation-489.conf
      version: Generation 489 NixOS 23.05pre468444.4bb072f0a8b, Linux Kernel 6.1.21, Built on 2023-03-29
   machine-id: c27c123a5ee1413cba4627f0c8805596
        linux: /boot/efi//efi/nixos/b5kf30fqm1l78hzgns27akyanmynw5sc-linux-6.1.21-bzImage.efi
       initrd: /boot/efi//efi/nixos/ifydwjjz3cm2b4arkw04i1k41rmk595l-initrd-linux-6.1.21-initrd.efi
      options: init=/nix/store/a87cvpww5xvd101wnmvq1kskrqbhf0sx-nixos-system-nixos-23.05pre468444.4bb072f0a8b/init quiet acpi_osi=! "acpi_osi=Windows 2015" splash loglevel=4 nvidia-drm.modeset=1
```

</details>

**Comment by bjornfor** [comment]
Did you run `nixos-rebuild` as root?

**Comment by Zahrun** [comment]
Yes. This issue is solved upstream, see https://github.com/NixOS/nixpkgs/pull/223998

**Comment by aou** [comment]
I'm able to work around the issue with --install-bootloader, waiting for upstream systemd fix to make it down nixos I guess?

**Comment by flokli** [comment]
Yes, this should get cherry-picked into systemd-stable.

**Comment by pedohorse** [comment]
cherry-picked systemd commits were merged to nixos-23.05  
but i still cannot `nixos-rebuild`, with or without `--install-bootloader` flag

the error message is exactly the same as in the first post, except instead of `"status"` it's either `"update"` or `"install"` (if run with `--install-bootloader`)

so I cannot update to 23.05 from 22.11

nixos-rebuilding from `nixos-22.11` branch works fine

**Comment by Majiir** [comment]
Bisected systemd this time and got https://github.com/systemd/systemd-stable/commit/bd80fd7e5621f1b07e789725d9f8813c37e8571c as the first bad commit. You need to `git cherry-pick -m 1 9a72e98f02` in order to `nix build` systemd at that commit.

@pedohorse What filesystems are you using? I don't really understand the systemd commit, but I'm using ZFS on root, and I wonder if this has something to do with that.

**Comment by pedohorse** [comment]
> What filesystems are you using

I'm on ZFS on root too!

> You need to `git cherry-pick -m 1 9a72e98f02` in order to `nix build` systemd at that commit.

I'm not that familiar with nixos to know how to make it build systemd from my own repo...

**Comment by frantisekhanzlikbl** [comment]
I'm not sure that this is exclusive to machines with mounted `/boot` either. I am experiencing the same issue on a machine with a BTRFS root, `/boot` being a normal directory and `/boot/efi` an ESP mount.

**Comment by pedohorse** [comment]
> Here's a workaround, as root:

i've managed to update from 22.11 to 23.05 using this boot hack (thank you!)

After update - next rebuilds work fine.

**Comment by lattwood** [comment]
Looks like this has been patched in systemd upstream, and was released in 254!

https://github.com/systemd/systemd/commit/f26c794308975a875a98faf22a6650d7134f17c1

I wouldn't know where to begin with bumping this version, could someone give some pointers? heh

**Comment by Majiir** [comment]
Systemd updates are generally a big operation. The 254 update is in progress in https://github.com/NixOS/nixpkgs/pull/243242.

**Comment by ElvishJerricco** [comment]
I guess the issue is that if you have `/boot` as its own mountpoint, but it *isn't* an "Extended Boot Loader partition", then `bootctl` gets very confused? It's certainly an odd setup to have, and I believe the assumptions upstream are that `/boot` is *either* the ESP or the XBOOTLDR, and if it's the XBOOTLDR then the ESP is either `/boot/efi` or `/efi`.

**Comment by lattwood** [comment]
I just switched to Grub, and life is good.

**Comment by Zahrun** [comment]
Should be fixed by now
