### ISSUE TITLE
google-cloud-sdk.withExtraComponents: fails due to missing libcrypt

### ISSUE THREAD

**Issue by johnrichardrinehart** [NixOS/nixpkgs#223805]
### Describe the bug

`google-cloud-sdk.withExtraComponents` fails even with an empty array passed as an argument.

### Steps To Reproduce

```bash
$ cd $NIXPKGS_CHECKOUT
$ nix build --impure --expr "with builtins.getFlake \"$PWD\"; legacyPackages.\${builtins.currentSystem}.google-cloud-sdk.withExtraComponents []"
```

### Expected behavior

That it would build successfully.

### Screenshots
```bash
$ nix build --impure --expr 'with builtins.getFlake "/home/john/code/repos/mine/JohnOS"; (builtins.elemAt nixosConfigurations.framework-laptop.config.home-manager.users.john.home.packages 30)'
error: builder for '/nix/store/q00anv3nnrdvs3fbvd199nppsfvn5p9w-bundled-python3-unix-linux-x86_64-3.9.12.drv' failed with exit code 1;
       last 10 log lines:
       > auto-patchelf: 4 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/is05j1lzydh3i0i32c838hnq4vvvr8f4-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/bin/python3
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/is05j1lzydh3i0i32c838hnq4vvvr8f4-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/bin/python3.9
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/is05j1lzydh3i0i32c838hnq4vvvr8f4-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/lib/libpython3.9.so.1.0
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/is05j1lzydh3i0i32c838hnq4vvvr8f4-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/lib/libpython3.9.so
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/gfjpk3574r2vzi04r25122mzyrb67h3j-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
       > /nix/store/gfjpk3574r2vzi04r25122mzyrb67h3j-stdenv-linux/setup: line 1457: pop_var_context: head of shell_variables not a function context
       > /nix/store/gfjpk3574r2vzi04r25122mzyrb67h3j-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/q00anv3nnrdvs3fbvd199nppsfvn5p9w-bundled-python3-unix-linux-x86_64-3.9.12.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-rustc-bootstrap-1.66.1.drv-5/rust-1.66.1-x86_64-unknown-linux-gnu/rust-docs/share/doc/rust/html/core/arch/x86_64': Directory not empty
error: 1 dependencies of derivation '/nix/store/a5491sbd2lvil9frmqdlgc27lrly8f33-google-cloud-sdk-408.0.1.drv' failed to build
```

### Additional contextf
I've bisected the problem commit down to 578fb7fd1ff1bee335fbcfe6df745c6cab914e6d. But, I don't know why this would require a new dependency in `google-cloud-sdk` (and only when it's built `withExtraComponents`). But, I do have an open PR which solves this problem by adding `libxcrypt` to `buildInputs` of the derivation. Any commentary on _why_ this is happening is more than welcome.

My best guess is that it's because `libxcrypt` now only exposes `libcrypt.so.2` (avoiding backward compatibility with `glibc`). `libxcrypt-legacy` has been added in the interim which exposes `libcrypt.so.1`. But, I'm still not sure why this only applies to the `gcloud` components.

### Notify maintainers

@iAmMrinal0 @pradyuman @stephenmw @zimbatm

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.6-JohnOS, NixOS, 23.05 (Stoat), 23.05.20230316.ae65ff2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0pre20230315_eb56cb7`
 - nixpkgs: `/nix/store/4miq0lkk9yfgdn2cb27wy4y44vc9kxl0-source`
 ```

**Comment by jboyens** [comment]
This was just merged which should fix the issue: https://github.com/NixOS/nixpkgs/pull/223615

**Comment by johnrichardrinehart** [comment]
@jboyens That's so annoying. I had opened this 7 hours prior to that: https://github.com/NixOS/nixpkgs/pull/223806

**Comment by johnrichardrinehart** [comment]
> This can't be prior to https://github.com/NixOS/nixpkgs/pull/223615, you can see it numerically.

True... I must have been comparing his merge time with my opening time.

> If a PR has exactly the same patch as yours, and it does appear later, you can just close it and leave a link to your PR.

It requires manual tracking? I wish GH would flag you on opening a PR if you're changing lines on the same base branch as other open PRs.

> Anyway, the discussion is off-topic and deserves another issue or even an RFC.

Meh, sounds like the process is manual, for now.

**Comment by audleman** [comment]
I'm still seeing this error. Any idea what I should do?

Package I'm trying to install:
```
packages = [
    pkgs.git
    pkgs.jq
    pkgs.yq
    (pkgs.google-cloud-sdk.withExtraComponents [pkgs.google-cloud-sdk.components.gke-gcloud-auth-plugin])
    ...
```

Error log: 
```
$ direnv reload
direnv: loading ~/strike/zap-infrastructure/.envrc
direnv: loading https://raw.githubusercontent.com/cachix/devenv/d1f7b48e35e6dee421cfd0f51481d17f77586997/direnvrc (sha256-YBzqskFZxmNb3kYVoKD9ZixoPXJh1C9ZvTLGFRkauZ0=)
direnv: using devenv
direnv: .envrc changed, reloading
Building shell ...
error:
       error: builder for '/nix/store/59kj94x8mw61h22797q5iyjbd9vw3cms-bundled-python3-unix-linux-x86_64-3.9.12.drv' failed with exit code 1;
       last 10 log lines:
       > auto-patchelf: 4 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/bq6a2rvpqw2jh40ryjvghi64rzl0mjr5-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/lib/libpython3.9.so
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/bq6a2rvpqw2jh40ryjvghi64rzl0mjr5-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/lib/libpython3.9.so.1.0
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/bq6a2rvpqw2jh40ryjvghi64rzl0mjr5-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/bin/python3
       > error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by /nix/store/bq6a2rvpqw2jh40ryjvghi64rzl0mjr5-bundled-python3-unix-linux-x86_64-3.9.12/google-cloud-sdk/platform/bundledpythonunix/bin/python3.9
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/sw36plhp82916wwg6i6097rkzza7d950-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
       > /nix/store/sw36plhp82916wwg6i6097rkzza7d950-stdenv-linux/setup: line 1457: pop_var_context: head of shell_variables not a function context
       > /nix/store/sw36plhp82916wwg6i6097rkzza7d950-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/59kj94x8mw61h22797q5iyjbd9vw3cms-bundled-python3-unix-linux-x86_64-3.9.12.drv'.
error:
       error: 1 dependencies of derivation '/nix/store/ziwjz69s3bi4kny1x8rw883ij8h78xp1-google-cloud-sdk-408.0.1.drv' failed to build
error:
       error: 1 dependencies of derivation '/nix/store/svjcijkcwhvwskllfzjpwrhk3q3favhi-devenv-profile.drv' failed to build
error:
       error: 1 dependencies of derivation '/nix/store/z1cd93r1pry987b3fd12mihhan4dmy7z-devenv-shell-env.drv' failed to build
direnv: loading the environment failed
```

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/home/kevin/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by johnrichardrinehart** [comment]
Which commit is your `nixpkgs` channel pinned to?
