### ISSUE TITLE
caddy: WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#22454]
## Issue description

set `ulimit -n 8192` for caddy user, if possible in systemd service

### Steps to reproduce

run caddy with NixOS module

## Technical details

* System: NixOS 16.09.1623.74f24c7 (Flounder)
* Nix version: 1.11.6
* Nixpkgs version: 16.09.1623.74f24c7

**Comment by joachifm** [comment]
Per `systemd.exec(5)`, this sounds like a job for `LimitNOFILE`.

**Comment by grahamc** [comment]
I wonder where the balance lays of applying tuning to services by default vs. leaving it up to the user. Example, this could be easily tuned by the user via `systemd.services.caddy.unitConfig.LimitNOFILE = 8192;` (for example.) That said, if the 8192 option really is a widely deployed default, perhaps it is appropriate to use it by default.

**Comment by davidak** [comment]
@grahamc sure, but in this case i think it is not optional. We should package the software so it is usable in production.

**Comment by grahamc** [comment]
Makes sense to me. Is this a patch you're willing to implement yourself, along the lines of using LimitNOFile? Note: It would live in the serviceConfig and not unitConfig (I corrected my previous comment.)

**Comment by davidak** [comment]
@grahamc yes, i will do it.

**Comment by xay216216** [comment]
how to deal with it?

**Comment by davidak** [comment]
@xay216216 the issue should be fixed. do you still have any problem with caddy and file descriptor limit?

**Comment by eszeus** [comment]
Hello ;)

still getting the ulimit -n 8192 WARNING when starting caddy with rocket.chat-server.

How can I fix this? >-<

thanks!

**Comment by FRidh** [comment]
@eszeus do you still have this issue? If so, which nixpkgs version?
