### ISSUE TITLE
`syncthing-init` broke suddenly because failure to connect to 127.0.0.1:8483

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#232679]
### Describe the bug

Since #226088, I'm getting long timeouts on my deployments with:
```
mai 18 19:33:04 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:05 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:06 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:07 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:08 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:09 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:10 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:11 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:12 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:13 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:14 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:15 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:16 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:17 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:18 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:19 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:20 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:21 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:22 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:23 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:24 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:25 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:26 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:27 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:28 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:29 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:30 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:31 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:32 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:33 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:34 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:35 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:36 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:37 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:38 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:39 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:40 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:41 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
mai 18 19:33:42 Thorkell mwgs4pbznn6rmxir5a7ixvrawdxa7hqn-merge-syncthing-config[148524]: curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Couldn't con>
```

in `syncthing-init.service`

No warning, no deprecation, nothing, this is bad.

My SyncThing configuration:
```
  services.syncthing = {
    enable = true;
    user = "raito";
    group = "users";
    dataDir = "/home/raito/.state/syncthing";
    configDir = "/home/raito/.config/syncthing";
    systemService = false;
  };
```

### Steps To Reproduce
1. Upgrade to this PR
2. Get breakage

### Expected behavior

Clear instructions on why this is happening or fixes or warnings.

### Notify maintainers

@peterhoeg @jokogr @andrew-d for the **maintainers**
@Xyz00777 @doronbehar @Lassulus for the people actively taking part in those recent changes

**Comment by doronbehar** [comment]
Can you check if the following also fails for you?

```
sudo env RUNTIME_DIRECTORY=$(mktemp -d) $(systemctl cat syncthing-init.service | nix run nixpkgs#initool -- g - Service ExecStart --value-only)
```

I just updated my system using `nixos-rebuild test` and I did experience the issue after the first `nixos-rebuild test`, which also updated and triggered a restart of `syncthing.service`. However I tried to play a bit with the dash script that `syncthing-init` runs, and then I reverted it back and `syncthing-init.service` didn't fail (I ran `nixos-rebuild test` again) - it seems to be because `syncthing.service` was already running.

Did you try to simply restart `syncthing.service`? Or test if the issue persists after reboots?

**Comment by RaitoBezarius** [comment]
Your command fails for me too.

I didn't restart anything yet, I didn't reboot, this issue needs to be solved without any manual intervention, otherwise this is badly broken. It has to upgrade gracefully or it has to provide proper migration instructions in the release notes (which are not there, neither in the Discourse post for unstable breaking changes).

**Comment by doronbehar** [comment]
@RaitoBezarius this was not meant to be a strongly breaking change. Putting a message in [the Discourse thread](https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574/) would have been nice, but I haven't thought about it when I merged the PR. We hoped the module options renaming would be enough. Please forgive us for the inconvenience.

Now regarding your issue: `nixos-rebuild` tries to do it's best when switching generations, but sometimes big rebuilds cannot be switched fully smoothly. Please try to reboot, or at least restart `syncthing.service`. My intuition tells me that `syncthing-init.service` didn't run when `syncthing`'s _API_ was ready - although the systemd service itself was running at that point.

If my guess is correct, your issue might not be strictly due to #226088, but it somehow appeared only now - possibly due to other changes done between your previous NixOS generations - or simply due to the nature of the particular generation switch you made now.

**Comment by Lassulus** [comment]
weird, seems like raito has no declarative stuff configured so there should be no syncthing-init service anyway, since we only configure it if settings are set. but maybe that fails due to some default values making the set not-empty. I will take a look tomorrow to fix this to work as expected. Yeah the problem is always, that people only report their errors if after we merge them because no one chims into open PRs to check if it breaks their workflow :)

But yeah, sorry for the breakage. but I'm certain we will fix those minor issues in time.

**Comment by RaitoBezarius** [comment]
@doronbehar Please provide enough notice for everyone, this issue is quite hairy.

> Now regarding your issue: nixos-rebuild tries to do it's best when switching generations, but sometimes big rebuilds cannot be switched fully smoothly. Please try to reboot, or at least restart syncthing.service. My intuition tells me that syncthing-init.service didn't run when syncthing's API was ready - although the systemd service itself was running at that point.

Unfortunately, those are all wrong assumptions I think, I do not have a system syncthing service, so this is meaningless. I need to start the user service and then the syncthing-init will still fail, relying on a **system** service.

This is a massive breakage for people having `systemService = false;` in their configuration…

No matter what I do I cannot get syncthing-init to start.

**Comment by RaitoBezarius** [comment]
> Yeah the problem is always, that people only report their errors if after we merge them because no one chims into open PRs to check if it breaks their workflow :)

I think here, proper testing coverage would have uncovered the system service issue ;) and the missing declarative options. :)

But I am not maintainer of that subsystem, more a user.

**Comment by Lassulus** [comment]
> This is a massive breakage for people having `systemService = false;` in their configuration…
> 
> No matter what I do I cannot get syncthing-init to start.

I guess the quickfix would be to set syncthing-init not if systemService = false is set. I will prepare a PR for that

**Comment by ncfavier** [comment]
I'm a bit confused - what's the point of setting `user`, `group`, `dataDir` and `configDir` (in fact, what's the point of using the NixOS module at all) if you're not using the systemd service nor the declarative configuration? Just to get syncthing in PATH and open the firewall?

**Comment by doronbehar** [comment]
I also wonder: how come @RaitoBezarius' configuration hasn't failed before? @RaitoBezarius did you rely upon `syncthing-init.service` in any way? Is this merely an issue of a systemd service you don't need that now is enabled and fails?

**Comment by Lassulus** [comment]
> I also wonder: how come @RaitoBezarius' configuration hasn't failed before? @RaitoBezarius did you rely upon `syncthing-init.service` in any way? Is this merely an issue of a systemd service you don't need that now is enabled and fails?

So my take on this is, since there was neither folders, devices or anything else set, the old check just skipped creating the service, so raito never had the syncthing-init service until we merged this PR, which played with the mkIf logic and now it's enabled by default and breaking things.

**Comment by doronbehar** [comment]
> ... this PR, which played with the mkIf logic and now it's enabled by default and breaking things.

If indeed this is the case, we need to find out why `cfg.settings != {}` in Raito's case.

**Comment by Lassulus** [comment]
> > ... this PR, which played with the mkIf logic and now it's enabled by default and breaking things.
> 
> If indeed this is the case, we need to find out why `cfg.settings != {}` in Raito's case.

well the default value for settings (checked in the repl):
```
 { devices = { }; folders = { }; options = { limitBandwidthInLan = false; localAnnounceEnabled = true; localAnnouncePort = 21027; maxFolderConcurrency = 0; relaysEnabled = true; urAccepted = 0; }; }
```

so that was changed, also the check got broken with https://github.com/NixOS/nixpkgs/pull/232439/files#diff-fd4c91fd302760b673b3e9b6c8d3474f0ae371005b6be1baff552d0aa7ffe223L613

**Comment by RaitoBezarius** [comment]
> I also wonder: how come @RaitoBezarius' configuration hasn't failed before? @RaitoBezarius did you rely upon `syncthing-init.service` in any way? Is this merely an issue of a systemd service you don't need that now is enabled and fails?

I probably never relied on that.

**Comment by RaitoBezarius** [comment]
I always had a non-declarative SyncThing configuration from the start.

**Comment by RaitoBezarius** [comment]
> I'm a bit confused - what's the point of setting `user`, `group`, `dataDir` and `configDir` (in fact, what's the point of using the NixOS module at all) if you're not using the systemd service nor the declarative configuration? Just to get syncthing in PATH and open the firewall? EDIT: and the upstream systemd units, i guess

I thought it was creating a user systemd service, but you are right by reading the code, it is not the case. I think it must be some mixup with Home-Manager.

**Comment by doronbehar** [comment]
> So my take on this is, since there was neither folders, devices or anything else set, the old check just skipped creating the service, so raito never had the syncthing-init service until we merged this PR, which played with the mkIf logic and now it's enabled by default and breaking things.

I still don't understand why `syncthing-init.service` fails when `systemService == false`. What if someone wishes to set `systemService` but still set some `service.syncthing.settings` -  I don't think we should change the `mkIf` logic in https://github.com/NixOS/nixpkgs/pull/232705. I do think this logic should documented though, such that users like @RaitoBezarius will be able to disable `syncthing-init.service` if it causes them issues they don't want to debug.

**Comment by doronbehar** [comment]
> well the default value for settings (checked in the repl):

How did you check that @Lassulus ? Do you think it is even possible to truely set `default = {}`? I'd like to play with that too.

I have proposed an alternative fix to this issue at #232969 - touching only the documentation for the `services.syncthing.settings` option instructing how to completely disable `syncthing-init.service`.

**Comment by Lassulus** [comment]
> > well the default value for settings (checked in the repl):
> 
> How did you check that @Lassulus ? Do you think it is even possible to truely set `default = {}`? I'd like to play with that too.
> 
> I have proposed an alternative fix to this issue at #232969 - touching only the documentation for the `services.syncthing.settings` option instructing how to completely disable `syncthing-init.service`.

ah I just put raitos config in a file and ran `nix repl -I nixos-config=./raito.nix '<nixpkgs/nixos>'`. To get settings to be {} on default we would need to remove all the default values in the nested types, since the nested default values override the outer ones.

**Comment by RaitoBezarius** [comment]
Branch-off is tomorrow night, we really need a fix here :) — were you able to find a convenient solution? (I still suffer from like 10 minutes long restart of home-manager due to this…)

**Comment by doronbehar** [comment]
> ah I just put raitos config in a file and ran `nix repl -I nixos-config=./raito.nix '<nixpkgs/nixos>'`.

To be more specific, and explain this for others, I created the following:

```nix
{ config, ... }:

{
  config = {
    services.syncthing = {
      enable = true;
      user = "raito";
      group = "users";
      dataDir = "/home/raito/.state/syncthing";
      configDir = "/home/raito/.config/syncthing";
      systemService = false;
    };
  };
}
```

I deleted all `default = ` lines in the `services.syncthing.settings` definitions:

```diff
diff --git i/nixos/modules/services/networking/syncthing.nix w/nixos/modules/services/networking/syncthing.nix
index 7f4338c4b43..0e7c954e561 100644
--- i/nixos/modules/services/networking/syncthing.nix
+++ w/nixos/modules/services/networking/syncthing.nix
@@ -123,7 +123,6 @@ in {
           options = {
             # global options
             options = mkOption {
-              default = {};
               description = mdDoc ''
                 The options element contains all other global configuration options
               '';
@@ -132,7 +131,6 @@ in {
                 options = {
                   localAnnounceEnabled = mkOption {
                     type = types.bool;
-                    default = true;
                     description = lib.mdDoc ''
                       Whether to send announcements to the local LAN, also use such announcements to find other devices.
                     '';
@@ -140,7 +138,6 @@ in {
 
                   localAnnouncePort = mkOption {
                     type = types.int;
-                    default = 21027;
                     description = lib.mdDoc ''
                       The port on which to listen and send IPv4 broadcast announcements to.
                     '';
@@ -148,7 +145,6 @@ in {
 
                   relaysEnabled = mkOption {
                     type = types.bool;
-                    default = true;
                     description = lib.mdDoc ''
                       When true, relays will be connected to and potentially used for device to device connections.
                     '';
@@ -156,17 +152,14 @@ in {
 
                   urAccepted = mkOption {
                     type = types.int;
-                    default = 0;
                     description = lib.mdDoc ''
                       Whether the user has accepted to submit anonymous usage data.
-                      The default, 0, mean the user has not made a choice, and Syncthing will ask at some point in the future.
                       "-1" means no, a number above zero means that that version of usage reporting has been accepted.
                     '';
                   };
 
                   limitBandwidthInLan = mkOption {
                     type = types.bool;
-                    default = false;
                     description = lib.mdDoc ''
                       Whether to apply bandwidth limits to devices in the same broadcast domain as the local device.
                     '';
@@ -174,7 +167,6 @@ in {
 
                   maxFolderConcurrency = mkOption {
                     type = types.int;
-                    default = 0;
                     description = lib.mdDoc ''
                       This option controls how many folders may concurrently be in I/O-intensive operations such as syncing or scanning.
                       The mechanism is described in detail in a [separate chapter](https://docs.syncthing.net/advanced/option-max-concurrency.html).
@@ -186,7 +178,6 @@ in {
 
             # device settings
             devices = mkOption {
-              default = {};
               description = mdDoc ''
                 Peers/devices which Syncthing should communicate with.
 
@@ -206,7 +197,6 @@ in {
 
                   name = mkOption {
                     type = types.str;
-                    default = name;
                     description = lib.mdDoc ''
                       The name of the device.
                     '';
@@ -221,9 +211,7 @@ in {
 
                   autoAcceptFolders = mkOption {
                     type = types.bool;
-                    default = false;
                     description = mdDoc ''
-                      Automatically create or share folders that this device advertises at the default path.
                       See <https://docs.syncthing.net/users/config.html?highlight=autoaccept#config-file-format>.
                     '';
                   };
@@ -234,7 +222,6 @@ in {
 
             # folder settings
             folders = mkOption {
-              default = {};
               description = mdDoc ''
                 Folders which should be shared by Syncthing.
 
@@ -256,7 +243,6 @@ in {
 
                   enable = mkOption {
                     type = types.bool;
-                    default = true;
                     description = lib.mdDoc ''
                       Whether to share this folder.
                       This option is useful when you want to define all folders
@@ -271,7 +257,6 @@ in {
                       check = x: types.str.check x && (substring 0 1 x == "/" || substring 0 2 x == "~/");
                       description = types.str.description + " starting with / or ~/";
                     };
-                    default = name;
                     description = lib.mdDoc ''
                       The path to the folder which should be shared.
                       Only absolute paths (starting with `/`) and paths relative to
@@ -282,7 +267,6 @@ in {
 
                   id = mkOption {
                     type = types.str;
-                    default = name;
                     description = lib.mdDoc ''
                       The ID of the folder. Must be the same on all devices.
                     '';
@@ -290,7 +274,6 @@ in {
 
                   label = mkOption {
                     type = types.str;
-                    default = name;
                     description = lib.mdDoc ''
                       The label of the folder.
                     '';
@@ -298,7 +281,6 @@ in {
 
                   devices = mkOption {
                     type = types.listOf types.str;
-                    default = [];
                     description = mdDoc ''
                       The devices this folder should be shared with. Each device must
                       be defined in the [devices](#opt-services.syncthing.settings.devices) option.
@@ -306,7 +288,6 @@ in {
                   };
 
                   versioning = mkOption {
-                    default = null;
                     description = mdDoc ''
                       How to keep changed/deleted files with Syncthing.
                       There are 4 different types of versioning with different parameters.
@@ -364,7 +345,6 @@ in {
 
                   copyOwnershipFromParent = mkOption {
                     type = types.bool;
-                    default = false;
                     description = mdDoc ''
                       On Unix systems, tries to copy file/folder ownership from the parent directory (the directory it’s located in).
                       Requires running Syncthing as a privileged user, or granting it additional capabilities (e.g. CAP_CHOWN on Linux).
```


And while `NIX_PATH=$PWD`, I ran:

```
nix repl -I nixos-config=./raito.nix '<nixpkgs/nixos>'
```

And in the REPL I typed:

```
nix-repl> config.services.syncthing.settings
{ devices = «error: error: The option `services.syncthing.settings.devices' is used but not defined.»; folders = «error: error: The option `services.syncthing.settings.folders' is used but not defined.»; options = «error: error: The option `services.syncthing.settings.options' is used but not defined.»; }
```

This seems problematic to me. Do you think @Lassulus this can be solved?

**Comment by doronbehar** [comment]
> we really need a fix here :) — were you able to find a convenient solution?

@RaitoBezarius we'd appreciate your review on https://github.com/NixOS/nixpkgs/pull/232969 or on https://github.com/NixOS/nixpkgs/pull/232705 ?

> (I still suffer from like 10 minutes long restart of home-manager due to this…)

@RaitoBezarius did you try to simply set `services.syncthing.services = {};`? In my PR (https://github.com/NixOS/nixpkgs/pull/232969) I suggest to simply document this.

**Comment by ncfavier** [comment]
I vote we revert https://github.com/NixOS/nixpkgs/pull/226088 for now as it's not clear how to resolve this without breaking anyone's setup and that PR's changes seem unnecessary anyway (simply adding `freeformType`s to existing options should be fine). Arguably my "fix" in https://github.com/NixOS/nixpkgs/pull/232439/files#diff-fd4c91fd302760b673b3e9b6c8d3474f0ae371005b6be1baff552d0aa7ffe223L612-R616 was also not well thought out.

> did you try to simply set `services.syncthing.services = {};`

Assuming you mean `settings`, that will just get merged with the other settings and be a no-op.

**Comment by Lassulus** [comment]
> I vote we revert #226088 for now as it's not clear how to resolve this without breaking anyone's setup and that PR's changes seem unnecessary anyway (simply adding `freeformType`s to existing options should be fine)

sadly thats not the case, with the settings we mirror how the API expects values and not everything we can set is under folders, devices or options. before that people could set folders twice (once through folders and once through extraSettings) which could lead to weird behaviour

**Comment by ThinkChaos** [comment]
Ran into this, the service times-out after 1min.

I also use `systemService = false;`, my goal is to get NixOS to open the firewall, but manage the service via HM.

My config is:
```nix
{
    services.syncthing = {
      enable = true;
      openDefaultPorts = true;

      # Use HM's service instead
      systemService = false;
    };
}
```

Could we make `systemService = false;` also disable `syncthing-init.service`?

**Comment by ncfavier** [comment]
I feel like you should probably not enable the service if you only want to open ports. At least I definitely don't think that's the intended use case for `systemService = false;`.

**Comment by ThinkChaos** [comment]
Agreed it's not ideal, but the HM module has no easy way to configure the ports and I'd rather do this than hardcode the default ports myself.

What do you think of changing `syncthing-init.wantedBy` to `syncthing.service` instead of `multi-user.target`?

**Comment by doronbehar** [comment]
> What do you think of changing `syncthing-init.wantedBy` to `syncthing.service` instead of `multi-user.target`?

Sounds good to me. https://github.com/NixOS/nixpkgs/pull/233386 is the place to add this..

> I feel like you should probably not enable the service if you only want to open ports. At least I definitely don't think that's the intended use case for `systemService = false;`.

Then what is the intended usecase for `systemService = false;` @ncfavier ? Perhaps the documentation for it could be improved a bit..

**Comment by peterhoeg** [comment]
`wantedBy` should reference a target, not a service. If anything we should then have a `syncthing.target` that pulls in everything which in turn has `wantedBy = [ "multi-user.target" ];`

As for systemService, I'll expand on that later.
