### ISSUE TITLE
Gnome SIGTRAP when a window is moved in the activities view

### ISSUE THREAD

**Issue by Sciencentistguy** [NixOS/nixpkgs#234408]
### Describe the bug
Gnome SIGTRAPs when a window is dragged around in the activities view

### Steps To Reproduce
1. run gnome
3. open some windows
4. move them around (perhaps between monitors)
5. ...
6. most of the time (its not 100% consistent) gnome-shell will SIGTRAP and restart

### Expected behavior
Not that

### Additional context
The system is "chronos" on this system flake:

https://github.com/Sciencentistguy/nixfiles/commit/2128635bc8a7c021dba2d2083d72e9d640b41bc7

### Notify maintainers
@NixOS/gnome 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.29, NixOS, 23.11 (Tapir), 23.11.20230525.21eb6c6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by jtojnar** [comment]
Do you have any extensions enabled? Is that on X11 or Wayland? Could you please get the output of `bt full` in `coredumpctl gdb $pid` with the following installed (where `pid` is from the output of `coredumpctl`)?

```
environment.enableDebugInfo = true;
environment.systemPackages = [
  # Explicitly install to get debug symbols.
  pkgs.gnome.gnome-shell
  pkgs.gnome.mutter
  pkgs.gnome.gnome-session
  pkgs.glib
];
```

Do not forget to re-login after switching to that configuration or run `coredumpctl` with `NIX_DEBUG_INFO_DIRS=/run/current-system/sw/lib/debug` environment variable, since `nixos-rebuild switch` cannot update environment variables for running programs.

**Comment by Sciencentistguy** [comment]
Yes, I use the following extensions:
- blur my shell
- custom hot corners - extended
- hide top bar
but these worked fine in previous revisions

This is X11 - have an nvidia GPU

Here's the output of `bt full`:
[gdb.txt](https://github.com/NixOS/nixpkgs/files/11581687/gdb.txt)

**Comment by jtojnar** [comment]
Interesting. The underlying error is “BadCursor (invalid Cursor parameter)”.

According to https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/411#note_266927, it can happen when you use a custom icon theme that lacks `dnd-none` icon.

**Comment by Sciencentistguy** [comment]
I use the `paper` icon theme, and the `MacOSMonterey` cursor theme (https://github.com/ful1e5/apple_cursor) (https://github.com/Sciencentistguy/nixfiles/blob/master/packages/apple-cursor-theme/default.nix).

Is that icon a new one for gnome 44?

**Comment by jtojnar** [comment]
No, the aforementioned issue was already fixed [four years ago](https://gitlab.gnome.org/GNOME/mutter/-/commit/e741adb82e18fff557cb95185756f56ca7afcf3d). Hoping this is another instance of it, you could try patching mutter similarly for the three other occurrences of `XFreeCursor`:

https://gitlab.gnome.org/search?search=XFreeCursor&nav_source=navbar&project_id=547&group_id=8&search_code=true

**Comment by Sciencentistguy** [comment]
I've found a fix/workaround: disabling the home-manager gtk module

**Comment by jtojnar** [comment]
Yeah, that will get rid of the custom cursor theme.

Ideally, it would be fixed on the Mutter side, though.

**Comment by Sciencentistguy** [comment]
I still have the theme set, just via gnome tweaks rather than through Nix

**Comment by koppor** [comment]
Also happens here with kind of standard setup. As of today, Gnome doesn't start . I put "gtk = {enable = false};" into home.nix, but did not help.
