### ISSUE TITLE
klipper-firmware not working due to missing board-link directory

### ISSUE THREAD

**Issue by jacob-swanson** [NixOS/nixpkgs#241413]
### Describe the bug
I am attempting to flash my SKR Mini E3 V3 from my raspberry pi using the `klipper-flash-mcu` command, but it's not working correctly. It seems that some files are missing from the nix store.

### Steps To Reproduce
I've setup Klipper with the following config:
```nix
services.klipper = {
    enable = true;
    firmwares = {
      mcu = {
        enable = true;
        configFile = ./firmware.cfg;
        serial = "/dev/ttyACM0";
      };
    };
    configFile = ./klipper.cfg;
  };
```

Then on my pi, when I run `klipper-flash-mcu`:
```console
[root@voron-v0:~]# klipper-flash-mcu 
make: Entering directory '/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source'
sh: line 1: /nix/store/vlw3mh75hqam27l78rdg3p46m4fmvjdj-klipper-firmware-mcu-unstable-2023-04-24/board-link: Read-only file system
Makefile:103: /nix/store/vlw3mh75hqam27l78rdg3p46m4fmvjdj-klipper-firmware-mcu-unstable-2023-04-24/board-link: No such file or directory
make: *** [Makefile:101: /nix/store/vlw3mh75hqam27l78rdg3p46m4fmvjdj-klipper-firmware-mcu-unstable-2023-04-24/board-link] Error 1
make: Leaving directory '/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source'
```

### Expected behavior
`klipper-flash-mcu` flashes the mcu.

### Additional context

I'm using [colmena](https://github.com/zhaofengli/colmena) to apply the changes, and I have `deployment.buildOnTarget = true` set since the other machine is x86.

Contents of the kipper firmware directory
```console
[root@voron-v0:~]# ls /nix/store/vlw3mh75hqam27l78rdg3p46m4fmvjdj-klipper-firmware-mcu-unstable-2023-04-24
config  klipper.bin  klipper.elf
```

### Notify maintainers

@vtuan10 

### Metadata

```console
[root@voron-v0:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.36, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vtuan10** [comment]
Thanks for bringing this up, but unfortunately, I don't have that specific board to test it myself.

As far as I can see, there are some issues here:
1. `board-link` missing: Since https://github.com/NixOS/nixpkgs/pull/230252 we only install `klipper.{bin,elf}`. Could you try building the firmware prior to the change, or provide me the `firmware.cfg`, so that I could try as well to see whether the missing files are indeed created.
2. I'm unsure whether flashing it from `klipper` is actually supported. According to the [`generic configfile`](https://github.com/Klipper3d/klipper/blob/a96608add40e316f25f15d9c9d1c1fbd86dbbebe/config/generic-bigtreetech-skr-mini-e3-v3.0.cfg#L5) from `klipper` using `make flash` is not supported (which is all the `klipper-flash-mcu` command actually does). Can you try building and flashing the firmware manually using `make` and `make flash`?

As a workaround, you could for now copy the built `klipper-firmware` manually.

**Comment by jacob-swanson** [comment]
Thanks for the help.

1. I reverted #230252, and the `klipper-flash-mcu` command now works... as intended.
2. Yep, I can confirm that flashing a SKR Mini E3 V3 doesn't work using this method.

I tried just adding the `board-link` file by adding `cp out/board-link $out/ || true`, but then it fails to find `autoconf.h`.
```console
[root@voron-v0:~]# klipper-flash-mcu 
make: Entering directory '/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source'
  Building /nix/store/iw9axna5z7bclzwrgm3nx5b4gac8zmzl-klipper-firmware-mcu-unstable-2023-04-24/autoconf.h
Traceback (most recent call last):
  File "/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source/lib/kconfiglib/genconfig.py", line 154, in <module>
    main()
  File "/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source/lib/kconfiglib/genconfig.py", line 117, in main
    kconf.write_autoconf()
  File "/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source/lib/kconfiglib/kconfiglib.py", line 1456, in write_autoconf
    if self._write_if_changed(filename, self._autoconf_contents(header)):
  File "/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source/lib/kconfiglib/kconfiglib.py", line 2280, in _write_if_changed
    with self._open(filename, "w") as f:
  File "/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source/lib/kconfiglib/kconfiglib.py", line 3927, in _open
    open(filename, mode, encoding=self._encoding)
OSError: [Errno 30] Read-only file system: '/nix/store/iw9axna5z7bclzwrgm3nx5b4gac8zmzl-klipper-firmware-mcu-unstable-2023-04-24/autoconf.h'
make: *** [Makefile:110: /nix/store/iw9axna5z7bclzwrgm3nx5b4gac8zmzl-klipper-firmware-mcu-unstable-2023-04-24/autoconf.h] Error 1
make: Leaving directory '/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source'
```

Then with, the `cp -r out/* $out`, it just fails to flash:
```console
[root@voron-v0:~]# klipper-flash-mcu 
make: Entering directory '/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source'
  Flashing /nix/store/d80bn2hdnpk2z9a4xvb4cmxwqcg6fs5w-klipper-firmware-mcu-unstable-2023-04-24/klipper.bin to /dev/serial/by-id/usb-Klipper_stm32g0b1xx_06002E001950425938323120-if00 via stm32flash
stm32flash 0.7

http://stm32flash.sourceforge.net/

Using Parser : Raw BINARY
Size         : 29920
Interface serial_posix: 57600 8E1
Failed to init device.

make: *** [src/stm32/Makefile:110: serialflash] Error 1
make: Leaving directory '/nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source'
```

**Comment by vtuan10** [comment]
Thanks for quickly trying it out. 
I'm unsure whether the flashing issue will ever be fixed in `klipper`, but I don't think it makes much sense to create any elaborate workarounds for this particular board in `klipper-flash`.

Regarding the missing files: 
@lovesegfault Should we revert this change? I don't have much knowledge about the various flashing tools which require more than the binaries and if those would fail anyway at a later stage like in this case.

**Comment by jacob-swanson** [comment]
Would it make sense to have an option like `services.klipper.firmwares.<mcu>.enableKlipperFlash` to enable/disable the `klipper-flash-<mcu>` command? In the description, you could tell the user to go check if their board supports flashing. That might help people like me from thinking the package was bugged.

**Comment by vtuan10** [comment]
Sorry, completely forgot about this. I created a PR: https://github.com/NixOS/nixpkgs/pull/243475

**Comment by pinpox** [comment]
This issue persists with an ender3v2 neo
```
[root@nixos-3dprint-raspi:~]# klipper-flash-ender3 
make: Entering directory '/nix/store/8wzv1hfgxxpc9lnw2k3dry9mnknmwfga-source'
sh: line 1: /nix/store/3lg1pd1977ada1jknsa0jai5lijlimwi-klipper-firmware-ender3-unstable-2023-11-16/board-link: Read-only file system
Makefile:103: /nix/store/3lg1pd1977ada1jknsa0jai5lijlimwi-klipper-firmware-ender3-unstable-2023-11-16/board-link: No such file or directory
make: *** [Makefile:101: /nix/store/3lg1pd1977ada1jknsa0jai5lijlimwi-klipper-firmware-ender3-unstable-2023-11-16/board-link] Error 1
make: Leaving directory '/nix/store/8wzv1hfgxxpc9lnw2k3dry9mnknmwfga-source'
```

If I understand [this post](https://www.obico.io/blog/install-klipper-ender-3/) correctly the board should support flashing, they do it there the manual way.

**Comment by vtuan10** [comment]
Sorry, I don't have the printer myself and cannot confirm this.
But according to the [klipper sample config](https://github.com/Klipper3d/klipper/blob/master/config/printer-creality-ender3-v2-neo-2022.cfg) of your printer it states that you should copy the file manually to the sd card.

Please try to flash it similar to https://github.com/NixOS/nixpkgs/issues/241413#issuecomment-1620331923, if it is only the `board-link` issue, we surely can revert the change.

**Comment by pinpox** [comment]
Manual flash via SD card worked. I guess it's printer-specific then and not an issue here.
