### ISSUE TITLE
xdg-open in plasma5 fails when multiple desktop files for the same firefox exist and some are invalid

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#24316]
## Issue description

i started with 
```
$ ls .local/share/applications/userapp-
userapp-Evolution-408OGY.desktop  userapp-Nightly-4M6KHY.desktop    userapp-Nightly-HJV0HY.desktop    userapp-Nightly-YSBYXY.desktop    
userapp-Nightly-38WZGY.desktop    userapp-Nightly-5HOWVY.desktop    userapp-Nightly-PIFGHY.desktop 
```

and xdg-open would fail

after i deleted them and restarted firefox, it asked for being the default again,
xdg-open started to work, the file named `userapp-Nightly-QX3WXY.desktop` was created

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by globin** [comment]
cc @ttuegel, @layus

**Comment by layus** [comment]
Yes, the implementation of "default" browsers is buggy (see #4370).
Your specific case should be solved with https://github.com/NixOS/nixpkgs/pull/23516.

**Comment by layus** [comment]
@RonnyPfannschmidt Can you confirm this works correctly now ? Firefox should not produce multiple .desktop files anymore. You may need to remove the old .desktop files beforehand.

**Comment by RonnyPfannschmidt** [comment]
@layus i can confirm after work since i decided to keep nix on my personal machines

**Comment by globin** [comment]
@RonnyPfannschmidt ping

**Comment by RonnyPfannschmidt** [comment]
firefox now always has a nice symlink there

other apps still have the issue tho (like chrome)

**Comment by RonnyPfannschmidt** [comment]
reopening, since i just noticed, that the symlink is concrete into a derivation and not adding a gc root

**Comment by ryukinix** [comment]
@layus how you fixed the .desktop generation on firefox nightly? I'm able to reproduce this issue even in another system (Arch Linux). This is pretty annoying because If I change the `Exec` line of `.desktop` file when I open the firefox it will say that firefox is not the default browser and will generated again a new `userapp-Nightly-<random>.desktop` file... I was wondering if is possible to configure that.
