### ISSUE TITLE
Woodpecker CI does not work correctly out of the box

### ISSUE THREAD

**Issue by j4m3s-s** [NixOS/nixpkgs#249602]
### Describe the bug
Unstable versions of Woodpecker have been updated to 1.0+ which changes how the software works. It introduces backends (ssh, local, docker, kubernetes).

- exec backend as referenced in configuration.nix doesn't exist anymore
- local backend seems to need plugin-git (https://github.com/woodpecker-ci/plugin-git which can be built using buildGoPackage -- you can use `gitMinimal` for the clone part it's lighter than `git`) and apparently has issues passing the token to clone private repos (haven't investigated further)
- daemon needs a configuration file (that can apparently be empty) for some things. I'm not sure if it needs to be writable.

### Steps To Reproduce
1. Use services.woodpecker-*.package = unstablePkgs.woodpecker-*;
2. Errors out in the logs / the systemd service when started.

### Expected behavior
I expected to use upstream package/module to work directly

### Additional context
- Agent and server must be of the same version otherwise it doesn't work
- It makes some non-reversibles migrations to the DB so beware of your DB if you care about it ~

### Notify maintainers
@ambroisie @techknowlogick @adamcstephens 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ambroisie** [comment]
Hi James!

I'd suggest you go look at [my configuration](https://git.belanyi.fr/ambroisie/nix-config/src/commit/424bb2e7b9dcaa3591a60d3895a76f91e2122f5e/modules/services/woodpecker) to see how to configure Woodpecker, as it should be a pretty good example of setting up multiple agents with different backends.

1. Indeed, this should be using `local` instead of `exec`, this was a typo in the docs.
2. `plugin-git` is [packaged in nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/continuous-integration/woodpecker-plugin-git/default.nix) already.
3. I have not had any issues relating to a configuration file, I would advise you to ask this on their [matrix channel](https://matrix.to/#/#woodpecker:matrix.org) to discuss it further.

The issue regarding private repositories is _not_ due to NixOS, and should be fixed by [this PR](woodpecker-ci/woodpecker#2017).

I'm not sure what issue you have against the current modules as they exist today, but please do provide feedback on what we could improve in our documentation.

**Comment by j4m3s-s** [comment]
Hey! 
Will take a look and get back to you shortly with the results. 
Thanks for answering quickly!

**Comment by 6543** [comment]
well `private repos + local backend + window` still dont work ... as netrc is not parsed on windows by default

also there was just reported regression for linux ... I'll investigate

**Comment by 6543** [comment]
> daemon needs a configuration file

you revere to the agent ... it only has to be writable on first agent run, as it saves the ID the server assign to an agent,
you can change the location with `WOODPECKER_AGENT_CONFIG_FILE` env var or `--agent-config` command argument

**Comment by 6543** [comment]
> local backend seems to need plugin-git

yes and for nix, nix should take care of that on its own ... as the pre build binary's might not work here ?

**Comment by pinpox** [comment]
> yes and for nix, nix should take care of that on its own ... as the pre build binary's might not work here ?

Yes, e.g. like this: https://github.com/lounge-rocks/the-lounge/blob/89f73ae27fa4141eb5bf7b5de1df7fdcd27ac7f6/modules/woodpecker/local-agent.nix#L61-L62

Since there also is a [NixOS modul](https://github.com/NixOS/nixpkgs/blob/b30c68669df77d981ce4aefd6b9d378563f6fc4e/nixos/modules/services/continuous-integration/woodpecker/agents.nix) it might make sense to enable it there. @ambroisie you seem to be maintainer of it, would you consider it useful to add it there? There might be other parts worth porting, e.g. the bindpaths required to allow nix to run in the local backend.

> Indeed, this should be using `local` instead of `exec`, this was a typo in the docs.
Should be fixed in the [example of the module](https://github.com/NixOS/nixpkgs/blob/466a8156831a39e86993c852d280c7b1a7242d29/nixos/modules/services/continuous-integration/woodpecker/agents.nix#L122-L126)

**Comment by ambroisie** [comment]
The modules are kept lightweight and un-opinionated to avoid stepping on anybody's toes when they're trying to setup their own agents.

I don't think it would make sense to make them much more complicated, adding a `services.woodpecker-agents.*.path` option would be nice, but I'm not looking to make them more complicated than they currently are.

Instead, if you feel like the setup is still non-trivial, I'd recommend documenting how to setup the agents,  like it has been for e.g: the GitLab runners.

**Comment by j4m3s-s** [comment]
And here I got some time to get back to this issue. (Can't believe it's been a month I'm sorry I haven't seen the notifications :x ).
I was about to write some config to add the `path` you just commited to the repo, 2fast4me. Thank you for all the changes!

Seems that private clone is still not working on my side (I'll work on it again). But having my own private clone works well instead!

**Comment by adamcstephens** [comment]
Is this still an issue?

**Comment by ambroisie** [comment]
Ah, no shouldn't be, thanks for the ping.
