### ISSUE TITLE
i915 doesn't work in Linux 6.6.0

### ISSUE THREAD

**Issue by blitz** [NixOS/nixpkgs#265187]
### Describe the bug

`linuxPackages_latest` on NixOS 23.05 now ships with Linux 6.6.0. This results in a non-booting system for my Tuxedo laptop with Intel GPU, because the system hangs after loading the kernel module.

I'm pretty sure this will be fixed with 6.6.1, so there's probably nothing to be done here except waiting. I'm just leaving this here for people to find it.

My GPU is:

```
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller]
```

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/37907/d68f5fa3-d3ab-4519-b19a-c89b26d000e4)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.05 (Stoat), 23.05.20231027.1a3c95e`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `""`
 - channels(julian): `""`
 - nixpkgs: `not found`
```

(PS. This is not the version that fails, because that doesn't boot.)

**Comment by K900** [comment]
#265015 should fix this.

**Comment by dedsm** [comment]
I'm having a similar issue here, but in my case it _looks_ like it's hanging, but it's only the framebuffer, so after typing my drive encryption password, the ssytem boots and as soon as the display manager starts, everything acts normal

**Comment by LSleutsky** [comment]
> I'm having a similar issue here, but in my case it _looks_ like it's hanging, but it's only the framebuffer, so after typing my drive encryption password, the ssytem boots and as soon as the display manager starts, everything acts normal

I can confirm that this same issue is happening with me. I see the `loading i915 module` console message, and then it appears like its hung, but if I enter my username and password (_in this case, a fingerprint authentication_), and then type `Hyprland`, my WM loads just fine, and is on kernel 6.6.0, without any other (_noticeable_) issues...

**Comment by Antiarchitect** [comment]
Hi, I've tired to exclude i915 from boot.initrd.kernelModules but still no luck. I cant see the prompt after opening my LUKS filesystem. Just black screen.

**Comment by K900** [comment]
Please wait for the fix PRs to make it to channels.

**Comment by eclairevoyant** [comment]
Or if you want to spend the CPU cycles, apply the contents of the PR yourself, until the PR lands.

```nix
boot.kernelPatches = let
      inherit (lib.kernel) yes;
    in [
      {
        name = "264832";
        patch = null;
        extraStructuredConfig = {
          FRAMEBUFFER_CONSOLE_DETECT_PRIMARY = yes;
          DRM_FBDEV_EMULATION = yes;
        };
      }
    ];
```

**Comment by FavoritoHJS** [comment]
breaking news:

https://nixpk.gs/pr-tracker.html?pr=265015

it's in, and i can confirm it indeed works as advertised.

GET IT WHILE IT'S HOT

**Comment by blitz** [comment]
I guess we can close this then. :+1:
