### ISSUE TITLE
'GstBase', version '1.0' not found

### ISSUE THREAD

**Issue by malkmusl** [NixOS/nixpkgs#268021]
### Describe the bug
Error connecting to graphical console:
Error opening SPICE console: Typelib file for namespace 'GstBase', version '1.0' not found
after updating darivation

### Steps To Reproduce
1. created a new Linux Kvm (Fedora 39)
2. Everything else default presented by virt-manager
3. Start VM not working
4. added this to nix configuration
    ```(virt-manager.overrideAttrs (old: {
      propagatedBuildInputs = [
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-good
      ];

      nativeBuildInputs = lib.lists.subtractLists [ wrapGAppsHook ] old.nativeBuildInputs;
      buildInputs = lib.lists.subtractLists [
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-good
      ]
        old.buildInputs
      ++ [
        python3.pkgs.pygobject3
        python3.pkgs.libvirt
        python3.pkgs.libxml2
        python3.pkgs.requests
      ];

    }))
   ```
5. tryed again to start the vm

### Expected behavior
The resulting VM window should show the video output of the VM.

### Screenshots
![282985916-f9736653-4ab6-454c-9ebf-a771cac361bf](https://github.com/NixOS/nixpkgs/assets/56474599/8f773fc4-22a2-4119-bf20-67e62a88b216)

### Notify maintainers

@qknight @offline @fpletz @globin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11pre546599.e44462d6021b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by iynaix** [comment]
Duplicate of #267579 and fixed in #267722.

**Comment by iynaix** [comment]
The suggested [temporary fix](https://github.com/NixOS/nixpkgs/issues/267579#issuecomment-1815519722) works for me.

**Comment by Mic92** [comment]
This should be fixed now.

**Comment by malkmusl** [comment]
I tried the temporary fix, added the things as in the other issue, but unfortunately, it was not successful. So i opend this one

**Comment by Mic92** [comment]
Please update nixpkgs instead of testing the temporary fix: https://nixpk.gs/pr-tracker.html?pr=267722 and re-open only if this doesn't work.

**Comment by malkmusl** [comment]
I updated the channel and removed the temp fix still not working...

**Comment by MikaelFangel** [comment]
But the temp fix works?

**Comment by Mic92** [comment]
> I updated the channel and removed the temp fix still not working...

Please post the output of `nixos-version` here. Did you install virt-manager with nixos?
