### ISSUE TITLE
OpenGL driver failure on unstable after update

### ISSUE THREAD

**Issue by Jackaed** [NixOS/nixpkgs#281009]
### Describe the bug
OpenGL driver failure after most recent update on unstable channel.

### Steps To Reproduce
1. Run `MESA_LOADER_DRIVER_OVERRIDE=zink glxinfo | grep 'renderer string'` before upgrade, get result OpenGL renderer string: zink Vulkan 1.3(AMD Radeon Graphics (RADV REMBRANDT) (MESA_RADV)).
2. Upgrade to newest unstable nixpkgs.
3. Get result: DRI3 not available failed to load driver: zink

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05.20240113.9b19f5e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/edward/.nix-defexpr/channels/nixpkgs`
```
Please note that this causes steam to fail to launch on my system. My system is a Lenovo ThinkPad T14s Gen3 AMD, with a Ryzen 7 6850u. 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Jackaed** [comment]
I imagine there is more information I can provide to make the process of fixing this easier, please let me know.

**Comment by CactiChameleon9** [comment]
I am also experiencing this issue, `glxgears` is using `llvmpipe` and `vkcube` doesn't work with the following error:
```
daniel@danielLaptop ~> vkcube 
Selected GPU 0: AMD Radeon Graphics (RADV RENOIR), type: IntegratedGpu
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
```

Here is the relevant part of my nixOS config:
```
    hardware = {
        opengl = {
            enable = true;

            extraPackages = with pkgs; [
                amdvlk
                rocm-opencl-icd
                rocm-opencl-runtime
            ];

            extraPackages32 = with pkgs; [driversi686Linux.amdvlk];

            driSupport = true;
            driSupport32Bit = true;
        };
    };
    environment.variables.AMD_VULKAN_ICD = "RADV";
```

I am running 23.11 with a fair number of graphical apps from unstable

**Comment by spikespaz** [comment]
I am here because after loading & logging-in, Steam displays a black rectangle that does not respond to SIGTERM.

**Comment by Jackaed** [comment]
This issue seems to still persist. The last version of mesa that I can confirm works as expected is 23.1.9. Mesa 23.3.3 does not work, meaning that it is one of these three commits which has caused the issue:
https://github.com/NixOS/nixpkgs/commit/abd1d7f93319df76c6fee7aee7ecd39ec6136d62
https://github.com/NixOS/nixpkgs/commit/436745338e7f794bd8807beb6fa62dbecda768b7
https://github.com/NixOS/nixpkgs/commit/8d214b9574efe2be28374ba11599ccd86b8fb401

Please could this be addressed ASAP? I essentially can't update until this gets fixed.

**Comment by spikespaz** [comment]
This also appears to have broken Firefox (it crashes on launch, silent errors) and switching to older generation corrupted my profile.

**Comment by Jackaed** [comment]
Okay something has gone very, very wrong here. I attempted to rollback to a very old unstable release (specifically 24.05.20231201.69a165d) and this issue persisted. I don't understand how that's even possible. Output of vkcube is:

```
Selected GPU 0: AMD Radeon Graphics (RADV REMBRANDT), type: IntegratedGpu
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
Could not find both graphics and present queues
```

I've tried my best to see if I am capable of fixing this and this is well beyond my knowledge or understanding, but this essentially means my laptop is unusable, since I cant roll back and fix this issue now.

**Comment by Jackaed** [comment]
Note to self, when messing with broken drivers, keep your system version and home-manager version the same.

**Comment by Jackaed** [comment]
Okay I can confirm that the issue is actually not related to any Mesa updates, release "NixOS 24.05.20240114.dd5621d" uses mesa 23.3.3 (i.e. latest) and this issue does not occur in this build.

**Comment by Jackaed** [comment]
Okay now I'm extremely confused. I've updated both home-manager and nixos to latest and it seems to just... work? I don't know what's changed, but for me everything is now fixed and working as intended. I was unable to switch home-manager version for a while because of a build failure, so the reason it didn't work may have just been due to the mismatched versions. I'm going to close this.

**Comment by CactiChameleon9** [comment]
Still very much broken for me - could be 23.11 vs unstable

**Comment by spikespaz** [comment]
Perhaps some other package update happened between the time this issue was opened and the day it was closed that caused it to start working for some. I will try again (I am afraid), but I have a feeling this issue is still relevant and should not be closed.

**Comment by Jackaed** [comment]
Except I rolled forward through a number of generations and every single nixpkgs build I tried worked as intended. I think my issue was just caused by the home-manager/NixOS version mismatch, any other issues are probably different, just causing the same symptoms.

**Comment by genevieve-me** [comment]
I am still having issues: this seems related to https://github.com/NixOS/nixpkgs/issues/238101 (Steam won't start without `-cef-disable-gpu`).

I'm on `nixos-unstable` faf912b086576fd1a15fca610166c98d47bc667e (latest as of 2024-02-07) and also have issues with `vkcube` ("No DRI3 support detected", as above). Possibly related, `glxinfo` can't identify my GPU and returns `OpenGL renderer string: llvmpipe (LLVM 16.0.6, 256 bits)`.

**Comment by justinrubek** [comment]
I'm seeing the same issue, on https://github.com/NixOS/nixpkgs/commit/d934204. I can start steam using the above workaround (`-cef-disable-gpu`), but the handful of games I've tried have failed to launch because of the DRI3 issue.

**Comment by spikespaz** [comment]
For me, OpenGl appears to work for Wayland applications, and I only norice that swrend/LLVMPIPE is chosen for Xwayland. Some applications tell me that they failed to load Zink, but the driver is present at `/run/opengl-driver/lib/dri/zink_dri.so`.
