### ISSUE TITLE
Zero Hydra Failures for 17.09

### ISSUE THREAD

**Issue by globin** [NixOS/nixpkgs#28643]
We currently have ~170 failing jobs on hydra:
https://hydra.nixos.org/jobset/nixos/trunk-combined

We're hoping for a big effort from all contributors and maintainers to get this down to zero for the release at the end of September.

@fpletz and I will be updating this issue with further information continuously.

Off we go on a sprint to making 17.09 the best release possible!
Getting latest evaluation for http://hydra.nixos.org/jobset/nixos/release-17.09
Parsing evaluation https://hydra.nixos.org/eval/1395311
- [ ] [nixos.tests.cjdns.i686-linux](https://hydra.nixos.org/build/61678751)
- [ ] [nixos.tests.ec2-config](https://hydra.nixos.org/build/61686363)
- [ ] [nixos.tests.gnome3-gdm.i686-linux](https://hydra.nixos.org/build/61677748)
- [ ] [nixos.tests.gnome3-gdm.x86_64-linux](https://hydra.nixos.org/build/61681871)
  - maintainers: @lethalman
- [ ] [nixos.tests.hibernate.i686-linux](https://hydra.nixos.org/build/61681012)
- [ ] [nixos.tests.networking.networkd.macvlan.i686-linux](https://hydra.nixos.org/build/61678429)
- [ ] [nixos.tests.networking.networkd.macvlan.x86_64-linux](https://hydra.nixos.org/build/61676902)
  - maintainers: @wkennington
- [ ] [nixos.tests.pam-oath-login.i686-linux](https://hydra.nixos.org/build/61680388)
- [ ] [nixos.tests.pam-oath-login.x86_64-linux](https://hydra.nixos.org/build/61682286)
- [ ] [nixos.tests.pgjwt.i686-linux](https://hydra.nixos.org/build/61677795)
- [ ] [nixos.tests.pgjwt.x86_64-linux](https://hydra.nixos.org/build/61682165)
  - maintainers: @spinus
- [ ] [nixos.tests.radicale.i686-linux](https://hydra.nixos.org/build/61682349)
- [ ] [nixos.tests.radicale.x86_64-linux](https://hydra.nixos.org/build/61678965)
  - maintainers: @aneeshusa, @infinisil
- [ ] [nixpkgs.altcoins.ethrun.x86_64-linux](https://hydra.nixos.org/build/61677132)
  - maintainers: @dbrock
- [ ] [nixpkgs.altcoins.hivemind.x86_64-linux](https://hydra.nixos.org/build/61680263)
  - maintainers: @canndrew
- [ ] [nixpkgs.altcoins.hivemindd.x86_64-linux](https://hydra.nixos.org/build/61650693)
  - maintainers: @canndrew
- [ ] [nixpkgs.amtterm.x86_64-linux](https://hydra.nixos.org/build/61461315)
  - maintainers: @ehmry
- [ ] [nixpkgs.casperjs.x86_64-linux](https://hydra.nixos.org/build/61678729)
  - maintainers: @bluescreen303
- [ ] [nixpkgs.darwin.opencflite.x86_64-linux](https://hydra.nixos.org/build/61455956)
- [ ] [nixpkgs.darwin.swift-corefoundation.x86_64-linux](https://hydra.nixos.org/build/61460054)
- [ ] [nixpkgs.emulationstation.x86_64-linux](https://hydra.nixos.org/build/61676816)
  - maintainers: @edwtjo
- [ ] [nixpkgs.envoy.x86_64-linux](https://hydra.nixos.org/build/61680590)
  - maintainers: @cstrahan
- [ ] [nixpkgs.ethrun.x86_64-linux](https://hydra.nixos.org/build/61681678)
  - maintainers: @dbrock
- [ ] [nixpkgs.fakenes.x86_64-linux](https://hydra.nixos.org/build/61680262)
- [ ] [nixpkgs.fenics.x86_64-linux](https://hydra.nixos.org/build/61680411)
- [ ] [nixpkgs.firebirdSuper.x86_64-linux](https://hydra.nixos.org/build/61466750)
  - maintainers: @marcweber
- [ ] [nixpkgs.flite.x86_64-linux](https://hydra.nixos.org/build/61455859)
- [ ] [nixpkgs.freebayes.x86_64-linux](https://hydra.nixos.org/build/61679395)
  - maintainers: @jdagilliland
- [ ] [nixpkgs.gcsfuse.x86_64-linux](https://hydra.nixos.org/build/61634789)
  - maintainers: @ehmry, @lethalman
- [ ] [nixpkgs.giv.x86_64-linux](https://hydra.nixos.org/build/61679331)
  - maintainers: @viric
- [ ] [nixpkgs.gmsh.x86_64-linux](https://hydra.nixos.org/build/61681073)
- [ ] [nixpkgs.gnaural.x86_64-linux](https://hydra.nixos.org/build/61680874)
  - maintainers: @ehmry
- [ ] [nixpkgs.gplates.x86_64-linux](https://hydra.nixos.org/build/61677710)
- [ ] [nixpkgs.grass.x86_64-linux](https://hydra.nixos.org/build/61679468)
- [ ] [nixpkgs.guile-xcb.x86_64-linux](https://hydra.nixos.org/build/61468836)
- [ ] [nixpkgs.guile_lib.x86_64-linux](https://hydra.nixos.org/build/61469403)
- [ ] [nixpkgs.haskellPackages.gore-and-ash-async.x86_64-linux](https://hydra.nixos.org/build/61469795)
- [ ] [nixpkgs.haskellPackages.rocksdb-haskell.x86_64-linux](https://hydra.nixos.org/build/61677254)
- [ ] [nixpkgs.helmholtz.x86_64-linux](https://hydra.nixos.org/build/61682027)
  - maintainers: @magnetophon
- [ ] [nixpkgs.hplip_3_15_9.x86_64-linux](https://hydra.nixos.org/build/61680177)
  - maintainers: @jgeerds, @nckx
- [ ] [nixpkgs.ibus-engines.anthy.x86_64-linux](https://hydra.nixos.org/build/61677024)
  - maintainers: @gebner, @ericsagnes
- [ ] [nixpkgs.ibus-engines.hangul.x86_64-linux](https://hydra.nixos.org/build/61681171)
  - maintainers: @ericsagnes
- [ ] [nixpkgs.julia-git.x86_64-linux](https://hydra.nixos.org/build/61677459)
  - maintainers: @7c6f434c
- [ ] [nixpkgs.kodiPlain.x86_64-linux](https://hydra.nixos.org/build/61679885)
  - maintainers: @domenkozar, @titanous, @edwtjo
- [ ] [nixpkgs.libsingular.x86_64-linux](https://hydra.nixos.org/build/61455215)
  - maintainers: @7c6f434c
- [ ] [nixpkgs.linuxPackages_4_13.openafsClient.x86_64-linux](https://hydra.nixos.org/build/61559047)
  - maintainers: @z77z
- [ ] [nixpkgs.linuxPackages_hardened.openafsClient.x86_64-linux](https://hydra.nixos.org/build/61559286)
  - maintainers: @z77z
- [ ] [nixpkgs.linuxPackages_latest.openafsClient.x86_64-linux](https://hydra.nixos.org/build/61559115)
  - maintainers: @z77z
- [ ] [nixpkgs.linuxPackages_latest_xen_dom0.openafsClient.x86_64-linux](https://hydra.nixos.org/build/61559167)
  - maintainers: @z77z
- [ ] [nixpkgs.lispPackages.pgloader.x86_64-linux](https://hydra.nixos.org/build/61467942)
- [ ] [nixpkgs.luajitPackages.cjson.x86_64-linux](https://hydra.nixos.org/build/61461536)
- [ ] [nixpkgs.luajitPackages.luaexpat.x86_64-linux](https://hydra.nixos.org/build/61458674)
  - maintainers: @flosse
- [ ] [nixpkgs.luajitPackages.luazip.x86_64-linux](https://hydra.nixos.org/build/61472440)
- [ ] [nixpkgs.meshlab.x86_64-linux](https://hydra.nixos.org/build/61678934)
  - maintainers: @viric
- [ ] [nixpkgs.mesos.x86_64-linux](https://hydra.nixos.org/build/61678387)
  - maintainers: @cstrahan, @kevincox, @offline
- [ ] [nixpkgs.natron.x86_64-linux](https://hydra.nixos.org/build/61679747)
  - maintainers: @puffnfresh
- [ ] [nixpkgs.nix-exec.x86_64-linux](https://hydra.nixos.org/build/61681349)
- [ ] [nixpkgs.odamex.x86_64-linux](https://hydra.nixos.org/build/61676876)
  - maintainers: @MP2E
- [ ] [nixpkgs.opencascade.x86_64-linux](https://hydra.nixos.org/build/61679393)
  - maintainers: @viric
- [ ] [nixpkgs.opencascade_6_5.x86_64-linux](https://hydra.nixos.org/build/61678184)
  - maintainers: @viric
- [ ] [nixpkgs.openmodelica.x86_64-linux](https://hydra.nixos.org/build/61676827)
  - maintainers: @smironov
- [ ] [nixpkgs.openrw.x86_64-linux](https://hydra.nixos.org/build/61677118)
  - maintainers: @kragniz
- [ ] [nixpkgs.ori.x86_64-linux](https://hydra.nixos.org/build/61678264)
- [ ] [nixpkgs.pjsip.x86_64-linux](https://hydra.nixos.org/build/61464384)
  - maintainers: @viric
- [ ] [nixpkgs.purePackages.gen.x86_64-linux](https://hydra.nixos.org/build/61680359)
  - maintainers: @asppsa
- [ ] [nixpkgs.python27Packages.bokeh.x86_64-linux](https://hydra.nixos.org/build/61681388)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python27Packages.flake8-future-import.x86_64-linux](https://hydra.nixos.org/build/61681630)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python27Packages.graph-tool.x86_64-linux](https://hydra.nixos.org/build/61680062)
- [ ] [nixpkgs.python27Packages.libagent.x86_64-linux](https://hydra.nixos.org/build/61648043)
  - maintainers: @np, @chaoflow
- [ ] [nixpkgs.python27Packages.libnacl.x86_64-linux](https://hydra.nixos.org/build/61461121)
  - maintainers: @xvapx, @chaoflow
- [ ] [nixpkgs.python27Packages.locustio.x86_64-linux](https://hydra.nixos.org/build/61457289)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python27Packages.marionette-harness.x86_64-linux](https://hydra.nixos.org/build/61465149)
  - maintainers: @7c6f434c, @chaoflow
- [ ] [nixpkgs.python27Packages.pycapnp.x86_64-linux](https://hydra.nixos.org/build/61470692)
  - maintainers: @cstrahan, @chaoflow
- [ ] [nixpkgs.python27Packages.pywbem.x86_64-linux](https://hydra.nixos.org/build/61455800)
  - maintainers: @peterhoeg, @chaoflow
- [ ] [nixpkgs.python27Packages.ws4py.x86_64-linux](https://hydra.nixos.org/build/61460691)
  - maintainers: @rickynils, @chaoflow
- [ ] [nixpkgs.python27Packages.xarray.x86_64-linux](https://hydra.nixos.org/build/61679757)
  - maintainers: @fridh, @chaoflow
- [ ] [nixpkgs.python36Packages.fedora_cert.x86_64-linux](https://hydra.nixos.org/build/61469018)
  - maintainers: @mornfall, @chaoflow
- [ ] [nixpkgs.python36Packages.hvac.x86_64-linux](https://hydra.nixos.org/build/61472577)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.internetarchive.x86_64-linux](https://hydra.nixos.org/build/61472902)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.lightblue.x86_64-linux](https://hydra.nixos.org/build/61678345)
  - maintainers: @leenaars, @chaoflow
- [ ] [nixpkgs.python36Packages.locustio.x86_64-linux](https://hydra.nixos.org/build/61461873)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.logster.x86_64-linux](https://hydra.nixos.org/build/61462788)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.ltc_scrypt.x86_64-linux](https://hydra.nixos.org/build/61460222)
  - maintainers: @asymmetric, @chaoflow
- [ ] [nixpkgs.python36Packages.mox3.x86_64-linux](https://hydra.nixos.org/build/61462605)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.nose-selecttests.x86_64-linux](https://hydra.nixos.org/build/61456567)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.packet-python.x86_64-linux](https://hydra.nixos.org/build/61462338)
  - maintainers: @dipinhora, @chaoflow
- [ ] [nixpkgs.python36Packages.paypalrestsdk.x86_64-linux](https://hydra.nixos.org/build/61455404)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.pushbullet.x86_64-linux](https://hydra.nixos.org/build/61463393)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.pyalgotrade.x86_64-linux](https://hydra.nixos.org/build/61457387)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.pyblock.x86_64-linux](https://hydra.nixos.org/build/61649027)
- [ ] [nixpkgs.python36Packages.pyechonest.x86_64-linux](https://hydra.nixos.org/build/61463371)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.pymacaroons-pynacl.x86_64-linux](https://hydra.nixos.org/build/61464468)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.pyscss.x86_64-linux](https://hydra.nixos.org/build/61461271)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.python-gnupg.x86_64-linux](https://hydra.nixos.org/build/61682302)
  - maintainers: @copumpkin, @chaoflow
- [ ] [nixpkgs.python36Packages.pywbem.x86_64-linux](https://hydra.nixos.org/build/61470237)
  - maintainers: @peterhoeg, @chaoflow
- [ ] [nixpkgs.python36Packages.rtslib_fb.x86_64-linux](https://hydra.nixos.org/build/61464472)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.tablib.x86_64-linux](https://hydra.nixos.org/build/61458071)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.tmdb3.x86_64-linux](https://hydra.nixos.org/build/61468017)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.tunigo.x86_64-linux](https://hydra.nixos.org/build/61471413)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.virtual-display.x86_64-linux](https://hydra.nixos.org/build/61454724)
  - maintainers: @layus, @chaoflow
- [ ] [nixpkgs.python36Packages.wp_export_parser.x86_64-linux](https://hydra.nixos.org/build/61469725)
  - maintainers: @chaoflow
- [ ] [nixpkgs.python36Packages.xarray.x86_64-linux](https://hydra.nixos.org/build/61678821)
  - maintainers: @fridh, @chaoflow
- [ ] [nixpkgs.python36Packages.zope_copy.x86_64-linux](https://hydra.nixos.org/build/61462685)
  - maintainers: @domenkozar, @chaoflow
- [ ] [nixpkgs.qpid-cpp.x86_64-linux](https://hydra.nixos.org/build/61676821)
  - maintainers: @cpages
- [ ] [nixpkgs.qxt.x86_64-linux](https://hydra.nixos.org/build/61681592)
  - maintainers: @forkk
- [ ] [nixpkgs.rustBeta.rustc.x86_64-linux](https://hydra.nixos.org/build/61679638)
  - maintainers: @madjar, @cstrahan, @wizeman, @globin, @havvy, @wkennington
- [ ] [nixpkgs.rustNightly.rustc.x86_64-linux](https://hydra.nixos.org/build/61681983)
  - maintainers: @madjar, @cstrahan, @wizeman, @globin, @havvy, @wkennington
- [ ] [nixpkgs.shotcut.x86_64-linux](https://hydra.nixos.org/build/61679564)
  - maintainers: @goibhniu
- [ ] [nixpkgs.singular.x86_64-linux](https://hydra.nixos.org/build/61462169)
  - maintainers: @7c6f434c
- [ ] [nixpkgs.spring.x86_64-linux](https://hydra.nixos.org/build/61681842)
  - maintainers: @phreedom, @qknight, @domenkozar
- [ ] [nixpkgs.swift.x86_64-linux](https://hydra.nixos.org/build/61679484)
  - maintainers: @jb55, @dtzWill
- [ ] [nixpkgs.tokei.x86_64-linux](https://hydra.nixos.org/build/61678564)
  - maintainers: @gebner
- [ ] [nixpkgs.torchPackages.lua-cjson.x86_64-linux](https://hydra.nixos.org/build/61461032)
- [ ] [nixpkgs.torchPackages.luaffifb.x86_64-linux](https://hydra.nixos.org/build/61467644)
- [ ] [nixpkgs.torchPackages.unsup.x86_64-linux](https://hydra.nixos.org/build/61680680)
- [ ] [nixpkgs.trackballs.x86_64-linux](https://hydra.nixos.org/build/61676867)
- [ ] [nixpkgs.vivaldi-ffmpeg-codecs.x86_64-linux](https://hydra.nixos.org/build/61681389)
  - maintainers: @lluchs
- [ ] [nixpkgs.xbmcPlain.x86_64-linux](https://hydra.nixos.org/build/61677516)
  - maintainers: @domenkozar, @titanous, @edwtjo

**Comment by 7c6f434c** [comment]
Technical proposal: «Progress on: #28643» in PRs if someone doesn't like putting a mere issue link in motivation. «Fixes» makes GitHub close the issue, which is not desired.

**Comment by 7c6f434c** [comment]
fbterm: fixed slightly before this issue was posted

**Comment by 7c6f434c** [comment]
`allegro`: works in a local sandbox build from `master`

**Comment by 7c6f434c** [comment]
Hm, «no maintainer» condition for such a list is not search-friendly.

**Comment by 7c6f434c** [comment]
`cuneiform`: bumped/fixed

**Comment by NeQuissimus** [comment]
Cannot figure out `nixpkgs.linuxPackages.pktgen.x86_64-linux`, got to this point and not sure what is wrong with the `Makefile`...
```
[...]
== common
  CC copyright_info.o
  CC port_config.o
  CC core_info.o
  CC cmdline_parse_args.o
  CC lscpu.o
  CC utils.o
  CC coremap.o
  CC _pcap.o
  CC cksum.o
  CC l2p.o
  CC pg_inet.o
  AR libcommon.a
  SYMLINK-FILE include/cksum.h
/nix/store/axldd4qjamb2c1lgi7d6k3s51qyy4610-bash-4.4-p12/bin/bash: /nix/store/4lqnmvmfaxy6bl279v5a3b05rjkzad6w-dpdk-17.05.1-4.9.45/buildtools/relpath.sh: No such file or directory
ln: '/tmp/nix-build-pktgen-3.4.0.drv-0/pktgen-3.4.0/lib/common/x86_64-native-linuxapp-gcc/include' and './include' are the same file
```

**Comment by NeQuissimus** [comment]
ChromiumOS and `pktgen` are mysteries to me. All other kernel modules should be fixed with the above PRs.

**Comment by bkchr** [comment]
xxdiff-tip can be marked as done.

**Comment by zraexy** [comment]
Some of the mentions (including mine) don't seem to be getting recognized. Does GitHub have some sort of cap on the number of users that can be mentioned at once? I count 49 unique users that were successfully mentioned.

**Comment by 7c6f434c** [comment]
`lincity_ng`: bumped to a working version.

**Comment by 7c6f434c** [comment]
`asc`: bumped to a working version.

**Comment by dtzWill** [comment]
`swift`: Build fails due to our clang stdenv no longer working: #28223.  Should get that fixed for 17.09 as well, will look into these soon-ish.

**Comment by ttuegel** [comment]
`clementineFree` is now fixed, no thanks to me.

**Comment by ttuegel** [comment]
`atlasWithLapack`: I removed this because it is no longer used in Nixpkgs. We should prefer OpenBLAS anyway.

**Comment by ttuegel** [comment]
`libsForQt56.prison`: I marked this package broken because it is not expected to build with Qt 5.6.

**Comment by NeQuissimus** [comment]
Maybe it's just me but I feel we should be more liberal with removing some of these packages. Some of them haven't built successfully in a long time and/or been updated in 2+ years...

**Comment by pbogdan** [comment]
`fstrm` - https://github.com/NixOS/nixpkgs/commit/263978219c
`projectm` - https://github.com/NixOS/nixpkgs/commit/8991610fbcdb9596dadf2a1b6a563ebd2d85cc8b

**Comment by 7c6f434c** [comment]
`xconq`: fixed
`xmacro`: bumped, fixed

**Comment by 7c6f434c** [comment]
`obliv-c`: bumped, fixed

**Comment by Fuuzetsu** [comment]
`afl`: made an issue https://github.com/NixOS/nixpkgs/issues/28712

**Comment by jb55** [comment]
notmuch-addrlookup is waiting for new release for notmuch-0.25 compatibility, 

https://github.com/aperezdc/notmuch-addrlookup-c/commit/88f156d04990a71c6ad6fc2757b537b44e3c4d00 
#27691 
/cc @adamruzicka

**Comment by canndrew** [comment]
hivemind/hivemindd should now be fixed: https://github.com/NixOS/nixpkgs/pull/28731#issuecomment-325900889

**Comment by 7c6f434c** [comment]
`nilfs-utils`: fixed

**Comment by adamruzicka** [comment]
`notmuch-addrlookup` should be fixed: #27691

**Comment by colescott** [comment]
`arm-frc-linux-gnueabi-binutils` currently being worked on. Binutils is always a bit of a pain :/

**Comment by Mic92** [comment]
special thanks to @disassembler for fixing all the gcc6 breakages.

**Comment by jtojnar** [comment]
[gnome-chess](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gnome3.gnome-chess.x86_64-linux), [gnome-dictionary](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gnome3.gnome-dictionary.x86_64-linux) and [gnome-shell](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gnome3.gnome-shell.x86_64-linux) build.

**Comment by canndrew** [comment]
I'm still getting hydra failure emails, but [the build it's complaining about](https://hydra.nixos.org/build/59124184) doesn't include [the fix that was merged](https://github.com/NixOS/nixpkgs/pull/28731). Is there anything else I need to do?

**Comment by vcunat** [comment]
@canndrew: the last Hydra builds are after the merge.

**Comment by disassembler** [comment]
helmholtz builds successfully.

**Comment by disassembler** [comment]
hhvm builds successfully.

**Comment by disassembler** [comment]
irrlicht builds successfully

**Comment by obadz** [comment]
smugline, pokerth, pokerth-server fixed (c91b4fe989, 52dc8f227f)

**Comment by disassembler** [comment]
no errors with lcdproc

**Comment by AndersonTorres** [comment]
Xiphos needs a new version of "libgtkhtml".

**Comment by disassembler** [comment]
Working on it... Tried upgrading to 4.x which compiled but broke other
packages. I'll add a gtkhtml4 library tonight...

I also have a new xiphos build I haven't pushed yet that builds from latest
GitHub release that needs some more deps. I'll try to get it pushed
tomorrow.

Sam

**Comment by AndersonTorres** [comment]
New version of namecoin complains about Boost::System.

**Comment by peterhoeg** [comment]
Further to @disassembler's note - I have just tried building lcdproc as well and it's fine.

Just fixed dbus-broker.

**Comment by makefu** [comment]
bepasty-server got fix with 63b66bf960d4e8749349bb593a776d472caaee88

**Comment by globin** [comment]
Just updated the list to the latest evaluation of 17.09

**Comment by NeQuissimus** [comment]
I fixed the build for `py3status` in #28976 but apparently the package is not really working to begin with...

**Comment by disassembler** [comment]
FYI, herqq released 2.1.0 for me. I re-did that PR this morning and it's ready to go.

**Comment by peterhoeg** [comment]
I have a fix for ```pywbem``` but it needs a little more testing before merging.

**Comment by rnhmjoj** [comment]
After a few hours of bisecting it seems the failure in `vapoursynth` is caused by the gcc 6 update.
Do you know anything about this error?
```
C++ compiler does not understand std::mutex (a C++11 feature)
```

**Comment by AndersonTorres** [comment]
Lighning runs OK against master.

**Comment by Mic92** [comment]
@colescott any update on arm-frc-linux-gnueabi-binutils?

**Comment by AndersonTorres** [comment]
I will get `mcomix` to fix.

**Comment by abuibrahim** [comment]
Sorry for the late reply.

Fixing odp-dpdk and pktgen an disabling ofp.

Pull request for master is pending:
https://github.com/NixOS/nixpkgs/pull/29100

Once it's merged I will send a PR for 17.09 branch.

Regards,
Ruslan

**Comment by abbradar** [comment]
I've fixed `openbrf` and `python.pkgs.xgboost`. Warning: the latter was because GFortran wasn't kept in sync with `gcc` so we used GFortran 5 and GCC 6. I've defaulted `gfortran = gfortran6` now; tried to build `R` and `python.pkgs.xgboost` with it and it works. Still, I'll keep in check what Hydra says about anything GFortran 6 breaks.

**Comment by moretea** [comment]
mcrl2 will be fixed by https://github.com/NixOS/nixpkgs/pull/29199

**Comment by colescott** [comment]
@Mic92 I fixed thew build but now I am having issues with the libgcc for the linker. I'll try some more stuff this week.

**Comment by matklad** [comment]
lxqtsession was fixed by #29132

**Comment by ThomasMader** [comment]
dmd will be fixed by https://github.com/NixOS/nixpkgs/pull/28635
I know it's a big PR but maybe someone finds the time to merge it fully.

**Comment by rvl** [comment]
About [jscoverage](https://hydra.nixos.org/build/60904349/nixlog/1). Newer gcc is picking up an error about casting int to pointer. However the value in question is always 0, so it's not really an error. Do we (a) patch the source, (b) adjust the CFLAGS, or (c) delete the package (it has been [deprecated](http://siliconforks.com/jscoverage/) in favour of a java implementation). cc @chaoflow

**Comment by xvapx** [comment]
python36Packages.libnacl: I cannot reproduce the failure locally neither in master nor in staging.
Also, mentions don't work properly.

**Comment by disassembler** [comment]
@rvl I just fixed it changing JS_FALSE -> NULL.

**Comment by rvl** [comment]
@disassembler OK option (a) then, good stuff :star: :+1:

**Comment by womfoo** [comment]
freeswitch will be fixed by #29463

**Comment by ThomasMader** [comment]
dmd will be fixed by https://github.com/NixOS/nixpkgs/pull/29469

**Comment by rnhmjoj** [comment]
Can someone cherry-pick #29258 into release-17.09?

**Comment by Mic92** [comment]
@rnhmjoj done

**Comment by aneeshusa** [comment]
I tested my changes to the radicale tests in #29521 locally when I made the PR and just again now with a fresh master, and `nix-build nixos/tests/radicale.nix` is succeeding for me. Would appreciate some help figuring out why it's failing on Hydra (cc @Infinisil and @pSub as co-maintainers).

I've been testing on Arch Linux with Nix 1.11.15, sandboxing enabled,

**Comment by asymmetric** [comment]
@globin I'm unsure if anyone aside of me has used the `ltc_scrypt` package. It is a dependency of `electrum-ltc`, which I myself don't use anymore.

So I'd be fine if it was removed.

**Comment by vcunat** [comment]
`electrum-ltc` [still builds](https://hydra.nixos.org/job/nixos/release-17.09/nixpkgs.electrum-ltc.x86_64-linux/all?page=1) actually; perhaps the package only won't support python3 or something...

**Comment by asppsa** [comment]
PR #29763 disable Hydra builds of purePackages.gen.  Not sure if anything else needs to be done with this in terms of this issue.

**Comment by globin** [comment]
The remaining packages will be marked as broken, thanks for your effort!
