### ISSUE TITLE
ristretto misbehaves – no image display, can't browse images

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#2946]
Recently I noticed my `ristretto` is broken:

```
[shana@lenalee:~]$ ristretto

(ristretto:22856): Gtk-WARNING **: Could not find the icon 'ristretto'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(ristretto:22856): GdkPixbuf-CRITICAL **: gdk_pixbuf_saturate_and_pixelate: assertion 'GDK_IS_PIXBUF (src)' failed
```

If I try to browse through files, it does not recognise any file as an image (doesn't show in file browser). If I try to open an image directly through CLI, it does not display.

I'm unsure what could have caused this breakage although the last time I remember it working was when I ran KDE alongside it.

**Comment by pSub** [comment]
@Fuuzetsu Do you still have this problem? ristretto works fine for me (unstable).

**Comment by vcunat** [comment]
It might've been fixed by mime changes in afdfe76, though that's not a complete fix for this.

**Comment by Fuuzetsu** [comment]
I no longer use it because it was unusuable. If it's fixed for you then it should be safe to close. If I try again in the future and it's broken I'll make a new issue.

**Comment by vcunat** [comment]
It does show images for me.

**Comment by kamilchm** [comment]
I have same problems in ristretto and viewnior, running qtile window manager from unstable channel.
They don't recognize any images :/

**Comment by Fuuzetsu** [comment]
Confirming that ristretto in master still shows no messages.

**Comment by a1russell** [comment]
Not sure if it's the same problem as ristretto, but I can confirm viewnior doesn't show any images for me.

**Comment by jagajaga** [comment]
`ristretto` works on xmonad nowadays.

**Comment by pSub** [comment]
Yes, I am using ristretto on xmonad and it works just fine. I close this issue again. Just reopen and post details like DE / WM if you still have this problem.

**Comment by Avaq** [comment]
Hi! This is the only place where I found mention of viewnior misbehaving on NixOS. Has anyone managed to overcome these issues? I'm still having them.

Would this be a problem with Viewnior or NixOS? I've looked through the viewnior issues and can't find anything related. 

I did notice this *`Desktop`* setting in viewnior:

![1462438463](https://cloud.githubusercontent.com/assets/1217745/15039797/f5eb3fe4-12af-11e6-8ad3-fcdc4d8971c3.png)

I'm using `services.xserver.desktopManager.default = "none"`, but viewnior wants me to choose between:

* GNOME 2
* GNOME 3
* XFCE
* LXDE
* FluxBox
* Nitrogen

Could that be the issue?

**Comment by vcunat** [comment]
I can't see description of the issues that viewnior is supposed to have, but it would probably be better to open a new issue for that. A one-minute usage showed no problems for me. (The "desktop" in config was set to gnome3 without my intervention, and I'm using something close to Xfce.)

**Comment by Avaq** [comment]
Hey, sorry for being unclear. The issues I'm having are those described in the comments above. Viewnior does **not**:

* ..show images in the `Open File`-dialog when `All Images` is selected from the dropdown
* ..display opened images (instead it errors: "The given locations contain no images")
* ..cycle through images in an opened folder

I think it somehow relies on a desktopManager being present, based on that "desktop"-config. I'll open a separate issue.

**Comment by Avaq** [comment]
I just tested with `services.xserver.desktopManager.xfce.enable = true` and viewnior now works.

**Comment by vcunat** [comment]
My guess is that it's because of adding `shared_mime_info` into `systemPackages`.

**Comment by Avaq** [comment]
Your guess is correct. Viewnior works with `xfce = false` and `shared_mime_info` added. Though this time around it complains about "*Could not find the icon 'image-jpeg'. The 'hicolor' theme
was not found either*". It's "set as wallpaper" function doesn't work either because it relies on some desktop-specific directory existing. 

It's pretty clear to me now that I shouldn't be using Viewnior *if* I'm not using a desktopManager. I might fall back to `feh` or enable xfce. Thanks for your thoughts!

**Comment by vcunat** [comment]
For the icons it should be enough to add `hicolor_icon_theme` to `systemPackages`. Many apps implicitly rely on these to be pulled by some DE, similarly to standard distros. Changing wallpapers is a completely DE-specific action, I believe.
