### ISSUE TITLE
A definition for option `services.gpg-agent.pinentryFlavor' is not of type `null or one of "curses", "gtk2", "gnome2", "qt", "emacs"'.

### ISSUE THREAD

**Issue by sanderhollaar** [NixOS/nixpkgs#294698]
### Describe the bug

After `nix flake update --flake .` this morning:

```console
$ home-manager switch
Home Manager not found at /nix/store/rgiag14hb0sdv3s5xgv7qnrp5hx19nmj-source.
error:
       … while calling the 'derivationStrict' builtin

         at /derivation-internal.nix:9:12:

            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/lkplh8bks7cp8wynhrkprvzwbw5w1in4-source/pkgs/stdenv/generic/make-derivation.nix:354:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'

         at /nix/store/lkplh8bks7cp8wynhrkprvzwbw5w1in4-source/pkgs/build-support/trivial-builders/default.nix:98:16:

           97|         enableParallelBuilding = true;
           98|         inherit buildCommand name;
             |                ^
           99|         passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: A definition for option `services.gpg-agent.pinentryFlavor' is not of type `null or one of "curses", "gtk2", "gnome2", "qt", "emacs"'. Definition values:
       - In `/nix/store/1qcac74liwlb20imzbfjypim6v1wi4hc-source/p70-home.nix': "tty"
```

`services.gpg-agent.pinentryFlavor = "tty";`

Seems related to https://github.com/NixOS/nixpkgs/pull/133542

### Notify maintainers
@fpletz
@SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.8.0-rc5-v8, NixOS, 24.05 (Uakari), 24.05.20240307.c8cd652`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - channels(root): `""`
 - nixpkgs: `/nix/store/iwzsz5nqyw7a6hwhs1gpn390nmsiik45-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
First of all this should properly be addressed in home-manager to not rely on the aliases defined here https://github.com/NixOS/nixpkgs/blob/3be0c7315f35cadb3ea6942909b368d63584eb8d/pkgs/top-level/aliases.nix#L905-L914

> ```
>        error: A definition for option `services.gpg-agent.pinentryFlavor' is not of type `null or one of "curses", "gtk2", "gnome2", "qt", "emacs"'. Definition values:
>        - In `/nix/store/1qcac74liwlb20imzbfjypim6v1wi4hc-source/p70-home.nix': "tty"
> ```

Te error originates from your config since the option changed and tty is no longer an option. To force tty you can choose any of the others (see https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/pinentry/default.nix#L114-L119) and set ``export GPG_TTY=$(tty)`` in your bashrc. 

I can't currently find the thread where it was decided to drop the tty flavor.

**Comment by sanderhollaar** [comment]
> Te error originates from your config since the option changed and tty is no longer an option. To force tty you can choose any of the others (see https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/pinentry/default.nix#L114-L119) and set `export GPG_TTY=$(tty)` in your bashrc.
> 
> I can't currently find the thread where it was decided to drop the tty flavor.

I understand that due to the change `tty` is no longer an option.

As `tty` is a supported GUI in https://github.com/gpg/pinentry and https://github.com/NixOS/nixpkgs/pull/133542 was not about dropping `tty`, I assume that `tty` getting dropped was not on purpose.

AIUI this change should not have broken my config. And I think I should not need to work around this with `export GPG_TTY=$(tty)`. Or am I missing something?

**Comment by SuperSandro2000** [comment]
> I assume that `tty` getting dropped was not on purpose.

I am not sure, the top-level packages that existed before got converted, not all outputs of the pinentry package as that mechanism is no longer being used. Since there was no top level tty package before, the extra output got under the wheels. We can probably add a top-level package that only contains the tty feature if desired.

> As `tty` is a supported GUI in [gpg/pinentry](https://github.com/gpg/pinentry) and #133542 was not about dropping `tty`, I assume that `tty` getting dropped was not on purpose.

The feature itself is not dropped, all the other packages contain it in the addition of the GUI frontend.

PS: It would have been nice if your initial issue contained more information than just the error message.

**Comment by SuperSandro2000** [comment]
Please test #294937

**Comment by andresilva** [comment]
FWIW I had the same issue but I wasn't using `tty`, I was using `gnome3` which isn't accepted anymore even though the package still exists. "gnome2" is accepted though, and it uses the `pinentry-gnome3` package.

**Comment by SuperSandro2000** [comment]
I think that is another oversight in the aliases definitions. Regardless, home-assistant should migrate away from using them rather sooner than later.
