### ISSUE TITLE
Build failure: fprintd (tests timeout)

### ISSUE THREAD

**Issue by spikespaz** [NixOS/nixpkgs#299111]
### Steps To Reproduce

1. `nix build 'github:nixos/nixpkgs/nixos-unstable#fprintd'`

### Build log

https://termbin.com/grgt

```
Timeout:            17
```

### Additional context
No additional context, package is built from `nixos-unstable` at the time of writing.

### Notify maintainers

@abbradar 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.19, NixOS, 24.05 (Uakari), 24.05.20240303.b8697e5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by spikespaz** [comment]
Overlay:
```nix
pkgs: pkgs0: {
  fprintd = pkgs0.fprintd.overrideAttrs {
    doCheck = false;
    doInstallCheck = false;
  };
}
```
Result:
```
> meson.build:140:18: ERROR: Dependency "pam_wrapper" not found, tried pkgconfig
```

Overlay:
```nix
pkgs: pkgs0: {
  fprintd = pkgs0.fprintd.overrideAttrs {
    doCheck = false;
    doInstallCheck = false;
    buildInputs = super.buildInputs or [ ] ++ (with pkgs; [ libpam-wrapper ]);
  };
}
```
Result:
```
> Run-time dependency pam_wrapper found: YES 1.1.3
> Program xmllint found: NO
> Program python3 found: YES
> WARNING: You should add the boolean check kwarg to the run_command call.
>          It currently defaults to false,
>          but it will default to true in future releases of meson.
>          See also: https://github.com/mesonbuild/meson/issues/9300
>
> meson.build:156:8: ERROR: Problem encountered: Python3 module 'cairo' required by test suite not found
```

`pycairo` is already in the `buildInputs` of the package as it currently stands.

**Comment by AlecsFerra** [comment]
Same issue

**Comment by jtojnar** [comment]
I believe this was resolved by https://github.com/NixOS/nixpkgs/pull/298491

**Comment by spikespaz** [comment]
> I believe this was resolved by #298491

I will reiterate the failing build command:

```
nix build 'github:nixos/nixpkgs/nixos-unstable#fprintd'
```

This was run yesterday (March 25) while the PR referenced was merged two days ago (March 23).

I believe this command will fetch that branch every time if necessary to get the latest revision. An I mistaken?

**Comment by jtojnar** [comment]
It might [take a while](https://discourse.nixos.org/t/differences-between-nix-channels/13998/5?u=jtojnar) for changes from master to propagate to nixos-unstable channel, you can track it with https://nixpk.gs/pr-tracker.html?pr=298491

**Comment by matejc** [comment]
The change is in unstable, I still get the timeout error:

```
Ok:                 512 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            1   
```

As for the output of tests, I cant pinpoint which test is timeout-ing. I guess I need more coffee to parse the test output.

**Comment by matejc** [comment]
This one:
```
199/513 fprintd:daemon+fprintd+FPrindConcurrentPolkitRequestsTest / FPrindConcurrentPolkitRequestsTest.test_hanging_claim_does_not_block_list                                                           TIMEOUT        30.10s   exit status 1
```

**Comment by isiko** [comment]
Any Updates?

**Comment by spikespaz** [comment]
@isiko it's in unstable

**Comment by isiko** [comment]
> @isiko it's in unstable

I'm on unstable and it just failed to build for me...

```
error: builder for '/nix/store/5j0b7wia9iz6m5cs57851aqzllxf3hni-fprintd-1.94.2.drv' failed with exit code 4;
       last 10 log lines:
       > 513/513 fprintd:+test_fprintd_utils+TestFprintdUtilsVerify / TestFprintdUtilsVerify.test_fprintd_verify_script                                                                                          OK             10.34s
       >
       > Ok:                 509
       > Expected Fail:      0
       > Fail:               1
       > Unexpected Pass:    0
       > Skipped:            0
       > Timeout:            3
       >
       > Full log written to /build/source/build/meson-logs/testlog.txt
       For full logs, run 'nix log /nix/store/5j0b7wia9iz6m5cs57851aqzllxf3hni-fprintd-1.94.2.drv'.
```

**Comment by spikespaz** [comment]
@isiko Go comment on the PR https://nixpk.gs/pr-tracker.html?pr=298491

**Comment by mayersj1** [comment]
As of today (Wednesday, May 8, 2024), I'm seeing this failure now for the past few days as well. Tracking unstable. Have tried the garbage collection tips that have been suggested in other iterations of this same type of error without any success.

**Comment by spikespaz** [comment]
Is anyone still affected? Can this be closed?

**Comment by danilevy1212** [comment]
Built-it real quick on my system, seems to not be stuck in the tests anymore. Tracking nixos-unstable

```
  # Finger print auth
  services.fprintd = {
    enable = true;
  };
```

Before this would get stuck in testing, as described in the issue.

**Comment by clementpoiret** [comment]
After a nix flake update yesterday, I am affected by this issue (unstable)
