### ISSUE TITLE
 yabridge is incompatible with wine 9.5

### ISSUE THREAD

**Issue by mksafavi** [NixOS/nixpkgs#300755]
### Describe the bug
yabridge doesn't work with wine 9.5. I was wondering as this is a reoccurring thing with yabridge, shouldn't the wine version be pinned for the yabridge package? 

### Expected behavior
running vst plugins

### Additional context
I tried overriding the wine version to 9.4 but I couldn't get it to build yabridge.
So for now, I installed yabridge from the revision before wine 9.5. 
```
final: prev:
let
  nixpkgs-wine94 = import (prev.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "59322d8a3603ef35a0b5564b00109f4a6436923e"; #wineWow64Packages.unstable: 9.3 -> 9.4
    sha256 = "Ln3mD5t96hz5MoDwa8NxHFq76B+V2BOppYf1tnwFBIc=";
  }) {
    system = "x86_64-linux";
  };
in {
  inherit (nixpkgs-wine94) yabridge yabridgectl;
}
```

### Notify maintainers

@kira-bruneau

### Metadata
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.0`
 - nixpkgs: `/nix/store/cb1gs888vfqxawvc65q1dk6jzbayh3wz-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by reckenrode** [comment]
Can yabridge use the stable Wine package? It’s updated annually except for occasional bug fix releases. It’s currently Wine 9.0.

**Comment by binarious** [comment]
@reckenrode Didn't work for me: https://github.com/NixOS/nixpkgs/issues/301445

**Comment by MkSafavi** [comment]
> Can yabridge use the stable Wine package? It’s updated annually except for occasional bug fix releases. It’s currently Wine 9.0.
From what I know, yabridge requires wine-staging but it's usually a few months behind. The project readme always had a downgrade section telling you to downgrade to a specific version.
There's an open issue for it on the yabridge repo: (https://github.com/robbert-vdh/yabridge/issues/320)

**Comment by kira-bruneau** [comment]
Just created [a PR](https://github.com/NixOS/nixpkgs/pull/303485) that should workaround this issue based on https://github.com/robbert-vdh/yabridge/issues/320#issuecomment-2018993210 😊

> shouldn't the wine version be pinned for the yabridge package?

I think it would be best to keep it following the default staging release. What you're doing right now to pin wine uses an import for derivation, which isn't allowed in nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/README.md#import-from-derivation.

It would be possible to maintain a separate derivation of wine just for yabridge, but I think it would be too costly for what it'd add - especially since we can't guarantee a version of wine that'll work with all VSTs.

**Comment by MkSafavi** [comment]
> Just created [a PR](https://github.com/NixOS/nixpkgs/pull/303485) that should workaround this issue based on [robbert-vdh/yabridge#320 (comment)](https://github.com/robbert-vdh/yabridge/issues/320#issuecomment-2018993210) 😊
> 
👍
I tried this as well, but most of my plugins were broken with wine 9.5 which will probably get fixed by yabridge upstream soon but I thought I should mention it.
> > shouldn't the wine version be pinned for the yabridge package?
> 
> I think it would be best to keep it following the default staging release. What you're doing right now to pin wine uses an import for derivation, which isn't allowed in nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/README.md#import-from-derivation.

Oh, I didn't know about the implications importing older packages. Good to know. 👍 
> It would be possible to maintain a separate derivation of wine just for yabridge, but I think it would be too costly for what it'd add - especially since we can't guarantee a version of wine that'll work with all VSTs.

Yeah that would be too much unnecessary work.

**Comment by DaKingof** [comment]
Still broken on 9.6

**Comment by mksafavi** [comment]
> Still broken on 9.6

https://github.com/NixOS/nixpkgs/pull/303485 is not merged yet. Even if it gets merged, I noticed some of my vsts breaking. I think it's better to pin version 9.4 for now.

**Comment by kira-bruneau** [comment]
Reopening since #303485 doesn't completely fix yabridge with 9.5+

**Comment by mrtnvgr** [comment]
Fixed on wine 9.8 🎊 (https://github.com/robbert-vdh/yabridge/issues/320)
