### ISSUE TITLE
filezilla - popup "An assertion failed!"

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#30151]
## Issue description

Using Nixos Unstable Small channel with KDE I noticed that filezilla now at every startup has a popup that can't be disabled permanently. Not sure if that happens for other desktops as well - it seems to be related to GTK.

https://images.sjau.ch/img/70890fe6.png

Even if I uncheck that "Show this dialog the next time" it will popup again.

### Steps to reproduce

0. Run KDE (maybe not necessary)
1. Install Filezilla
2. Start Filezilla

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

`18.03pre117305.88fc0e4610 (Impala)`

* Nix version: (run `nix-env --version`)

`nix-env (Nix) 1.11.15`

* Nixpkgs version: (run `nix-instantiate --eval "<nixpkgs>" -A lib.nixpkgsVersion`)

`"18.03pre117305.88fc0e4610"`

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

`build-use-sandbox = false`

**Comment by dermetfan** [comment]
+1 on nixos-unstable 18.03pre117013.aebdc892d6 (Impala)

![2017-10-06t16 31 40 256187310 02 00](https://user-images.githubusercontent.com/4956158/31282810-fcf1b442-aab3-11e7-9647-edcc065ffb45.png)

**Comment by jtojnar** [comment]
Can you paste here the content of the backtrace?

**Comment by dermetfan** [comment]
Oh sure, sorry:

```
ASSERT INFO:
./src/gtk/toplevel.cpp(988): assert "m_widget" failed in Show(): invalid frame

BACKTRACE:
[1] wxTopLevelWindowGTK::Show(bool)
[2] wxTopLevelWindowBase::Destroy()
[3] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[4] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[5] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[6] wxEvtHandler::TryHereOnly(wxEvent&)
[7] wxEvtHandler::ProcessEventLocally(wxEvent&)
[8] wxEvtHandler::ProcessEvent(wxEvent&)
[9] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[10] wxTimerImpl::SendEvent()
[11] g_main_context_dispatch
[12] g_main_loop_run
[13] gtk_main
[14] wxGUIEventLoop::DoRun()
[15] wxEventLoopBase::Run()
[16] wxAppConsoleBase::MainLoop()
[17] wxEntry(int&, wchar_t**)
[18] main
[19] __libc_start_main
[20] _start
```

**Comment by jtojnar** [comment]
This is an upstream error: https://trac.wxwidgets.org/ticket/17942

(via https://bugzilla.redhat.com/show_bug.cgi?id=1484955 and https://forum.filezilla-project.org/viewtopic.php?p=157690&sid=a2f204e02f6c58970616a5fe5c3f2a3c#p157725)

**Comment by sjau** [comment]
So we just need to wait then :)

**Comment by jtojnar** [comment]
Or we can patch wxWidgets until the new version is released.

**Comment by sjau** [comment]
it's just an annoying thing... and filezilla seems to release every few weeks... so IMHO we can wait - I can't patch it anway :)

**Comment by vcunat** [comment]
Yes, should be fixed by https://github.com/NixOS/nixpkgs/pull/30909; reopen otherwise.

**Comment by vcunat** [comment]
(No idea how I managed to skip before the last post.)

**Comment by sjau** [comment]
With latest unstable small the popup has vanished... so it works as before again.

@dermetfan how is it for you?

**Comment by dermetfan** [comment]
Yes, the popup is gone on the latest unstable (small only).

**Comment by brambil** [comment]
Still have the problem ...

ASSERT INFO:
../src/gtk/toplevel.cpp(988): assert "m_widget" failed in Show(): invalid frame

BACKTRACE:
[1] wxTopLevelWindowGTK::Show(bool)
[2] wxTopLevelWindowBase::Destroy()
[3] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[4] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[5] wxEvtHandler::TryHereOnly(wxEvent&)
[6] wxEvtHandler::ProcessEventLocally(wxEvent&)
[7] wxEvtHandler::ProcessEvent(wxEvent&)
[8] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[9] wxTimerImpl::SendEvent()
[10] g_main_context_dispatch
[11] g_main_loop_run
[12] gtk_main
[13] wxGUIEventLoop::DoRun()
[14] wxEventLoopBase::Run()
[15] wxAppConsoleBase::MainLoop()
[16] wxEntry(int&, wchar_t**)
[17] __libc_start_main


Linux nicola-debian 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux


FileZilla Client
----------------

Version:          3.28.0

Build information:
  Compiled for:   x86_64-pc-linux-gnu
  Compiled on:    x86_64-pc-linux-gnu
  Build date:     2017-10-29
  Compiled with:  gcc (Debian 7.2.0-12) 7.2.1 20171025
  Compiler flags: -g -O2 -fdebug-prefix-map=/build/filezilla-uBfTzd/filezilla-3.28.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall

Linked against:
  wxWidgets:      3.0.3
  SQLite:         3.22.0
  GnuTLS:         3.5.17

Operating system:
  Name:           Linux 4.14.0-3-amd64 x86_64
  Version:        4.14
  CPU features:   sse sse2 sse3
  Settings dir:   /home/nicola/.filezilla/

**Comment by sjau** [comment]
Do you use nixos unstable?

**Comment by brambil** [comment]
Debian Testing, FluxBox

**Comment by sjau** [comment]
:)
