### ISSUE TITLE
obs-studio no window and fails to screen capture on Wayland after update to Qt 6.7.0

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#307271]
### Describe the bug

When starting OBS:

- There is a "window" but no displayed info on it. It can be seen in GNOME's window switcher but otherwise doesn't exist.
- The taskbar icon exists and is functional.
- Recording resulted in back for me, but my scene just has a screen capture so presumably that is failing.

### Steps To Reproduce
1. Launch OBS

### Expected behavior

The window appears and I can screen capture.

### Screenshots

<details><summary>Logs:</summary>

```
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /nix/store/c32l44k27qsafczki22fz3422kqdj803-obs-studio-30.1.2/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /nix/store/c32l44k27qsafczki22fz3422kqdj803-obs-studio-30.1.2/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/locale/en-GB.ini
debug: Attempted path: /nix/store/c32l44k27qsafczki22fz3422kqdj803-obs-studio-30.1.2/share/obs/obs-studio/locale/en-GB.ini
info: Using preferred locale 'en-GB'
debug: Attempted path: share/obs/obs-studio/themes
debug: Attempted path: /nix/store/c32l44k27qsafczki22fz3422kqdj803-obs-studio-30.1.2/share/obs/obs-studio/themes
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /nix/store/c32l44k27qsafczki22fz3422kqdj803-obs-studio-30.1.2/share/obs/obs-studio/themes/Yami.qss
info: Platform: Wayland
info: CPU Name: AMD Ryzen 9 5950X 16-Core Processor
info: CPU Speed: 3716.068MHz
info: Physical Cores: 16, Logical Cores: 32
info: Physical Memory: 128706MB Total, 119865MB Free
info: Kernel Version: Linux 6.6.28
info: Distribution: NixOS "24.05"
info: Desktop Environment: GNOME (gnome)
info: Session Type: wayland
info: Qt Version: 6.7.0 (runtime), 6.7.0 (compiled)
info: Portable mode: false
info: OBS 30.1.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
info: Initialized EGL 1.5
info: Loading up OpenGL on adapter AMD AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 17.0.6, DRM 3.54, 6.6.28)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 24.0.5, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
info: NV12 texture support enabled
info: P010 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
info: [obs-browser]: Version 2.23.4
info: [obs-browser]: CEF Version 121.0.6167.184 (runtime), 121.3.13+g5c4a81b+chromium-121.0.6167.184 (compiled)
info: VAAPI: API version 1.21
info: FFmpeg VAAPI H264 encoding supported
info: FFmpeg VAAPI AV1 encoding not supported
info: FFmpeg VAAPI HEVC encoding supported
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.4.2 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.7.0 | Qt version (run-time): 6.7.0
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 102400
info: [obs-websocket] [obs_module_load] Module loaded.
info: [vlc-video]: VLC 3.0.20 Vetinari found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-webrtc.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-qsv11.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-jack.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
warning: QWidget::setTabOrder: 'first' and 'second' must be in the same window
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.5) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_0f_00.4.analog-stereo.2.monitor' (default)
info: [Loaded global audio device]: 'Desktop Audio'
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.5) 15.0.0'
info: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
info: pulse-input: Started recording from 'alsa_input.usb-0d8c_C-Media_USB_Audio_Device-00.mono-fallback' (default)
info: [Loaded global audio device]: 'Mic/Aux'
info: PipeWire initialized
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Friend 2' (jack_output_capture)
info:     - source: 'Friend 1' (jack_output_capture)
info:     - source: 'Game' (jack_output_capture)
info:     - source: 'Window Capture (PipeWire)' (pipewire-window-capture-source)
info: ------------------------------------------------
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Game)

info: [pipewire] Screencast session created
info: [pipewire] Asking for window
info: [pipewire] window selected, setting up screencast
info: [pipewire] Server version: 1.0.5
info: [pipewire] Library version: 1.0.5
info: [pipewire] Header version: 1.0.4
info: [pipewire] Created stream 0x40e65e0
info: [pipewire] Stream 0x40e65e0 state: "connecting" (error: none)
info: [pipewire] Playing stream 0x40e65e0
info: [pipewire] Stream 0x40e65e0 state: "paused" (error: none)
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 12 (Spa:Enum:VideoFormat:BGRA)
info: [pipewire]     Modifier: 0xffffffffffffff
info: [pipewire]     Size: 2560x1440
info: [pipewire]     Framerate: 0/1
info: [pipewire] Stream 0x40e65e0 state: "streaming" (error: none)
^Cinfo: ==== Shutting down ==================================================
info: pulse-input: Stopped recording from 'alsa_output.pci-0000_0f_00.4.analog-stereo.2.monitor'
info: pulse-input: Got 430 packets with 516000 frames
info: pulse-input: Stopped recording from 'alsa_input.usb-0d8c_C-Media_USB_Audio_Device-00.mono-fallback'
info: pulse-input: Got 428 packets with 513600 frames
info: [pipewire] Stream 0x40e65e0 state: "paused" (error: none)
info: [pipewire] Stream 0x40e65e0 state: "unconnected" (error: none)
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
info: All scene data cleared
info: ------------------------------------------------
info: [obs-websocket] [obs_module_unload] Shutting down...
error: Tried to call obs_frontend_remove_event_callback with no callbacks!
info: [obs-websocket] [obs_module_unload] Finished shutting down.
info: [Scripting] Total detached callbacks: 0
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 1213.1 ms
info:  ┣OBSApp::AppInit: 3.085 ms
info:  ┃ ┗OBSApp::InitLocale: 0.453 ms
info:  ┗OBSApp::OBSInit: 1122.94 ms
info:    ┣obs_startup: 2.145 ms
info:    ┗OBSBasic::OBSInit: 1094.34 ms
info:      ┣OBSBasic::InitBasicConfig: 0.073 ms
info:      ┣OBSBasic::ResetAudio: 0.212 ms
info:      ┣OBSBasic::ResetVideo: 84.18 ms
info:      ┃ ┗obs_init_graphics: 82.436 ms
info:      ┃   ┗shader compilation: 24.55 ms
info:      ┣OBSBasic::InitOBSCallbacks: 0.002 ms
info:      ┣OBSBasic::InitHotkeys: 0.013 ms
info:      ┣obs_load_all_modules2: 684.738 ms
info:      ┃ ┣obs_init_module(aja-output-ui.so): 0.055 ms
info:      ┃ ┣obs_init_module(aja.so): 0.049 ms
info:      ┃ ┣obs_init_module(decklink-captions.so): 0 ms
info:      ┃ ┣obs_init_module(decklink-output-ui.so): 0 ms
info:      ┃ ┣obs_init_module(decklink.so): 0.113 ms
info:      ┃ ┣obs_init_module(frontend-tools.so): 59.41 ms
info:      ┃ ┣obs_init_module(image-source.so): 0.01 ms
info:      ┃ ┣obs_init_module(linux-alsa.so): 0.002 ms
info:      ┃ ┣obs_init_module(linux-capture.so): 0 ms
info:      ┃ ┣obs_init_module(linux-jack.so): 0.003 ms
info:      ┃ ┣obs_init_module(linux-pipewire.so): 12.121 ms
info:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0.002 ms
info:      ┃ ┣obs_init_module(linux-v4l2.so): 13.477 ms
info:      ┃ ┣obs_init_module(obs-browser.so): 0.042 ms
info:      ┃ ┣obs_init_module(obs-ffmpeg.so): 22.809 ms
info:      ┃ ┃ ┗nvenc_check: 1.426 ms
info:      ┃ ┣obs_init_module(obs-filters.so): 0.022 ms
info:      ┃ ┣obs_init_module(obs-libfdk.so): 0.002 ms
info:      ┃ ┣obs_init_module(obs-outputs.so): 0.007 ms
info:      ┃ ┣obs_init_module(obs-qsv11.so): 12.374 ms
info:      ┃ ┣obs_init_module(obs-transitions.so): 0.006 ms
info:      ┃ ┣obs_init_module(obs-vst.so): 0.002 ms
info:      ┃ ┣obs_init_module(obs-webrtc.so): 0.003 ms
info:      ┃ ┣obs_init_module(obs-websocket.so): 3.428 ms
info:      ┃ ┣obs_init_module(obs-x264.so): 0.002 ms
info:      ┃ ┣obs_init_module(rtmp-services.so): 0.435 ms
info:      ┃ ┣obs_init_module(text-freetype2.so): 0.007 ms
info:      ┃ ┗obs_init_module(vlc-video.so): 1.562 ms
info:      ┣OBSBasic::InitService: 0.752 ms
info:      ┣OBSBasic::ResetOutputs: 0.114 ms
info:      ┣OBSBasic::CreateHotkeys: 0.018 ms
info:      ┣OBSBasic::InitPrimitives: 0.358 ms
info:      ┗OBSBasic::Load: 257.433 ms
info: obs_hotkey_thread(25 ms): min=0 ms, median=0 ms, max=0.001 ms, 99th percentile=0 ms, 100% below 25 ms
info: audio_thread(Audio): min=0.003 ms, median=0.031 ms, max=5.009 ms, 99th percentile=0.168 ms
info: obs_graphics_thread(16.6667 ms): min=0.059 ms, median=0.139 ms, max=222.256 ms, 99th percentile=0.482 ms, 99.8551% below 16.667 ms
info:  ┣tick_sources: min=0 ms, median=0.003 ms, max=222.081 ms, 99th percentile=0.005 ms
info:  ┣output_frame: min=0.052 ms, median=0.124 ms, max=10.807 ms, 99th percentile=0.458 ms
info:  ┃ ┗gs_context(video->graphics): min=0.052 ms, median=0.124 ms, max=10.804 ms, 99th percentile=0.458 ms
info:  ┃   ┣render_video: min=0.002 ms, median=0.033 ms, max=1.212 ms, 99th percentile=0.052 ms
info:  ┃   ┃ ┗render_main_texture: min=0.002 ms, median=0.031 ms, max=1.21 ms, 99th percentile=0.045 ms
info:  ┃   ┗gs_flush: min=0.001 ms, median=0.089 ms, max=9.584 ms, 99th percentile=0.416 ms
info:  ┗render_displays: min=0.002 ms, median=0.003 ms, max=0.028 ms, 99th percentile=0.005 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.011 ms, median=25.059 ms, max=27.635 ms, 99.1489% within ±2% of 25 ms (0% lower, 0.851064% higher)
info: obs_graphics_thread(16.6667 ms): min=11.064 ms, median=16.667 ms, max=222.261 ms, 98.2583% within ±2% of 16.667 ms (0.870827% lower, 0.870827% higher)
info: =================================================
info: Number of memory leaks: 0
```

</details>

### Additional context

I bisected the problem and found  that the first bad commit is abf354c5e5f1c8ec9f725a7db9c2e084be956ac1. (cc @NickCao)

The commit before fails to build: 2c35581d1df90df767241f03236b9790b0dfa6ae

The last good commit (the above commit's parent) is 8f1a3fbaa92f1d59b09f2d24af6a607b5a280071 (linux x86-64 resulting path is /nix/store/1qqs4hvvs12ca8wwif452hydjwzc0a69-obs-studio-30.1.2).

### Notify maintainers

@eclairevoyant @jb55 @MP2E @materusPL  @fpletz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre616726.7bb2ccd8cdc4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
can't repro (sway, intel), nor do I see much of any error in the logs above
does this happen in any other compositor?

**Comment by kevincox** [comment]
This seems to have fixed itself. I can no longer reproduce on GNOME Wayland.

**Comment by kevincox** [comment]
I tried rebuilding the first broken commit and it works now. So it seems like there was a temporary incompatibility between GNOME or some other part of the system that was causing trouble. With my latest GNOME, KDE or Sway all versions of OBS that I have tried seem to work.

I'm too lazy to bisect the change that fixed it but it seems that this issue is resolved.

**Comment by adminy** [comment]
Still failing to open the window, on latest master for me:

https://logpaste.com/kzqyEiPV

And from the logs you can almost say that it should be opened somewhere ...

**Comment by eclairevoyant** [comment]
Screen capture works fine, so this is obviously a configuration issue. Probably forgot to export some envvar to the systemd/dbus user environment, in any case I don't see any evidence that this is an OBS issue.
