### ISSUE TITLE
Build failure: python3.11-k5test-0.10.4

### ISSUE THREAD

**Issue by aaronpkelly** [NixOS/nixpkgs#314569]
### Steps To Reproduce

1. run `nix-channel --update && darwin-rebuild switch --verbose --show-trace`

### Build log

```
evaluating file '/nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/development/python-modules/k5test/default.nix'
evaluating file '/nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/development/python-modules/parameterized/default.nix'
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'darwin-system-24.11pre630522.3305b2b25e4a+darwin4'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'activationScript' of derivation 'darwin-system-24.11pre630522.3305b2b25e4a+darwin4'

         at /nix/store/2cd2pjc368rz01w0928w4cr7f9bw4x15-darwin/darwin/modules/system/default.nix:95:7:

           94|
           95|       activationScript = cfg.activationScripts.script.text;
             |       ^
           96|       activationUserScript = cfg.activationScripts.userScript.text;

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1205:18:

         1204|         mapAttrs
         1205|           (name: value:
             |                  ^
         1206|             if isAttrs value && cond value

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1208:18:

         1207|             then recurse (path ++ [ name ]) value
         1208|             else f (path ++ [ name ]) value);
             |                  ^
         1209|     in

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `system.activationScripts.script.text':

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:824:28:

          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                            ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/2cd2pjc368rz01w0928w4cr7f9bw4x15-darwin/darwin/modules/system/activation-scripts.nix':

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:825:137:

          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          826|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:896:25:

          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1205:18:

         1204|         mapAttrs
         1205|           (name: value:
             |                  ^
         1206|             if isAttrs value && cond value

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1208:18:

         1207|             then recurse (path ++ [ name ]) value
         1208|             else f (path ++ [ name ]) value);
             |                  ^
         1209|     in

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `system.activationScripts.postActivation.text':

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:824:28:

          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                            ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/Users/aaronkelly/.nix-defexpr/channels/home-manager/nix-darwin':

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:825:137:

          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          826|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:896:25:

          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1096:10:

         1095|     attrs:
         1096|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
         1097|

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1096:16:

         1095|     attrs:
         1096|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
         1097|

       … while calling anonymous lambda

         at /Users/aaronkelly/.nix-defexpr/channels/home-manager/nix-darwin/default.nix:16:36:

           15|       system.activationScripts.postActivation.text = concatStringsSep "\n"
           16|         (mapAttrsToList (username: usercfg: ''
             |                                    ^
           17|           echo Activating home-manager configuration for ${username}

       … while evaluating derivation 'activation-aaronkelly'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'text' of derivation 'activation-aaronkelly'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:103:16:

          102|       ({
          103|         inherit text executable checkPhase allowSubstitutes preferLocalBuild;
             |                ^
          104|         passAsFile = [ "text" ]

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:68:16:

           67|         enableParallelBuilding = true;
           68|         inherit buildCommand name;
             |                ^
           69|         passAsFile = [ "buildCommand" ]

       … while evaluating derivation 'activation-script'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'text' of derivation 'activation-script'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:103:16:

          102|       ({
          103|         inherit text executable checkPhase allowSubstitutes preferLocalBuild;
             |                ^
          104|         passAsFile = [ "text" ]

       … while calling 'mkCmd'

         at /Users/aaronkelly/.nix-defexpr/channels/home-manager/modules/home-environment.nix:666:17:

          665|       let
          666|         mkCmd = res: ''
             |                 ^
          667|             _iNote "Activating %s" "${res.name}"

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1205:18:

         1204|         mapAttrs
         1205|           (name: value:
             |                  ^
         1206|             if isAttrs value && cond value

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1208:18:

         1207|             then recurse (path ++ [ name ]) value
         1208|             else f (path ++ [ name ]) value);
             |                  ^
         1209|     in

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `home-manager.users.aaronkelly.home.activation.checkFilesChanged.data':

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:824:28:

          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                            ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/Users/aaronkelly/.nix-defexpr/channels/home-manager/modules/files.nix':

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:825:137:

          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          826|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:896:25:

          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … from call site

         at /Users/aaronkelly/.nix-defexpr/channels/home-manager/modules/files.nix:256:12:

          255|         declare -A changedFiles
          256|       '' + concatMapStrings (v:
             |            ^
          257|         let

       … while calling 'concatMapStrings'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/strings.nix:60:25:

           59|   */
           60|   concatMapStrings = f: list: concatStrings (map f list);
             |                         ^
           61|

       … while calling anonymous lambda

         at /Users/aaronkelly/.nix-defexpr/channels/home-manager/modules/files.nix:264:22:

          263|             || changedFiles[${targetArg}]=1
          264|         '') (filter (v: v.onChange != "") (attrValues cfg))
             |                      ^
          265|       + ''

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1205:18:

         1204|         mapAttrs
         1205|           (name: value:
             |                  ^
         1206|             if isAttrs value && cond value

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/attrsets.nix:1208:18:

         1207|             then recurse (path ++ [ name ]) value
         1208|             else f (path ++ [ name ]) value);
             |                  ^
         1209|     in

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `home-manager.users.aaronkelly.home.file."Library/Fonts/.home-manager-fonts-version".onChange':

       … while calling anonymous lambda

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:824:28:

          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                            ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/Users/aaronkelly/.nix-defexpr/channels/home-manager/modules/targets/darwin/fonts.nix':

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:825:137:

          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          826|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/modules.nix:896:25:

          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … from call site

         at /Users/aaronkelly/.nix-defexpr/channels/home-manager/modules/targets/darwin/fonts.nix:22:13:

           21|         run ${pkgs.rsync}/bin/rsync $VERBOSE_ARG -acL --chmod=u+w --delete \
           22|           ${escapeShellArgs [ "${fonts}/" installDir ]}
             |             ^
           23|       '';

       … while calling 'concatMapStringsSep'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/strings.nix:116:5:

          115|     # List of input strings
          116|     list: concatStringsSep sep (map f list);
             |     ^
          117|

       … while calling 'escapeShellArg'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/lib/strings.nix:454:20:

          453|   */
          454|   escapeShellArg = arg: "'${replaceStrings ["'"] ["'\\''"] (toString arg)}'";
             |                    ^
          455|

       … while evaluating derivation 'home-manager-fonts'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'passAsFile' of derivation 'home-manager-fonts'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:69:9:

           68|         inherit buildCommand name;
           69|         passAsFile = [ "buildCommand" ]
             |         ^
           70|           ++ (derivationArgs.passAsFile or [ ]);

       … while evaluating derivation 'visidata-3.0.2'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'propagatedBuildInputs' of derivation 'visidata-3.0.2'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:385:7:

          384|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
          385|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
             |       ^
          386|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;

       … while evaluating derivation 'python3.11-pyarrow-16.0.0'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'buildInputs' of derivation 'python3.11-pyarrow-16.0.0'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:378:7:

          377|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          378|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          379|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       … while evaluating derivation 'python3.11-fsspec-2024.3.0'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'propagatedBuildInputs' of derivation 'python3.11-fsspec-2024.3.0'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:385:7:

          384|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
          385|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
             |       ^
          386|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;

       … while evaluating derivation 'python3.11-paramiko-3.4.0'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'python3.11-paramiko-3.4.0'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:375:7:

          374|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          375|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          376|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       … while evaluating derivation 'python3.11-gssapi-1.8.3'
         whose name attribute is located at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'python3.11-gssapi-1.8.3'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:375:7:

          374|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          375|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          376|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       … from call site

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/check-meta.nix:511:13:

          510|           else if valid == "no" then (
          511|             handleEvalIssue { inherit meta attrs; } { inherit (validity) reason errormsg; }
             |             ^
          512|           )

       … while calling 'handleEvalIssue'

         at /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/stdenv/generic/check-meta.nix:269:38:

          268|
          269|   handleEvalIssue = { meta, attrs }: { reason , errormsg ? "" }:
             |                                      ^
          270|     let

       error: Package ‘python3.11-k5test-0.10.4’ in /nix/store/sxvhj6d9sf0fk7c4fzpks32pdijk25il-nixpkgs/nixpkgs/pkgs/development/python-modules/k5test/default.nix:42 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
```

### Additional context

Seems like this has been noticed by someone else: https://github.com/NixOS/nixpkgs/issues/312692#issuecomment-2128270442

### Notify maintainers

No maintainers found? @fabaff do you have any idea?

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mradalbert** [comment]
It builds against nixos-unstable@https://github.com/NixOS/nixpkgs/commit/bfb7a882678e518398ce9a31a881538679f6f092

**Comment by mradalbert** [comment]
I have opened backport PR: https://github.com/NixOS/nixpkgs/pull/315062

**Comment by mradalbert** [comment]
fixed on release-24.05

**Comment by aaronpkelly** [comment]
sorry if I'm asking a silly question @mradalbert - I see this was merged to the release-24.05 branch in https://github.com/NixOS/nixpkgs/commit/c75d10d93d2994ba2710d947366f11e639722f0e... thank you very much

but does this mean this commit will also be included at some stage in the future in the branch **nixpkgs-24.05-darwin**?

**Comment by mradalbert** [comment]
This is my understanding. Before getting to specific channel changes has to be tested, built and pushed to cache by Hydra.

**Comment by YaroKasear** [comment]
Does this mean I have to use a specific branch on MacOS? That's going to make using my flake difficult as it's not only used for Darwin. I still can't update right now using `24.05-release`.

**Comment by robled** [comment]
I'm also unable to update my Darwin systems to 24.05.  Is there any workaround?

**Comment by aca** [comment]
```
nixpkgs-unstable.url = "github:NixOS/nixpkgs/master";
darwin = {
  url = "github:LnL7/nix-darwin/master";
  inputs.nixpkgs.follows = "nixpkgs-unstable";
};
```
this is unsafe, but works for now.

**Comment by mradalbert** [comment]
I have just built nix-darwin with home-manager on M1:
```
{
  # Packages
  inputs = {
    nixpkgs = {
      url = "github:nixos/nixpkgs/nixos-24.05";
    };

    # MacOS support
    darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Home-Manger
    home-manager = {
      url = "github:nix-community/home-manager/release-24.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
}
```

**Comment by robled** [comment]
Can confirm it's fixed on my end.  Thank you!

**Comment by donovanglover** [comment]
If this is fixed now, let's close the issue
