### ISSUE TITLE
.NET Core tooling stops working due to `ñ` in release codename and lack of HTTP headers sanitization

### ISSUE THREAD

**Issue by nazarewk** [NixOS/nixpkgs#315574]
EDIT1: Series of issues filed in ends up with this one https://github.com/Azure/azure-sdk-for-net/issues/44300

EDIT2: there are more issues across .NET than just Azure SDK (eg: NuGet has it's own faulty implementation), see the discussion for details.

### Describe the bug
Yesterday evening I ran update to latest `nixos-unstable`, today when using [`msgraph-cli`](https://github.com/NixOS/nixpkgs/pull/314619) I'm running across `Request headers must contain only ASCII characters.` errors.

Running it with debug I have noticed following header:
```
User-Agent:azsdk-net-Identity/1.10.4 (.NET 8.0.5; NixOS 24.11 (Vicuña))
```

### Steps To Reproduce
1. run (probably) anything doing HTTP requests using .NET SDK/azsdk on latest nixos-unstable
2. get the error

### Expected behavior
I'm quite sure this is improper escaping on the side of .NET SDK, but still using non-latin characters in names NixOS might yield such errors here and there.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nazarewk** [comment]
seems to be a .NET Core thing https://stackoverflow.com/questions/49879502/is-there-built-in-support-for-automatically-escaping-invalid-http-header-charact

**Comment by nazarewk** [comment]
Actually I can't fix it myself:
```nix
(lib.mkIf (lib.trivial.codeName == "Vicuña") { system.nixos.codeName = lib.mkForce "Vicuna"; })
```
results in:
```
       error: The option `system.nixos.codeName' is read-only, but it's set multiple times. Definition values:
       - In `/nix/store/s94zxf55wpvq06d80vjp1s6bzxz32qsl-source/nixos/modules/misc/version.nix': "Vicuña"
       - In `/nix/store/19sqqhhf11l3v5458f52d4npifn8pc24-source/modules/profile/machine/baseline/default.nix': "Vicuna"
```

**Comment by nazarewk** [comment]
I have finally got it to work, you can find code and explanation comments at https://github.com/nazarewk-iac/nix-configs/commit/5a76297893bbb171c440da90fb5e417bf9993bfe#diff-9bd1903895edc8ec69ce6debf7823905ba99fa41c35d4482d0464ab7f47aa627 :
```nix
/* Last reviewied: 2024-05-29

  fixes issues with lack of HTTP header sanitization in .NET Core, see:
  - https://github.com/NixOS/nixpkgs/issues/315574
  - https://github.com/microsoftgraph/msgraph-cli/issues/477
*/
{ lib, options, ... }: {
  /*
    using just `readOnly` because it can contain neither of: default, example, description, apply, type
    see https://github.com/NixOS/nixpkgs/blob/aae38d0d557d2f0e65b2ea8e1b92219f2c0ea8f9/lib/modules.nix#L752-L756
   */
  options.system.nixos.codeName = lib.mkOption { readOnly = false; };
  config.system.nixos.codeName =
    let
      codeName = options.system.nixos.codeName.default;
      renames."Vicuña" = "Vicuna";
    in
      renames."${codeName}" or (throw "Unknown `codeName`: ${codeName}, please add it to `renames` in `ascii-workaround.nix`");
}
```

**Comment by l0b0** [comment]
Ping @NixOS/dotnet

**Comment by l0b0** [comment]
Whoops, sorry. I thought I was assigning a reviewer! :facepalm:

**Comment by GGG-KILLER** [comment]
I believe there's nothing we can do here ourselves, instead it seems to be a problem with the upstream tool not accounting for this.

In this case I think it'd be be better to open an issue on the msgraph-cli repo so they can work on it.

**Comment by eclairevoyant** [comment]
There already is such an issue: https://github.com/microsoftgraph/msgraph-cli/issues/477

**Comment by purepani** [comment]
As per https://github.com/Azure/azure-sdk-for-net/issues/44300#issuecomment-2145495387, it looks like setting the environment variable `AZURE_TELEMETRY_DISABLED=1` fixes the issue(at least when using the dotnet cli).

**Comment by GGG-KILLER** [comment]
Upstream fix has been merged, now we have to wait for consumers of the SDK package to update to it.

**Comment by m-redding** [comment]
This will be released today in Azure.Core 1.40

**Comment by qubitnano** [comment]
What exactly needs to be updated on NixOS? Are we waiting for a new dotnet sdk/runtime version with this fix?

**Comment by nazarewk** [comment]
> What exactly needs to be updated on NixOS? Are we waiting for a new dotnet sdk/runtime version with this fix?

as far as I understand it is the issue with Azure SDK and all affected tools need to update it by themselves.


The only thing NixOS can do as a workaround is:

> As per [Azure/azure-sdk-for-net#44300 (comment)](https://github.com/Azure/azure-sdk-for-net/issues/44300#issuecomment-2145495387), it looks like setting the environment variable `AZURE_TELEMETRY_DISABLED=1` fixes the issue(at least when using the dotnet cli). Might be worth putting that into the deriviation, or patching it with the setting also mentioned in that comment.

**Comment by SuperSandro2000** [comment]
> As per [Azure/azure-sdk-for-net#44300 (comment)](https://github.com/Azure/azure-sdk-for-net/issues/44300#issuecomment-2145495387), it looks like setting the environment variable `AZURE_TELEMETRY_DISABLED=1` fixes the issue(at least when using the dotnet cli). Might be worth putting that into the deriviation, or patching it with the setting also mentioned in that comment.

At least for the dotnet update scripts, that isn't working and still failing with the rather misleading error ``error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json`` unless I change the release name.

**Comment by purepani** [comment]
The fix is no longer working for me, so I have no clue what is happening...

**Comment by purepani** [comment]
How hard would it be to override the azure-sdk version to require 1.40 for any package that is broken by this?

**Comment by SuperSandro2000** [comment]
I've just now set ``system.nixos.codeName = "Vicuna";`` since the linked PR to change it went no where.

**Comment by purepani** [comment]
Actually, are we sure that this solution propagating would fix the dotnet-cli issues? The original issue was about msgraph, and the fix was implemented in the azure sdk, and at least on a surface level, I'm not quite sure why the dotnet-sdk would depend on the azure-sdk

**Comment by SuperSandro2000** [comment]
Hmmm 🤔 I didn't find it either in the generated sources

**Comment by anpin** [comment]
@purepani 

> The fix is no longer working for me, so I have no clue what is happening...

Some packages might have been cached, so the CLI wouldn’t make any requests. That’s what I have seen on my machine at least. Only renaming the distro worked for me, setting aforementioned variable did nothing.

**Comment by purepani** [comment]
> @purepani
> 
> > The fix is no longer working for me, so I have no clue what is happening...
> 
> Some packages might have been cached, so the CLI wouldn’t make any requests. That’s what I have seen on my machine at least. Only renaming the distro worked for me, setting aforementioned variable did nothing.

I am reasonably certain I attempted to build using dotnet, it failed, and I then set the environment variable and it worked; though it was a week ago, so I may be misremembering.

**Comment by SuperSandro2000** [comment]
I think we also need to patch dotnet/dotnet but I didn't fully verify it and it could be that I missed something. Leaving the breadcrumbs here anyway, wo that other people get the chance to verify my initial thought without having to search for the traces first.

- https://github.com/dotnet/dotnet/blob/main/src/runtime/src/libraries/Common/src/Interop/Linux/os-release/Interop.OSReleaseFile.cs#L38
- https://github.com/dotnet/dotnet/blob/main/src/runtime/src/libraries/Common/src/Interop/Linux/os-release/Interop.OSReleaseFile.cs#L17
- https://github.com/dotnet/dotnet/blob/main/src/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/RuntimeInformation.Unix.cs#L13
- https://github.com/dotnet/dotnet/blob/main/src/nuget-client/src/NuGet.Core/NuGet.Protocol/UserAgentStringBuilder.cs#L93


In the first link PRETTY_NAME gets read and in the last one it is added to some user agent which might be the one that is used to fetch from nugget (I did not verify this further)

**Comment by m-redding** [comment]
The fix in Azure.Core will fix tools that were failing with "Request headers must contain only ASCII characters" coming from packages that use Azure.Identity or other Azure SDK libraries.

It doesn't seem like the "error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json" is related to the Azure Identity SDK error, especially since setting the AZURE_TELEMETRY_DISABLED=1 doesn't work. The Azure.Core code-in-question is not run if that is set, which is true in all versions of Azure.Core.

@SuperSandro2000 I took a quick look and agree it seems likely that is also an issue. I would open an issue in their repository. `dotnet restore` uses nuget but IDK that it uses any Azure packages (although I could be wrong about that)

**Comment by GGG-KILLER** [comment]
For the .NET CLI I've opened the bug NuGet/Home#13531 and once this is fixed we'll probably need to update the .NET binaries to fix this.

Patching isn't possible outside of source builds and the source builds currently don't have the latest SDK version unless for .NET 9 which is still in preview.

**Comment by purepani** [comment]
Is it possible to modify `nuget-to-nix` generation to run inside the nix sandbox somehow? The sandbox does in lode /etc/os-release AFAIK so that should fix it.

**Comment by SuperSandro2000** [comment]
No, it needs network access. We could hack around it with bwrap or libredirect but that maybe also breaks the next thing.

**Comment by purepani** [comment]
Is there a tag to add to this in order to put this on the task list for the 24.11 release? Given the temporary fix being a name change, and the slightly controversial discussion in #318511 it should probably come up for discussion again in the unlikely even that there's not a fix or a patch by the next release.

**Comment by arianvp** [comment]
Systemd 260 adds a new `FANCY_NAME=` field to `os-release` that supports Unicode

```

        * The os-release(5) gained a new field FANCY_NAME= that is similar
          to PRETTY_NAME= but may contain ANSI sequences such as Unicode
          emojis. The new field is also defined to NOT contain any version
          specification, providing better separation between the OS name
          and version.

          The systemd manager, systemd-hostnamed, and hostnamectl will now
          show FANCY_NAME= in preference to PRETTY_NAME=.
```

I think this means animals with Unicode are back on the menu for the next release!
