### ISSUE TITLE
freeglut/Haskell problem

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#32280]
## Issue description

When developing OpenGL programs under NixOS in Haskell, they give an error message when run.

### Steps to reproduce

Try to build and run a Haskell/OpenGL project, like `https://github.com/turion/sonnendemo`.

```
# git clone https://github.com/turion/sonnendemo.git
# cd sonnendemo
# nix-shell -p mesa mesa_glu freeglut
# cabal install --only-dependencies
# cabal build
# cabal run sonnendemo
Preprocessing library for sonnendemo-0.3.0.0..
Building library for sonnendemo-0.3.0.0..
Preprocessing executable 'sonnendemo' for sonnendemo-0.3.0.0..
Building executable 'sonnendemo' for sonnendemo-0.3.0.0..
Running sonnendemo...
sonnendemo: user error (unknown GLUT entry glutInit)
```

I think `glutInit` should be supplied by `freeglut`. On all other OSes I tried (Windows, Ubuntu), it worked.

## Technical details

```
# nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.12pre5732_fd10f6f2, channels(root): "nixos-18.03pre121670.4cbbecc85db", channels(turion): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

**Comment by turion** [comment]
Seems related to #17547.

**Comment by turion** [comment]
A workaround is using `stack` and adding the following lines (taken from [here](https://stackoverflow.com/questions/41527061/nixos-haskell-opengl-problems-with-building-and-running-opengl-programs)):

```
nix:
  enable: true
  packages: [mesa freeglut]
```

**Comment by barryfm** [comment]
There is a problem with the latest freeglut in that it produces a pkg-config file named glut.pc and no freeglut.pc.
This means any autoconfig approach will not find proper libraries to link.  I brought it up before and the response was that it was not going to be fixed. #76073

**Comment by turion** [comment]
I think the best approach is to use `cabal2nix`. That solves the issue for me.

**Comment by barryfm** [comment]
I don't want to to reopen this issue, since the maintainer doesn't seem to care.

The Haskell package was fixed by patching around the issue.  The other dependent packages seem to just be left broken or also patch around the problem.  I just use my own nix setup which is attached, in case someone is interested.
[freeglut.txt](https://github.com/NixOS/nixpkgs/files/4978597/freeglut.txt)

**Comment by turion** [comment]
@billksun See https://github.com/NixOS/cabal2nix.

For example:

```
$ cabal2nix cabal://OpenGLRaw
{ mkDerivation, base, bytestring, containers, fixed, half, lib
, libGL, text, transformers
}:
mkDerivation {
  pname = "OpenGLRaw";
  version = "3.3.4.1";
  sha256 = "121abdea149ac74514efb2c1c1c319466757242d1b72a8bdf99d49535f06d31e";
  libraryHaskellDepends = [
    base bytestring containers fixed half text transformers
  ];
  librarySystemDepends = [ libGL ];
  homepage = "http://www.haskell.org/haskellwiki/Opengl";
  description = "A raw binding for the OpenGL graphics system";
  license = lib.licenses.bsd3;
}
```

See that it added `librarySystemDepends = [ libGL ];` which pulls in the right depencies.

So when you develop a package `foo.cabal`, move to your project directory and do `cabal2nix --shell foo.cabal > shell.nix`, and then enter `nix-shell`. In there, you have a development environment that includes all necessary dependencies, including system dependencies outside Haskell.

**Comment by billksun** [comment]
@turion, how would I do this using Nix Flakes? Would I just add the packages in `librarySystemDepends` to `devShell` in the flake output?

**Comment by turion** [comment]
I have no idea how it would work with flakes, unfortunately. But it should be possible in a similar way.

**Comment by gfarrell** [comment]
Having just tried to get an OpenGL programme running (using `gloss`) in a flake environment, and getting the same error (`user error (unknown GLUT entry glutInit)`), it seems that lots of people have this problem (there are many github issues and SO questions) but that it still isn't really fixed?

I have tried a flake with `nativeBuildInputs = with pkgs; [ libGL libGLU freeglut ]` and various combinations of these, with or without `mesa`, etc., but nothing fixes the issue for me.

It's unclear whether this is a problem with the haskell `GLUT` package, the `OpenGL` package, `nixpkgs`, or something else.

It works fine for me if I just don't use `nix` (I'm on Arch not NixOS).

**Comment by barryfm** [comment]
I have not had a problem using flakes on `nixos-24.11` or a `nixpkgs-unstable` home-manager setup on Fedora-41.  I use both the Haskell GLUT and C.  The Haskell program seems to just work.
My C program uses  `libGL, libGLU, freeglut` as its dependencies in the `default.nix`.  In the Makefile I use `pkg-config gl glu glut` with `--cflags` and `--libs` to get its required libraries.
