### ISSUE TITLE
Haskell: setupCompilerEnvironmentPhase doesn't recognize internal libraries

### ISSUE THREAD

**Issue by rihardsk** [NixOS/nixpkgs#33149]
## Issue description
`haddock-api` fails to build due to a missing dependency `haddock-library ==1.4.4.*`

### Steps to reproduce
```
git clone git://github.com/NixOS/nixpkgs.git && cd nixpkgs
nix-build -A haskellPackages.haddock-api
```
The same thing happens using the `nixos-unstable` channel.

## Technical details
Here's a bit of the build output
```
Configuring haddock-api-2.18.1...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:948:20 in Cabal-2.0.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:470:12 in Cabal-2.0.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:570:20 in Cabal-2.0.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.0.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:174:19 in Cabal-2.0.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:119:27 in Cabal-2.0.1.0:Distribution.Simple
  defaultMain, called at Setup.lhs:3:10 in main:Main
Setup: Encountered missing dependencies:
haddock-library ==1.4.4.*
builder for ‘/nix/store/drfsrikcl2p212iwgipsjglvm5b6r4as-haddock-api-2.18.1.drv’ failed with exit code 1
error: build of ‘/nix/store/drfsrikcl2p212iwgipsjglvm5b6r4as-haddock-api-2.18.1.drv’ failed
```

I've tried adding my own expression for `haddock-library_1_4_4` taken from `Cabal` and it builds just fine, but it gets ignored when building `haddock-api` (could be a separate issue on my part though).

_Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results._
```
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/qxh4z54pcy7cr5dhq8c059zh571s70ri-nix-info
fetching path ‘/nix/store/qxh4z54pcy7cr5dhq8c059zh571s70ri-nix-info’...

*** Downloading ‘https://cache.nixos.org/nar/054fgr1zk7qlm19s6z182ag95mr97l2r48x4y4jj5fl828901bni.nar.xz’ to ‘/nix/store/qxh4z54pcy7cr5dhq8c059zh571s70ri-nix-info’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1644  100  1644    0     0   7008      0 --:--:-- --:--:-- --:--:--  7116

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.8-1-ARCH, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.13`
 - channels(rihards): `"nixpkgs-18.03pre123609.93829f1b031"`
 - nixpkgs: `/home/rihards/.nix-defexpr/channels/nixpkgs`
```

**Comment by hamishmack** [comment]
This is working for me on nixos (perhaps it has been fixed for Linux), but I get a an error on macOS.   The macOS error seems to be related to [this macOS only code in setupCompilerEnvironmentPhase](https://github.com/NixOS/nixpkgs/blob/016aa581a757d468e35a03c6f8a3a0309af95e31/pkgs/development/haskell-modules/generic-builder.nix#L247).

**nixos**
```
[hamish@nixos:/home/hamish/nixpkgs]$ nix-build -A haskellPackages.haddock-api
/nix/store/gpwqi5268wgfqnc57jg7nny2p7ynypvp-haddock-api-2.18.1

[hamish@nixos:/home/hamish/nixpkgs]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.58, NixOS, 18.03pre118381.4068703502 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre122666.afe9649210c"`
 - channels(hamish): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**macOS**
```
~/nixpkgs$ nix-build -A haskellPackages.haddock-api
these derivations will be built:
  /nix/store/96ml3gl7iq6ldr9zyr4xz2iqas71hwlg-haddock-api-2.18.1.drv
building path(s) ‘/nix/store/mnrmiz8fx02rb1mjrmwr0n6adv2dmkil-haddock-api-2.18.1-doc’, ‘/nix/store/nis2ncsl5qcvacyca4cdim5j605zrjas-haddock-api-2.18.1’, ‘/nix/store/ynn92mzcsy1r97klb5bwmm8rmd7x60zk-haddock-api-2.18.1-data’
setupCompilerEnvironmentPhase
Build with /nix/store/yszz79gj05f4dlgjbwbmglq8ydndnzr3-ghc-8.2.2.
ln: failed to create symbolic link '/nix/store/nis2ncsl5qcvacyca4cdim5j605zrjas-haddock-api-2.18.1/lib/links/libHShaddock-library-1.4.4-BXedb9tEAJEKpUW5xu3aRK-attoparsec-ghc8.2.2.dylib': File exists
ln: failed to create symbolic link '/nix/store/nis2ncsl5qcvacyca4cdim5j605zrjas-haddock-api-2.18.1/lib/links/libHShaddock-library-1.4.4-G8iPfxLjJ1KJncaQAcQooZ-ghc8.2.2.dylib': File exists
builder for ‘/nix/store/96ml3gl7iq6ldr9zyr4xz2iqas71hwlg-haddock-api-2.18.1.drv’ failed with exit code 1
error: build of ‘/nix/store/96ml3gl7iq6ldr9zyr4xz2iqas71hwlg-haddock-api-2.18.1.drv’ failed
/Users/hamish/.nix-profile/bin/ghc /Users/hamish/.nix-profile/bin/pkg-config
~/nixpkgs$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.3.0, macOS 10.13.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(hamish): `"nixpkgs-18.03pre122127.79081322ab9"`
 - channels(root): `"nixpkgs-18.03pre116939.d7d774deea"`
 - nixpkgs: `/Users/hamish/.nix-defexpr/channels/nixpkgs`
```

**Comment by hamishmack** [comment]
I think the problem on macOS is that it assumes there will only be on `.conf` file.  However `haddock-library-1.4.4` has an internal sub library (a version of attoparsec) and so it has two `.conf` files.

```
~/nixpkgs$ ls `nix-build -A haskellPackages.haddock-library_1_4_4`/lib/ghc-8.2.2/package.conf.d 
haddock-library-1.4.4-BXedb9tEAJEKpUW5xu3aRK-attoparsec.conf haddock-library-1.4.4-G8iPfxLjJ1KJncaQAcQooZ.conf
```

The simplest fix might be to change [the expression here](https://github.com/NixOS/nixpkgs/blob/016aa581a757d468e35a03c6f8a3a0309af95e31/pkgs/development/haskell-modules/generic-builder.nix#L246) from:

```
grep dynamic-library-dirs "$packageConfDir/"*|awk '{print $2}'
```
to:
```
grep dynamic-library-dirs "$packageConfDir/"*|awk '{print $2}'|sort -u
```

CC @peti

**Comment by peti** [comment]
Ping @shlevy who wrote patches to support internal libraries before.

**Comment by shlevy** [comment]
Ah, I think @hamishmack has it right here. I'll test on my macbook.

**Comment by rihardsk** [comment]
#33333 doesn't solve the original issue on Arch Linux. I still get the same error output as in the original post, when I run `nix-build -A haskellPackages.haddock-api` on `master` at c11b87b5733. @peti I think this should be reopened.

**Comment by peti** [comment]
I cannot reproduce this in `master` @ 2280127e854a585f19a7db63a6bc8934fc2dd965:

~~~
$ nix-build -A haskellPackages.haddock-api 
/nix/store/hizhrclihvb14mr78famzvipmcdi5rg5-haddock-api-2.18.1
~~~

**Comment by rihardsk** [comment]
Any suggestions then how to debug what's wrong with my setup?
