### ISSUE TITLE
Purescript-0.11.7 fails to compile on unstable (dependencies)

### ISSUE THREAD

**Issue by kwohlfahrt** [NixOS/nixpkgs#33355]
## Issue description

Purescript-0.11.7 fails to install with the error below:

```
Setup: Encountered missing dependencies:
Glob >=0.7 && <0.9, ansi-terminal >=0.6.2 && <0.7
```

The `Glob` dependency is bumped upstream, `ansi-terminal` is not.

### Steps to reproduce

Run `nix-env --install purescript`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.71, NixOS, 18.03pre123588.ade98dc442e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - channels(kai): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mekeor** [comment]
Do I understand correctly, that bumping the version of ansi-terminal [here](https://github.com/purescript/purescript/blob/master/package.yaml#L37) should fix this issue?

**Comment by mekeor** [comment]
Currently, in nixpkgs, ansi-terminal defaults to version 0.7.1.1.

**Comment by kwohlfahrt** [comment]
Yes I think that should fix it (plus a version bump upstream so we can actually use this).

**Comment by mpickering** [comment]
Either create an attribute for `ansi-terminal-0.6.*` and override that dependency specifically or alternatively, does jailbreaking it work?

Either way, getting it to build without upstream intervention is desirable imo as this is an important executable for non-haskell users.

**Comment by mekeor** [comment]
What do you think about @hdgarrood's comment on the upstream-issue https://github.com/purescript/purescript/issues/3189?

**Comment by mpickering** [comment]
That’s not how haskell packages are packaged normally. It is less maintenance effort to not have lots of different versions of packages.

**Comment by juselius** [comment]
Ok, but how do I install the working purescript compiler? I have pulled the latest nixpkgs containing the fix, but ``nix-env -f . -iA purescirpt`` still fails with the same error.

Btw. psc-package chokes on the turtle (==1.3.*) dependency.

**Comment by mpickering** [comment]
See #33607

I made a mistake originally and thought the build failed with the latest version of `ansi-terminal` but it turns out jailbreaking is sufficient. 

I don't know what `psc-package` is sorry.

**Comment by juselius** [comment]
It works! Thanks!
