### ISSUE TITLE
Build failure: rPackages.V8

### ISSUE THREAD

**Issue by savyajha** [NixOS/nixpkgs#339861]
### Steps To Reproduce

1. Be on unstable
2. `nix build nixpkgs#rPackages.V8`
3. If the version is 5.0.0, then it won't build.

### Build log

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/92nvrcn6w8k2ylbrjzmd3lalwri0c4mv-V8_5.0.0.tar.gz
source root is V8
setting SOURCE_DATE_EPOCH to timestamp 1723808402 of file V8/MD5
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
patching script interpreter paths in configure
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: checkPhase
@nix { "action": "setPhase", "phase": "checkPhase" }
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
* installing *source* package 'V8' ...
file 'configure' has the wrong MD5 checksum
** using staged installation
Found C++20 compiler: /nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/c++
Found INCLUDE_DIR and/or LIB_DIR!
Using CXXCPP=/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/c++ -std=gnu++20 -E
Using PKG_CFLAGS=-I/nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/include -I/usr/include/v8
Using PKG_LIBS=-L/nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/lib -lv8
Running feature test for pointer compression...
/nix/store/d828ccvc2148g7m49hh3mzvyzwpipy46-binutils-2.42/bin/ld: /build/cci07brP.o: in function `main':
/build/V8/tools/test.cpp:7:(.text.startup+0x36): undefined reference to `v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::unique_ptr<v8::TracingController, std::default_delete<v8::TracingController> >)'
/nix/store/d828ccvc2148g7m49hh3mzvyzwpipy46-binutils-2.42/bin/ld: /build/V8/tools/test.cpp:8:(.text.startup+0x48): undefined reference to `v8::V8::InitializePlatform(v8::Platform*)'
/nix/store/d828ccvc2148g7m49hh3mzvyzwpipy46-binutils-2.42/bin/ld: /build/cci07brP.o: in function `v8::V8::Initialize()':
/nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/include/v8-initialization.h:104:(.text.startup+0x4f): undefined reference to `v8::V8::Initialize(int)'
collect2: error: ld returned 1 exit status
Pointer compression not needed
/nix/store/d828ccvc2148g7m49hh3mzvyzwpipy46-binutils-2.42/bin/ld: /build/ccvxSXdC.o: in function `main':
/build/V8/tools/version.cpp:5:(.text.startup+0x2): undefined reference to `v8::V8::GetVersion()'
collect2: error: ld returned 1 exit status
./configure: line 154: ./v8version: not found
** libs
using C++ compiler: 'g++ (GCC) 13.3.0'
using C++20
rm -f V8.so RcppExports.o bindings.o
/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/c++ -std=gnu++20 -I"/nix/store/fnl3bp7k0qw8cayqz2lciq8sq0xmib2c-R-4.4.1/lib/R/include" -DNDEBUG -I/nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/include -I/usr/include/v8 -DV8_ENABLE_CHECKS -I'/nix/store/sx72hmip9xs97vqw2dsjm67n63sc17f0-r-Rcpp-1.0.13/library/Rcpp/include'    -fvisibility=hidden -fpic  -g -O2   -c RcppExports.cpp -o RcppExports.o
/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/c++ -std=gnu++20 -I"/nix/store/fnl3bp7k0qw8cayqz2lciq8sq0xmib2c-R-4.4.1/lib/R/include" -DNDEBUG -I/nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/include -I/usr/include/v8 -DV8_ENABLE_CHECKS -I'/nix/store/sx72hmip9xs97vqw2dsjm67n63sc17f0-r-Rcpp-1.0.13/library/Rcpp/include'    -fvisibility=hidden -fpic  -g -O2   -c bindings.cpp -o bindings.o
/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/c++ -std=gnu++20 -shared -L/nix/store/fnl3bp7k0qw8cayqz2lciq8sq0xmib2c-R-4.4.1/lib/R/lib -o V8.so RcppExports.o bindings.o -L/nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/lib -lv8 -L/nix/store/fnl3bp7k0qw8cayqz2lciq8sq0xmib2c-R-4.4.1/lib/R/lib -lR
installing to /nix/store/xry9hlna4xhk4zn7s91rx02gbh3ip9ym-r-V8-5.0.0/library/00LOCK-V8/00new/V8/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'V8' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/nix/store/xry9hlna4xhk4zn7s91rx02gbh3ip9ym-r-V8-5.0.0/library/00LOCK-V8/00new/V8/libs/V8.so':
  /nix/store/xry9hlna4xhk4zn7s91rx02gbh3ip9ym-r-V8-5.0.0/library/00LOCK-V8/00new/V8/libs/V8.so: undefined symbol: _ZN2v815ArrayBufferView9CheckCastEPNS_5ValueE
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/nix/store/xry9hlna4xhk4zn7s91rx02gbh3ip9ym-r-V8-5.0.0/library/V8'
```

### Notify maintainers
@jbedo I think you'd be the right person to ping about this.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.153.1-microsoft-standard-WSL2, NixOS, 24.11 (Vicuna), 24.11.20240903.2830c7c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/3k5a074975asfpx63n29agzskx822gp5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jbedo** [comment]
This is an issue with the libv8 build, the library is empty:

```
❯ nm /nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/lib/libv8.a

❯ stat /nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/lib/libv8.a
  File: /nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/lib/libv8.a
  Size: 8               Blocks: 1          IO Block: 512    regular file
Device: 259,2   Inode: 273319414   Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-09-06 08:36:02.609609321 +1000
Modify: 1970-01-01 10:00:01.000000000 +1000
Change: 2024-09-02 10:23:27.078380614 +1000
 Birth: 2024-09-02 10:23:27.077380599 +1000

❯ cat !$
cat /nix/store/sl8zwksqc08asblhr5r36dlhzy6brmpk-nodejs-20.16.0-libv8/lib/libv8.a
!<arch>

❯
```

Ping @aduh95.

**Comment by aduh95** [comment]
I suspect this was solved by https://github.com/NixOS/nixpkgs/pull/337360.

**Comment by aduh95** [comment]
@savyajha https://github.com/NixOS/nixpkgs/pull/337360 has landed on `staging`, not `master`. Can you try to cherry-pick https://github.com/NixOS/nixpkgs/commit/efbf70d52cbd6038d3476fcc2a6358ba5f57d5d9 on top of `master` and re-try to build?

**Comment by savyajha** [comment]
@aduh95 Yup, I should have been more careful, I assumed it had landed on master. It builds with that specific patch. Cheers.

**Comment by telegott** [comment]
Are there any estimates on when this can be expected to be solved? As of today, it still does not build

**Comment by aduh95** [comment]
When https://github.com/NixOS/nixpkgs/pull/343421 is merged
