### ISSUE TITLE
Bluetooth not working on latest nixos-unstable commit

### ISSUE THREAD

**Issue by qussaif10** [NixOS/nixpkgs#346443]
### Describe the bug
Bluetooth does not work, i tried to connect my bluetooth headphones and it failed
### Steps To Reproduce
1. use latest nixos-unstable commit 27e30d177e57d912d614c88c622dcfdb2e6e6515
2. attempt to connect bluetooth device
3. ...

### Additional context
I can reproduce the issue on my machine

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.53, NixOS, 24.11 (Vicuna), 24.11.20241001.27e30d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/lryfc8mhk1czqsa421di2y5nzz5c3b8m-source````

```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by winterqt** [comment]
You need to be much more specific about what you've tried to debug so far. Does this work on NixOS 24.05? How are you trying to connect Bluetooth devices? What happens other than "...?"

Please consider asking for help in Matrix or Discourse, before just assuming that this is a NixOS bug; it likely isn't.

**Comment by qussaif10** [comment]
oh sorry for my ignorance, i assumed it's a NixOS bug because when i switched from unstable to 24.05 it was fixed, though looking back i did not do a lot of debugging except for successfully replicating the issue.

I will do some more research, should i close the issue?

**Comment by bobvanderlinden** [comment]
I also ran into this issue when (re)connecting my headphones (Bose QuietComfort2). Bringing the device into pairing mode and connecting from my laptop does work. Reconnects after that keep working, until I reboot my laptop and I need to repair.

When the headphones are not able to connect it gets into a weird state where (seems?) to connect and immediately disconnects (this is just theory, as I don't hear disconnect/connect sounds, I think because it happens so fast).

When I restart bluetoothd (`systemctl restart bluetoothd`) I get into the same state as rebooting. After doing so I need to re-pair the headphones. Without that, my headphones cannot connect to my laptop and my laptop cannot connect to my headphones.

The bluetooth mouse keeps working fine. It's just the headphones that are problematic.

I ran `btmon` and saw the following messages related to the headphones:

```
> HCI Event: Command Complete (0x0e) plen 10                                        #286 [hci0] 60.306435
      IO Capability Request Reply (0x01|0x002b) ncmd 1
        Status: Success (0x00)
        Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
> HCI Event: Simple Pairing Complete (0x36) plen 7                                  #287 [hci0] 60.329519
        Status: Authentication Failure (0x05)
        Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
> HCI Event: Auth Complete (0x06) plen 3                                            #288 [hci0] 60.330447
        Status: Authentication Failure (0x05)
        Handle: 256 Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
@ MGMT Event: Authentication Failed (0x0011) plen 8                             {0x0001} [hci0] 60.330494
        BR/EDR Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
        Status: Authentication Failed (0x05)
> ACL Data RX: Handle 256 flags 0x02 dlen 12                                        #289 [hci0] 60.338605
      L2CAP: Disconnection Response (0x07) ident 5 len 4
        Destination CID: 3909
        Source CID: 64
> HCI Event: Number of Completed Packets (0x13) plen 5                              #290 [hci0] 60.339426
        Num handles: 1
        Handle: 256 Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
        Count: 1
        #278: len 12 (2 Kb/s)
        Latency: 38 msec (6-42 msec ~29 msec)
bluetoothd[28470]: = profiles/audio/avdtp.c:avdtp_connect_cb() connect to 2C:41:A1:C8:E5:04..   60.434024
< HCI Command: Disconnect (0x01|0x0006) plen 3                                      #291 [hci0] 62.473891
        Handle: 256 Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
        Reason: Remote User Terminated Connection (0x13)
> HCI Event: Command Status (0x0f) plen 4                                           #292 [hci0] 62.597677
      Disconnect (0x01|0x0006) ncmd 1
        Status: Success (0x00)
> HCI Event: Disconnect Complete (0x05) plen 4                                      #293 [hci0] 62.694907
        Status: Success (0x00)
        Handle: 256 Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
        Reason: Connection Terminated By Local Host (0x16)
@ MGMT Event: Device Disconnected (0x000c) plen 8                               {0x0001} [hci0] 62.695046
        BR/EDR Address: 2C:41:A1:C8:E5:04 (Bose Corporation)
        Reason: Connection terminated by local host (0x02)
```

(Notice the `Authentication Failed` and `Remote User Terminated Connection`)

`journalctl --follow` shows the following when attempting to connect to the headphones:

```
Oct 09 09:33:07 nac44250 bluetoothd[30207]: src/profile.c:ext_connect() Hands-Free Voice gateway failed connect to 2C:41:A1:C8:E5:04: Connection refused (111)
Oct 09 09:33:07 nac442oesn't output anything related it seems.50 bluetoothd[30207]: profiles/audio/avdtp.c:avdtp_connect_cb() connect to 2C:41:A1:C8:E5:04: Connection refused (111)
Oct 09 09:33:09 nac44250 bluetoothd[30207]: profiles/audio/avdtp.c:avdtp_connect_cb() connect to 2C:41:A1:C8:E5:04: Connection refused (111)
```

What I also notice is that the headphones is sometimes advertised as `LE-My Headphones` and sometimes `My Headphones`.

This issue from bluez is probably related: https://github.com/bluez/bluez/issues/953

**Comment by bobvanderlinden** [comment]
I wasn't sure anymore whether my issue is related to NixOS anymore, as I've now tried to use a month-old version of nixpkgs, but got the same results. I upgrade NixOS weekly, so I should've noticed it earlier. I've created a separate issue at bluez: https://github.com/bluez/bluez/issues/973

**Comment by ryuheechul** [comment]
Bluetooth audio quality got affected after I upgraded nixos to the recent one (13th Oct), https://github.com/NixOS/nixpkgs/commit/a3c0b3b21515f74fd2665903d4ce6bc4dc81c77c from this older one (14th Aug), https://github.com/NixOS/nixpkgs/commit/c3aa7b8938b17aebd2deecf7be0636000d62a2b9.

In my case, Bluetooth pairing to my headset itself worked fine but the audio play stuttered and the audio does not sync with video and skips some frames and resyncs briefly and keep repeating the unsync and the resync forever.

I tried to identify which package is exactly affected (looked into the upgrdaed `pipewire`, `wireplumber`, `bluez`), however instead of being able to tell which of version of which package is affected, weirdly fixing a drift in the system time was the solution since every time I fix the system time the problem immediately disappeared.

I don't possess enough knowledge to understand why the system time was the cause and the solution but that's what I experienced and tested in my case non the less.

**Comment by paveloom** [comment]
I've noticed that the Bluetooth device discovery (and consequently, a Bluetooth mouse I own) stopped working after updating from https://github.com/paveloom/nixpkgs/commits/2809d61 to https://github.com/paveloom/nixpkgs/commits/3222e4f7.

Here's the log of the changes to `bluez` that happened in the meantime:

```console
$ git log --oneline --grep bluez 2809d61..3222e4f
3052d8e23003 bluez: add patch for musl 1.2.5
ae51a98646ce bluez: 5.76 -> 5.78 (#341994)
c4ba2c64b4d8 bluez: 5.76 -> 5.78
478bc3b40ccd bluez: python3.pkgs -> python3Packages
eeb076b7eda8 bluez: substitute --replace with --replace-fail (#337280)
b232187bd351 bluez: substitute --replace with --replace-fail
```

So, could the update to the new version have caused this? I tried reverting the commits, but that's too much to recompile.

**Comment by florian-sanders-cc** [comment]
I've been experiencing the same issue for a few days and I think it comes from the last commit that added a patch from VoidLinux:
https://github.com/NixOS/nixpkgs/commit/3052d8e23003c1bb16e5b875ba952079ac34bf54

I found an issue that exactly matches what I'm facing:
https://github.com/void-linux/void-packages/issues/52732

When I try to find devices (using a GUI or CLI, it fails to reconnect to some of devices that were already paired + after 30 secs discoverable devices just vanish and I cannot discover any device until I reboot).

I'm trying to revert back to before the patch was added but I have to rebuild so much stuff to do so. I'll post here if it does fix my issue once I finish building.

**Comment by florian-sanders-cc** [comment]
Alright so I've realized I didn't have to rebuild everything and that I could just build `bluez` in a flake and `nix develop`. 

Turns out it has nothing to do with any of the commits made to `bluez` (for my case, we may all have different issues of course).
However, as stated in the issue I linked within voidlinux + some others I found (https://bbs.archlinux.org/viewtopic.php?id=300398), it turns out the issue is related to the latest linux kernel.

Moving back to linux 6.10 fixed my issues :wink:. If you're on the latest, it may be worth a try to see if it fixes your issues too?

**Comment by 4JX** [comment]
Adding my experience here:
```
» nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11.20241023.2768c7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `""`
 - nixpkgs: `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source`
```
**Misc:** Intel AX2000, GNOME as the Desktop Environment, attempting to pair with a previously paired Sony WH-CH720N.

### Symptoms
I cannot connect or pair through the GNOME bluetooth settings, the screen just hangs on the spinner. Tried on `6.6`, `6.10.2` and `6.11.5`. Logs show:
```
Oct 25 21:58:15 terra .gnome-control-[8110]: Setting up /org/bluez/hci0/dev_ID failed: Timeout was reached
...
Oct 25 21:59:50 terra bluetoothd[1105]: Pair device failed: Timeout (0x08)
(trying again)
Oct 25 22:02:23 terra .gnome-control-[8110]: Setting up /org/bluez/hci0/dev_ID failed: GDBus.Error:org.bluez.Error.AuthenticationRejected: Authentication Rejected
```

After the connection attempt fails `bluetoothctl` still shows `[WH-CH720N]` as though the connection setup has been left in some limbo state. The output of `btmon` is not quite the same as bob's, no explicit auth faileds show up there.

### Workaround
Since my device was already paired, this may have allowed me to bypass some authentication steps. To connect from a disconnected and forgotten state, I used the following commands:
```
sudo bluetoothctl
power on // <--- If bluetooth is off
scan on
[bluetooth]# [NEW] Device DEVICEMAC DEVICENAME // <--- Wait for your device to appear
connect DEVICEMAC
```

For others trying to follow this, there's also `pair DEVICEMAC` to initiate pairing. Not sure how that'll go.

I noticed that sometimes with this method the headphones would be picked up as generic bluetooth audio devices. Turning them off and on again to let them advertise themselves fixes it. Putting them in pairing mode is not needed. 

After doing this once I'm also able to use the GNOME UI to connect to them and it survives a reboot.

Will eventually play around with the `bluez` version patching, but this at least temporarily solves my issue.

**Comment by bobvanderlinden** [comment]
> Edit: I've checked and generations that have issues with the bluetooth are all running on linux kernel `6.11.4`. Upgrading again to latest fixed my issue (`6.11.5`).

That matches with the experiment I did. Switching nixpkgs+bluez during the same boot didn't change anything.

With the latest version of nixpkgs-unstable it also seems to be resolved for me.

**Comment by vkraven** [comment]
I had this issue as well, and it just got "fixed" after a rebuild. 

I'm not sure it's entirely related specifically to the 6.11 kernel, as mine has been pinned to `linux_6_10` on 24.05.  My bluetooth issue was similar to @bobvanderlinden 's with `avdtp_connect_cb(): ... connection refused`, and went away after a `6.10.13` -> `6.10.14` upgrade. Upgrades / downgrades to `bluez` also didn't solve it.

I wonder whether all of us who experienced this issue are on Intel AX2XX chips on our host? It might have been something to do with the `ibt` code in `linux-firmware` (I've experience instability on bluetooth before that was solved with a `linux-firmware` upgrade). 

Alternatively, it could have been fixed by a change to the audio stack (`wireplumber`, `pulseaudio`, `pipewire`, etc.). But I find this less likely because my error was tied to `avdtp`  which presumably kicks in before the audio stack takes over.

**Comment by cician** [comment]
I just upgraded from NixOS 24.05 to 24.11 and BT headphones stopped working for me too. It connects, I can hear sound for a few seconds then it stops and I can't reconnect unless I redo pairing. KDE/pipewire shows them as still connected, but the system log shows errors like this:

```
[  173.299699] input: OPENEAR Duet (AVRCP) as /devices/virtual/input/input25
[  178.523961] Bluetooth: hci0: ACL packet for unknown connection handle 3837
[  332.252774] input: OPENEAR Duet (AVRCP) as /devices/virtual/input/input26
[  337.687566] Bluetooth: hci0: ACL packet for unknown connection handle 3837
[  464.692552] input: OPENEAR Duet (AVRCP) as /devices/virtual/input/input27
[  469.713167] Bluetooth: hci0: ACL packet for unknown connection handle 3837
[  496.066954] Bluetooth: hci0: ACL packet for unknown connection handle 3837
[  514.904226] Bluetooth: hci0: link tx timeout
[  514.904235] Bluetooth: hci0: killing stalled connection 41:42:ff:e3:39:0a
[  544.290349] input: OPENEAR Duet (AVRCP) as /devices/virtual/input/input28
[  549.277843] Bluetooth: hci0: ACL packet for unknown connection handle 3837
[ 1122.569662] input: OPENEAR Duet (AVRCP) as /devices/virtual/input/input29
[ 1127.511346] Bluetooth: hci0: ACL packet for unknown connection handle 3837
[ 1185.083655] Bluetooth: hci0: corrupted SCO packet
[ 1837.749682] perf: interrupt took too long (2512 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
[ 2064.931431] sched: RT throttling activated
[ 2571.966485] perf: interrupt took too long (3155 > 3140), lowering kernel.perf_event_max_sample_rate to 63000
[ 3099.322908] input: OPENEAR Duet (AVRCP) as /devices/virtual/input/input30
[ 3104.563181] Bluetooth: hci0: ACL packet for unknown connection handle 3837

```

The discovery and pairing doesn't seem to be affected in my case.

This is on Linux kernel 6.11.10 and bluez-5.78. On the old system I was already on 6.11.10. I'm on a NixOS flake so I can still boot into the older derivation and confirm that it works well there.
I'm not running LTS kernel only because some of my hardware is not yet supperted there.

I noted two things:

1. When I manage to make it work, the quality sucks compared to before. Making me thing the used codecs changed. So I checked and in fact not all BT modes/codecs are available. I only have "Headset Unit mSBC" on NixOS 24.11, but on NixOS 24.05 I used "High Fidelity Playback" with AAC or SBC codec.

2. If sound is already playing when connecting as long as it continues (just playing a song) then the connection stays on. I can disconnect and reconnect without unpairing and pairing again. Just pausing the song causes it to disconnect within a few seconds. KDE/Pipewire shows it as still connected, but I see it in logs or with bluetoothctl open.

I have MEDIATEK MT7921 802.11ax PCI Express Wireless Network Adapter.

**Comment by cician** [comment]
Just an update on my situation. I updated to Linux 6.12.4, which is the current LTS. Issues persist exactly as on Linux 6.11.10 with my built-in MEDIATEK controller, both disconnecting and codec availability. I've connected a BT adapter dongle and everything works as expected with same headsets. Meaning it's specific to Mediatek driver in the kernel in my case. I had to enable blueman to switch between BT controllers, since I can't do it from usual KDE Plasma UI I use otherwise.

**Comment by cician** [comment]
I found a workaround that works for me. I'm not sure if OP or other commenters here have the same problem as me, but @bobvanderlinden's comment led me to this solution/workaround, at least we may have the same or similar problem.

I've added this to my NixOS config:
`hardware.bluetooth.settings.General.ControllerMode = "bredr";`
It disables bluetooth low energy mode. It's not a perfect solution because it may result in higher power usage, but it's better than not having BT headphones at all.  See [here](https://github.com/bluez/bluez/blob/dfb1ffdc95a00bc06d81a75c11ab5ad2e24d37bf/src/main.conf#L52) for more details.

In summary some possibly useful info about my case, if anyone needs it:
1. It's mediatek specific or at least dependent on the BT controller. It happens with my laptop's built-in WiFi/BT controller, but not with an ASUS USB BT adapter.
2. It's not BT headset specific. I tried two BT headsets and have the exact same behavior.
3. It's something to do with power saving and BT LE mode.
4. It worked well with kernels 6.10 and 6.11. Issues introduced with some changes backported to the 6.11 kernel that I received when upgrading to NixOS 24.11 and/or bluez. I didn't try the 6.6 LTS since I have other hardware that doesn't work there properly (intel sound card AND nvidia GPU). Some info on arch forums and a bluez bug lead me to believe it's the changes in the kernel.

**Comment by leonhma** [comment]
Still happening, now also on 25.05 stable. My bluetooth mouse (Razer Aetheris) fails to connect and enters a connecting - disconnected - connecting - ... loop. It was already paired.
The error message is `Bluetooth: hci0: ACL packet for unknown connection handle 3837`. The error appeared with both 6.6 and 6.15 kernels.

**Comment by eclairevoyant** [comment]
No info present to actually debug this and verify if there's a NixOS issue here. Most likely you'll need to repro and send this upstream, if you're still seeing this on a current kernel.
