### ISSUE TITLE
Applications (gnome related possibly) don't work after update

### ISSUE THREAD

**Issue by radek-stasta** [NixOS/nixpkgs#353990]
### Describe the bug
I am using nixos with flakes and Hyprland desktop. After recent update of nixpkgs (unstable), I don't seem to be able to run some applications. So far that happened to me with nautilus and bottles, so maybe there is connection with gnome specific applications. Running those applications with GSK_RENDERER=gl solves the issue, but I didn't have to do that before. Don't know if this is some nixos change or upstream problem (like hyprland).

### Steps To Reproduce
1. run nautilus

### Expected behavior
Application opens

### Additional context
` rstasta  ~ 
      nautilus
** Message: 11:58:29.302: Connecting to org.freedesktop.Tracker3.Miner.Files
nautilus-application-Message: 11:58:29.302: Failed to initialize display server connection: Cannot invoke method; proxy is for the well-known name org.gnome.Mutter.ServiceChannel without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Gdk-Message: 11:58:29.893: Error 71 (Protocol error) dispatching to Wayland display.

 rstasta  ~ 
      bottles
11:58:31 (INFO) Launching with URI: None
11:58:31 (INFO) [Activate] request received.
11:58:31 (INFO) Bottles Started!
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Gdk-Message: 11:58:31.996: Error 71 (Protocol error) dispatching to Wayland display.`

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20241105.4aa3656`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source`

**Comment by kozm9000** [comment]
Greetings!
Experiencing the same behaviour. Can confirm - works with GSK_RENDERER=gl

**Additional context**
```
nautilus             
** Message: 23:37:57.483: Connecting to org.freedesktop.Tracker3.Miner.Files
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Gdk-Message: 23:37:57.833: Error 71 (Protocol error) dispatching to Wayland display.

nautilus --version

GNOME nautilus 47.0
```

**Metadata**
>     "type": "OS",
>     "result": {
>       "buildID": "24.11pre703931.4aa36568d413",
>       "name": "NixOS",
>       "version": "24.11 (Vicuna)",
>       "versionID": "24.11"
>     }
>     "type": "Kernel",
>     "result": {
>       "architecture": "x86_64",
>       "name": "Linux",
>       "release": "6.6.59",
>       "version": "#1-NixOS SMP PREEMPT_DYNAMIC Fri Nov  1 00:58:34 UTC 2024",
>       "displayVersion": "",
>       "pageSize": 4096
>     }
>     "type": "Display",
>     "result": 
>       {
>         "platformApi": "wayland-global"
>       },
>     "type": "WM",
>     "result": {
>       "processName": "gnome-shell",
>       "prettyName": "Mutter",
>       "protocolName": "Wayland",
>     }
>     "type": "GPU",
>     "result": 
>       {
>         "driver": "nvidia (proprietary) 560.35.03",
>         "name": "GeForce GTX 1050 Ti Mobile",
>         "type": "Unknown",
>         "vendor": "NVIDIA",
>         "platformApi": "DRM (card2)",
>       },
>         "driver": "i915",
>         "name": "UHD Graphics 630",
>         "type": "Integrated",
>         "vendor": "Intel",
>         "platformApi": "DRM (card1)",
>       }
>     ]

**Comment by SrEstegosaurio** [comment]
I'm encountering the same issue with both `easyeffects` and `pavucontrol`. Adding `GSK_RENDERER=gl` does solve the issue.

Maybe related: https://discussion.fedoraproject.org/t/gdk-message-error-71-protocol-error-dispatching-to-wayland-display/127927/1

**Comment by nbCloud91** [comment]
This is an nvidia bug which has been fixed in later nvidia drivers, it resolved after I moved to nvidia beta driver (565).

**Comment by radek-stasta** [comment]
Any info when it will be fixed in stable? It is now month old and it is still not working

**Comment by Herschenglime** [comment]
> Any info when it will be fixed in stable? It is now month old and it is still not working

Looks like a PR just got merged: https://github.com/NixOS/nixpkgs/pull/362162

I imagine it'll take a bit to hit the repos, though

**Comment by Herschenglime** [comment]
Although after manually specifying that driver version, it is still broken in X11 with the same error specified by @chr314.

`GSK_RENDERER=gl` still results in the same issue. For it to launch properly, I had to use
```
GSK_RENDERER=cairo nautilus
```

as suggested by [this stackoverflow post](https://unix.stackexchange.com/a/785348). Hopefully this is fixed soon, but it may be a lingering upstream error with Gnome.

**Comment by yajo** [comment]
https://github.com/NixOS/nixpkgs/issues/353990#issuecomment-2467063091 should not be needed anymore now that https://github.com/NixOS/nixpkgs/pull/363040 is merged.

**Comment by yeldiRium** [comment]
I'm also experiencing the problem on AMD hardware. Nvidia drivers do not apply. Settings GSK_RENDERER=ngl fixes my issues.

**Comment by atimofeev** [comment]
Same issue with Intel iGPU.
Works with `GDK_BACKEND=x11 <app>` or `GSK_RENDERER=cairo <app>`

**Comment by emmanuelrosa** [comment]
https://github.com/NixOS/nixpkgs/issues/358827

**Comment by opsroller** [comment]
Just found this lovely message in GNOME's Gitlab PR's, https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5062

```
 environment.sessionVariables = {
    "GDK_DISABLE" = "gles-api";
  };
```

Fixes most issues.

**Comment by voronind-com** [comment]
AMD GPU same issue with `GDK_BACKEND=wayland`. `GDK_BACKEND=x11` works fine.

**Comment by opsroller** [comment]
> AMD GPU same issue with `GDK_BACKEND=wayland`. `GDK_BACKEND=x11` works fine. Just checked on latest release.
> 
> `"GDK_DISABLE" = "gles-api";` made no effect, but `GSK_RENDERER=cairo` works with GDK_BACKEND=wayland.

I actually went on a debugging spree, to the depths of GTK3/GDK and the bugs are everywhere. The GStreamer stuff is all broken and needs some basic rewrites that offload via Vulkan instead of OpenGL to take advantage of newer hardware. So I gave up and switched out my media player app to VLC. I really wanted a GTK4 / libadwaita based player but oh well.

**Comment by n-riesco** [comment]
I'm still experiencing this issue:
- NixOS 25.05
- Intel graphics card

The `GSK_RENDERER=cairo nautilus` workaround works for me.
