### ISSUE TITLE
apple_sdk's setup hook breaks /usr/bin/git in devshells

### ISSUE THREAD

**Issue by midchildan** [NixOS/nixpkgs#355486]
### Describe the bug
apple_sdk now has a setup hook that sets the environment variable `DEVELOPER_DIR`. This is propagated to devshells through stdenv. When /usr/bin/git from Apple's Xcode Command Line Tools is run in a Nix devshell, it references `DEVELOPER_DIR`, changes its behavior, and fails. Other tools from Xcode Command Line Tools may also be affected.

### Steps To Reproduce
1. Download flake in https://github.com/midchildan/playground/blob/main/2024-11-darwin-devshell/flake.nix
2. Run commands in https://github.com/midchildan/playground/blob/main/2024-11-darwin-devshell/README.md

### Expected behavior
Apple's /usr/bin/git runs normally in a devshell.

### Screenshots
```
❯ git rev-parse HEAD
warning: unhandled Target key DefaultVariant
warning: unhandled Target key SupportedTargets
warning: unhandled Target key VersionMap
warning: unhandled Target key Variants
warning: unhandled Target key DebuggerOptions
warning: unhandled Product key iOSSupportVersion
warning: unhandled Target key DefaultVariant
warning: unhandled Target key SupportedTargets
warning: unhandled Target key VersionMap
warning: unhandled Target key Variants
warning: unhandled Target key DebuggerOptions
warning: unhandled Product key iOSSupportVersion
warning: unhandled Target key DefaultVariant
warning: unhandled Target key SupportedTargets
warning: unhandled Target key VersionMap
warning: unhandled Target key Variants
warning: unhandled Target key DebuggerOptions
warning: unhandled Product key iOSSupportVersion
error: tool 'git' not found
```

### Additional context
I'm not sure if there's a good fix for this. In a typical devshell, `DEVELOPER_DIR` and maybe also `SDKROOT` are probably unnecessary. But in some cases like running `nix develop` against a package, there might be a need. I don't think there's a way to distinguish the two without knowing the user intent.

Furthermore, I used Devenv in my example and easy workarounds like setting `env.DEVELOPER_DIR = ""` or `enterShell = "unset DEVELOPER_DIR"` didn't work because they ran either too early or too late. Both of these cases are in the reproduction code. The workaround that worked was adding a setup hook that unsets the environment variables to stdenv. So maybe something similar can be added to Nixpkgs as `stdenvNoAppleSdkVars`, but there's still a discoverability problem.

```nix
stdenv = pkgs.stdenvAdapters.overrideInStdenv pkgs.stdenvNoCC [
  (pkgs.makeSetupHook { name = "unset-apple-sdk-vars"; } (
    pkgs.writeShellScript "unset-apple-sdk-vars.sh" ''
      unset DEVELOPER_DIR SDKROOT
    ''
  ))
];
```

### Notify maintainers

@reckenrode 

### Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `""`
 - nixpkgs: `/Users/midchildan/.nix-defexpr/50-home-manager/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by reckenrode** [comment]
This is fixed on staging-next.

**Comment by reckenrode** [comment]
> In a typical devshell, DEVELOPER_DIR and maybe also SDKROOT are probably unnecessary

These are used by the new Darwin SDK implementation to locate the SDK. If they are unset, `clang` in nixpkgs will fall back to a default SDK, but it won’t be possible to use a non-default SDK. It may also break other language tooling (like Zig and `bindgen` for Rust). In general, Darwin support in nixpkgs is changing to work more like a native toolchain because that’s what things expect, which means relying on these standard variables and an SDK that is set up more like a native one.

**Comment by reckenrode** [comment]
Also, to explain the issue a bit more. The Darwin stdenv includes `xcrun` now. However, in dev shells, there is a problem when running system binaries. `/usr/bin/git` is a stub that invokes `xcrun git`. `xcrun` in nixpkgs checks `PATH` for `git`, which it will find in `/usr/bin`, which causes an infinite recursion when it invokes `xcrun git` again.

The original fix for that issue was to ignore `/usr/bin`, but that causes issues like this and https://github.com/NixOS/nixpkgs/issues/353875. https://github.com/NixOS/nixpkgs/pull/353893 changes the approach to fall back to the system toolchain when `/usr/bin` is in the `PATH`, allowing `/usr/bin/git` to work as expected.

**Comment by midchildan** [comment]
Thanks for the detailed explanation! I was kind of baffled why something like git was behaving this way. I'll close this issue since it's already fixed.

**Comment by gustavomedeiross** [comment]
Was this issue really fixed? After updating my flake.lock (rev `5e4fbfb6b3de1aa2872b76d49fafc942626e2add`) I still see `error: tool 'git' not found`, but this time without the warnings, e.g. `warning: unhandled Target key DefaultVariant [...]`. My output looks like this:

```
$ git st
error: tool 'git' not found

$ xcrun --find git
error: tool 'git' not found

$ xcrun --find clang
/nix/store/v39c0h6xv6hvki2k1bsyp5n090q8y2bp-clang-wrapper-16.0.6/bin/clang
```

**Comment by reckenrode** [comment]
That commit should have `xcrun` with the fix. If you’re seeing those warnings, you still have the old version somewhere. I made a flake pinned that that commit, and it works for me.

```shell
$ cat flake.nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs?ref=5e4fbfb6b3de1aa2872b76d49fafc942626e2add";

  outputs = { self, nixpkgs }:
  {
    devShells.aarch64-darwin.default = nixpkgs.legacyPackages.aarch64-darwin.mkShell { };
  };
}
$ nix develop
$ command -v xcrun
/nix/store/3a99nvsn1jh7h3vklnd8py5jplls9q41-xcbuild-0.1.1-unstable-2019-11-20-xcrun/bin/xcrun
$ git --version
git version 2.39.5 (Apple Git-154)
$ xcrun --find git
/Applications/Xcode.app/Contents/Developer/usr/bin/git
```

**Comment by reckenrode** [comment]
Are you on macOS 15 or something older? The path to the system toolchain is apparently different on older releases. https://github.com/NixOS/nixpkgs/pull/357132 fixes it for them.

**Comment by gustavomedeiross** [comment]
I was indeed running on macOS 14 - I just updated to Sequoia 15.1, but the problem persists. This is probably related to the fact that I don't have anything installed on `/private/var/select/developer_dir`. However I also don't have anything installed on `/private/var/db/xcode_select_link` 🤔 so there must be something off with my computer, idk. Thanks for the help so far!

**Comment by reckenrode** [comment]
Try using `xcode-select` to restore your Xcode or command-line tool setup. I assume it got wiped out on the OS upgrade.

**Comment by skrhlm** [comment]
> Running
> 
> ```
> sudo xcode-select --reset
> sudo xcode-select --switch /Library/Developer/CommandLineTools
> ```
> 
> fixed the issue for me. Now I have both `/private/var/select/developer_dir` and `/private/var/db/xcode_select_link` on my system, and git is back to normal on my devShells :)

this was the only search result on google for "error: tool 'git' not found" - and your comment solved my issue. thanks.

**Comment by woile** [comment]
I've run those commands and the error `git not found` is gone 💪🏻 . But now the shell fails to open `vim` when `git commit --amend` uses it. Or if I try to open `ipython` from `make` also it isn't able to. Has anyone faced the same issue? I ask here because it might be related.
I get an warning like:
> Vim: Warning: Output is not to a terminal

has anyone faced something similar? thanks 🙏🏻

**Comment by midchildan** [comment]
@woile  Try `DEVELOPER_DIR= git commit`.

There's an issue in https://github.com/NixOS/nixpkgs/issues/358795.

**Comment by cideM** [comment]
The annoying thing about the `DEVELOPER_DIR=` workaround is that you can't just add it to your `.envrc` in some cases. If you're working with `clang` (e.g., through Go linking), you'll get an error:

```text
Multiple conflicting values defined for DEVELOPER_DIR_aarch64_apple_darwin
Existing value is
Attempting to set to /nix/store/2y71rl5mnazwnpwpcq07xx97jl7sy5lh-apple-sdk-11.3 via DEVELOPER_DIR
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by reckenrode** [comment]
I’m not able to reproduce with `DEVELOPER_DIR= nix run github:NixOS/nixpkgs#clang test.c -o test`. The only time I’ve seen that error is when two different role variables (such as `DEVELOPER_DIR` and `DEVELOPER_DIR_FOR_BUILD` resolve to the same suffix salt (e.g., `DEVELOPER_DIR_aarch64_apple_darwin`). That shouldn’t be happening normally.

Does this dev shell add the SDK to `packages`? It needs to be added to `buildInputs`. `packages` maps to `nativeBuildInputs`, which is technically the target packages input for `depsBuildBuild`. It normally doesn’t matter, but this is one of the situations where it does (since the SDK supports different versions in different roles for cross-compilation).

**Comment by antoineco** [comment]
As an additional note, the current setup inside devshells (`nix develop ...`) still prevents the execution of certain stubbed tools provided by Xcode, such as `lldb`.

```console
$ command -v xcrun
/nix/store/3bmh81r1bxb168bb273pa964x4nxv4nr-xcbuild-0.1.1-unstable-2019-11-20-xcrun/bin/xcrun
```
```console
$ xcrun --find lldb
error: tool 'lldb' not found
```
```console
$ command -v lldb
/usr/bin/lldb
```
```console
$ lldb
error: tool 'lldb' not found
```

Outside of the shell, `lldb` works as expected:
```console
$ xcrun --find lldb
/Applications/Xcode.app/Contents/Developer/usr/bin/lldb
```
```console
$ lldb
(lldb)
```

**Comment by reckenrode** [comment]
The fix has not yet landed in master yet. The staging cycle that includes it is still in progress. The progress of the PR can be tracked at https://nixpkgs-tracker.ocfox.me/?pr=359721.

**Comment by rouzwelt** [comment]
> As an additional note, the current setup inside devshells (`nix develop ...`) still prevents the execution of certain stubbed tools provided by Xcode, such as `lldb`.
> 
> $ command -v xcrun
> /nix/store/3bmh81r1bxb168bb273pa964x4nxv4nr-xcbuild-0.1.1-unstable-2019-11-20-xcrun/bin/xcrun
>  $ xcrun --find lldb
> error: tool 'lldb' not found
>  $ command -v lldb
> /usr/bin/lldb
>  $ lldb
> error: tool 'lldb' not found
> Outside of the shell, `lldb` works as expected:
> 
> $ xcrun --find lldb
> /Applications/Xcode.app/Contents/Developer/usr/bin/lldb
>  $ lldb
> (lldb)
> Cross-referencing:
> 
> * [xcrun breaks interactive applications #358795 (comment)](https://github.com/NixOS/nixpkgs/issues/358795#issuecomment-2598552176)

yea I exactly have the same problem with `SetFile` and none of the suggestions above helped so far, need to mention that Im using nixpkgs `master` branch, its master at 2025/03 btw.

anyone got any idea how to tackle this?

**Comment by reckenrode** [comment]
Does `/var/select/developer_dir` exist? If not, do `sudo xcode-select -s <path to>/Xcode.app`.

**Comment by rouzwelt** [comment]
> Does `/var/select/developer_dir` exist? If not, do `sudo xcode-select -s <path to>/Xcode.app`.

inside devshell?

**Comment by reckenrode** [comment]
> > Does `/var/select/developer_dir` exist? If not, do `sudo xcode-select -s <path to>/Xcode.app`.
> 
> inside devshell?

On your system.


> I guess you dont mean inside devshell, but how that is gonna help? I have the same issue with gihtub macos runners for github actions

`xcrun` checks that (and another path), but there are situations where that path does not exist. Running `xcode-select -s` forces it to be created.

**Comment by rouzwelt** [comment]
> > > Does `/var/select/developer_dir` exist? If not, do `sudo xcode-select -s <path to>/Xcode.app`.
> > 
> > 
> > inside devshell?
> 
> On your system.
> 
> > I guess you dont mean inside devshell, but how that is gonna help? I have the same issue with gihtub macos runners for github actions
> 
> `xcrun` checks that (and another path), but there are situations where that path does not exist. Running `xcode-select -s` forces it to be created.

hmm, but is it a good solution when it needs to be done gh macos runners? 
I kinda found a workaround or a fix last night which I can apply at shelhook:
```bash
export PATH=''${PATH//'${pkgs.xcbuild.xcrun}/bin:'/}
unset DEVELOPER_DIR
```
at least this doesnt require a system wide thing.
what do you think?

**Comment by reckenrode** [comment]
> hmm, but is it a good solution when it needs to be done system wide and for gh macos runners?

No. The ideal solution would be to modify `xcrun` to check for the `__xcrun_shim` segment in the binary, but that requires parsing Mach-O, and there’s limited Darwin maintainer bandwidth to make that change at the moment.


> hmm, but is it a good solution when it needs to be done system wide and for gh macos runners? I kinda found a workaround or a fix last night which I can apply at shelhook:
> 
> export PATH=''${PATH//'${pkgs.xcbuild.xcrun}/bin:'/}
> unset DEVELOPER_DIR
> at least this doesnt require a system wide thingi. what do you think?

If you don’t need a nixpkgs toolchain, that’s a pretty common workaround. If you’re using `mkShellNoCC`, you can do the following as well (the SDK is included due to https://github.com/NixOS/nixpkgs/issues/371465). I’ve been using it in a dev shell I set up to use hledger 3.41 and fava.

```nix
mkShellNoCC = pkgs.mkShellNoCC.override {
  stdenv = pkgs.stdenvNoCC.override { extraBuildInputs = [ ]; };
};
```

**Comment by rouzwelt** [comment]
> > hmm, but is it a good solution when it needs to be done system wide and for gh macos runners?
> 
> No. The ideal solution would be to modify `xcrun` to check for the `__xcrun_shim` segment in the binary, but that requires parsing Mach-O, and there’s limited Darwin maintainer bandwidth to make that change at the moment.
> 
> > hmm, but is it a good solution when it needs to be done system wide and for gh macos runners? I kinda found a workaround or a fix last night which I can apply at shelhook:
> > export PATH=''${PATH//'${pkgs.xcbuild.xcrun}/bin:'/}
> > unset DEVELOPER_DIR
> > at least this doesnt require a system wide thingi. what do you think?
> 
> If you don’t need a nixpkgs toolchain, that’s a pretty common workaround. If you’re using `mkShellNoCC`, you can do the following as well (the SDK is included due to [#371465](https://github.com/NixOS/nixpkgs/issues/371465)). I’ve been using it in a dev shell I set up to use hledger 3.41 and fava.
> 
> mkShellNoCC = pkgs.mkShellNoCC.override {
>   stdenv = pkgs.stdenvNoCC.override { extraBuildInputs = [ ]; };
> };

ok thanks for clarification, I guess the shellhook solution works for me atm, but at least I know another solution if I evenr needed it, I guess this can help others as well.

**Comment by seh** [comment]
> If you don’t need a nixpkgs toolchain, that’s a pretty common workaround. If you’re using `mkShellNoCC`, you can do the following as well (the SDK is included due to [#371465](https://github.com/NixOS/nixpkgs/issues/371465)).

Thank you for the suggestion. That got me past bazelbuild/bazel#23111, but then landed me at bazelbuild/bazel#21718.
