### ISSUE TITLE
Build failure: python3Packages.jaxlib-build

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#362120]
## Steps To Reproduce

1. build python312Packages.jaxlib-build on master

## Build log

This is the log of an earlier failure on staging where python312Packages.jax still referred to the build from source.

<details>

<summary>Build Log</summary>

```
>     self._CheckAgainstNumpy(np_fun, jnp_fun, args_maker)

[1m[31mtests/lax_numpy_reducers_test.py[0m:811: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[1m[31mjax/_src/test_util.py[0m:1188: in _CheckAgainstNumpy
    self.assertAllClose(numpy_ans, lax_ans, check_dtypes=check_dtypes,
[1m[31mjax/_src/test_util.py[0m:1109: in assertAllClose
    self.assertArraysAllClose(x, y, check_dtypes=False, atol=atol, rtol=rtol,
[1m[31mjax/_src/test_util.py[0m:1074: in assertArraysAllClose
    _assert_numpy_allclose(x, y, atol=atol, rtol=rtol, err_msg=err_msg)
[1m[31mjax/_src/public_test_util.py[0m:127: in _assert_numpy_allclose
    np.testing.assert_allclose(a, b, **kw, err_msg=err_msg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (<function assert_allclose.<locals>.compare at 0x7ffc9fc81760>, array([[4294967294, 4294967293, 4294967293, 4294967293...4294967294, 4294967290]], dtype=uint32), array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint32))
kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=0', 'strict': False, ...}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
[1m[31mE           AssertionError: [0m
[1m[31mE           Not equal to tolerance rtol=1e-07, atol=0[0m
[1m[31mE           [0m
[1m[31mE           Mismatched elements: 7 / 12 (58.3%)[0m
[1m[31mE           Max absolute difference among violations: 6[0m
[1m[31mE           Max relative difference among violations: inf[0m
[1m[31mE            ACTUAL: array([[4294967294, 4294967293, 4294967293, 4294967293],[0m
[1m[31mE                  [         0,          0,          0,          0],[0m
[1m[31mE                  [         0, 4294967294, 4294967294, 4294967290]], dtype=uint32)[0m
[1m[31mE            DESIRED: array([[0, 0, 0, 0],[0m
[1m[31mE                  [0, 0, 0, 0],[0m
[1m[31mE                  [0, 0, 0, 0]], dtype=uint32)[0m

[1m[31m/nix/store/m39g4rdzilni9qz18901b3cbxwlx49h8-python3-3.12.8/lib/python3.12/contextlib.py[0m:81: AssertionError
[36m[1m=========================== short test summary info ============================[0m
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUnique1[0m - AssertionError: Tuples differ: (3,) != (3, 1)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUnique2[0m - AssertionError: Tuples differ: (2,) != (2, 1, 1)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUnique4[0m - AssertionError: Tuples differ: (3,) != (3, 1)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUniqueSize0[0m - AssertionError: Tuples differ: (4,) != (1, 4)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUniqueSize4[0m - AssertionError: Tuples differ: (4,) != (1, 4)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUniqueSize5[0m - AssertionError: Tuples differ: (1,) != (1, 1)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUniqueSize6[0m - AssertionError: Tuples differ: (3,) != (3, 1)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUniqueSize8[0m - AssertionError: Tuples differ: (4,) != (1, 1, 4)
[31mFAILED[0m tests/lax_numpy_test.py::[1mLaxBackedNumpyTests::testUniqueSize9[0m - AssertionError: Tuples differ: (3,) != (3, 1)
[31mFAILED[0m tests/lax_numpy_test.py::[1mNumpySignaturesTest::testWrappedSignaturesMatch[0m - AssertionError: {'clip': {'np_params': ['a', 'a_min', 'a_max', 'min', 'max'...
[31mFAILED[0m tests/lax_numpy_reducers_test.py::[1mJaxNumpyReducerTests::testCumulativeSum0[0m - AssertionError: 
[31m========== [31m[1m11 failed[0m, [32m25315 passed[0m, [33m9534 skipped[0m[31m in 977.35s (0:16:17)[0m[31m ==========[0m
```

</details>

## Additional context

Perhaps the update to Numpy 2 broke the tests?

## Notify maintainers

@samuela

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by V3ntus** [comment]
Experiencing this on `nixos-unstable`:
```
warning: Git tree '/root/nixos' is dirty
building the system configuration...
warning: Git tree '/root/nixos' is dirty
error: builder for '/nix/store/ny312wicgi2aqvs8j2jv0m3s805lw497-python3.12-jax-0.4.28.drv' failed with exit code 1;
       last 25 log lines:
       >       with np.errstate(invalid='ignore'):
       >         # TODO(phawkins): surprisingly, assert_allclose sometimes reports invalid
       >         # value errors. It should not do that.
       > >       np.testing.assert_allclose(a, b, **kw, err_msg=err_msg)
       > E       AssertionError:
       > E       Not equal to tolerance rtol=1e-07, atol=0
       > E
       > E       Mismatched elements: 7 / 12 (58.3%)
       > E       Max absolute difference among violations: 6
       > E       Max relative difference among violations: inf
       > E        ACTUAL: array([[4294967294, 4294967293, 4294967293, 4294967293],
       > E              [         0,          0,          0,          0],
       > E              [         0, 4294967294, 4294967294, 4294967290]], dtype=uint32)
       > E        DESIRED: array([[0, 0, 0, 0],
       > E              [0, 0, 0, 0],
       > E              [0, 0, 0, 0]], dtype=uint32)
       >
       > jax/_src/public_test_util.py:127: AssertionError
       > =========================== short test summary info ============================
       > FAILED tests/lax_numpy_reducers_test.py::JaxNumpyReducerTests::testCumulativeSum0 - AssertionError:
       > ERROR tests/lax_numpy_test.py - ValueError: matvec: Input operand 0 does not have enough dimensions (has 1,...
       > ERROR tests/lax_numpy_test.py - ValueError: matvec: Input operand 0 does not have enough dimensions (has 1,...
       > ERROR tests/lax_numpy_test.py - ValueError: matvec: Input operand 0 does not have enough dimensions (has 1,...
       > ERROR tests/lax_numpy_test.py - ValueError: matvec: Input operand 0 does not have enough dimensions (has 1,...
       > ===== 1 failed, 22243 passed, 9511 skipped, 4 errors in 3296.32s (0:54:56) =====
       For full logs, run 'nix log /nix/store/ny312wicgi2aqvs8j2jv0m3s805lw497-python3.12-jax-0.4.28.drv'.
error: 1 dependencies of derivation '/nix/store/m9x90jfyw17l1hhn9lhd31i1rhclh1n7-python3.12-nanobind-2.4.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bi5bwgy5padqighxkm7q2c9hdf47vgzh-python3.12-soxr-0.5.0.post1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nppmrps7xhkva537q7hxdjqmnwpa8r38-python3.12-librosa-0.10.2.post1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y3kn0fn2sqlj98ncc77hpim064vmdlx7-beets-2.2.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5pw7v01i94zs0yzj415bqipzcp8pblxz-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h3ca3jjs5d27fz3czdmh1462gcgymhvz-unit-script-beets-import-soulseek-start.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rasqxlp4d5xq5mxr4i45b7bmi742m4sm-nixos-system-unnamed-25.05.20241229.88195a9.drv' failed to build
```

**Comment by antonmosich** [comment]
The build was already fixed in #363130, which hasn't reached `nixos-unstable` yet

**Comment by FliegendeWurst** [comment]
Still applies for the source build, I think

**Comment by samuela** [comment]
is this still an issue on master? we're now on jaxlib v0.5.0. if so please report what architecture you're seeing the build failure on

**Comment by FliegendeWurst** [comment]
It is still an issue for the jaxlib-build variant, which is still on 0.4.28 on master. I have not tried updating it to 0.5.0 yet.
