### ISSUE TITLE
beets: version from command is 1.6.1, not 2.0.0

### ISSUE THREAD

**Issue by jwillikers** [NixOS/nixpkgs#362527]
## Describe the bug

```
$ result/bin/beet --version
beets version 1.6.1
Python version 3.12.7
plugins: chroma
```

## Steps To Reproduce

1. `nix build .#beets`
2. `result/bin/beet --version`

## Expected behavior

Expected the version of the package, `2.0.0`.

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.10-300.fc41.x86_64, Fedora Linux, 41.20241205.0 (Sway Atomic), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: aarch64-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/jordan/.config/nix/nix.conf:/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/lknx1arna0x37dg61ixsjbdlwcy9dvld-lix-2.91.1/share`
 - nixpkgs: `/nix/store/w66xaybnxjf5zhxapxs3pd3zp7gxk9dw-source`
```

## Notify maintainers

@aszlig @doronbehar @lovesegfault @pjones

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
This is an upstream issue. I installed beets 2.0.0 on openSUSE and got the following output:

```
$ beet --version 
beets version 1.6.1
Python version 3.11.10
no plugins loaded
```

**Comment by jwillikers** [comment]
It would be great if we could patch it. It's blocking me from packaging `beets-audible` which requires `beets` 2.0.0.

**Comment by chewblacka** [comment]
Unless I'm mistaken I *think* this issue upstream may deal with it? If so proposed fix is in there.

https://github.com/beetbox/beets/issues/5539

**Comment by jwillikers** [comment]
Looks like it should be fixed in #358086

**Comment by doronbehar** [comment]
Fixed by #358086. Thanks for pinging this issue.

**Comment by chewblacka** [comment]
With #358086 I get:

```
./result/bin/beet --version
beets version 2.1.0
Python version 3.12.7
no plugins loaded
```

**Comment by doronbehar** [comment]
Yes, the upstream issue is still present:

- https://github.com/beetbox/beets/issues/5539

I've updated this issue's title to match the current state of things, but I'll keep the issue closed.

**Comment by snejus** [comment]
I am to blame for this hiccup, apologies! It's addressed [in this PR](https://github.com/beetbox/beets/pull/5536) and should hopefully not happen again.
