### ISSUE TITLE
Package request: Powershell

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#36269]
## Issue description
Despite being open-sourced, only pash is in the repos, even though Powershell is available for Linux.

**Comment by yrashk** [comment]
Done in #41242

**Comment by abhi18av** [comment]
@yrashk , could you please let me know how can I install `powershell` in `NixOS`.

I keep running into 

```
[vagrant@nixos:~/dhall-nix]$ nix-env -i powershell
error: selector 'powershell' matches no derivations

```

**Comment by Mic92** [comment]
```
nix-shell -p powershell --command 'pwsh'
```

**Comment by abhi18av** [comment]
@Mic92 Hey, I tried this but there's an error still 

```
[vagrant@nixos:~]$ nix-shell -p powershell --command 'pwsh'
error: undefined variable 'powershell' at (string):1:94
(use '--show-trace' to show detailed location information)

```

Is there any other way I could get it to work ?

**Comment by Mic92** [comment]
You need nixpkgs-unstable. It is not available in 18.03.

**Comment by Mic92** [comment]
You need the unstable channel: https://nixos.org/nix/manual/#sec-channels

**Comment by abhi18av** [comment]
Ah, I see.

Since that time, I have resolved the issue. Thanks for your answer :)
