### ISSUE TITLE
Settings button doesn't work in GSConnect extension interface (GNOME Extensions App)

### ISSUE THREAD

**Issue by bittner** [NixOS/nixpkgs#363724]
## Describe the bug

Pressing the Settings button in the GSConnect extension interface in the [GNOME Extensions App](https://apps.gnome.org/Extensions/) has no effect.

## Steps To Reproduce

1. Start the [GNOME Extensions App](https://apps.gnome.org/Extensions/)
2. Open the GSConnect extension interface
3. Press the Settings button

## Expected behavior

The GSConnect settings dialog opens.

(Note: The dialog opens normally via the GNOME system tray > Mobile Devices > Mobile Settings.)

## Additional context

See https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1807#issuecomment-2481319983 for a related issue.

## System Info

- OS: NixOS 24.11 (Vicuna)
- GNOME / GNOME Shell: 47.0
- gnome-extensions / gnome-extensions-app: 47.0
- GSConnect: 58

## Notify maintainers

@jtojnar
@babbaj
@doronbehar

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
Thanks for reporting. I can reproduce and see the following in the journal:

```
Dec 09 21:26:14 nixos gjs[2504]: JS ERROR: Error: Requiring Gdk, version 3.0: Typelib file for namespace 'Gdk', version '3.0' not found
                                 require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
                                 @gi://Gdk:3:25
Dec 09 21:26:14 nixos gjs[2504]: Module file:///run/current-system/sw/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences threw an exception
```

This is a Nixpkgs packaging bug. Since we do not have FHS, we need to patch `preferences.js` to insert the path to typelib path explicitly.

**Comment by doronbehar** [comment]
@jtojnar I don't experience this issue, perhaps because my desktop session has an `$XDG_DATA_DIRS` that includes the correct path for this Gdk typelib?

<details><summary> Here are my `$XDG_DATA_DIRS`</summary>

```
/nix/store/994xi4i3mn2212pc9z860y6fzg52yidw-shared-mime-info-2.4/share
/nix/store/lhgy3736lcxfilbqyqss4sfyvd3m27ls-gnome-shell-47.1/share
/nix/store/p5nz6gdblng41fiqqb7z88l119dc9v56-gsettings-desktop-schemas-47.1/share/gsettings-schemas/gsettings-desktop-schemas-47.1
/nix/store/jbck0ahim6cbjjzl1wmrch5inhbhkkra-gtk4-4.16.3/share/gsettings-schemas/gtk4-4.16.3
/nix/store/jm91z9firz48bka6i1lzlf4ldg3dv5iw-gnome-keyring-46.2/share/gsettings-schemas/gnome-keyring-46.2
/nix/store/jafg82h0x96756am4nl5w52v7avbqf4c-mutter-47.1/share/gsettings-schemas/mutter-47.1
/nix/store/cxpv2dcv81f1kcgk7yvb967j07ziy5b9-evolution-data-server-3.54.1/share/gsettings-schemas/evolution-data-server-3.54.1
/nix/store/myw887ziq1j5431d5zxx22c49ww0fxwz-gdm-47.0/share/gsettings-schemas/gdm-47.0
/nix/store/ahw5bb4z7cd7nm8cfr14wbk459mspvsl-gnome-clocks-47.0/share/gsettings-schemas/gnome-clocks-47.0
/nix/store/wkcrggr5f1nbnw2w4fnyvi5nm5pmnx2q-ibus-1.5.31/share/gsettings-schemas/ibus-1.5.31
/nix/store/sv8x05vbi1jhadpx73dnv3raynlcbxh4-gnome-settings-daemon-47.1/share/gsettings-schemas/gnome-settings-daemon-47.1
/nix/store/mhp5jkwqgyz0s7klvpl23x3axgvn6msm-pipewire-1.2.6/share/gsettings-schemas/pipewire-1.2.6
/nix/store/hs2xyq4s1868fcabcfnaik733lb0p50n-libgweather-4.4.4/share/gsettings-schemas/libgweather-4.4.4
/nix/store/79hcwyipm640qah964b69x1xga5i1lrz-libnma-1.10.6/share/gsettings-schemas/libnma-1.10.6
/nix/store/lhgy3736lcxfilbqyqss4sfyvd3m27ls-gnome-shell-47.1/share/gsettings-schemas/gnome-shell-47.1
/nix/store/mqxa5a0l9cfpkj6pyx861lpd1ig221pb-gnome-mimeapps/share
/nix/store/11s4ivs86p0s8idhj8cnr1sfw8s93g70-desktops/share
/home/doron/.local/share/flatpak/exports/share
/var/lib/flatpak/exports/share
/home/doron/.nix-profile/share
/nix/profile/share
/home/doron/.local/state/nix/profile/share
/etc/profiles/per-user/doron/share
/nix/var/nix/profiles/default/share
/run/current-system/sw/share
/nix/store/lhgy3736lcxfilbqyqss4sfyvd3m27ls-gnome-shell-47.1/share/gsettings-schemas/gnome-shell-47.1
/nix/store/drb23knbdal3j1ha28aj4hw67c9rfm53-gnome-shell-extensions-47.1/share/gsettings-schemas/gnome-shell-extensions-47.1
/nix/store/xwc8raa4mwi6rsba9qmd86q668r0l6hc-gnome-session-47.0.1/share
/nix/store/p5nz6gdblng41fiqqb7z88l119dc9v56-gsettings-desktop-schemas-47.1/share/gsettings-schemas/gsettings-desktop-schemas-47.1
/nix/store/vbw9c3pvwli5iidik8dddgz423wr1h18-gtk+3-3.24.43/share/gsettings-schemas/gtk+3-3.24.43
/nix/store/sv8x05vbi1jhadpx73dnv3raynlcbxh4-gnome-settings-daemon-47.1/share/gsettings-schemas/gnome-settings-daemon-47.1
/nix/store/xwc8raa4mwi6rsba9qmd86q668r0l6hc-gnome-session-47.0.1/share/gsettings-schemas/gnome-session-47.0.1
/nix/store/lhgy3736lcxfilbqyqss4sfyvd3m27ls-gnome-shell-47.1/share
```
</details>

I also noticed that this `@typelibPath`:

https://github.com/NixOS/nixpkgs/blob/80643438112fae873869b4c6b74a85ac68e803c4/pkgs/desktops/gnome/extensions/gsconnect/fix-paths.patch#L14-L21

Doesn't get replaced by the `substituteAll`:

https://github.com/NixOS/nixpkgs/blob/80643438112fae873869b4c6b74a85ac68e803c4/pkgs/desktops/gnome/extensions/gsconnect/default.nix#L38-L41

**Comment by jtojnar** [comment]
@doronbehar Good catch, looks like it as forgotten in https://github.com/NixOS/nixpkgs/pull/269668. cc @kranich

**Comment by doronbehar** [comment]
Fix is available in:

- https://github.com/NixOS/nixpkgs/pull/363911 .

I wonder if `substituteInPlace --subst-var-by` should fail if the substitution does nothing, like `--replace-fail`.

**Comment by doronbehar** [comment]
@bittner please reopen if the above PR hasn't fixed the issue.

**Comment by doronbehar** [comment]
> I did a `nix flake update` and a `nixos-rebuild switch`

That PR probably hasn't reached the `nixos-unstable` branch which you are probably using. See:

https://nixpk.gs/pr-tracker.html?pr=363911

Could you please verify that by building `gnomeExtensions.gsconnect` from the exact same Nixpkgs revision, and check the contents of `result/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/__nix-prepend-search-paths.js`?

**Comment by bjornfor** [comment]
> > I did a `nix flake update` and a `nixos-rebuild switch`
> 
> That PR probably hasn't reached the `nixos-unstable` branch which you are probably using. See:
> 
> https://nixpk.gs/pr-tracker.html?pr=363911
> 
> Could you please verify that by building `gnomeExtensions.gsconnect` from the exact same Nixpkgs revision, and check the contents of `result/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/__nix-prepend-search-paths.js`?

I rebuilt my system with this PR backported to release-24.11 and see the fixed `.../__nix-prepend-search-paths.js` file, but gnome-settings-app still fails to do anything when I navigate to GSConnect -> hamburger menu -> Settings.

I get the same error as @jtojnar in `journalctl -f`:

```
Dec 16 16:16:01 whitetip gjs[6554]: JS ERROR: Error: Requiring Gdk, version 3.0: Typelib file for namespace 'Gdk', version '3.0' not found
                                    require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
                                    @gi://Gdk:3:25
Dec 16 16:16:01 whitetip gjs[6554]: Module file:///run/current-system/sw/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences threw an exception
```

**Comment by jtojnar** [comment]
Oh, looks like the the `prefs.js` invokes a separate program:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/ab119d9d3e273de9f9813eb9b1449198ce2dcd00/src/prefs.js#L29

So we need to also patch https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/v58/src/gsconnect-preferences

Or we could even probably wrap that.

**Comment by doronbehar** [comment]
Fix is in:

- https://github.com/NixOS/nixpkgs/pull/365869

Only tested it builds, have no idea if it fixes the issue. Please help by testing this.

**Comment by Janov911** [comment]
I can confirm it no longer works on Nixos 26.05 (2.34.8). The settings window does not appear when selecting it in the interface.

**Comment by doronbehar** [comment]
@Janov911 please open a new issue with all the relevant details you can provide.

**Comment by Janov911** [comment]
Will do, as soon as I am back in the office I'll dump the logs and open a new issue, thx

**Comment by bittner** [comment]
I can confirm that, too! 💣

And the behavior is interesting: While in the Quick Settings menu the "Mobile Settings" item opens the settings dialog normally, clicking on the <kbd>⚙️ Settings</kbd> button in the [Extensions](https://apps.gnome.org/it/Extensions/) app ➜ GSConnect ➜ <kbd>⋮</kbd> seems to _attempt_ to open a dialog (the dock flickers), but ultimately fails.

**Comment by bjornfor** [comment]
And please link to the new issue here, so that interested parties can follow. (Thanks!)

**Comment by Janov911** [comment]
will do of course
