### ISSUE TITLE
Build failure: linuxKernel.packages.linux_6_13.cpupower

### ISSUE THREAD

**Issue by flandweber** [NixOS/nixpkgs#375865]
### Nixpkgs version

- Stable (24.11)

### Steps to reproduce

`nix build github:nixos/nixpkgs/nixos-24.11#linuxKernel.packages.linux_6_13.cpupower`

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

https://hydra.nixos.org/build/286311724

### Relevant log output

```console
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/slb0xw3a6q9jkb964nx5d2r4b2341h14-linux-6.13.tar.xz
source root is linux-6.13
setting SOURCE_DATE_EPOCH to timestamp 1737330705 of file linux-6.13/virt/lib/irqbypass.c
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
applying patch /nix/store/mnlqwys9dxznjcvq4w3s0435s9ql8qv8-bridge-stp-helper.patch
patching file net/bridge/br_private.h
Hunk #1 succeeded at 51 with fuzz 2 (offset 12 lines).
applying patch /nix/store/mbz5gln1q4swlzmqs2399br98qjif9kn-request-key-helper.patch
patching file security/keys/request_key.c
Hunk #1 succeeded at 117 (offset 3 lines).
applying patch /nix/store/23728y7zgh1jb55kpwxv5qnjbq0ykca6-randstruct-provide-seed-5.19.patch
patching file scripts/gen-randstruct-seed.sh
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: -j8 SHELL=/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash CROSS= CC=cc LD=cc
/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash: line 1: which: command not found
Makefile:222: "Install xgettext to extract translatable strings."
/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash: line 1: which: command not found
Makefile:231: "Install msgfmt to generate binary message catalogs."
/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash: line 1: which: command not found
Makefile:241: "Install msgmerge to merge translations."
  CC       lib/cpufreq.o
  CC       lib/cpupower.o
  CC       lib/cpuidle.o
  CC       lib/acpi_cppc.o
  CC       lib/powercap.o
  CC       utils/helpers/amd.o
  CC       utils/helpers/msr.o
  CC       utils/helpers/sysfs.o
  CC       utils/helpers/misc.o
  CC       utils/helpers/cpuid.o
  CC       utils/helpers/pci.o
  CC       utils/helpers/bitmask.o
  CC       utils/idle_monitor/nhm_idle.o
  CC       utils/idle_monitor/snb_idle.o
  CC       utils/idle_monitor/hsw_ext_idle.o
  CC       utils/idle_monitor/amd_fam14h_idle.o
  CC       utils/idle_monitor/cpuidle_sysfs.o
  CC       utils/idle_monitor/mperf_monitor.o
  CC       utils/idle_monitor/cpupower-monitor.o
  CC       utils/cpupower.o
  CC       utils/idle_monitor/rapl_monitor.o
  CC       utils/cpufreq-info.o
  CC       utils/cpufreq-set.o
  CC       utils/cpupower-set.o
  CC       utils/cpupower-info.o
  CC       utils/cpuidle-info.o
  CC       utils/cpuidle-set.o
  CC       utils/powercap-info.o
  LD       libcpupower.so.0.0.1
make[1]: Entering directory '/build/linux-6.13/tools/power/cpupower/bench'
  CC       main.o
  CC       parse.o
  CC       system.o
  CC       benchmark.o
  CC       cpupower
  CC       cpufreq-bench
make[1]: Leaving directory '/build/linux-6.13/tools/power/cpupower/bench'
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
install flags: -j8 SHELL=/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash CROSS= CC=cc LD=cc bash_completion_dir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/bash-completion/completions bindir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/bin confdir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/etc docdir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/doc/cpupower includedir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/include libdir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/lib localedir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale mandir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man sbindir=/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/sbin install
/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash: line 1: which: command not found
Makefile:222: "Install xgettext to extract translatable strings."
/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash: line 1: which: command not found
Makefile:231: "Install msgfmt to generate binary message catalogs."
/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash: line 1: which: command not found
Makefile:241: "Install msgmerge to merge translations."
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -d /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/lib
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -d /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/bin
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower.1
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -d /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale
cp -fpR ./libcpupower.so* /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/lib/
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c ./cpupower /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/bin
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-frequency-set.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-frequency-set.1
make[1]: Entering directory '/build/linux-6.13/tools/power/cpupower/bench'
make[1]: 'cpufreq-bench' is up to date.
make[1]: Leaving directory '/build/linux-6.13/tools/power/cpupower/bench'
for HLANG in de fr it cs pt ka zh_CN; do \
	echo '/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo'; \
	/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo; \
done;
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -d /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/include
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-frequency-info.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-frequency-info.1
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -d /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/bash-completion/completions
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install: cannot stat './po/de.gmo': No such file or directory
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 lib/cpufreq.h /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/include/cpufreq.h
make[1]: Entering directory '/build/linux-6.13/tools/power/cpupower/bench'
mkdir -p //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/sbin
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-idle-set.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-idle-set.1
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install: cannot stat './po/fr.gmo': No such file or directory
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 cpupower-completion.sh '/nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/bash-completion/completions/cpupower'
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 lib/cpuidle.h /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/include/cpuidle.h
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install: cannot stat './po/it.gmo': No such file or directory
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo
mkdir -p //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/bin
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-idle-info.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-idle-info.1
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install: cannot stat './po/cs.gmo': No such file or directory
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 lib/powercap.h /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/include/powercap.h
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo
mkdir -p //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/doc/cpupower
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-set.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-set.1
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install: cannot stat './po/pt.gmo': No such file or directory
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install: cannot stat './po/ka.gmo': No such file or directory
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D ./po/$HLANG.gmo /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/locale/$HLANG/LC_MESSAGES/cpupower.mo
mkdir -p //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/etc
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-info.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-info.1
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install: cannot stat './po/zh_CN.gmo': No such file or directory
make: *** [Makefile:308: install-gmo] Error 1
make: *** Waiting for unfinished jobs....
install -m 755 .//cpufreq-bench //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/sbin/cpufreq-bench
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-monitor.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-monitor.1
install -m 755 cpufreq-bench_plot.sh //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/bin/cpufreq-bench_plot.sh
/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin/install -c -m 644 -D man/cpupower-powercap-info.1 /nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/man/man1/cpupower-powercap-info.1
install -m 644 README-BENCH //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/doc/cpupower/README-BENCH
install -m 755 cpufreq-bench_script.sh //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/share/doc/cpupower/cpufreq-bench_script.sh
install -m 644 example.cfg //nix/store/sn3jp2lsjg3c59jmmdk4izxv0fsn46dp-cpupower-6.13/etc/cpufreq-bench.conf
make[1]: Leaving directory '/build/linux-6.13/tools/power/cpupower/bench'
```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.10, NixOS, 24.11 (Vicuna), 24.11.20250119.107d5ef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/sbnwhhx7zjp45n53bkmnj4whg79aw8pq-source`

### Notify maintainers

no maintainer
---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+build+failure%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by unclechu** [comment]
I didn’t test it further yet, but this package at least fix made it build successfully:

```
    boot.kernelPackages = pkgs.linuxPackages_latest.extend (lpFinal: lpPrev: {
      cpupower = lpPrev.cpupower.overrideAttrs (old: {
        nativeBuildInputs = (old.nativeBuildInputs or []) ++ [ pkgs.which ];
        makeFlags = (old.makeFlags or []) ++ [ "INSTALL_NO_TRANSLATIONS=1" ];
      });
    });
```

**Comment by flandweber** [comment]
so this seems related: https://github.com/NixOS/nixpkgs/pull/375631

**Comment by unclechu** [comment]
With the fix I showed above NixOS 24.11 also boots fine and `cpupower` utility seems to work just fine too.

**Comment by fpletz** [comment]
Fixed #376078.

**Comment by flandweber** [comment]
> Fixed [#376078](https://github.com/NixOS/nixpkgs/pull/376078).

As a matter of fact, the build failiure did not seem to be fixed through the [backport of the mentioned pull request](https://github.com/NixOS/nixpkgs/pull/376651) on `nixos-24.11`.
```
nix build github:nixos/nixpkgs?rev=1ab3373f153b684a08e714f42fd38a42350c4272#linuxKernel.packages.linux_6_13.cpupower
``` 
(with 1ab3373f153b684a08e714f42fd38a42350c4272 being the merge commit of the pr) still fails.

**Comment by flandweber** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/375631
