### ISSUE TITLE
mcpelauncher-qt: Cant play multiplayer world

### ISSUE THREAD

**Issue by TheHyperZtar** [NixOS/nixpkgs#380493]
### Nixpkgs version

- Unstable (25.05)

### Describe the bug

I tried to play a multiplayer world with friends but it didn't appear, I tried to send invites but those wont work too

The flatpak version doesn't have this issues

### Steps to reproduce

Open mcpe, open a world, friends can't connect

### Expected behaviour

The multiplayer works

### Relevant log output

```console

```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.13.1, NixOS, 25.05 (Warbler), 25.05.20250204.799ba5b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.12`
 - nixpkgs: `/nix/store/k8nkf470zpidpa5nh76lh2x6rxfzpwa4-source`

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

**Comment by Aleksanaa** [comment]
Could you test https://github.com/NixOS/nixpkgs/pull/388240?

**Comment by Aleksanaa** [comment]
I see. It's because the flatpak version is still packaging https://github.com/minecraft-linux/msa-manifest (https://github.com/flathub/io.mrarm.mcpelauncher/blob/master/io.mrarm.mcpelauncher.json#L91-L123), but it's said to be no longer needed in newer minecraft versions:

> Xbox live integration of Minecraft Bedrock 1.16.20 and later is mostly handled inside the native game binary itself (official Xbox Authentication Library) and no longer requires this project.

**Comment by TheHyperZtar** [comment]
This doesn't happen in the flatpak, I tried to connect using a phone in the same network

**Comment by Aleksanaa** [comment]
Could you try to grab some logs somewhere? Also @Morxemplum @phanirithvij

**Comment by TheHyperZtar** [comment]
I couldn't grab any logs, neither the nix package or flatpak

**Comment by Morxemplum** [comment]
> Could you try to grab some logs somewhere? Also [@Morxemplum](https://github.com/Morxemplum) [@phanirithvij](https://github.com/phanirithvij)

Hm. Interesting. Perhaps this is the bug that is being referred to with the latest mcpelauncher update?

But yeah if you need to get logs, make sure that you are running the client on the terminal by running the following command

`mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.21.62.01`. Or of course, replace the version number with one you have installed.

**Comment by TheHyperZtar** [comment]
I got the logs

[log.txt](https://github.com/user-attachments/files/19176336/log.txt)

**Comment by Morxemplum** [comment]
So from what I'm reading from the logs, it seems like there's something happening with the web sockets that are forcing them to close the connection. 

Seeing as the [flatpak](https://flathub.org/apps/io.mrarm.mcpelauncher) has *already* been updated to use 1.2.0, that probably means the error you're experiencing with the Nix package is the bug that was found in 1.1.2 and has been fixed in 1.2.0; you've said that you don't experience this problem with the flatpak.

With this deduction, and the pull request updating mcpelauncher 1.2.0 being merged, I'd consider this issue FIXED.

If this issue can be reproduced in the updated Nixpkg, then I think it's safe to say this issue can be closed.

**Comment by TheHyperZtar** [comment]
I was on 1.2.0, the bug was on both versions

**Comment by Frostlefog** [comment]
this bug persist for me even in the new [1.3.0](https://github.com/NixOS/nixpkgs/pull/404963)

**Comment by Aleksanaa** [comment]
@phanirithvij Could you help with this?

**Comment by phanirithvij** [comment]
I tried for a bit but I am not sure how to debug it.

**Comment by Frostlefog** [comment]
I'm still facing this issue, now with 1.4.0 there is no audio

**Comment by jrcarl624** [comment]
Same here

**Comment by Morxemplum** [comment]
Oh, did they finally fix the audio issues with the SDL3 media library? Well, if that is the case, perhaps we can undo some of my patches regarding switching to GLFW and the PulseAudio server.

Does the game run natively under Wayland through SDL3? The primary reason I switched to use GLFW is to not use XWayland and experience the bugs that come with it.

**Comment by Frostlefog** [comment]
I don't know if its wayland or not, but i don't see issues in niri. The build intructions says that using sdl3 makes it use wayland

**Comment by Frostlefog** [comment]
Last time I build the game with only that line it told me an error when trying to run it. I had to use steam-run but maybe it was just me running the game directly from the result folder

**Comment by arexon** [comment]
Yeah, I still encounter the same error.

**Comment by arexon** [comment]
Opened a PR for fixing audio in #457014.

**Comment by Frostlefog** [comment]
The fix works. Also I can now confirm that adding msa doesn't do anything to fix the multiplayer issue

**Comment by phanirithvij** [comment]
I can't launch the game on xfce to even see if audio is working with the new PR. Logs have nothing much. I will strace and maybe find/file a bug.
