### ISSUE TITLE
Build failure: lldb_14

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#381880]
### Nixpkgs version

- Unstable (25.05)

### Steps to reproduce

`nix-shell -p lldb_14`

### Can Hydra reproduce this build failure?

The last build job was manually cancelled.

### Link to Hydra build job

https://hydra.nixos.org/build/289601669

### Relevant log output

```console
...
-- Installing: /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb
-- Installing: /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldbIntelFeatures.so.14
-- Installing: /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldbIntelFeatures.so
-- Up-to-date: /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldbIntelFeatures.so.14
-- Up-to-date: /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldbIntelFeatures.so
-- Installing: /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-instr
-- Installing: /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-vscode
-- Installing: /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-server
Running phase: fixupPhase
shrinking RPATHs of ELF executables and libraries in /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6
shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-argdumper
shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-instr
shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-vscode
shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-server
shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/.lldb-wrapped
checking for references to /build/ in /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6...
patching script interpreter paths in /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6
stripping (with command strip and flags -S -p) in  /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin
shrinking RPATHs of ELF executables and libraries in /nix/store/658ygqrlwzfbxym9kayqmrfb21yb3ws8-lldb-14.0.6-dev
checking for references to /build/ in /nix/store/658ygqrlwzfbxym9kayqmrfb21yb3ws8-lldb-14.0.6-dev...
patching script interpreter paths in /nix/store/658ygqrlwzfbxym9kayqmrfb21yb3ws8-lldb-14.0.6-dev
shrinking RPATHs of ELF executables and libraries in /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib
shrinking /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldb.so.14.0.6
shrinking /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldbIntelFeatures.so.14
checking for references to /build/ in /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib...
patching script interpreter paths in /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib
stripping (with command strip and flags -S -p) in  /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib
rewriting symlink /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/share/vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode to be relative to /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6
ERROR: noBrokenSymlinks: the symlink /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/python3.12/site-packages/lldb/lldb-argdumper points to a missing target /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/bin/lldb-argdumper
ERROR: noBrokenSymlinks: found 1 dangling symlinks and 0 reflexive symlinks
error: builder for '/nix/store/kg6bbfa13kw3pi0wzadlhh3jm9lyn3b7-lldb-14.0.6.drv' failed with exit code 1;
       last 25 log lines:
       > -- Installing: /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-instr
       > -- Installing: /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-vscode
       > -- Installing: /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-server
       > Running phase: fixupPhase
       > shrinking RPATHs of ELF executables and libraries in /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6
       > shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-argdumper
       > shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-instr
       > shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-vscode
       > shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/lldb-server
       > shrinking /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin/.lldb-wrapped
       > checking for references to /build/ in /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6...
       > patching script interpreter paths in /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6
       > stripping (with command strip and flags -S -p) in  /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/bin
       > shrinking RPATHs of ELF executables and libraries in /nix/store/658ygqrlwzfbxym9kayqmrfb21yb3ws8-lldb-14.0.6-dev
       > checking for references to /build/ in /nix/store/658ygqrlwzfbxym9kayqmrfb21yb3ws8-lldb-14.0.6-dev...
       > patching script interpreter paths in /nix/store/658ygqrlwzfbxym9kayqmrfb21yb3ws8-lldb-14.0.6-dev
       > shrinking RPATHs of ELF executables and libraries in /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib
       > shrinking /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldb.so.14.0.6
       > shrinking /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/liblldbIntelFeatures.so.14
       > checking for references to /build/ in /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib...
       > patching script interpreter paths in /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib
       > stripping (with command strip and flags -S -p) in  /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib
       > rewriting symlink /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6/share/vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode to be relative to /nix/store/a6j3rrig42wkhy1vxipkd7mfvfk0g6nz-lldb-14.0.6
       > ERROR: noBrokenSymlinks: the symlink /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/lib/python3.12/site-packages/lldb/lldb-argdumper points to a missing target /nix/store/cp8qzly18x4dncza6a7z6kxhvs3v9000-lldb-14.0.6-lib/bin/lldb-argdumper
       > ERROR: noBrokenSymlinks: found 1 dangling symlinks and 0 reflexive symlinks
       For full logs, run 'nix log /nix/store/kg6bbfa13kw3pi0wzadlhh3jm9lyn3b7-lldb-14.0.6.drv'.
```

### Additional context

Same error when running `nix-shell -p lldb`.

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.11, Athena OS, 25.05 (Warbler), 25.05beta743381.825479c345a7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+build+failure%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by paparodeo** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/380775

**Comment by HirschBerge** [comment]
Can confirm there is still this build failure **after** #380775

**Comment by paparodeo** [comment]
> Can confirm there is still this build failure **after** [#380775](https://github.com/NixOS/nixpkgs/pull/380775)

https://github.com/NixOS/nixpkgs/pull/380775 removes the `lib` output and the log in this issue shows that the `lib` output still exists and therefor doesn't contain the fix.

**Comment by HirschBerge** [comment]
https://nixpk.gs/pr-tracker.html?pr=380775 states it has been merged into unstable for a long time, but on a fresh update the issue persists. So either the PR doesn't actually fix it, or the tracker is wrong

**Comment by paparodeo** [comment]
> https://nixpk.gs/pr-tracker.html?pr=380775 states it has been merged into unstable for a long time, but on a fresh update the issue persists. So either the PR doesn't actually fix it, or the tracker is wrong

or you're wrong. seems fine on hydra: https://hydra.nixos.org/build/289199825

**Comment by Shawn8901** [comment]
The bump build on nixos-unstable was 6h ago. Yesterday I was still Cherry-Picking the fix into my fork (and it was building afterwards). The bump build in hydra was included here (https://hydra.nixos.org/build/289445832) but eval had fails, so it did not update the channel)
Sincle the latest eval Hydra seems also to be happy with lldb_14 https://hydra.nixos.org/build/289443965 .

So you might want to double check if you had really the commit included I have doubts, as you stated "long time ago" which has been 2h old when you wrote the comment.

**Comment by D3vil0p3r** [comment]
It works. I close the issue.
