### ISSUE TITLE
yt-dlp: impersonation with curl-cffi not working (again?)

### ISSUE THREAD

**Issue by jgarvin** [NixOS/nixpkgs#402179]
### Nixpkgs version

- Stable (24.11)

### Describe the bug

yt-dlp’s impersonation feature does not work. [This old issue](https://github.com/NixOS/nixpkgs/issues/353882) suggests this might be a recurring issue; I opened a new issue because that one is closed as fixed. It doesn't appear to work on stable (24.11) or unstable (25.05). 

### Steps to reproduce

```
$ nix-shell -p yt-dlp
$ yt-dlp --list-impersonate-targets
[info] Available impersonate targets
Client    OS   Source
--------------------------------------------
Edge      -    curl_cffi (unavailable)
Firefox   -    curl_cffi>=0.10 (unavailable)
Safari    -    curl_cffi (unavailable)
Chrome    -    curl_cffi (unavailable)
```

### Expected behaviour

The targets should show as available

### Relevant log output

```console

```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.14.2, NixOS, 24.11 (Vicuna), 24.11.20250412.26d499f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.14`
 - channels(root): `"nixos-24.11, nixos-unstable"`
 - nixpkgs: `/nix/store/hzaj4d6ari2wq2cbg1j60n9zw42gnshy-source`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
#395466 should fix this.

**Comment by nmouha** [comment]
It appears that #395466 is not sufficient to fix this: yt-dlp will return the error: "Impersonating chrome133a is not supported"

This appears to be due to an outdated version of curl-impersonate-chrome, which does support the new impersonate targets requested by yt-dlp.
 
@GGG-KILLER: Could you update curl-impersonate-chrome to fix this issue?

**Comment by nmouha** [comment]
@GGG-KILLER: Thanks for the quick reply! I tried updating curl-impersonate-chrome myself, and I also realized that it wasn't so easy. Let's move this conversation over to #369972.

**Comment by jgarvin** [comment]
When I try the latest `unstablePkgs.yt-dlp` it still doesn't work though the error message is different now

```
ERROR: [vimeo] 1031249640: Unable to download webpage: Impersonating chrome133a is not supported (caused by TransportError('Impersonating chrome133a is not supported'))
```

I had a friend confirm the URL I was trying does work on a non-nixos distro. Note I just gave yt-dlp the URL and didn't request any specific impersonation, it seems to be defaulting to something that it can't do.

If you ask yt-dlp to list what it can impersonate it does have a nonempty list now though:

```
$ yt-dlp --list-impersonate-targets
[info] Available impersonate targets
Client        OS           Source
------------------------------------
Safari-17.2   Ios-17.2     curl_cffi
Safari-18.0   Ios-18.0     curl_cffi
Chrome-99     Android-12   curl_cffi
Chrome-131    Android-14   curl_cffi
Edge-99       Windows-10   curl_cffi
Edge-101      Windows-10   curl_cffi
Firefox-133   Macos-14     curl_cffi
Firefox-135   Macos-14     curl_cffi
Safari-15.3   Macos-14     curl_cffi
Safari-15.5   Macos-14     curl_cffi
Safari-17.0   Macos-14     curl_cffi
Safari-18.0   Macos-15     curl_cffi
Chrome-99     Windows-10   curl_cffi
Chrome-100    Windows-10   curl_cffi
Chrome-101    Windows-10   curl_cffi
Chrome-104    Windows-10   curl_cffi
Chrome-107    Windows-10   curl_cffi
Chrome-110    Windows-10   curl_cffi
Chrome-116    Windows-10   curl_cffi
Chrome-119    Macos-14     curl_cffi
Chrome-120    Macos-14     curl_cffi
Chrome-123    Macos-14     curl_cffi
Chrome-124    Macos-14     curl_cffi
Chrome-131    Macos-14     curl_cffi
Chrome-133    Macos-15     curl_cffi
```

**Comment by jgarvin** [comment]
Quick workaround for anyone who stumbles on this: [yt-dlp releases standalone linux binaries](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#release-files), they work fine

**Comment by nmouha** [comment]
@jgarvin: The standalone Linux binaries are not expected to work on NixOS. I'm getting the following error: `SSL: CERTIFICATE_VERIFY_FAILED`.

For a quick workaround, replace `yt-dlp` in your `configuration.nix` by:

```
(callPackage (import (builtins.fetchurl {
  url = "https://raw.githubusercontent.com/NixOS/nixpkgs/da2504032ba518133db8f559862d95bc95b1f81c/pkgs/by-name/yt/yt-dlp/package.nix";
  sha256 = "sha256:1ffrks7nk9s30g70k6b5qfyiy9ad8ydsqkq3y69f35pfxqblwfb7";
})) {})
```

This uses the binary builds for curl-cffi (#413385).

**Comment by jleightcap** [comment]
in case others run into this, ad hoc use with the workaround on https://github.com/NixOS/nixpkgs/pull/413385https://github.com/NixOS/nixpkgs/pull/413385 could also be

```sh
$ nix run github:nmouha/nixpkgs/patch-1#yt-dlp
```

**Comment by jgarvin** [comment]
> [@jgarvin](https://github.com/jgarvin): The standalone Linux binaries are not expected to work on NixOS. I'm getting the following error: `SSL: CERTIFICATE_VERIFY_FAILED`.

They're fully statically linked, so I don't see why they shouldn't work

```
$ ldd ~/Downloads/yt-dlp_linux 
	not a dynamic executable
```

**Comment by nmouha** [comment]
@jgarvin: I just checked again to make sure...

Both `./yt-dlp_linux -v` and `./yt-dlp_linux --list-impersonate-targets` give the expected outputs. But did you try a download that requires curl-cffi?

I'm getting a `SSL: CERTIFICATE_VERIFY_FAILED` error, and the most likely reason is that `yt-dlp_linux` didn't bundle any TLS certificates...

**Comment by egrieco** [comment]
> I'm sorry everyone, I remain unable to work on this.
> 
> I believe it might be for the better that I stop being a maintainer for this package so that someone that's able to act more assertively can take over, I am sorry for letting you all down.

No need to apologize. That's how it goes. If it's important enough, someone else will pick it up.

**Comment by nmouha** [comment]
@GGG-KILLER: Sorry again to hear about your situation. Hopefully your health will get better soon!

@entropie: Just FYI, here is another workaround:

``
nix run github:nmouha/nixpkgs/patch-1#yt-dlp -- -vU --write-auto-sub --sleep-requests 0.75 --sleep-subtitles 5 --convert-subs srt -o "%(id)s.%(ext)s" --skip-download --no-mtime --no-playlist --sub-lang en "https://www.youtube.com/watch?v=hCQCP-5g5bo"
``

**Comment by jaredmontoya** [comment]
are you using nixpkgs-unstable or some other version?

**Comment by SuperSandro2000** [comment]
A few lines above those optional dependencies are always provided https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/yt/yt-dlp/package.nix#L45

I do not use that feature and have not planned to really support it due to time constraints but what you tried to provide the dependencies likely does not work on NixOS.

**Comment by SuperSandro2000** [comment]
see #447979

**Comment by FlameFlag** [comment]
@no-ej Right now there is https://github.com/NixOS/nixpkgs/pull/447979, which will backport `curl-impersonate-chrome` to `release-25.05`, and it will end up in stable in roughly 3-4 days (prob by Sunday or Monday) you can track the progress here https://nixpk.gs/pr-tracker.html?pr=447979

> Is there hope for when the next stable 25.11 will be out?

It's been in 25.11 for a while (ever since https://github.com/NixOS/nixpkgs/pull/434011 got merged), 25.11 is basically unstable

**Comment by SuperSandro2000** [comment]
Yep, anything currently in nixos-unstable will end up in 25.11. the branch is only in a bit.
