### ISSUE TITLE
linuxKernel.packages.linux_6_12: wifi (hospot) connections fail

### ISSUE THREAD

**Issue by nicolasdumitru** [NixOS/nixpkgs#409858]
### Nixpkgs version

- Unstable (25.05)

### Describe the bug

Mobile hotspot wifi connections stop working shortly after they are initiated. They work normally for a few seconds (enough to send 1-3 pings) to a few minutes and then, although the connection is still there, it does not provide internet access (DNS resolution fails, pings don't go through, webpages don't load).

### Steps to reproduce

The behavior is somewhat difficult to reproduce consistently. Nevertheless, on my laptop (an Asus Zephyrus G16 2024) it occurs when it connects to a mobile wifi hotspot (I have tried this with multiple phone models and brands and I also experimented with various frequency and WPA security settings).
The NixOS configuration that exhibits this issue on my hardware can be found [here](https://github.com/nicolasdumitru/nixos-config/tree/9d349687fcecc1d2462b69d37dde228476061e27/hosts/turing).
I was unable to reproduce this behavior using regular wifi networks with _this_ version of the kernel.

### Expected behaviour

The expected behavior is to have a stable, working wifi connection on both regular and hotspot wifi networks.

### Relevant log output

```console

```

### Additional context

I would love to provide relevant logs, but I don't really know how to get them (and then sanitize them).

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.14.7, NixOS, 25.11 (Xantusia), 25.11.20250520.2795c50`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-pre20250118-0795280
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux, x86_64-v4-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/nick/.config/nix/nix.conf:/nix/store/rjfwcv6fkrka322pmbf7mj277yqf46yb-kglobalacceld-6.3.5/etc/xdg/nix/nix.conf:/nix/store/rjfwcv6fkrka322pmbf7mj277yqf46yb-kglobalacceld-6.3.5/etc/xdg/nix/nix.conf:/home/nick/.config/kdedefaults/nix/nix.conf:/nix/store/y32npsjm15i7d2i0y77gjh7c635k8vrx-plasma-workspace-6.3.5/etc/xdg/nix/nix.conf:/nix/store/rjfwcv6fkrka322pmbf7mj277yqf46yb-kglobalacceld-6.3.5/etc/xdg/nix/nix.conf:/nix/store/mp2qhfjrpkw3qsrbbgcam6cd9kysab5s-baloo-6.14.0/etc/xdg/nix/nix.conf:/home/nick/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/nick/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/nick/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/nick/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/ip6k2lrwvbbplsqmhzvj5hhvf99ic3jp-lix-2.92.0-pre20250118-0795280/share`
 - nixpkgs: `/etc/nix/path/nixpkgs`

### Notify maintainers

@thoughtpolice @TredwellGit @K900 @Ma27 @NeQuissimus @alyssais 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
What's the wifi chip model?

**Comment by K900** [comment]
This is extremely likely fixed in 6.14.8.

**Comment by nicolasdumitru** [comment]
Sounds great! When can we expect 6.14.8 in nixpkgs (at least as the latest kernel version)? Until then, is there a way to test 6.14.8 right now?

**Comment by K900** [comment]
It should be in unstable-small right about now, and will be making it to other channels in due time.

**Comment by nicolasdumitru** [comment]
have tried using the 6.14.8 kernel from NixOS unstable small. Not only does the issue persist, it might actually be even worse than in 6.14.7. I reproduced the bug on my home wifi network last night while doing some really light web browsing and the newer kernel managed to completely cripple my system. You can see the results in the picture below. I am going to wait for 6.14.8 to make it to unstable, but can that make a difference? Maybe I haven't set it up right. I have also started to wonder whether this could be a hardware defect. If 6.14.8 in unstable doesn't fix it, I will consider running Windows 11 for a couple of (dreadful) days to see if I can reproduce the issue. Are there any other ways to rule out hardware defects in this case?

![Image](https://github.com/user-attachments/assets/fbb9b2b3-429d-4427-83d9-cc582f15e4d3)

**Comment by K900** [comment]
That sounds like an unrelated graphics driver issue. Just to be clear, you've rebooted after installing 6.14.8, right?

**Comment by nicolasdumitru** [comment]
I am positive I was running 6.14.8. I checked by running `uname`.

**Comment by nicolasdumitru** [comment]
I have tested my hardware using Windows and the diagnostic tool in the BIOS. I can confirm that this is not a hardware defect but a driver bug, as I was unable to reproduce the issue on Windows. After reinstalling NixOS, I also tested the hotspot connection and was able to reproduce the bug on version 6.14.8.

If relevant, I’d also like to note that my laptop cannot detect my phone’s 6GHz Wi-Fi hotspot. However, after changing the hotspot setting to 5GHz, the network was detected instantly.

**Comment by nicolasdumitru** [comment]
I have just managed to reproduce the issue on a regular Wi-Fi network using kernel 6.14.8. Regular connections fail significantly less often than hotspot connections.

**Comment by K900** [comment]
OK so it's not the one MT7925 bug that was fixed in 6.14.8. Weirdly I have no issues like that on my MT7925. Are you using wpa_supplicant or iwd?

**Comment by nicolasdumitru** [comment]
This issue is no longer present in later versions of the Kernel
