### ISSUE TITLE
Virtualbox guest additions build failure with linuxPackages_latest

### ISSUE THREAD

**Issue by RdN-MSF** [NixOS/nixpkgs#41360]
## Issue description
Virtualbox guest additions do not build when using linuxPackages_latest, Virtualbox 5.2.12 added Linux 4.16 support.

### Steps to reproduce
```
  kernelPackages = pkgs.linuxPackages_latest;
  virtualisation.virtualbox.guest = {
    enable = true;
    x11 = false;
  };
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 17.09.2955.76614894f34 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03.132545.c40fdcd26c2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by peterhoeg** [comment]
Please dump the error here.

**Comment by RdN-MSF** [comment]
Here you go: https://pastebin.com/uqCxH9kb

This is on the same system but it was upgraded by now:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.13, NixOS, 18.03.132610.49a6964a425 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.03.132610.49a6964a425"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by xeji** [comment]
FYI: upstream bug report with this error: https://www.virtualbox.org/ticket/17678 ; they  closed it saying it's fixed in 5.2.12 ???

**Comment by bbigras** [comment]
I have the same problem with 4.17.

**Comment by peterhoeg** [comment]
@RdN-MSF, you are trying to build 5.2.8 ref your error dump:
> make[1]: Entering directory '/tmp/nix-build-VirtualBox-GuestAdditions-5.2.8-4.16.14.drv-0

Are you sure this is still an issue with 5.2.12?

**Comment by xeji** [comment]
Virtualbox in 18.03 was  bumped to 5.2.12 two days ago (#43237).
Please confirm whether the problem still exists.

**Comment by bbigras** [comment]
I still have the same or similar problem with 4.17. I didn't try `x11 = false;`.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.55, NixOS, 18.03.132865.411cc559c05 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(bidon): `""`
 - channels(root): `"nixos-18.03, nixos-unstable-18.09pre142796.4b649a99d84"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```
=== Building 'vboxguest' module ===
make[1]: Entering directory '/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest'
make V= CONFIG_MODULE_SIG= -C /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build SUBDIRS=/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest SRCROOT=/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest -j2 modules
make[2]: Entering directory '/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build'
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBoxGuest-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBoxGuest.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBoxGuestR0LibGenericRequest.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBoxGuestR0LibHGCMInternal.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBoxGuestR0LibInit.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBoxGuestR0LibPhysHeap.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBoxGuestR0LibVMMDev.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/alloc-r0drv.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/initterm-r0drv.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/memobj-r0drv.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/mpnotification-r0drv.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/powernotification-r0drv.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/alloc-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/assert-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/initterm-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/memobj-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/memuserkernel-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/mp-r0drv-linux.o
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: .fixup: unexpected end of section
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/mpnotification-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/process-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/semevent-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/semeventmulti-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/semfastmutex-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/semmutex-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/spinlock-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/thread-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/thread2-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/time-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/timer-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/linux/RTLogWriteDebugger-r0drv-linux.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/r0drv/generic/semspinmutex-r0drv-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/alloc/alloc.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/err/RTErrConvertFromErrno.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/err/RTErrConvertToErrno.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/err/errinfo.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/log/log.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/log/logellipsis.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/log/logrel.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/log/logrelellipsis.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/log/logcom.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/log/logformat.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/RTAssertMsg1Weak.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/RTAssertMsg2.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/RTAssertMsg2Add.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/RTAssertMsg2AddWeak.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/RTAssertMsg2AddWeakV.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/RTAssertMsg2Weak.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/RTAssertMsg2WeakV.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/assert.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/misc/thread.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/RTStrCat.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/RTStrCopy.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/RTStrCopyEx.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/RTStrCopyP.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/strformat.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/strformatrt.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/strformattype.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/strprintf.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/string/strtonum.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/table/avlpv.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/time/time.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTAssertShouldPanic-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTLogWriteStdErr-stub-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTLogWriteStdOut-stub-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTMpGetCoreCount-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTSemEventWait-2-ex-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTSemEventWaitNoResume-2-ex-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTSemEventMultiWait-2-ex-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/RTSemEventMultiWaitNoResume-2-ex-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/rtStrFormatKernelAddress-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/errvars-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/generic/mppresent-generic.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBox/log-vbox.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/VBox/logbackdoor.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/common/alloc/heapsimple.o
  LD [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/vboxguest.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/vboxguest.mod.o
  LD [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest/vboxguest.ko
make[2]: Leaving directory '/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build'
make[1]: Leaving directory '/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxguest'
=== Building 'vboxsf' module ===
make[1]: Entering directory '/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf'
make V= CONFIG_MODULE_SIG= -C /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build SUBDIRS=/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf SRCROOT=/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf -j2 modules
make[2]: Entering directory '/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build'
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/vfsmod.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/dirops.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/lnkops.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/regops.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/utils.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/VBoxGuestR0LibHGCM.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/VBoxGuestR0LibIdc.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/VBoxGuestR0LibIdc-unix.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/VBoxGuestR0LibSharedFolders.o
  LD [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/vboxsf.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/vboxsf.mod.o
  LD [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf/vboxsf.ko
make[2]: Leaving directory '/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build'
make[1]: Leaving directory '/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxsf'
=== Building 'vboxvideo' module ===
make[1]: Entering directory '/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo'
make V= CONFIG_MODULE_SIG= -C /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build SUBDIRS=/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo SRCROOT=/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo -j2 modules
make[2]: Entering directory '/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build'
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/hgsmi_base.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/modesetting.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_drv.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_fb.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_irq.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_main.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_mode.o
  CC [M]  /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.o
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c: In function 'vbox_ttm_tt_create':
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:219:22: warning: passing argument 2 of 'ttm_tt_init' from incompatible pointer type [-Wincompatible-pointer-types]
  if (ttm_tt_init(tt, bdev, size, page_flags, dummy_read_page)) {
                      ^~~~
In file included from /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/drm/ttm/ttm_bo_driver.h:45:0,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_drv.h:69,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:31:
/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/drm/ttm/ttm_tt.h:161:5: note: expected 'struct ttm_buffer_object *' but argument is of type 'struct ttm_bo_device *'
 int ttm_tt_init(struct ttm_tt *ttm, struct ttm_buffer_object *bo,
     ^~~~~~~~~~~
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:219:6: error: too many arguments to function 'ttm_tt_init'
  if (ttm_tt_init(tt, bdev, size, page_flags, dummy_read_page)) {
      ^~~~~~~~~~~
In file included from /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/drm/ttm/ttm_bo_driver.h:45:0,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_drv.h:69,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:31:
/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/drm/ttm/ttm_tt.h:161:5: note: declared here
 int ttm_tt_init(struct ttm_tt *ttm, struct ttm_buffer_object *bo,
     ^~~~~~~~~~~
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c: At top level:
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:248:19: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .ttm_tt_create = vbox_ttm_tt_create,
                   ^~~~~~~~~~~~~~~~~~
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:248:19: note: (near initialization for 'vbox_bo_driver.ttm_tt_create')
In file included from /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/uapi/linux/posix_types.h:5:0,
                 from /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/uapi/linux/types.h:14,
                 from /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/linux/types.h:6,
                 from /nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/linux/genalloc.h:33,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_drv.h:43,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:31:
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c: In function 'vbox_bo_create':
/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/linux/stddef.h:8:14: warning: passing argument 8 of 'ttm_bo_init' makes integer from pointer without a cast [-Wint-conversion]
 #define NULL ((void *)0)
              ^
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:400:34: note: in expansion of macro 'NULL'
      align >> PAGE_SHIFT, false, NULL, acc_size,
                                  ^~~~
In file included from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_drv.h:68:0,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:31:
/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/drm/ttm/ttm_bo_api.h:544:5: note: expected 'size_t {aka long unsigned int}' but argument is of type 'void *'
 int ttm_bo_init(struct ttm_bo_device *bdev, struct ttm_buffer_object *bo,
     ^~~~~~~~~~~
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:400:40: warning: passing argument 9 of 'ttm_bo_init' makes pointer from integer without a cast [-Wint-conversion]
      align >> PAGE_SHIFT, false, NULL, acc_size,
                                        ^~~~~~~~
In file included from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_drv.h:68:0,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:31:
/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/drm/ttm/ttm_bo_api.h:544:5: note: expected 'struct sg_table *' but argument is of type 'size_t {aka long unsigned int}'
 int ttm_bo_init(struct ttm_bo_device *bdev, struct ttm_buffer_object *bo,
     ^~~~~~~~~~~
/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:398:8: error: too many arguments to function 'ttm_bo_init'
  ret = ttm_bo_init(&vbox->ttm.bdev, &vboxbo->bo, size,
        ^~~~~~~~~~~
In file included from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_drv.h:68:0,
                 from /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.c:31:
/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/include/drm/ttm/ttm_bo_api.h:544:5: note: declared here
 int ttm_bo_init(struct ttm_bo_device *bdev, struct ttm_buffer_object *bo,
     ^~~~~~~~~~~
make[5]: *** [/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/scripts/Makefile.build:312: /tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/vbox_ttm.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/source/Makefile:1571: _module_/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo] Error 2
make[3]: *** [Makefile:146: sub-make] Error 2
make[2]: *** [Makefile:24: __sub-make] Error 2
make[2]: Leaving directory '/nix/store/apcw8p1lwjk0k0fsqgl11k14v5a8d72i-linux-4.17-dev/lib/modules/4.17.0/build'
make[1]: *** [/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo/Makefile.include.footer:101: vboxvideo] Error 2
make[1]: Leaving directory '/tmp/nix-build-VirtualBox-GuestAdditions-5.2.12-4.17.drv-0/install/src/vboxguest-5.2.12/vboxvideo'
make: *** [Makefile:34: all] Error 1
builder for '/nix/store/7sygwdigp0xbpazdg27ism74awh6vcn9-VirtualBox-GuestAdditions-5.2.12-4.17.drv' failed with exit code 2
cannot build derivation '/nix/store/r04msv2jjsp4d2x5c14xcj5zw8vbgcj7-kernel-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/35szfnyis9f2sxjwyj8gh6lvinihwz61-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/f59q28djb50m8yvvpavmimayswjv0wsi-unit-virtualbox.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ngncpcdg3vhj9q36pcgfgc6x4wa9p2c1-nixos-system-nixos-18.03.132865.411cc559c05.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ngncpcdg3vhj9q36pcgfgc6x4wa9p2c1-nixos-system-nixos-18.03.132865.411cc559c05.drv' failed
```

**Comment by xeji** [comment]
fixed by update to 5.2.14, backported to 18.03 in bbad2e55558
