### ISSUE TITLE
vectorcode: fails to start bundled chromadb

### ISSUE THREAD

**Issue by growler** [NixOS/nixpkgs#415770]
### Nixpkgs version

- Unstable (25.11)

### Describe the bug

vectorcode fails to start buhdled chromadb with the following error message:

```
Error while finding module specification for 'chromadb.cli.cli' (ModuleNotFoundError: No module named 'chromadb')
```

This happens because it [starts a new process ](https://github.com/Davidyz/VectorCode/blob/4e96ad3f4f9342421369a8e02f0d94d51825fa51/src/vectorcode/common.py#L91) using `sys.executable`. The new process does not inherit the internal `sys.path` initialized by the wrapper and therefore knows nothing about the location of the chromadb module. 

### Steps to reproduce

1. Add vectorcode as a home manager package
2. Run `vectorcode ls`

### Expected behaviour

vectorcode should start the bundled chromadb without error.

### Relevant log output

```console

```

### Additional context

Surprisingly it works in a devshell because the devshell sets up the PYTHONPATH environment variable with chromadb along with all its dependencies.

I guess the best approach to fix would be to patch the vectorcode to launch chromadb wrapper instead of calling the cli.cli module directly. 

### System metadata

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 24.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.28.3`
 - channels(root): `""`
 - nixpkgs: `/nix/store/g2blcjx71rx6h97ras4z753xb2m0vqm6-nixpkgs/nixpkgs`
 ```

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.32, NixOS, 25.11 (Xantusia), 25.11.20250607.3e3afe5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.3`
 - nixpkgs: `/nix/store/syvnmj3hhckkbncm94kfkbl76qsdqqj3-source`
```

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by auipga** [comment]
```sh
journalctl -u chromadb

Jun 15 14:08:55 laptop chroma[42094]: error: unexpected argument '--log-path' found
Jun 15 14:08:55 laptop chroma[42094]:   tip: to pass '--log-path' as a value, use '-- --log-path'
Jun 15 14:08:55 laptop chroma[42094]: Usage: chroma run <CONFIG_PATH|--path <PATH>|--host <HOST>|--port <PORT>>
Jun 15 14:08:55 laptop chroma[42094]: For more information, try '--help'.
```


https://github.com/NixOS/nixpkgs/blob/56b033fe4f9da755b1872466f24b32df7cfc229e/nixos/modules/services/databases/chromadb.nix#L84

**Comment by auipga** [comment]
An override with omitted `--log-path /var/log/chromadb/chromadb.log` works.

`sudo systemctl edit --runtime chromadb.service`

```
[Service]
ExecStart=
ExecStart=/nix/store/xxx-python3.12-chromadb-1.0.12/bin/chroma run --path /var/lib/chromadb --host 127.0.0.1 --port 8000
```

**Comment by auipga** [comment]
Now I run into https://github.com/Davidyz/VectorCode/issues/164

Temporary solution is to downgrade (before it gets dropped https://github.com/NixOS/nixpkgs/pull/416834)
`services.chromadb.package = pkgs.python3Packages.chromadb_0;`

**Comment by AdrienLemaire** [comment]
it seems like @sarahec already set chromadb_0 [last week](2e6caf7dcf5ab710d45451ea048b8554da609cc4)

Getting the `Error while finding module specification for 'chromadb.cli.cli' (ModuleNotFoundError: No module named 'chromadb')` from both stable vectorcode 0.6.7 and unstable 0.6.10

I had to install from unstable `vectorcode` and `python3Packages.chromadb_0`, then exec `chroma run` in order for `vectorcode vectorize` to work.

Edit: finally understood @auipga's message about the chromadb service.

Works with this setup.
```nix
  services.chromadb = {
    enable = true;
    package = pkgs.userPkgs.python3Packages.chromadb_0;
  };

  home.packages = [
    pkgs.userPkgs.vectorecode
  ];
```

In projects using `.env` files, vectorize fails with error
```
ImportError: python-dotenv is not installed, run `pip install pydantic[dotenv]`
```
maybe we should have it installed in vectorize.nix as well? 
edit: I see it's been reported in #412043 already

**Comment by AdrienLemaire** [comment]
After running `nix flake update`, I'm now getting this error on `nixos-rebuild`

```
error: builder for '/nix/store/591i8lhlrb3wrjz3vjsbwm2fz4ax7dpx-vectorcode-0.6.10.drv' failed with exit code 1;
       last 25 log lines:
       >  - Adding src/vectorcode/mcp_main.py -> vectorcode/mcp_main.py
       >  - Adding src/vectorcode/subcommands/__init__.py -> vectorcode/subcommands/__init__.py
       >  - Adding src/vectorcode/subcommands/check.py -> vectorcode/subcommands/check.py
       >  - Adding src/vectorcode/subcommands/chunks.py -> vectorcode/subcommands/chunks.py
       >  - Adding src/vectorcode/subcommands/clean.py -> vectorcode/subcommands/clean.py
       >  - Adding src/vectorcode/subcommands/drop.py -> vectorcode/subcommands/drop.py
       >  - Adding src/vectorcode/subcommands/hooks.py -> vectorcode/subcommands/hooks.py
       >  - Adding src/vectorcode/subcommands/init.py -> vectorcode/subcommands/init.py
       >  - Adding src/vectorcode/subcommands/ls.py -> vectorcode/subcommands/ls.py
       >  - Adding src/vectorcode/subcommands/prompt.py -> vectorcode/subcommands/prompt.py
       >  - Adding src/vectorcode/subcommands/query/__init__.py -> vectorcode/subcommands/query/__init__.py
       >  - Adding src/vectorcode/subcommands/query/reranker/__init__.py -> vectorcode/subcommands/query/reranker/__init__.py
       >  - Adding src/vectorcode/subcommands/query/reranker/base.py -> vectorcode/subcommands/query/reranker/base.py
       >  - Adding src/vectorcode/subcommands/query/reranker/cross_encoder.py -> vectorcode/subcommands/query/reranker/cross_encoder.py
       >  - Adding src/vectorcode/subcommands/query/reranker/naive.py -> vectorcode/subcommands/query/reranker/naive.py
       >  - Adding src/vectorcode/subcommands/update.py -> vectorcode/subcommands/update.py
       >  - Adding src/vectorcode/subcommands/vectorise.py -> vectorcode/subcommands/vectorise.py
       >  - Adding vectorcode-0.6.10.dist-info/RECORD -> vectorcode-0.6.10.dist-info/RECORD
       > Successfully built vectorcode-0.6.10-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for vectorcode-0.6.10-py3-none-any.whl
       >   - chromadb<=0.6.3 not satisfied by version 1.0.12
       For full logs, run:
         nix log /nix/store/591i8lhlrb3wrjz3vjsbwm2fz4ax7dpx-vectorcode-0.6.10.drv
error: 1 dependencies of derivation '/nix/store/w41iwqq68k1jp2g4hjrdnwpdbbliz2q7-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sy2qd5yqb7h8k8lb1yq2pkdcwk8m5hkm-nixos-system-xps13-9320-25.11.20250617.c539ae8.drv' failed to build
Command '['nix', '--extra-experimental-features', 'nix-command flakes', 'build', '--print-out-paths', 'git+file:///home/dori/Projects/Perso/hydenix#nixosConfigurations."xps13-9320".config.system.build.toplevel', '--no-link']' returned non-zero exit status 1.
```

>  chromadb<=0.6.3 not satisfied by version 1.0.12


Looks like it's been mentioned in https://github.com/NixOS/nixpkgs/pull/416834#discussion_r2153541359  , wait and see

🤷

**Comment by MattSturgeon** [comment]
> After running `nix flake update`, I'm now getting this error on `nixos-rebuild`
> 
> ```
> >  chromadb<=0.6.3 not satisfied by version 1.0.12
> ```
> 
> Looks like it's been mentioned in https://github.com/NixOS/nixpkgs/pull/416834#discussion_r2153541359  , wait and see

Yes, this is fixed by https://github.com/NixOS/nixpkgs/pull/417720. You just need to wait for it to reach your unstable channel and update again.

There are also ways to try out a PR early, but I won't go into them here.

**Comment by AdrienLemaire** [comment]
**nixos-unstable** got updated today, and I gave it another try:

<details><summary>Console traceback</summary>

```console
$ gcam "update hydenix to v4.3.0"
WARNING: vectorcode.cli_utils : Loading default config.
WARNING: vectorcode.common : Starting bundled ChromaDB server at http://127.0.0.1:43085.
/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/bin/python3.13: Error while finding module specification for 'chromadb.cli.cli' (ModuleNotFoundError: No module named 'chromadb')
Traceback (most recent call last):
  File "/nix/store/5ri8j2fqbk51cms566hisnl239a3jrgw-vectorcode-0.6.12/bin/.vectorcode-wrapped", line 9, in <module>
    sys.exit(main())
             ~~~~^^
  File "/nix/store/5ri8j2fqbk51cms566hisnl239a3jrgw-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/main.py", line 125, in main
    return asyncio.run(async_main())
           ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/nix/store/5ri8j2fqbk51cms566hisnl239a3jrgw-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/main.py", line 78, in async_main
    server_process = await start_server(final_configs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/5ri8j2fqbk51cms566hisnl239a3jrgw-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/common.py", line 109, in start_server
    await wait_for_server(server_url)
  File "/nix/store/5ri8j2fqbk51cms566hisnl239a3jrgw-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/common.py", line 67, in wait_for_server
    raise TimeoutError(f"Server did not start within {timeout} seconds.")
TimeoutError: Server did not start within 10 seconds.
```

</details> 

```console
$ nix-store -qR /run/current-system | grep -E '/nix/store' | grep -E 'vectorcode|chromadb'
/nix/store/rh1izjx2h653jh1vy1pghzs1iwsqb6c4-python3.13-chromadb-0.6.3
/nix/store/5ri8j2fqbk51cms566hisnl239a3jrgw-vectorcode-0.6.12
```

I understand that vectorcode and chromadb are both using python 3.13, and that vectorcode installs the old v0.6.3 for now (as was done with chromadb_0 a few days earlier).

But with vectorcode auto-installing chromadb, the chromadb service is not available anymore.

I can start chroma manually

<details><summary>Details</summary>

```console
$ /nix/store/rh1izjx2h653jh1vy1pghzs1iwsqb6c4-python3.13-chromadb-0.6.3/bin/chroma run --host 127.0.0.1 --port 43085


                (((((((((    (((((####
             ((((((((((((((((((((((#########
           ((((((((((((((((((((((((###########
         ((((((((((((((((((((((((((############
        (((((((((((((((((((((((((((#############
        (((((((((((((((((((((((((((#############
         (((((((((((((((((((((((((##############
         ((((((((((((((((((((((((##############
           (((((((((((((((((((((#############
             ((((((((((((((((##############
                (((((((((    #########



Running Chroma

Saving data to: ./chroma_data
Connect to chroma at: http://127.0.0.1:43085
Getting started guide: https://docs.trychroma.com/getting-started


INFO:     [20-06-2025 17:35:24] Set chroma_server_nofile to 65535
INFO:     [20-06-2025 17:35:24] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [20-06-2025 17:35:24] Starting component System
DEBUG:    [20-06-2025 17:35:24] Starting component OpenTelemetryClient
DEBUG:    [20-06-2025 17:35:24] Starting component SqliteDB
DEBUG:    [20-06-2025 17:35:24] Starting component SimpleQuotaEnforcer
DEBUG:    [20-06-2025 17:35:24] Starting component Posthog
DEBUG:    [20-06-2025 17:35:24] Starting component SimpleRateLimitEnforcer
DEBUG:    [20-06-2025 17:35:24] Starting component LocalSegmentManager
DEBUG:    [20-06-2025 17:35:24] Starting component LocalExecutor
DEBUG:    [20-06-2025 17:35:24] Starting component SegmentAPI
DEBUG:    [20-06-2025 17:35:24] Starting component SimpleAsyncRateLimitEnforcer
INFO:     [20-06-2025 17:35:24] Started server process [3332543]
INFO:     [20-06-2025 17:35:24] Waiting for application startup.
INFO:     [20-06-2025 17:35:24] Application startup complete.
INFO:     [20-06-2025 17:35:24] Uvicorn running on http://127.0.0.1:43085 (Press CTRL+C to quit)
```

</details> 

But vectorcode still tries to start the server by itself and fails to find the module (because chroma is an executable, not a module).
Not sure how to debug this further

**Comment by sarahec** [comment]
It's not quite in `nixpkgs-unstable` yet: https://nixpk.gs/pr-tracker.html?pr=417720

**Comment by AdrienLemaire** [comment]
@sarahec I didn't understand your comment since I'm using nixos-unstable, but I have waited for nixpkgs-unstable to be updated, and after a `nix flake update` and `nixos-rebuild`, I still observe the same issues: rebuild works and vectorcode doesn't.
I tried installing vectorcode from both nixos-unstable and nixpkgs-unstable.

<details><summary>Details</summary>

```console
$ vectorcode ls
WARNING: vectorcode.cli_utils : Loading default config.
WARNING: vectorcode.common : Starting bundled ChromaDB server at http://127.0.0.1:44281.
/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/bin/python3.13: Error while finding module specification for 'chromadb.cli.cli' (ModuleNotFoundError: No module named 'chromadb')
Traceback (most recent call last):
  File "/nix/store/yfdhid1whqv2qrylpnwnh3y6zawhf9kh-vectorcode-0.6.12/bin/.vectorcode-wrapped", line 9, in <module>
    sys.exit(main())
             ~~~~^^
  File "/nix/store/yfdhid1whqv2qrylpnwnh3y6zawhf9kh-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/main.py", line 125, in main
    return asyncio.run(async_main())
           ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/nix/store/yfdhid1whqv2qrylpnwnh3y6zawhf9kh-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/main.py", line 78, in async_main
    server_process = await start_server(final_configs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yfdhid1whqv2qrylpnwnh3y6zawhf9kh-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/common.py", line 109, in start_server
    await wait_for_server(server_url)
  File "/nix/store/yfdhid1whqv2qrylpnwnh3y6zawhf9kh-vectorcode-0.6.12/lib/python3.13/site-packages/vectorcode/common.py", line 67, in wait_for_server
    raise TimeoutError(f"Server did not start within {timeout} seconds.")
TimeoutError: Server did not start within 10 seconds.
```

</details>

**Comment by sarahec** [comment]
@GaetanLepage I'm thinking we can fix this by wrapping the bin to start chromadb. ~~Starting it as a system service is out as this release of chromadb is obsolete.~~ Setting `PATH` in `postFixup` works to launch `chromadb`, but the `cli` module issue still exists. I'm stuck. Thoughts?

UPDATE: Got it!
