### ISSUE TITLE
Failing nixos.tests.gnome3 tests block channel update 

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#41616]
The `nixos.tests.gnome3` test hasn't succeeded in quite a while (https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.gnome3.x86_64-linux), blocking any channel updates of `nixos-unstable`. Could someone who knows what this test does please have a look?

Ping @jtojnar, @edolstra, @domenkozar.

**Comment by jtojnar** [comment]
gnome-desktop failure was fixed by https://github.com/NixOS/nixpkgs/commit/fd9cfc4db512f41612727a4a4fe0303fe8f67bef
vinagre failure was fixed by https://github.com/NixOS/nixpkgs/commit/67eaab86b4fb2541d63571d99935f790f9e500f7#diff-8e47d7592641d21375c5a4053d3d1d3c

Not sure if there is any other failure.

**Comment by peti** [comment]
So the test failure from https://hydra.nixos.org/build/75538093 is fixed now?

**Comment by jtojnar** [comment]
Did not see this one. Will investigate later.

**Comment by jtojnar** [comment]
The session starts normally in VM, not sure why the tests fail. Possibly some `XAuthority` shenanigans like in https://github.com/NixOS/nixpkgs/issues/37642 cc @xeji @hedning @pbogdan

**Comment by xeji** [comment]
I'm looking into it. Not sure it's a problem with the test yet, there may be an underlying issue.

**Comment by xeji** [comment]
After some experiments I don't think there's a problem with the test itself. https://hydra.nixos.org/build/75538093 fails because the gnome3 session reproducibly fails to start in a VM with the slim display manager (which is the default used in the test), while it works fine with lightdm and gdm. Don't know why yet, the logs don't tell much.
@jtojnar maybe you have an idea ?

I did my experiments on the same revision as the hydra test failure. Cannot test this on current master as some gnome3 packages currently fail to build, so these will have to be fixed first.

**Comment by jtojnar** [comment]
No idea. I will not be able to debug this anytime soon. Can we switch to
lightdm for now?

**Comment by xeji** [comment]
Done in #41742. The channel will still be blocked by failing gnome3 packages: https://hydra.nixos.org/eval/1462266?filter=gnome3

**Comment by jtojnar** [comment]
Looks like mostly an issue with gnome-keyring. Though the logs look fine.

**Comment by xeji** [comment]
totem build fails, too

**Comment by jtojnar** [comment]
The status seems to be "timed out" for `gnome3.gnome-keyring` and it builds fine for me on master.

**Comment by jtojnar** [comment]
Also it is weird that hydra does not show the packages as dependency failed.

**Comment by jtojnar** [comment]
Totem blocks gnome-control-center via cheese. The error should have been fixed by https://github.com/NixOS/nixpkgs/commit/be17bccf38a2e5a5701115e15adf7ed5c585ac7d. We might need to disable the vala plugi-ns as upstream suggests.

**Comment by jtojnar** [comment]
Let's see if https://github.com/NixOS/nixpkgs/commit/05b9e9f011f2873329e8da62a1147f520caa15db fixes that.

**Comment by xeji** [comment]
Looks good, thanks!

**Comment by xeji** [comment]
Latest hydra eval still shows [gnome3.gnome-keyring](https://hydra.nixos.org/eval/1462313?filter=gnome3.gnome-keyring.x86_64-linux)  as "timed out"  but the build outputs (same hash) are available on `cache.nixos.org` when I install it locally. Do  ofborg builders feed the cache, too?
Anyway, I guess we need someone with access rights to restart the hydra build.

**Comment by peti** [comment]
I restarted build https://hydra.nixos.org/build/75683862 of `nixpkgs:trunk:gnome3.gnome-keyring`.

**Comment by worldofpeace** [comment]
@peti @jtojnar @xeji 
Any status on this. The channel is so old :frowning_face:

**Comment by peti** [comment]
@worldofpeace, the current status is visible at https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents.

**Comment by xeji** [comment]
This particular problem should be solved, but the channel is still not moving because the last few Hydra evaluations have failed due to issues with the Hydra machines (insufficient memory).

**Comment by worldofpeace** [comment]
Ok, problem solved, just waiting until the Hydra machines are playing nice :+1:

**Comment by xeji** [comment]
opened #41835 for the hydra issue.
