### ISSUE TITLE
Enable initrd modules required by cryptsetup --kernel-crypto

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#42163]
See: https://github.com/NixOS/nixpkgs/pull/38382#discussion_r196077562

**Comment by sh4r3m4n** [comment]
I've been using cryptsetup with an SSD and without kernel crypto to run my entire NixOS and didn't noted any performance issues, but I agree that my patch was a temporary workaround, so enabling the crypto module would be a better solution.

**Comment by zarelit** [comment]
The `disable-kernel-crypto` option also breaks the feature of `cryptsetup benchmark` that can be used when installing nixos to reason about the speed of disk encryption

**Comment by fpletz** [comment]
The `installer.luksroot` NixOS test works with and the kernel userapace crypto API enabled in `cryptsetup` on at least 19.03. `cryptsetup` was updated to 2.0.6 in the meantime, maybe the bug was fixed? Haven't noticed anything in `cryptsetup` release notes. This API shouldn't in fact be need for LUKS, only for tcrypt and the benchmark.

@cript0nauta Did you also run the test or did you just notice that on your local machine? Do you have any non-standard config concerning the initrd?

**Comment by fpletz** [comment]
Hmm, even with `cryptsetup-2.0.2` the `installer.luksroot` test succeeds. We need more information.

**Comment by cript0nauta** [comment]
@fpletz I haven't ran any tests, I just tested it in my work laptop and in a VM used to isolate the issue. I used a non-standard initrd config only for debugging, but after finding the problem I used the standard one.

The only strange thing I did was to have a LUKS2 encrypted volume, which isn't very common (or at least it wasn't at the moment I experienced the issue).

In a few days I will try to boot my system both with and without kernel crypto to check whether it is necessary or not.

**Comment by cript0nauta** [comment]
@fpletz: I can confirm that I still have problems booting my system when kernel crypto is enabled. I put this in my configuration.nix, in an updated unstable NixOS:

```nix
  nixpkgs.config.packageOverrides = super: {
    cryptsetup = (super.cryptsetup.overrideAttrs (old: rec {configureFlags = [
      "--enable-cryptsetup-reencrypt"
      "--with-crypto_backend=openssl"
      # "--disable-kernel_crypto"
    ];}));
  };
```

With this configuration, my system boots. If I uncomment the `"--disable-kernel_crypto"` line, it doesn't because it fails to unencrypt my root partition.

I'm using LVM inside a LUKS2 partition.

**Comment by cript0nauta** [comment]
Here is the result of using `--verbose --debug` when mounting my LUKS2 volume with kernel crypto enabled. The last image is the most important. Sorry for pasting screenshots, I didn't have a flash drive to copy the logs.

![1](https://user-images.githubusercontent.com/1222362/59122687-ba174200-8931-11e9-9a7e-5591acd8f6a7.jpeg)

![2](https://user-images.githubusercontent.com/1222362/59122693-bedbf600-8931-11e9-8edd-1475c13940f6.jpeg)

![3](https://user-images.githubusercontent.com/1222362/59122698-c26f7d00-8931-11e9-91a8-65c1c1427524.jpeg)

![4](https://user-images.githubusercontent.com/1222362/59122700-c7343100-8931-11e9-9ec5-1f8e7b2ba38a.jpeg)

![5](https://user-images.githubusercontent.com/1222362/59122703-cac7b800-8931-11e9-976e-a3ec2f45f00e.jpeg)

**Comment by fpletz** [comment]
Thank you very much for your detailed analysis. :+1:

Oh, LUKS2! Seems the userspace API is indeed needed for LUKS2 but not LUKS1. I'll try to adapt the `installer.luksroot` test and fix this issue. There are probably just some `algif_*` modules missing.
