### ISSUE TITLE
Some applications are missing icons in gnome-shell activity and dock (not reproducible in a fresh account)

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#45935]
## Issue description

I have several applications (installed with `nix-env -i`) that are missing icons in gnome-shell activity and dock (dash-to-dock).  Here are a few: Chromium, Emacs, Inkscape,  Geary, LibreOffice, VLC.

Firefox was also missing the icon, but it was fixed: #38536.

Similar issues are mentioned in #247 and #16758.

There is no problems with applications installed using `environment.systemPackages`.

### Steps to reproduce

I cannot currently reproduce the issue in a fresh user account, but I have it in my user accounts on two different machines.

In my case, with GNOME desktop:
```shell
nix-env -i vlc
```
If i restart gnome-shell and look for VLC, the VLC icon is missing.

## Technical details

Output of `nix-shell -p nix-info --run "nix-info -m"`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.133183.a37638d4670 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(alexey): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3238.e984f9e48e1"`
 - channels(root): `"nixos-18.03.133183.a37638d4670"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by jtojnar** [comment]
And I still cannot reproduce. Could you share your `configuration.nix`?

P.S. `nix-env -iA` is much faster (without `-A` it needs to go through the whole nixpkgs and check `name` attributes of packages, instead of just traversing attribute path)

**Comment by alexeymuranov** [comment]
Here is my [`configuration.nix`](https://gist.github.com/alexeymuranov/b791550cb371c1fcb075a73637dc913a).

**Comment by jtojnar** [comment]
One thing that comes to mind is `gtk-update-icon-cache` in system-path module:

https://github.com/NixOS/nixpkgs/blob/8c172c4426529d245a65b55da2997ab2aca9d331/nixos/modules/config/system-path.nix#L140-L142

Try `nix-env -iA gtk3`. (Though, I do not have it installed in user profile and icons still works for me.)

**Comment by alexeymuranov** [comment]
I tried `nix-env -iA nixos.gtk3` on one of the two machines, it did not help.

**Comment by alexeymuranov** [comment]
@jtojnar, could you try reinstalling your GNOME Shell?  Apparently my icons disappeared [after i reinstalled it](https://github.com/NixOS/nixpkgs/issues/38536#issuecomment-381396478) somehow.

**Comment by jtojnar** [comment]
I did restart GNOME Shell (using <kbd>alt</kbd>-<kbd>f2</kbd> `r`) because the launchers would not appear without it due to https://github.com/NixOS/nixpkgs/issues/12757.

Firefox issue was caused by a broken symlink in the package. Also unrelated,
Libreoffice had a [similar issue](https://github.com/NixOS/nixpkgs/issues/34806#issuecomment-385298626) caused by a wrong `Icon=` value in the desktop file, but that has been fixed as well.

Chromium’s icon matches, therefore the issue must be unrelated to those two:

```ShellSession
$ grep Icon $(nix-build -A chromium)/share/applications/chromium-browser.desktop
Icon=chromium
$ find $(nix-build -A chromium)/share/icons -follow -name chromium.png
/nix/store/hmnd65lwj5zgd3hm18s1h8sahspjkfs2-chromium-68.0.3440.106/share/icons/hicolor/24x24/apps/chromium.png
/nix/store/hmnd65lwj5zgd3hm18s1h8sahspjkfs2-chromium-68.0.3440.106/share/icons/hicolor/256x256/apps/chromium.png
/nix/store/hmnd65lwj5zgd3hm18s1h8sahspjkfs2-chromium-68.0.3440.106/share/icons/hicolor/48x48/apps/chromium.png
/nix/store/hmnd65lwj5zgd3hm18s1h8sahspjkfs2-chromium-68.0.3440.106/share/icons/hicolor/64x64/apps/chromium.png
/nix/store/hmnd65lwj5zgd3hm18s1h8sahspjkfs2-chromium-68.0.3440.106/share/icons/hicolor/128x128/apps/chromium.png
/nix/store/hmnd65lwj5zgd3hm18s1h8sahspjkfs2-chromium-68.0.3440.106/share/icons/hicolor/22x22/apps/chromium.png
```

**Comment by alexeymuranov** [comment]
By "reinstalling GNOME shell", I meant something like `nix-env -iA nixos.gnome3.gnome-shell`.  I remember that it was this or similar command that provoked the issue in my case. 

However, now I do not have `gnome-shell` explicitly installed anywhere, but the issue remains.  I think i might have installed it before with `nix-env -i` trying to debug something.

**Comment by alexeymuranov** [comment]
I cannot reproduce the issue in a fresh account even after copying over my `~/.config`, `~/.local`, `~/.cache`, and a few other dot-files and dot-folders.

Where else could some configuration be hiding?  Could something get out of order in my `~/.nix-profile`?

**Comment by jtojnar** [comment]
Try to check if the profile you installed the packages to is listed in `$XDG_DATA_DIRS` environment variable and if the icons are in the profile. Not sure what else could that be.

**Comment by alexeymuranov** [comment]
The output of `echo $XDG_DATA_DIRS` is identical in old and fresh accounts -- apart from the difference in the account name.

**Comment by alexeymuranov** [comment]
Still debugging...

So far i noticed one thing in common in the two affected accounts, which is not present in the fresh account: in the affected accounts i have `channels-N-link` links in `/nix/var/nix/profiles/per-user/account-name/`, but no such links in the fresh account. Moreover, the date of creation of `channels-82-link` is 12 April, and i first noticed the issue on 15 April.  Could this somehow be relevant?

I removed extra channels from the user account and did `nix-collect-garbage -d`, but i still have
```shell
# ls /nix/var/nix/profiles/per-user/alexey/channels
binary-caches  manifest.nix  nixos-17.03  nixos-17.09
```
How can i clean up those completely?

**Comment by alexeymuranov** [comment]
It seems that my icons are in place:
```
§ ls /nix/store/*-vlc-*/share/icons/hicolor/*/apps/*.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/128x128/apps/vlc-kb.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/128x128/apps/vlc.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/128x128/apps/vlc-xmas.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/16x16/apps/vlc.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/256x256/apps/vlc.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/32x32/apps/vlc.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/48x48/apps/vlc.png
/nix/store/bjh7z6mcx1jhgmdfn72gp70j049cw6b3-vlc-3.0.3/share/icons/hicolor/48x48/apps/vlc-xmas.png
```

@jtojnar, could you suggest me some documentation or explain how icon lookup works in GNOME Shell, so that i could try to trace where it breaks?

By the way, from which directory did you execute this line?
```
$ find $(nix-build -A chromium)/share/icons -follow -name chromium.png
```

**Comment by jtojnar** [comment]
[Icon Theme Spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) should be used. Basically, `icons` subdirectories of paths in `$XDG_DATA_DIRS` are checked for the icon.  Try something like

```
IFS=: for d in $XDG_DATA_DIRS; do
    find $d -name vlc.png -follow
done
```

I ran the `nix-build` command in nixpkgs checkout.

**Comment by alexeymuranov** [comment]
Thanks for the link to Icon Theme Specification.

Running `find` as you suggested for `vlc` icons, give me this in the affected account:
```
find: ‘/etc/profiles/per-user/alexey/share’: No such file or directory
/home/alexey/.nix-profile/share/icons/hicolor/16x16/apps/vlc.png
/home/alexey/.nix-profile/share/icons/hicolor/128x128/apps/vlc.png
/home/alexey/.nix-profile/share/icons/hicolor/32x32/apps/vlc.png
/home/alexey/.nix-profile/share/icons/hicolor/256x256/apps/vlc.png
/home/alexey/.nix-profile/share/icons/hicolor/48x48/apps/vlc.png
find: ‘/nix/var/nix/profiles/default/share’: No such file or directory
```
and the same thing in the fresh account.

Looking for `inkscape` icons finds strictly more files in the affected account than in the fresh one:
```
find: ‘/etc/profiles/per-user/alexey/share’: No such file or directory
/home/alexey/.nix-profile/share/icons/hicolor/16x16/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/hicolor/24x24/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/hicolor/32x32/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/hicolor/256x256/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/hicolor/48x48/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/hicolor/22x22/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/HighContrast/16x16/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/HighContrast/24x24/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/HighContrast/32x32/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/HighContrast/256x256/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/HighContrast/48x48/apps/inkscape.png
/home/alexey/.nix-profile/share/icons/HighContrast/22x22/apps/inkscape.png
find: ‘/nix/var/nix/profiles/default/share’: No such file or directory
/run/current-system/sw/share/icons/HighContrast/16x16/apps/inkscape.png
/run/current-system/sw/share/icons/HighContrast/24x24/apps/inkscape.png
/run/current-system/sw/share/icons/HighContrast/32x32/apps/inkscape.png
/run/current-system/sw/share/icons/HighContrast/256x256/apps/inkscape.png
/run/current-system/sw/share/icons/HighContrast/48x48/apps/inkscape.png
/run/current-system/sw/share/icons/HighContrast/22x22/apps/inkscape.png
```
Nothing is found in `~/.nix-profile/share/icons/HighContrast/` in the fresh account.

**Comment by jtojnar** [comment]
Are the icons shown when you install the packages using `environment.systemPackages`?

**Comment by alexeymuranov** [comment]
Yes.

**Comment by alexeymuranov** [comment]
Ok, stupid me: i did not copy over enough dot-folders to reproduce the issue in a fresh account.  The following fixed my problem:
```ShellSession
rm -r ~/.themes
```

Should i close this, or is there anything to investigate on the side of Nix?  I must be able to reproduce the problem now, but maybe it is not a problem.

**Comment by alexeymuranov** [comment]
I will remove my previous comment. So, i fixed the problem on both computers. What fixed it was upgrading to 18.09 and then executing
```ShellSession
nix-env -u '*'
```
This was quite strange, because VLC and some other affected applications were not updated, but all icons got fixed.

**Comment by alexeymuranov** [comment]
I am closing this as i still do not see how to reproduce it, and maybe it will not occur again.

**Comment by alexeymuranov** [comment]
I observe that installing, upgrading, or reinstalling packages imperatively in user profile behaves rather strangely, and the effects are difficult to predict or reproduce.

For example, my icons disappeared after some command of the form `nix-env -i`.  Now i upgraded NixOS to 18.09 and did `nix-env -iA nixos.vlc`, but VLC icon did not appear.  Then i did `nix-env -u '*'`, which did not touch VLC, but its icon appeared. Then i noticed that network streaming in VLC did not work anymore. I did `nix-env -iA nixos.vlc` once again and it got fixed.

I do not know yet how to report this as an issue...

**Comment by alexeymuranov** [comment]
I am reopening this. I still cannot reproduce the problem in a fresh account, but I have it again in my usual account with apparently the same symptoms, and I cannot fix it.

**Comment by alexeymuranov** [comment]
I upgraded to `19.03` and the icons got fixed again.  I missed the exact operation that got them fixed, but i noticed it after upgrading manually installed packages.

Closing this (at least for another half a year).

**Comment by maxkrieger** [comment]
For me, my issue was selecting GNOME instead of GNOME+Xorg on login (click the cog icon).

**Comment by matheus23** [comment]
> For me, my issue was selecting GNOME instead of GNOME+Xorg on login (click the cog icon).

Fascinating.
I had this issue as well. However, I was *not* on GNOME+Xorg.
But simply the act of switching from one to the other fixed it for both for me.
