### ISSUE TITLE
Rstudio qt error

### ISSUE THREAD

**Issue by mredaelli** [NixOS/nixpkgs#48826]
## Issue description

RStudio does't start. (See also on [Discourse](https://discourse.nixos.org/t/rstudio-doesnt-start/1119))

### Steps to reproduce

Create a `default.nix` as follows:
```
with import <nixpkgs> {};
let
  my-R-packages = with rPackages; [ mongolite ]; 
  R-with-my-packages = rWrapper.override{ packages = with rPackages; my-R-packages; };
  RStudio-with-my-packages = rstudioWrapper.override{ packages = with rPackages; my-R-packages; };
in stdenv.mkDerivation {
  name = "feeds";
  buildInputs = [ R-with-my-packages RStudio-with-my-packages ];
}
```

Then
```
nix-shell
```

Then this happens:
```
[nix-shell:~/test]$ rstudio
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.932.09195057114, nixos-unstable-18.09pre149415.8395f9aa85e, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ma27** [comment]
I'm fairly certain that this is due to an improperly configured QT_PLUGIN_PATH, let me see if I can fix it :)

**Comment by Ma27** [comment]
hmm... testing your expression on nixpkgs `09195057114` (the commit you specified as commit of your nixos installation) seems to work fine though.

**Comment by mredaelli** [comment]
:/
Can it be that it's because I'm using i3 for wm?
Can I try anything to pinpoint the issue?

**Comment by Ma27** [comment]
I use `i3wm` as window manager as well.

>  Can I try anything to pinpoint the issue?

Probably. Is there anything special in your QT_PLUGIN_PATH? I'm still fairly certain that this is related to such an issue, in the past I fixed several issues with an equal message.

**Comment by mredaelli** [comment]
Hmmm...
```
[nix-shell:/tmp]$  for i in $(echo $QT_PLUGIN_PATH | sed s"/[:]/\n/g"); do ls $i; done
ls: cannot access '/home/turing/.nix-profile/lib/qt4/plugins': No such file or directory
ls: cannot access '/home/turing/.nix-profile/lib/kde4/plugins': No such file or directory
ls: cannot access '/nix/var/nix/profiles/default/lib/qt4/plugins': No such file or directory
ls: cannot access '/nix/var/nix/profiles/default/lib/kde4/plugins': No such file or directory
ls: cannot access '/run/current-system/sw/lib/qt4/plugins': No such file or directory
ls: cannot access '/run/current-system/sw/lib/kde4/plugins': No such file or directory
ls: cannot access '/etc/profiles/per-user/mredaelli/lib/qt4/plugins': No such file or directory
ls: cannot access '/etc/profiles/per-user/mredaelli/lib/kde4/plugins': No such file or directory
```

**Comment by Ma27** [comment]
yeah, I was obviously wrong with this idea. I fixed this in some packages where a component was missing and could be added manually into `QT_PLUGIN_PATH`, I guess I'm missing something here as your expression works perfectly fine for me.

Does `rstudio` itself work, when invoking `./result/bin/rstudio` from `nix-build -A rstudio`?

**Comment by mredaelli** [comment]
It does!

**Comment by Ma27** [comment]
that’s certainly good to know, at least the basic functionality is available.

Although I couldn’t reproduce it yet, I suspect a bug in the expression which breaks overrides in certain cases. I’ll have a deeper look at the expression tomorrow and report back:)

**Comment by Ma27** [comment]
after having a look at the expression I couldn't find an obvious issue.

However a typical workaround for such issues usually looks like this:

``` patch
diff --git a/pkgs/development/r-modules/wrapper-rstudio.nix b/pkgs/development/r-modules/wrapper-rstudio.nix
index dd9b0e9c538..51cd6298175 100644
--- a/pkgs/development/r-modules/wrapper-rstudio.nix
+++ b/pkgs/development/r-modules/wrapper-rstudio.nix
@@ -1,4 +1,8 @@
-{ stdenv, R, rstudio, makeWrapper, recommendedPackages, packages }:
+{ stdenv, R, rstudio, makeWrapper, recommendedPackages, packages, qtbase }:
+
+let
+  qtVersion = with stdenv.lib.versions; "${major qtbase.version}.${minor qtbase.version}";
+in
 
 stdenv.mkDerivation rec {
 
@@ -24,7 +28,8 @@ stdenv.mkDerivation rec {
     echo -n $R_LIBS_SITE | sed -e 's/:/", "/g' >> $out/${fixLibsR}
     echo -n "\"))" >> $out/${fixLibsR}
     echo >> $out/${fixLibsR}
-    makeWrapper ${rstudio}/bin/rstudio $out/bin/rstudio --set R_PROFILE_USER $out/${fixLibsR}
+    makeWrapper ${rstudio}/bin/rstudio $out/bin/rstudio --set R_PROFILE_USER $out/${fixLibsR} \
+      --prefix QT_PLUGIN_PATH : ${qtbase}/lib/${qtVersion}/plugins
   '';
   
   meta = {
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index d1ab34eba6f..60ed9787301 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -13084,7 +13084,7 @@ with pkgs;
     packages = [];
   };
 
-  rstudioWrapper = callPackage ../development/r-modules/wrapper-rstudio.nix {
+  rstudioWrapper = libsForQt5.callPackage ../development/r-modules/wrapper-rstudio.nix {
     recommendedPackages = with rPackages; [
       boot class cluster codetools foreign KernSmooth lattice MASS
       Matrix mgcv nlme nnet rpart spatial survival
```

Would you mind applying the patch in your local `nixpkgs` checkout and rebuild your expression?

**Comment by mredaelli** [comment]
Sorry it took me a while.

I patched it locally, but still get the same error.

Just to make sure I did it correctly, the point was to get the rstudio script to look like this (specifically, the `QT_PLUGIN_PATH` variable), right?
```
#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export R_PROFILE_USER='/nix/store/zmda1qdpg0gnlvj8rskaxd19zj283ikl-RStudio-1.1.456-wrapper/fix_libs.R'
export QT_PLUGIN_PATH='/nix/store/v1g34bsiwv0qi0q80pawjx3qvimlbhdg-qtbase-5.11.1-bin/lib/5.11/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
exec "/nix/store/4x2vjn0q8xqyridcznvv2vzzax817p5m-RStudio-1.1.456/bin/rstudio"  "${extraFlagsArray[@]}" "$@"
/nix/store/zmda1qdpg0gnlvj8rskaxd19zj283ikl-RStudio-1.1.456-wrapper/bin/rstudio
```

Anyway, the problem seems to be that the directory
```
/nix/store/v1g34bsiwv0qi0q80pawjx3qvimlbhdg-qtbase-5.11.1-bin/lib/5.11/plugins
```
does not exist. It should be
```
/nix/store/v1g34bsiwv0qi0q80pawjx3qvimlbhdg-qtbase-5.11.1-bin/lib/qt-5.11/plugins
```
(there's a **qt-** too much or too little).
But I have no clue how to fix that :)

**Comment by Ma27** [comment]
does it work **with** the `qt-` prefix?

**Comment by mredaelli** [comment]
Lol, I should have mentioned :) Yes it does.

**Comment by Ma27** [comment]
Then it's likely that I screwed my patch up :)
But when it works with the `qt-` prefix, would you mind updating and filing the patch?

**Comment by mredaelli** [comment]
Ahhh I see what you mean.
Sure :)

**Comment by mredaelli** [comment]
Submitted PR #50964
