### ISSUE TITLE
gdb does not work on macOS Mojave

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#51293]
## Issue description

`gdb` does not work on on macOS Mojave, [because Apple has introduced a new load command to to o-mach executables.](https://stackoverflow.com/questions/52529838/gdb-8-2-cant-recognized-executable-file-on-macos-mojave-10-14). A [patch](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=fc7b364aba41819a5d74ae0ac69f050af282d057) has been applied upstream to fix this problem.

### Steps to reproduce

Run `gdb` on any executable file.

```
% gdb /usr/bin/true 
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
BFD: /usr/bin/true: unknown load command 0x32
BFD: /usr/bin/true: unknown load command 0x32
BFD: /usr/bin/true: unknown load command 0x32
"/usr/bin/true": not in executable format: Format de fichier non reconnu
```
## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.1`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(smaret): `"nixpkgs-19.03pre160749.3a393eecafb"`
 - nixpkgs: `/Users/smaret/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
Nice that there is a fix available! If you open a PR with that patch, we can definitely get it into unstable.

This sounds like the same issue I was running in to with otool:

https://github.com/tpoechtrager/cctools-port/issues/60

For now, at least, it looks like binutils is quicker to update than Apple!

**Comment by smaret** [comment]
I'm working on a PR, but I'm stuck on this [issue](https://discourse.nixos.org/t/stripping-options-and-fetchpatch/1554).

**Comment by smaret** [comment]
It turns out that the patch cannot be applied to `gdb-8.1.1` (nor `gdb-8.2`), because it modifies files with the `binutils/` directory which is absent from the tarballs.

**Comment by smaret** [comment]
Indeed the patch is from `binutils-gdb` repository that contains both the `gdb` and `binutils` source codes. I don't know how to apply this.

**Comment by smaret** [comment]
The easiest way to fix this is probably to update the Nix package to the latest gdb weekly release. What do you think @matthewbauer ?

**Comment by matthewbauer** [comment]
We may just have to wait for the next binutils release.

**Comment by matthewbauer** [comment]
This should be fixed once #52730 hits master.

**Comment by smaret** [comment]
> This should be fixed once #52730 hits master.

I still get the error with `gdb 8.2.1` from `staging`:

```
% gdb /usr/bin/true 
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
BFD: /usr/bin/true: unknown load command 0x32
BFD: /usr/bin/true: unknown load command 0x32
BFD: /usr/bin/true: unknown load command 0x32
"/usr/bin/true": not in executable format: file format not recognized
```

**Comment by matthewbauer** [comment]
Ok- we probably need to update binutils as well.

**Comment by matthewbauer** [comment]
Maybe 53e1db960a0663313e950f4ad45c98a82ad7d2c3 will work?

**Comment by smaret** [comment]
Still not working.

I'm not sure how `gdb` uses `binutils`. The binary isn't linked against it:

```
% otool -L gdb
gdb:
	/nix/store/idgg2ss7a457f6mj5vq8pmhj31a2dmdv-readline-6.3p08/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	/nix/store/14r7mlpqpmyasbfvccskzld7lzh48572-zlib-1.2.11/lib/libz.dylib (compatibility version 1.0.0, current version 1.2.11)
	/nix/store/mxw8k3jjag288cjk7qk4aycvcqsh000y-ncurses-6.1-20190112/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
	/nix/store/4n305f16w7z7csw2lsflr379biid9aph-Libsystem-osx-10.11.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/nix/store/x6vai6pdzmmr5mqhwbr86qz76ffxqsl4-python3-3.7.2/lib/libpython3.7m.dylib (compatibility version 3.7.0, current version 3.7.0)
	@rpath/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.90.0)
	/nix/store/hm91n39fnhp2nn6njpnmr66b91yd1sl5-expat-2.2.6/lib/libexpat.1.dylib (compatibility version 8.0.0, current version 8.8.0)
	/nix/store/06pj3piyaxryxd6sasrdmz45m6chchvv-mpfr-4.0.1/lib/libmpfr.6.dylib (compatibility version 7.0.0, current version 7.1.0)
	/nix/store/7b8af3z6pp4v89h8b350afchsh0c534r-libc++-5.0.2/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by smaret** [comment]
It looks like #61545 solved this. Thanks!
