### ISSUE TITLE
libsForQt5.qgpgme fails tests (breaking kde/plasma)

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#53632]
## Issue description

[qgpgme failure on hydra](https://hydra.nixos.org/build/86830084) (this is a qt specific test):
> FAIL!  : TofuInfoTest::testTofuConflict() 'sig.validity() == Signature::Marginal' returned FALSE. ()
   Loc: [t-tofuinfo.cpp(458)]
PASS   : TofuInfoTest::cleanupTestCase()
Totals: 7 passed, 1 failed, 0 skipped, 0 blacklisted, 1047ms

[kde breakage](https://hydra.nixos.org/eval/1499088?filter=kde&compare=1498930&full=)

This seems to affect master too, but for some reason it's been built successfully once.

The aarch64 build started failing when updating qt5 from 5.11 to 5.12 making it the likely root cause: https://hydra.nixos.org/build/86769014

Edit: the cause was expired testing keys: https://dev.gnupg.org/T3815#121469

cc `gpgpme` maintainer @primeos 
cc @bkchr as you've been active in keeping plasma/kde up to date lately.

ping staging next: #53483

**Comment by bkchr** [comment]
Did you found [this](https://dev.gnupg.org/T3815)? Sounds very similar and should be fixed...

**Comment by hedning** [comment]
No didn't find that, but yeah, that sure looks exactly the same issue. I'm guessing the qt issue were never actually fixed:

> [That leaves the qt issue to be done.](https://dev.gnupg.org/T3815#114105)

Blame on the test gives no change at least:
https://github.com/gpg/gpgme/blame/b182838f71d8349d6cd7be9ecfb859b893d09127/lang/qt/tests/t-tofuinfo.cpp#L458

**Comment by hedning** [comment]
Applying the suggested patch fixes the build at least:
```diff
+++ gpgme-1.10.0/lang/qt/tests/t-tofuinfo.cpp
@@ -455,7 +455,7 @@ private Q_SLOTS:
 
         QVERIFY(result.numSignatures() == 1);
         auto sig = result.signatures()[0];
-        QVERIFY(sig.validity() == Signature::Marginal); 
+        QVERIFY(sig.validity() == Signature::Marginal || sig.validity() == Signature::Unknown);
 
         auto stats = sig.key().userID(0).tofuInfo();
         QVERIFY(!stats.isNull());

**Comment by bkchr** [comment]
So, what are we want to do? Do you maybe want to comment on the upstream issue?

**Comment by hedning** [comment]
Hmm, strange, I'm getting the same failure on master (using `nix-build --check`), forcing single core does not fix the problem though, so probably not a race condition.

I've reported the failure as you suggested: https://dev.gnupg.org/T3815#121448

**Comment by hedning** [comment]
The cause is most likely qt 5.11 to 5.12 upgrade, as the aarch64 build started failing the test then: https://hydra.nixos.org/build/86769014

**Comment by hedning** [comment]
So the keys used in this test expired on 2019-01-06, which explains why we suddenly saw this without any apparent reason. https://dev.gnupg.org/T3815#121469 :
> Oh,.. it is even worse. The conflict keys expired 2019-01-06 so they are actually expired right now.
>
> I'll change the test to use keys without expiry.

**Comment by primeos** [comment]
@hedning Thanks for fixing this and sorry for my late reply...
