### ISSUE TITLE
mkShell needs more documentation in the manual

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#58624]

**Comment by worldofpeace** [comment]
Only thing I see that really could be more helpful is explaining these parameters
```
  inputsFrom ? [],
  buildInputs ? [],
  nativeBuildInputs ? [],
  propagatedBuildInputs ? [],
  propagatedNativeBuildInputs ? [],
```

All of which are the same for `stdenv.mkDerivation` except `inputsFrom` which should have a more detailed description.

And maybe get a link to https://nixos.org/nix/manual/#sec-nix-shell somewhere in there.

**Comment by toraritte** [comment]
Adding @manveru's summary (from [discourse thread](https://discourse.nixos.org/t/mkshell-vs-buildenv/681)):

> all [`mkShell`] does is provide some defaults for a `stdenv.mkDerivation`. So you don’t need to give it a `src` or `name`, all you really need is `buildInputs`, maybe a `shellHook` that runs when you enter the `nix-shell`, and any env variables you want.

I always wondered why certain examples use `mkDerivation` while others prefer `mkShell`, and [the Nixpkgs manuals `mkShell` section](https://nixos.org/nixpkgs/manual/#sec-pkgs-mkShell) is not overly informative.

**Comment by jtojnar** [comment]
When using `mkDerivation`, you need to set `name` and `src`. `mkShell` is a convenience utility that does not require that.

In fact it is just `mkDerivation` wrapper:

https://github.com/NixOS/nixpkgs/blob/d0017d7b7e0d36ec7c905ab75b59494eb36fb2d0/pkgs/build-support/mkshell/default.nix#L31

that

1. sets a default name:
    https://github.com/NixOS/nixpkgs/blob/d0017d7b7e0d36ec7c905ab75b59494eb36fb2d0/pkgs/build-support/mkshell/default.nix#L32
2. removes phases in order to not need `src`:
    https://github.com/NixOS/nixpkgs/blob/d0017d7b7e0d36ec7c905ab75b59494eb36fb2d0/pkgs/build-support/mkshell/default.nix#L33
3. Sets up dummy phase to prevent `nix build`:
    https://github.com/NixOS/nixpkgs/blob/d0017d7b7e0d36ec7c905ab75b59494eb36fb2d0/pkgs/build-support/mkshell/default.nix#L40-L45
4. Also there is `inputsFrom`, that allows you to inherit inputs from other packages:
    https://github.com/NixOS/nixpkgs/blob/d0017d7b7e0d36ec7c905ab75b59494eb36fb2d0/pkgs/build-support/mkshell/default.nix#L14-L20

The last part is little harder to understand and perhaps it would deserve a comment but otherwise the code is understandable and linking there from manual should be enough.

**Comment by hyperfekt** [comment]
Is there any reason to ever use non-native buildInputs, since the derivation is never built and thus there is no build target, but instead the inputs should be working on the 'builder' that invokes the shell?

**Comment by drewmullen** [comment]
> When using `mkDerivation`, you need to set `name` and `src`. `mkShell` is a convenience utility that does not require that.

it appears as though `src` is no longer *required* with `mkDerivation` as ive been running `$ nix-shell shell.nix`. `name` is still required though.

shell.nix:

```
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "my-environment";

  buildInputs = with pkgs; [
     coreutils
     bash
     wget
     zip
     awscli
  ];
}
```

**Comment by samuela** [comment]
Bumping, as more documentation for `mkShell` would still be useful.

**Comment by deliciouslytyped** [comment]
Very quick comment:
When I originally posted this I had much less of an understanding of Nix, Nixpkgs, and the surrounding things in general.
The difficulty of understanding mkShell came from not having an understanding of `nix-shell`'s special (citation needed - I still can't explain it with certainty) behaviour, combined with a lack of understanding of `mkDerivation` and how `mkShell`. These are probably the things that would need to be explained to the level of making sense of `mkShell`. I now personally have a much clearer understanding of `mkDerivation` and the inner workings of nix and things are clearer.

**Comment by pmarreck** [comment]
I landed here because I'm trying to flake-ify my project's `default.nix` by following this guide https://garnix.io/blog/converting-to-flakes and there seems to be nothing in it (which uses `mkShell`) that is producing an output of type Derivation (at least, one that I can see, given my still-limited understanding) that would permit me to understand how to relate the two.

As a point of discussion, perhaps.

**Comment by majidaldo** [comment]
wow. no wonder nix has not caught on.

**Comment by majidaldo** [comment]
can't figure out the difference  between buildInputs and inputsFrom

**Comment by jtojnar** [comment]
As mentioned above:

> there is `inputsFrom`, that allows you to inherit inputs from other packages
> https://github.com/NixOS/nixpkgs/blob/d0017d7b7e0d36ec7c905ab75b59494eb36fb2d0/pkgs/build-support/mkshell/default.nix#L14-L20

That means 

```nix
pkgs.mkShell {

  inputsFrom = [
   pkgs.foo
   pkgs.bar
  ];
  nativeBuildInputs = [
   pkgs.qux
  ];
}
```

The result will be the same as if you did:

```nix
pkgs.mkShell {
  buildInputs = [
   pkgs.foo
   pkgs.bar
  ];
  nativeBuildInputs = [
   pkgs.qux
   pkgs.foo
   pkgs.bar
  ];
  propagatedBuildInputs = [
   pkgs.foo
   pkgs.bar
  ];
  propagatedNativeBuildInputs = [
   pkgs.foo
   pkgs.bar
  ];
}
```

**Comment by jonknapp** [comment]
FWIW that explanation is way more helpful as a tangible example. Thanks.

**Comment by jenr24G** [comment]
Working on a shell environment that needs its `buildInputs` to be on the `$PATH` for the `shellHook`. my `opam switch import` is returning package config errors in the `shellHook` that don't occur when run outside of it. Is there any way to get the `buildInputs` on the `PATH` during the `shellHook`?

**Comment by HackingPheasant** [comment]
+1 For needing to improve the doc's, I am completely new to Nix and spent the last 3 days trying various options and reading various blog and docs to figure out why some of dependencies I listed in the Dev shell showed up but others did not. It ended up being a complete misunderstanding of what exactly inputsFrom did or should be used for. :(

**Comment by truh** [comment]
Would certainly be good to have a setence/paragraph explaining what it is for.

> `pkgs.mkShell` is a specialized `stdenv.mkDerivation` that removes some
repetition when using it with `nix-shell` (or `nix develop`).

Feels like a setence that is only written for people that are too familiar with nix to look at the manual anyway.
