### ISSUE TITLE
Tootle - has no icons , crash on startup after add account

### ISSUE THREAD

**Issue by pirboazo** [NixOS/nixpkgs#63089]
## Issue description
Hi @dtzWill 
i open 3 issues on tootle  : https://github.com/bleakgrey/tootle
No icons 
![Selection_023](https://user-images.githubusercontent.com/1702929/59446476-dddefa00-8e01-11e9-961a-4be0c3f444e1.png)
Impossible to mdify setting 
crash after append a new account.

### Steps to reproduce
Just install and launch application

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/m57p0m5m6fz7j58g1bamsrxq5prsgpl2-bash-interactive-4.4-p23-dev
copying path '/nix/store/m57p0m5m6fz7j58g1bamsrxq5prsgpl2-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.50, NixOS, 19.03.172880.49dc8087a20 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172880.49dc8087a20"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pirboazo** [comment]
Hi after installation of gnome 3 and test with gnome it's OK
for icons et setting.
It's also good for kde plasma.

**Comment by jtojnar** [comment]
Installing icon theme of your choice to `environment.systemPackages` (e.g. `gnome3.adwaita-icon-theme`) should fix that.

Regarding the crash do you see any errors if you run it in terminal?

**Comment by pirboazo** [comment]
Hello,
Yes, it works.
Isn't this an addiction to add to the package?

**Comment by jtojnar** [comment]
Well, we do not know what icon theme user wants so we do not know which to add to the package. See https://github.com/NixOS/nixpkgs/pull/43150 for more info.

**Comment by pirboazo** [comment]
> Well, we do not know what icon theme user wants so we do not know which to add to the package. See #43150 for more info.

I think it would be better to have icons that the user doesn't like than no icons

**Comment by davidak** [comment]
I can confirm that it still crashes on NixOS stable.

After logging in at first start, the app crashes.

```
[davidak@X230:~]$ com.github.bleakgrey.tootle 
[INFO 23:01:31.573466] Application.vala:155: Tootle version: 0.2.0
[INFO 23:01:31.573507] Application.vala:157: Kernel version: 4.19.107
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Opening in existing browser session.
[INFO 23:14:42.376259] NewAccountDialog.vala:134: Received tokens from https://chaos.social
[INFO 23:14:42.376312] NewAccountDialog.vala:148: Requesting auth token
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Opening in existing browser session.
[INFO 23:15:09.582990] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 23:15:09.584783] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 23:15:09.587456] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 23:15:09.588801] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
[INFO 23:15:09.703233] Watchlist.vala:23: Reloading
[INFO 23:15:09.703281] Watchlist.vala:34: Watching for 0 users and 0 hashtags

(com.github.bleakgrey.tootle:4574): Gtk-WARNING **: 23:15:10.431: Failed to set text '<b>nerven::gift::<💀>()</b>' from markup due to error parsing markup: Error on line 1 char 32: “💀” is not a valid name

(com.github.bleakgrey.tootle:4574): Gtk-WARNING **: 23:15:10.431: Failed to set text '<b>nerven::gift::<💀>()</b>' from markup due to error parsing markup: Error on line 1 char 32: “💀” is not a valid name
**
ERROR:com.github.bleakgrey.tootle@exe/src/API/NotificationType.c:215:tootle_notification_type_from_string: code should not be reached
Aborted (core dumped)
```

After that, it crashes everytime with this after about 0.5 seconds:
```
[davidak@X230:~]$ com.github.bleakgrey.tootle 
[INFO 23:18:27.704947] Application.vala:155: Tootle version: 0.2.0
[INFO 23:18:27.705039] Application.vala:157: Kernel version: 4.19.107
[INFO 23:18:27.730118] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 23:18:27.733561] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 23:18:27.737798] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 23:18:27.739306] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
[INFO 23:18:28.214087] Watchlist.vala:23: Reloading
[INFO 23:18:28.214135] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:com.github.bleakgrey.tootle@exe/src/API/NotificationType.c:215:tootle_notification_type_from_string: code should not be reached
Aborted (core dumped)
```

I have icons tho. I use the Pantheon desktop (from elementary OS, for which the program was developed)

![Screenshot from 2020-03-24 23-20-19](https://user-images.githubusercontent.com/91113/77482687-d6379180-6e26-11ea-8465-9927fa0139da.png)

NixOS unstable has the same version which runs a little longer (~1.7sec.) before it crashes with:

```
[davidak@X230:~]$ time com.github.bleakgrey.tootle 
[INFO 23:31:03.382101] Application.vala:156: Tootle version: 0.2.0
[INFO 23:31:03.382147] Application.vala:158: Kernel version: 4.19.107
[INFO 23:31:03.409513] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 23:31:03.412327] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 23:31:03.415556] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 23:31:03.417148] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
[INFO 23:31:03.884705] Watchlist.vala:23: Reloading
[INFO 23:31:03.884751] Watchlist.vala:34: Watching for 0 users and 0 hashtags

(com.github.bleakgrey.tootle:9510): Gtk-WARNING **: 23:31:04.539: Failed to set text '<b>nerven::gift::<💀>()</b>' from markup due to error parsing markup: Error on line 1 char 32: “💀” is not a valid name

(com.github.bleakgrey.tootle:9510): Gtk-WARNING **: 23:31:04.540: Failed to set text '<b>nerven::gift::<💀>()</b>' from markup due to error parsing markup: Error on line 1 char 32: “💀” is not a valid name
**
ERROR:com.github.bleakgrey.tootle@exe/src/API/NotificationType.c:210:tootle_notification_type_from_string: code should not be reached
Bail out! ERROR:com.github.bleakgrey.tootle@exe/src/API/NotificationType.c:210:tootle_notification_type_from_string: code should not be reached
Aborted (core dumped)
```
It has the same problem on elementary OS too btw. https://github.com/bleakgrey/tootle/issues/170
The developer works on a refactored version: https://github.com/bleakgrey/tootle/commits/refactor
So the best option is to wait for that.
If you care about the project, consider donating to the developer: https://liberapay.com/bleakgrey/donate

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 19.09.2284.bf7c0f0461e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.09.2284.bf7c0f0461e, nixos-hardware, nixos-unstable-20.09pre217537.d96bd3394b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
It does work now on unstable.
