### ISSUE TITLE
localtimed fails to set time zone

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#68489]
**Describe the bug**
Enabling the localtime service is not enough to make time zone setting work. After starting it I get unhelpful messages like this in the journal:

> localtimed: Failed to set timezone: Europe/Zurich

The time zone never changes.

**To Reproduce**
1. Set `services.localtime.enable = true;`
2. Set `time.timeZone = "UTC";` to work around #67673
3. `sudo nixos-rebuild switch`

**Expected behavior**

systemd-timedated should Just Work™.

**Additional context**

[Rebooting](https://github.com/NixOS/nixpkgs/issues/55288#issuecomment-500140886) does not help.

Removing  `time.timeZone = "UTC";`, rebuilding and rebooting also does not help.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.71, NixOS, 19.03.173481.8a30e242181 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173481.8a30e242181"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

and

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.71, NixOS, 19.09pre192418.e19054ab3cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09pre192418.e19054ab3cd"`
 - channels(username): `"nixpkgs-20.03pre193309.c4196cca9ac"`
 - nixpkgs: `/home/username/.nix-defexpr/channels/nixpkgs`

**Comment by l0b0** [comment]
Seems to have been fixed in unstable at some point.

**Comment by l0b0** [comment]
Seems to have been fixed in unstable at some point.

**Comment by gueorgui** [comment]
I'm having the same issue. I've been told on IRC that the only way to set the timezone is by using the `time.timeZone` option in `/etc/nixos/configuration.nix`. This does work, but it would be great to actually be able to set the timezone based on location.

**Comment by afics** [comment]
Same issue here.

**Comment by enricozb** [comment]
Still happening... However for me 
```
$ journalctl -b -u localtime
-- Journal begins at Sat 2021-10-30 15:15:44 EDT, ends at Fri 2022-01-14 21:58:35 EST. --
Jan 14 17:17:13 frame systemd[1]: Started Timezone Updater Daemon.
```
there are no more logs than this.

I need to run `sudo -u localtimed localtimed` for the timezone to be set. Without using the `localtimed` user it fails with
```
localtimed: Failed to set timezone: <my timezone>
```
However after running `sudo -u localtimed localtimed`, `localtimed localtimed` as my personal user works without issue and reports:
```
2022/01/14 21:59:48 Updated timezone to: <my timezone>
```

**Comment by l0b0** [comment]
Not stale; still happens in 22.05. `journalctl --unit=localtime.service` simply says "Started Timezone Updater Daemon." but never gets anywhere. Running `sudo -u localtimed localtimed` just hangs seemingly forever.

**Comment by l0b0** [comment]
Is it possible that `services.localtime.enable = true;` conflicts with `time.hardwareClockInLocalTime = true;`?

**Comment by l0b0** [comment]
Also, is it possible that this only works with specific network interfaces or something? I'm only connecting to Wi-Fi.

**Comment by lovesegfault** [comment]
I've been using it successfully for a while now, you obviously need `geoclue` to be working, but other than that it should just work.

It can fail when geoclue doesn't provide a timezone, in which case you can just manually `timedatectl`. I've had this happen when on airplane wifi a couple times.

**Comment by l0b0** [comment]
@lovesegfault Would you be willing to share the relevant configuration? [GeoClue2 is already enabled as part of setting `services.localtime.enable = true`](https://github.com/NixOS/nixpkgs/blob/22.05/nixos/modules/services/system/localtime.nix), but clearly something is still missing for it to work out of the box.

**Comment by lovesegfault** [comment]
@l0b0 Out of curiosity, is this on `nixos-unstable` or a release channel?

**Comment by l0b0** [comment]
@lovesegfault 22.05 channel.

**Comment by lovesegfault** [comment]
@l0b0 Ah, yes, the fixes were not backported, it should work on `unstable`, and in the upcoming `22.11` release.

There were a few PRs:

https://github.com/NixOS/nixpkgs/pull/186369
https://github.com/NixOS/nixpkgs/pull/186336
https://github.com/NixOS/nixpkgs/pull/175831
https://github.com/NixOS/nixpkgs/pull/176904
https://github.com/NixOS/nixpkgs/pull/175675

**Comment by l0b0** [comment]
@lovesegfault Thank you, that's really useful! I'll leave this open until I have a chance to test on 22.11.

**Comment by l0b0** [comment]
I just applied [this change](https://gitlab.com/engmark/root/-/merge_requests/257/diffs) on 22.11, and it did not work. The relevant services just keep restarting:

```console
$ journalctl --follow --output=cat --unit geoclue.service
Starting Location Lookup Service...
Started Location Lookup Service.
Service not used for 60 seconds. Shutting down..
geoclue.service: Deactivated successfully.
Starting Location Lookup Service...
Started Location Lookup Service.
Service not used for 60 seconds. Shutting down..
geoclue.service: Deactivated successfully.
Starting Location Lookup Service...
Started Location Lookup Service.
```

```console
$ journalctl --follow --output=cat --unit localtimed-geoclue-agent.service
Starting localtimed-geoclue-agent.service...
Started localtimed-geoclue-agent.service.
Geolocation service not in use
Geolocation service not in use
[…]
```

**Comment by krav** [comment]
On `unstable` this seems to conflict with having `time.timeZone` set. This disables setting timezone through `timedatectl` and localtimed reports "Failed to set timezone: <tz>". 

Removing `time.timeZone` fixes localtimed.

**Comment by l0b0** [comment]
> On `unstable` this seems to conflict with having `time.timeZone` set. This disables setting timezone through `timedatectl` and localtimed reports "Failed to set timezone: ".
> 
> Removing `time.timeZone` fixes localtimed.

I'm not sure what you mean here. As you can see from [my last comment](https://github.com/NixOS/nixpkgs/issues/68489#issuecomment-1332798989) I no longer have `time.timeZone` set, and I don't see "Failed to set timezone" anymore, but localtimed still doesn't do what it's supposed to. Did you mean to say that there are some new patches on unstable which have fixed the remaining issues?

**Comment by mimame** [comment]
Hi @l0b0 
I think you are missing in your config:
```
  services.localtimed.enable = true;
  services.automatic-timezoned.enable = true;
  location.provider = "geoclue2";
```

**Comment by l0b0** [comment]
@mimame 

[`services.localtime.enable = true;` is equivalent to `services.localtimed.enable = true;`](https://github.com/NixOS/nixpkgs/blob/ce20e9ebe1903ea2ba1ab006ec63093020c761cb/nixos/modules/services/system/localtimed.nix#L8). (Presumably `services.localtime` is about to be deprecated for `services.localtimed`, so I've changed that; thanks!)

Based on the documentation it looks like [localtimed and automatic-timezoned should be mutually exclusive](https://search.nixos.org/options?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=services.localtimed.enable++services.automatic-timezoned.enable), because both of them say they "[keep] the system timezone up-to-date based on the current location".

Both of them set up geoclue2, so I don't understand why `location.provider = "geoclue2";` should be necessary.

**Comment by l0b0** [comment]
I tried switching to automatic-timezoned (`automatic-timezoned.enable = true;` instead of `localtime.enable = true;``) with similar results:

```
$ journalctl --output=cat --follow 
Service not used for 60 seconds. Shutting down..
geoclue.service: Deactivated successfully.
Error: MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.NoReply")))), Some("Message recipient disconnected from message bus without replying"), Msg { type: Error, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 2, body: Signature("s") })
automatic-timezoned.service: Main process exited, code=exited, status=1/FAILURE
automatic-timezoned.service: Failed with result 'exit-code'.
```

Setting `location.provider = "geoclue2";` in addition didn't seem to change anything.

**Comment by Enzime** [comment]
I fixed my issues with `automatic-timezoned` (`automatic-timezoned.enable = true;`) by re-enabling the Geoclue2 demo agent:

```nix
{
  services.geoclue2.enableDemoAgent = lib.mkForce true;
}
```

Enabling GNOME or Pantheon disables the demo agent and removes it from the agent whitelist which is necessary for the NixOS `automatic-timezoned` service.

**Comment by l0b0** [comment]
@Enzime [Can confirm](https://gitlab.com/engmark/root/-/merge_requests/257/diffs) your workaround on release-23.05. @7c6f434c @mimame Would either of you be willing to look into this?

**Comment by 7c6f434c** [comment]
I don't have any NixOS environment around (nor do I have any DE) to try this easily… (I have only ever cared about geoclue as a library dependency of a few things, I am not even sure I have ever checked whether the data coming from it is reasonable)

**Comment by nosewings** [comment]
I think I've at least partially figured out what's causing the "Failed to set timezone" error, at least on my system. It seems to be a permission error, or at least related to one. `localtimed` is being run as user `localtimed`, but it needs to be running as root. To confirm, the error message is coming from [this file](https://github.com/Stebalien/localtime/blob/master/localtimed.go), when making a dbus call to `org.freedesktop.timedate1.SetTimezone`. You can emulate this call via the following line:

    dbus-send --system --print-reply --type=method_call --dest='org.freedesktop.timedate1' '/org/freedesktop/timedate1' 'org.freedesktop.timedate1.SetTimezone' string:"America/Chicago" boolean:false

though you may need to first manually restart the `systemd-timedated` service, for reasons that I don't understand. In any case, when run as root, this call succeeds for me. But if I run it as `localtimed` (via `sudo -u localtimed`), I get a permission error.

Weirdly, though, this only happens on _one_ of my systems. On the other one, running the command as `localtimed` works just fine.

**Comment by 99linesofcode** [comment]
Where there are a few issues with the `localtimed` module (ie. https://github.com/NixOS/nixpkgs/issues/329522) the main problem here and in the `automatic-timezoned` module is related to https://github.com/NixOS/nixpkgs/issues/321121.

Finding an alternative to MLS could take a while so for those looking for a workaround, override `services.geoclue2.geoProviderUrl` with your own Google Maps API key like so:

```nix
services.geoclue2.geoProviderUrl = "https://www.googleapis.com/geolocation/v1/geolocate?key=YOUR_KEY"
```

**Comment by 99linesofcode** [comment]
> While there are a few issues with the `localtimed` module (ie. #329522) the main problem here and in the `automatic-timezoned` module is related to #321121.
> 
> Finding an alternative to MLS could take a while so for those looking for a workaround and willing to incur some costs associated with the Geolocation API, override `services.geoclue2.geoProviderUrl` with your own Google Maps API key like so:
> 
> ```nix
> services.geoclue2.geoProviderUrl = "https://www.googleapis.com/geolocation/v1/geolocate?key=YOUR_KEY"
> ```
> 
> edit: clarified that there are costs associated with using the Geolocation API

Decided I'd rather not incur any costs either. The Archlinux Wiki mentioned a couple of providers here: https://wiki.archlinux.org/title/System_time#Setting_based_on_geolocation. Seems like all of them are commercial parties. Most offer free access either with or without creating an account and obtaining an API key.

**Comment by peterhoeg** [comment]
FWIW, I've been using beacondb for a while with the following config:

```
{
  services.geoclue2.geoProviderUrl = "https://beacondb.net/v1/geolocate";
}
```

**Comment by 99linesofcode** [comment]
> FWIW, I've been using beacondb for a while with the following config:
> 
> ```
> {
>   services.geoclue2.geoProviderUrl = "https://beacondb.net/v1/geolocate";
> }
> ```

Yeah that's what I settled on yesterday as well. It's important to note however that beacondb is still in it's infancy and the developer is working on scaling it. This URL actually points to his home server, not the VPS he is in the process of setting up. 

See: https://codeberg.org/beacondb/beacondb/issues/5#issuecomment-2182940 for more info on this.

**Comment by yajo** [comment]
Probably the problem is that [Mozilla shut down their geolocation service](https://gitlab.freedesktop.org/geoclue/geoclue/-/issues/186#note_2462494). But we use it: https://github.com/NixOS/nixpkgs/blob/98ef8c0167c42c661cab33b0d31538f531534710/nixos/modules/services/desktops/geoclue2.nix#L128

I found this alternative:

```nix
{
  services.tzupdate.enable = true;
}
```

It queries many endpoints, so it seems to work here.

**Comment by l0b0** [comment]
> It queries many endpoints, so it seems to work here.

[Reference](https://github.com/cdown/tzupdate/blob/437b3f0cef1ac85a97f8ba3dab97bd7090deb2bb/src/http.rs#L15-L44)

**Comment by Jasper-Ben** [comment]
@99linesofcode, I am trying to consolidate the (for me) relevant information in this thread on using geoclue with beacondb. I think I have it correctly set up and the only reason why it is currently not working for me is that my area is currently not covered by the DB (I started uploading reports already) but I am not 100% sure. Also I am not sure whether I can still set a default timeZone with automatic-timezoned enabled. Maybe you (or someone else) could quickly confirm?

My config:

```nix
  # Set default timeZone to home time
  time.timeZone = lib.mkDefault "Europe/Berlin";
  # Enable automatic timezone updates 
  services.automatic-timezoned.enable = true;
  # Force enable required geoclue2 DemoAgent, since GNOME disables it: https://github.com/NixOS/nixpkgs/issues/68489#issuecomment-1484030107
  services.geoclue2.enableDemoAgent = lib.mkForce true;
  # Use beacondb.net since Mozilla Location Service is retired: https://github.com/NixOS/nixpkgs/issues/321121
  services.geoclue2.geoProviderUrl = "https://beacondb.net/v1/geolocate";
```

The log output from geoclue:

```
sudo journalctl -u geoclue --follow
Okt 24 13:34:17 2693-nixos systemd[1]: Stopped Location Lookup Service.
Okt 24 13:34:17 2693-nixos systemd[1]: geoclue.service: Consumed 691ms CPU time, 38.5M memory peak, 0B memory swap peak, no IO, received 5.6K IP traffic, sent 5.3K IP traffic.
Okt 24 13:34:17 2693-nixos systemd[1]: Starting Location Lookup Service...
Okt 24 13:34:17 2693-nixos .geoclue-wrappe[16924]: Failed to open /etc/geoclue/conf.d/: Error opening directory “/etc/geoclue/conf.d/”: No such file or directory
Okt 24 13:34:17 2693-nixos systemd[1]: Started Location Lookup Service.
Okt 24 13:34:17 2693-nixos .geoclue-wrappe[16924]: Failed to query location: No WiFi networks found
Okt 24 13:34:21 2693-nixos .geoclue-wrappe[16924]: Failed to query location: Query location SOUP error: Not Found
Okt 24 13:40:23 2693-nixos .geoclue-wrappe[16924]: Service not used for 60 seconds. Shutting down..
Okt 24 13:40:23 2693-nixos systemd[1]: geoclue.service: Deactivated successfully.
Okt 24 13:40:23 2693-nixos systemd[1]: geoclue.service: Consumed 613ms CPU time, 38.5M memory peak, 0B memory swap peak, no IO, received 5.7K IP traffic, sent 5.5K IP traffic.
```

**Comment by 99linesofcode** [comment]
@Jasper-Ben hi, since last reporting on this I've switched time zones and haven't been able to get it working either. I haven't spent much time debugging this yet. I've resorted to manually updating my timezone through `timedatectl` for the time being:

`sudo timedatectl set-timezone "Europe/Berlin"` in your case.

**Comment by 99linesofcode** [comment]
@Jasper-Ben `services.tzupdate.enable = true` seems to work for me. I'm on the following commits:

![image](https://github.com/user-attachments/assets/c5ffac8d-568b-438b-b336-38aefa9e5ae0)

**Comment by yajo** [comment]
See https://github.com/NixOS/nixpkgs/pull/361373 for making tzupdate actually work out of the box when enabled.

**Comment by hustlerone** [comment]
tzupdate works though

**Comment by hustlerone** [comment]
Can confirm, it works.

Should we proceed to lib.mkForce this?

**Comment by VictorEngmarkHexagon** [comment]
>         geoProviderUrl = "https://beacondb.net/v1/geolocate";

This URL is unreachable for me.

**Comment by prasannavl** [comment]
@VictorEngmarkHexagon, it's a POST only API, just leaving it here for ref. 

```
curl -X POST https://api.beacondb.net/v1/geolocate \
  -H "Content-Type: application/json" \
  -H "User-Agent: MyTestClient/1.0" \
  -d '{"considerIp": true}'
```
