### ISSUE TITLE
Spurious "bash: hash: hashing disabled" when activating virtualenv

### ISSUE THREAD

**Issue by dms-cat** [NixOS/nixpkgs#69396]
**Describe the bug**
Whenever activating or deactivating a Python 3.7 virtualenv I get what looks like spurious error messages:

> bash: hash: hashing disabled

**To Reproduce**
1. `dir="$(mktemp -d)" && python -m venv "$dir" && . "${dir}/bin/activate"`

**Expected behavior**
There should be no output while activating the virtualenv

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03pre193781.d484f2b7fc0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(username): `""`
 - channels(root): `"nixos-20.03pre193781.d484f2b7fc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute: python37
```

**Comment by NilsIrl** [comment]
@FRidh

**Comment by FRidh** [comment]
I recall seeing this with poetry.

**Comment by d-goldin** [comment]
`bin/activate` tries to clear the potential command hashing for zsh and bash (see `hash [-lr] [-p filename] [-dt] [name]` in `bash(1)`). When using bash from the nixos module through `programs.bash` hashing is disabled per default, which makes a lot of sense for nix/os. This can be briefly tested doing something like;
```
$ set -o | grep hash
hashall        	off
```
A quick workaround could be adding `set -h` to the `shellHook` if, nix-shell is used.
I think this is likely something that should be fixed upstream by checking before trying to clear the cache and is more of a cosmetic issue.

**Comment by d-goldin** [comment]
I made a PR for upstream https://github.com/python/cpython/pull/17966/files but no idea if they're interested in this type of fixes, what it might be backported to or whether nixpkgs cares to patch the packaged versions.

**Comment by NilsIrl** [comment]
I don't think silencing the output is the right way to go. We are just dealing with symptoms.

I don't really understand what is going on though. If `set -h` makes sense then it is probably better.

**Comment by d-goldin** [comment]
@NilsIrl: It's not really silencing a symptom in this case - it's silencing a not applicable action. If you have a look at the linked PR you'll see that the traditional `virtualenv` has been doing it exactly like that. Enabling `set -h` _per default_ makes even less sense imho. But as mentioned, feel free to use that as a local workaround.

**Comment by d-goldin** [comment]
The fix has been merged upstream. Lets see where/when it trickles down.

**Comment by arianvp** [comment]
That patch is not enough as it makes the `activate` script return exit code 1 _silently_ 

I was bitten by this today by automation siently dying with no error whatsoever, and I tracked it back down to the PR by tracing bash scripts https://github.com/python/cpython/pull/17966/files :/

**Comment by d-goldin** [comment]
@arianvp: I agree that this would be generally saner and I was briefly contemplating it back then, but decided that it's safer to propose at least restoring the behaviour of virtualenv.

**Comment by prusnak** [comment]
@arianvp Will you open a PR against https://github.com/python/cpython? I see the master still not contains your suggestion.

**Comment by GuillaumeDesforges** [comment]
https://github.com/python/cpython/pull/17966 was merged, any idea when it's supposed to land?
