### ISSUE TITLE
Giving the loopback network interface an alias IP in configuration.nix seems tricky

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#7227]
I've tried the following:

``` nix
{
 networking.interfaces."lo:metadata".ip4 = [
    { address = "169.254.169.254"; prefixLength = 16; }
  ];
}
```

which should assign an alias (`ifconfig` happily accepts the colon syntax in NixOS). Instead it tells me: "invalid character ‘:’ in name ‘unit-network-addresses-lo:metadata.service'"

I also tried:

``` nix
{
  networking.interfaces.lo.ip4 = [
    { address = "127.0.0.1"; prefixLength = 8; }
    { address = "169.254.169.254"; prefixLength = 16; }
  ];
}
```

which doesn't throw an error but also doesn't get me an alias.

Is it not currently possible to alias the loopback interface via NixOS configuration, or am I missing something?

**Comment by domenkozar** [comment]
@wkennington

**Comment by Profpatsch** [comment]
(triage) any leads?

**Comment by copumpkin** [comment]
More than question I think it's a bug that it doesn't work. @edolstra, any thoughts?

**Comment by mweinelt** [comment]
Resolved in https://github.com/NixOS/nixpkgs/pull/28730

**Comment by dhess** [comment]
Sorry, is this actually resolved? I try this in my config:

```
networking.interfaces."lo:unbound".ip4 = [
  { address = "10.8.8.8"; prefixLength = 32; }
];
```

And I get this:

```
Oct 21 01:07:04 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start timed out.
Oct 21 01:07:04 host systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo:unbound.device.
-- Subject: Unit sys-subsystem-net-devices-lo:unbound.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sys-subsystem-net-devices-lo:unbound.device has failed.
-- 
-- The result is timeout.
Oct 21 01:07:04 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start failed with result 'timeout
Oct 21 01:09:52 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start timed out.
Oct 21 01:09:52 host systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo:unbound.device.
-- Subject: Unit sys-subsystem-net-devices-lo:unbound.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sys-subsystem-net-devices-lo:unbound.device has failed.
-- 
-- The result is timeout.
Oct 21 01:09:52 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start failed with result 'timeout
-- Reboot --
Oct 21 01:17:18 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start timed out.
Oct 21 01:17:18 host systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo:unbound.device.
-- Subject: Unit sys-subsystem-net-devices-lo:unbound.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sys-subsystem-net-devices-lo:unbound.device has failed.
-- 
-- The result is timeout.
Oct 21 01:17:18 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start failed with result 'timeout
Oct 21 01:19:41 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start timed out.
Oct 21 01:19:41 host systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo:unbound.device.
-- Subject: Unit sys-subsystem-net-devices-lo:unbound.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sys-subsystem-net-devices-lo:unbound.device has failed.
-- 
-- The result is timeout.
Oct 21 01:19:41 host systemd[1]: sys-subsystem-net-devices-lo:unbound.device: Job sys-subsystem-net-devices-lo:unbound.device/start failed with result 'timeout
```

If I run the setup script by hand, it works fine.

@copumpkin is this working for you now?

**Comment by Mic92** [comment]
use `lo` instead:

```nix
networking.interfaces."lo".ip4 = [
  { address = "10.8.8.8"; prefixLength = 32; }
];
```

**Comment by dhess** [comment]
I finally had a chance to follow up on this. Using the config that @Mic92 suggested above, I still get these errors:

```
-- Logs begin at Sun 2018-01-21 22:04:12 UTC. --
Feb 11 21:46:03 vpn-sjc-v systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/start timed out.
Feb 11 21:46:03 vpn-sjc-v systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo.device.
-- Subject: Unit sys-subsystem-net-devices-lo.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sys-subsystem-net-devices-lo.device has failed.
-- 
-- The result is timeout.
Feb 11 21:46:03 vpn-sjc-v systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/start failed with result 'timeout'.
-- Reboot --
Feb 11 21:48:29 vpn-sjc-v systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/start timed out.
Feb 11 21:48:29 vpn-sjc-v systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo.device.
-- Subject: Unit sys-subsystem-net-devices-lo.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sys-subsystem-net-devices-lo.device has failed.
-- 
-- The result is timeout.
Feb 11 21:48:29 vpn-sjc-v systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/start failed with result 'timeout'.
Feb 11 21:51:01 vpn-sjc-v systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/start timed out.
Feb 11 21:51:01 vpn-sjc-v systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo.device.
-- Subject: Unit sys-subsystem-net-devices-lo.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sys-subsystem-net-devices-lo.device has failed.
-- 
-- The result is timeout.
Feb 11 21:51:01 vpn-sjc-v systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/start failed with result 'timeout'.

```

`lo` *does* actually get the `10.8.8.8` address. However, boot-up and NixOps `deploy` takes a lot longer, presumably because of the timeouts. So something is still not quite right here.

**Comment by Mic92** [comment]
That device dependency `sys-subsystem-net-devices-lo.device` should be not added according to this source code:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces-scripted.nix#L80

Are you running the latest NixOS 17.09?

**Comment by dhess** [comment]
Ahh, no, I’m running `master` but from a few weeks ago. I’ll try again once I’ve updated.

**Comment by Mic92** [comment]
I still recommend to people to switch to `systemd-networkd` since the scripted module is just a hack...
well.

**Comment by dhess** [comment]
So with a recent masters, assigning an IP address to `lo` still causes `systemd` timeouts. However, the IP address does successfully get assigned.

**Comment by Mic92** [comment]
if the service assign ip addresses contains a `device` dependency, something went wrong.

**Comment by grahamc** [comment]
I see the same:

```
$ systemctl list-jobs
   JOB UNIT                                TYPE  STATE  
734400 network-interfaces.target           start waiting
734450 sys-subsystem-net-devices-lo.device start running
734449 network-link-lo.service             start waiting

3 jobs listed.

Jul 06 18:36:04 zoidberg systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/star>
Jul 06 18:38:07 zoidberg systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/star>
Jul 06 18:38:07 zoidberg systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo.device.
Jul 06 18:38:07 zoidberg systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/star>
Jul 06 18:40:09 zoidberg systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/star>
Jul 06 18:40:09 zoidberg systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo.device.
Jul 06 18:40:09 zoidberg systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/star>
Jul 06 18:50:18 zoidberg systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/star>
Jul 06 18:50:18 zoidberg systemd[1]: Timed out waiting for device sys-subsystem-net-devices-lo.device.
Jul 06 18:50:18 zoidberg systemd[1]: sys-subsystem-net-devices-lo.device: Job sys-subsystem-net-devices-lo.device/star>
```

**Comment by grahamc** [comment]
The bug appears to be here: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces.nix#L1056-L1065

compared to this: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces-scripted.nix#L73

**Comment by grahamc** [comment]
Testing this patch:

```
diff --git a/nixos/modules/tasks/network-interfaces.nix b/nixos/modules/tasks/network-interfaces.nix
index 95641c03b14..5743771a233 100644
--- a/nixos/modules/tasks/network-interfaces.nix
+++ b/nixos/modules/tasks/network-interfaces.nix
@@ -1098,7 +1098,7 @@ in
       };
     } // (listToAttrs (flip map interfaces (i:
       let
-        deviceDependency = if config.boot.isContainer
+        deviceDependency = if (config.boot.isContainer || i == "lo")
           then []
           else [ (subsystemDevice i.name) ];
       in
```
