### ISSUE TITLE
buildGoModule appears to fail to find a mod file, even when the go build/go install/go mod download works

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#75926]
**Describe the bug**

I'm using the latest Nixos Unstable revision: `d942688fc137169b577e7bf0c09e01a2ac919b73`.

My go project located here: https://github.com/MatrixAI/Golang-Demo. Is just a basic Go project that brings in 1 dependency:

```
require github.com/pelletier/go-toml v1.6.0
```

It then has a number of subpackages, and a `main.go` that just outputs some hello world outputs and calculations.

Using go 1.13, I'm able to run `go build`, `go install`, `go mod tidy`, `go mod download` perfectly.

However if I try to use `goBuildModule` to build, I end up with:

```
these derivations will be built:
  /nix/store/93ldirdj463bmpvj6aq0lc169mi6n849-golang-demo-0.0.1.drv
building '/nix/store/93ldirdj463bmpvj6aq0lc169mi6n849-golang-demo-0.0.1.drv'...
unpacking sources
unpacking source archive /nix/store/hnzl2wdcbyljzrr97nkd19bj022zxnla-Golang-Demo
source root is Golang-Demo
patching sources
configuring
building
Building subPackage .
go: github.com/pelletier/go-toml@v1.6.0: reading file:///nix/store/icppvv4fnn8w72gwhi3mb9b9fm6n7pzz-golang-demo-0.0.1-go-modules/github.com/pelletier/go-toml/@v/v1.6.0.mod: Not Found
builder for '/nix/store/93ldirdj463bmpvj6aq0lc169mi6n849-golang-demo-0.0.1.drv' failed with exit code 1
error: build of '/nix/store/93ldirdj463bmpvj6aq0lc169mi6n849-golang-demo-0.0.1.drv' failed
```

I tried with other version of go-toml, but the same problem occurs.

**To Reproduce**

1. `git clone https://github.com/MatrixAI/Golang-Demo.git`
2. `cd Golang-Demo`
3. `nix-build ./release.nix --attr application`

**Expected behavior**

It should just build `result` symlink with `bin/Golang-Demo`.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.80, Formbay ML 2 A, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by CMCDragonkai** [comment]
It turns out that the reason for this failure is because the `modSha256` was wrong. I updated the `modSha256` and the `nix-build` started to work again. Which is strange cause Nix never complained about `modSha256`. I don't think this `goBuildModule` is the most robust system, there seems to be impurities in it.

Anyway this is fixed now.

**Comment by fricklerhandwerk** [comment]
@CMCDragonkai This is actually still an open issue (which I can reproduce), since `buildGoModule` indeed does not point out that the hash is wrong.

**Comment by isubasinghe** [comment]
Can confirm that this is unfortunately still an issue, was helping out a person on the CNCF slack who couldn't get argo running because it was complaining about a missing go.mod file. 

I suggest this be reopened @r-ryantm

**Comment by pinpox** [comment]
I'm running into the same problem with [this build](https://github.com/pinpox/nixos-caddy-patched/blob/8b4602da9f79235ce5d81d2e87da0284a440645e/flake.nix)

It has `pkgs.lib.fakeSha256` set, but does not compain about it being wrong. Instead when running `nix buil` it fails with:

```
caddy> go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
caddy> go: downloading github.com/go-logfmt/logfmt v0.6.0
caddy> go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
caddy> go: downloading github.com/mattn/go-colorable v0.1.13
caddy> go: downloading github.com/mattn/go-isatty v0.0.19
caddy> internal error: failed to find embedded files of github.com/Microsoft/go-winio: //go:build comment without // +build comment
error: builder for '/nix/store/q71lfphwj6b5lymn7g4xg0hpmpgxph53-caddy-20231004-go-modules.drv' failed with exit code 1;
       last 10 log lines:
       > go: downloading github.com/jackc/pgservicefile v0.0.0-20221227161230-091c0ba34f0a
       > go: downloading github.com/golang/snappy v0.0.4
       > go: downloading github.com/golang/glog v1.1.2
       > go: downloading github.com/jackc/chunkreader/v2 v2.0.1
       > go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
       > go: downloading github.com/go-logfmt/logfmt v0.6.0
       > go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
       > go: downloading github.com/mattn/go-colorable v0.1.13
       > go: downloading github.com/mattn/go-isatty v0.0.19
       > internal error: failed to find embedded files of github.com/Microsoft/go-winio: //go:build comment without // +build comment
       For full logs, run 'nix log /nix/store/q71lfphwj6b5lymn7g4xg0hpmpgxph53-caddy-20231004-go-modules.drv'.
error: 1 dependencies of derivation '/nix/store/xwf8sz0fxhg3685d8afswx627dfxkdix-caddy-20231004.drv' failed to build
```

**Comment by katexochen** [comment]
This seems to be working fine for `vendorHash = lib.fakeHash`. Has anyone a reproducer for this on master?

**Comment by isubasinghe** [comment]
This always happens when the hash is wrong, I've taken to manually keeping the nix file up to date for myself. 

We need some way of automating this process though, or perhaps agreeing to a weekly/monthly cadence of updating the nix file.

**Comment by isubasinghe** [comment]
Its a bit difficult to keep dependencies up to date because of dependabot (which doesn't update Nix deps)
