### ISSUE TITLE
zip-archive test suite fails on Darwin because "libnatspec.0.dylib" cannot be loaded

### ISSUE THREAD

**Issue by nomosyn** [NixOS/nixpkgs#7675]
`nix-env -u` output + system info: 

https://gist.github.com/nomosyn/9e414bfbbbf50d7445f9

**Comment by domenkozar** [comment]
This should be fixed once channel updates.

**Comment by nomosyn** [comment]
nice :+1:  !

**Comment by peti** [comment]
Are we sure that this issue was fixed, really? It seems people do still have this problem.

**Comment by peti** [comment]
According to https://github.com/NixOS/nixpkgs/issues/7646, the problem still exists in 4cdb4a4fef93b54dd41aab93d333c703df4d5803. @domenkozar, do you happen to know which commit is supposed to fix this issue?

**Comment by domenkozar** [comment]
@peti, I was misinformed, apparently the problem still exists.

**Comment by peti** [comment]
No activity for 1 month ... does this issue still exist?

**Comment by nomosyn** [comment]
yes : https://gist.github.com/nomosyn/b7593625c5e77fc34ac1

**Comment by nomosyn** [comment]
After updating nixpkgs, it is fixed, so clothing. Thx!
