### ISSUE TITLE
Encrypted root filesystem regression

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#7859]
After I updated my system to nixpkgs master ef66f1536dcfd9a78757436807de98be31e6cb48, I can no longer boot due to an error related to the encrypted root. The error from the initrd is:

```
Cannot initialize device-mapper. Is dm_mod kernel module loaded?
starting device mapper and LVM...
Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
waiting for device /dev/mapper/enc-root to appear................
```
The related part of my system configuration is:
```
  fileSystems."/" =
    { device = "/dev/mapper/enc-root";
      fsType = "ext4";
    };
```

**Comment by ambrop72** [comment]
Picture of boot error:
![20150516_224223](https://cloud.githubusercontent.com/assets/2626481/7668110/2f3c256a-fc27-11e4-9171-48fa8b87852c.jpg)

**Comment by geerds** [comment]
same here

**Comment by geerds** [comment]
encrypted btrfs volume, [configs here](https://github.com/geerds/configs/blob/master/nixos/moon.nix)

![img_20150517_001149](https://cloud.githubusercontent.com/assets/1473909/7668180/6faddc30-fc2a-11e4-8054-e88a4f622b69.jpg)

**Comment by copumpkin** [comment]
I thought I'd seen a NixOS test for that functionality

**Comment by domenkozar** [comment]
@edolstra @wkennington thoughts?

**Comment by geerds** [comment]
@copumpkin We have a lot of installer tests but none of them with an encrypted root partition

**Comment by peti** [comment]
I have the same problem on my machine with a standard ext4 root file system; no btrfs, LVM, or any other fancy stuff is involved. The `nixos-unstable` channel version before that, 15.05pre61665.4c01e6d (Dingo), used to work fine.

**Comment by geerds** [comment]
@peti but still an encrypted volume?

maybe due to 8ca8b0868c419418cdddc612ef84f93f244bce90

**Comment by hiberno** [comment]
Same here. I am on `nixos-unstable-small`. The channel with 7bda733f8bb59c3efa13a374bad94ef74bd7f895 works, 97e5461f46b6e27cf3b3e18b63529d5a1483586e doesn't anymore. 

This is, btw, also true for decrypting volumes after a succesful boot and switch to the newer channel version. This doesn't work as well.

**Comment by devhell** [comment]
Can confirm, post-decryption of volumes doesn't work either. I get this when calling cryptsetup manually or when using `udisksctl`:
```
Error unlocking /dev/sd[XY]: Command-line `cryptsetup luksOpen "/dev/sd[XY]" "luks-super-long-uuid" ' exited with non-zero exit status 1: Cannot initialize device-mapper. Is dm_mod kernel module loaded?
```
And yes, `dm_mod` is loaded.

**Comment by peti** [comment]
I guess we should build and install a system with https://github.com/NixOS/nixpkgs/commit/8ca8b0868c419418cdddc612ef84f93f244bce90 revoked to see whether it makes a difference.

**Comment by geerds** [comment]
There was also a `libgcrypt` specific commit: a71f78acf71b4063be1912b8655ce53acb48f24e (it's a dependency of cryptsetup)

**Comment by geerds** [comment]
I think the reason is a71f78a

`cryptsetup` with current nixos-unstable channel (f93a8ee) is broken:
```
$ dd if=/dev/zero of=/tmp/encrypted.img bs=50M count=1
1+0 records in
1+0 records out
52428800 bytes (52 MB) copied, 0.0385183 s, 1.4 GB/s

$ sudo cryptsetup -q luksFormat /tmp/encrypted.img 
Enter passphrase: 

$ nix-build -A cryptsetup
[...]
/nix/store/qcw7y4jdd5hcna0j5fjpw3w4q4w5ij15-cryptsetup-1.6.7

$ sudo /nix/store/qcw7y4jdd5hcna0j5fjpw3w4q4w5ij15-cryptsetup-1.6.7/bin/cryptsetup luksOpen /tmp/encrypted.img encrypted
Cannot initialize device-mapper. Is dm_mod kernel module loaded?
```

After reverting 0b3af3074ef66724c2083ae0e9c6a0a5567be67a and a71f78acf71b4063be1912b8655ce53acb48f24e

```
$ git revert 0b3af30

$ git revert a71f78a

$ nix-build -A cryptsetup
[...]                                   
/nix/store/84594719cqqz8fgb7y5sp1b8qmjaniy5-cryptsetup-1.6.7

$ sudo /nix/store/84594719cqqz8fgb7y5sp1b8qmjaniy5-cryptsetup-1.6.7/bin/cryptsetup luksOpen /tmp/encrypted.img encrypted
Enter passphrase for /tmp/encrypted.img:

$ file /dev/mapper/encrypted 
/dev/mapper/encrypted: symbolic link to `../dm-1'
```

**Comment by geerds** [comment]
@wkennington ping :smirk:

**Comment by devhell** [comment]
Is it a `cryptsetup/libgcrypt` problem? Or does the problem lie with the expression?

**Comment by jcumming** [comment]
This is related to http://comments.gmane.org/gmane.linux.kernel.device-mapper.dm-crypt/7531 -- the libgcrypt used by cryptsetup needs to have libpcap disabled.

**Comment by matthiasbeyer** [comment]
I just hit the very same issue. i have ext4 on a SSD and two HDDs, no LVM involved. I'm back on 2d8cfe7 plus my local patches for some package updates because of this. 

I guess the issue is solved but the channel is not updated for this yet, is it?

**Comment by peti** [comment]
@matthiasbeyer, yes, exactly.

**Comment by anderspapitto** [comment]
for anyone else who needs to work around this before the channel updates, it's enough to cherry-pick fd588f

**Comment by flosse** [comment]
thx @anderspapitto

**Comment by fare** [comment]
Same issue, here, and it seems the advertised fix isn't working for me.

I added kernelParams = [ "boot.shell_on_fail" ]; so I could debug the issue. The cryptsetup on my initrd is 1.6.7 indeed rather than 1.6.3, so it looks like I do have change fd588f9 in my channels. Yet I still get the infamous "Cannot initialize device-mapper. Is dm_mod kernel module loaded?" error message when trying to cryptsetup luksOpen /dev/sdb2 cryptnix, which I believe is the failing boot step. lsmod shows that dm_mod is loaded, and dmesg | less shows that device-mapper is initialised and that sdb is detected, etc.

**Comment by fare** [comment]
Not sure whether 86e9279 is included, though. Probably not. Will try again...

**Comment by tohl** [comment]
François-René Rideau <notifications@github.com> writes:
> Not sure whether 86e9279 is included, though. Probably not. Will
> try again...

I am using nixos-unstable channel and that fix is not included there
yet.  Not sure how long does it take for unstable to pick commits like
this, this commit has been in the master for some time already.

I simply copied the the cryptsetup.nix file from master to
/etc/nixos/cryptsetup.nix and in my /etc/nixos/configuration.nix
included the following:

  nixpkgs.config.packageOverrides = pkgs: {
    cryptsetup = pkgs.callPackage ./cryptsetup.nix {};
  };

This fixed the issue for me.
