### ISSUE TITLE
Neovim (luajitPackages.luv) does not install correctly

### ISSUE THREAD

**Issue by y-usuzumi** [NixOS/nixpkgs#80704]
**Describe the bug**
I have neovim in my systemPackages, I did `nix-channel --update` and `nixos-rebuild switch` today and it stuck at building luajit:

**To Reproduce**
1. Add `neovim` to `environment.systemPackages`
2. Run `nix-channel --update`
3. Run `nixos-rebuild switch`

**Expected behavior**
The system should upgrade properly.

**Additional context**
Output:

```
# nixos-rebuild switch
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/r1r1sprc1r1yb29w17vfyfnmi2r09zjv-luajit-2.1.0-beta3-luv-1.34.1-1.drv
  /nix/store/0xasdnwd3fvxzl7qrs2zf5wsh2f86yrj-neovim-unwrapped-0.4.3.drv
  /nix/store/6v9iv9jrlwik9a3m5v4hn6gwhph1sc27-neovim-0.4.3.drv
  /nix/store/chlys5ihvxllkfdrpdxrssgfycyjwlb3-system-path.drv
  /nix/store/knjjhw14i55dnb0f34k9lxjks4hkr8jz-unit-polkit.service.drv
  /nix/store/ys2y4qjp6x78813l7zjr0iyfd2p2l2c6-dbus-1.drv
  /nix/store/nc4fxkfdmkr9vdhp1divs0w72l12q2ij-unit-dbus.service.drv
  /nix/store/wbdxd6s8vbhv8yi3hpv2l4bqb4h67c9n-unit-systemd-fsck-.service.drv
  /nix/store/0x79iyhxplm1jajiffzkhpklrsvkblfb-system-units.drv
  /nix/store/an5xzvddamzanbh8800bn3c6pvg6aa2b-unit-dbus.service.drv
  /nix/store/yyaj6djyh21lrqsv6aiban63q1c2y8xz-user-units.drv
  /nix/store/kkhv203dzw38y5lsb1c8h9mdskklnlxf-etc.drv
  /nix/store/xdifd63sygqxswwh67vm1dyh95dl72yn-nixos-system-DCHORUS-LEGION-NIXOS-20.09pre213994.e2b4abe3c8f.drv
building '/nix/store/r1r1sprc1r1yb29w17vfyfnmi2r09zjv-luajit-2.1.0-beta3-luv-1.34.1-1.drv'...
unpacking sources
unpacking source archive /nix/store/f0az73f8fi7fp7cz55iapzwr0wh1kd93-luv-1.34.1-1.src.rock

Done. You may now enter directory 
luv-1.34.1-1/luv-1.34.1-1
and type 'luarocks make' to build.
source root is ./luv-1.34.1-1/luv-1.34.1-1
setting SOURCE_DATE_EPOCH to timestamp 1579323846 of file ./luv-1.34.1-1/luv-1.34.1-1/src/work.c
patching sources
configuring
building
patching script interpreter paths in .
./deps/lua-compat-5.3/tests/test.lua: interpreter directive changed from "/usr/bin/env lua" to "/nix/store/zhsgiagaqx27hp5j94hy6i46rv3gnh75-luajit-2.1.0-beta3/bin/lua"
installing

luv 1.34.1-1 depends on lua >= 5.1 (5.1-1 provided by VM)
Warning: unmatched variable LUA_LIBDIR
-- The C compiler identification is GNU 9.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /nix/store/fqhjxf9ii4w4gqcsx59fyw2vvj91486a-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/fqhjxf9ii4w4gqcsx59fyw2vvj91486a-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/fqhjxf9ii4w4gqcsx59fyw2vvj91486a-gcc-wrapper-9.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found LIBUV: /nix/store/gk304dpcw0x4fx7vp3di9v1lv9s8rhdc-libuv-1.34.2/lib/libuv.so  
-- Lua: using information from luarocks
-- LUA_LIBDIR: 
-- LUA_INCDIR: /nix/store/zhsgiagaqx27hp5j94hy6i46rv3gnh75-luajit-2.1.0-beta3/include/luajit-2.1
-- LUA: /nix/store/zhsgiagaqx27hp5j94hy6i46rv3gnh75-luajit-2.1.0-beta3/bin/luajit
-- Lua library: LUA_LIBRARIES-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /build/luv-1.34.1-1/luv-1.34.1-1/build.luarocks
Scanning dependencies of target luv
[ 50%] Building C object CMakeFiles/luv.dir/src/luv.c.o
[100%] Linking C shared library libluv.so
[100%] Built target luv
[100%] Built target luv
Install the project...
-- Install configuration: ""
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so.1.34.1
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so.1
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/pkgconfig/libluv.pc
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/luv.h
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/util.h
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/lhandle.h
-- Installing: /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/lreq.h
cp: cannot stat '/nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so': No such file or directory

Error: Failed copying /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so to /nix/store/s7kkgp1i5nl383wkc392zwpb88fl03cr-luajit-2.1.0-beta3-luv-1.34.1-1/lib/lua/5.1/libluv.so
builder for '/nix/store/r1r1sprc1r1yb29w17vfyfnmi2r09zjv-luajit-2.1.0-beta3-luv-1.34.1-1.drv' failed with exit code 1
cannot build derivation '/nix/store/0xasdnwd3fvxzl7qrs2zf5wsh2f86yrj-neovim-unwrapped-0.4.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6v9iv9jrlwik9a3m5v4hn6gwhph1sc27-neovim-0.4.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/chlys5ihvxllkfdrpdxrssgfycyjwlb3-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xdifd63sygqxswwh67vm1dyh95dl72yn-nixos-system-DCHORUS-LEGION-NIXOS-20.09pre213994.e2b4abe3c8f.drv': 1 dependencies couldn't be built
error: build of '/nix/store/xdifd63sygqxswwh67vm1dyh95dl72yn-nixos-system-DCHORUS-LEGION-NIXOS-20.09pre213994.e2b4abe3c8f.drv' failed
```

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.20, NixOS, 20.09pre213994.e2b4abe3c8f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre213994.e2b4abe3c8f"`
 - channels(kj): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment]
Possible fix is in #80369 . There was already an open issue about it (#79870) but from an unclear reason people have reached the conclusion it was fixed on latest master.

**Comment by doronbehar** [comment]
Oh I meant https://github.com/NixOS/nixpkgs/pull/80528, not https://github.com/NixOS/nixpkgs/pull/80369 .

**Comment by vcunat** [comment]
Well, I agree with that conclusion.  On e2b4abe3c8f the build is broken with the error above and on current master it isn't.

**Comment by y-usuzumi** [comment]
Yea right. For me on NixOS I tried with the nixpkgs-unstable channel and could install successfully. The nixos-unstable still fails yet.

**Comment by mweinelt** [comment]
I have this the same issue and somehow bisected it to

```
7aee5b838b25a353a453aa7db0560390dc8089cf is the first bad commit
commit 7aee5b838b25a353a453aa7db0560390dc8089cf
Author: Matthieu Coudron <mattator@gmail.com>
Date:   Tue Feb 25 17:34:29 2020 +0100

    build-lua-package: dont patchShebangs folder
    
    It can be source of trouble for some read-only folders (libluv for
    instance) and slow down install.

 pkgs/development/interpreters/lua-5/build-lua-package.nix | 2 --
 1 file changed, 2 deletions(-)
```

<details><summary>Build log</summary>
<code>
building '/nix/store/lxahff1nlq1zlc0flsgllcjl5im9pzyd-etc-os-release.drv'...
building '/nix/store/13b9s9iqkp1sgr7rln7m1qf4790y5dfc-lua5.2-luasocket-3.0rc1-2.drv' on 'ssh://hexa@phoibe.cysec.de'...
building '/nix/store/8kvhvsifpmi1b0l37njwm355b8z755vf-luajit-2.1.0-beta3-luv-1.34.1-1.drv' on 'ssh://hexa@phoibe.cysec.de'...
building '/nix/store/s42dc98hwzdk8pgmndngjrn9ykzbpp06-luajit-2.1.0-beta3-luv-1.34.1-1.drv' on 'ssh://hexa@phoibe.cysec.de'...
unpacking sources
unpacking source archive /nix/store/1j76bhk1vndanwrhizv01az62vs5ccx0-luasocket-3.0rc1-2.src.rock

Done. You may now enter directory
luasocket-3.0rc1-2/luasocket-3.0-rc1
and type 'luarocks make' to build.
source root is ./luasocket-3.0rc1-2/luasocket-3.0-rc1
setting SOURCE_DATE_EPOCH to timestamp 1371209252 of file ./luasocket-3.0rc1-2/luasocket-3.0-rc1/win32.cmd
patching sources
configuring
building
installing

luasocket 3.0rc1-2 depends on lua >= 5.1 (5.2-1 provided by VM)
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/buffer.c -o src/buffer.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/auxiliar.c -o src/auxiliar.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/options.c -o src/options.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
src/options.c: In function 'opt_meth_setoption':
src/options.c:41:43: warning: '%.35s' directive writing up to 35 bytes into a region of size 25 [-Wformat-overflow=]
   41 |         sprintf(msg, "unsupported option `%.35s'", name);
      |                                           ^~~~~
In file included from /nix/store/6gv97caz9j97bgq4kb7wjxs75znzd6bb-glibc-2.30-dev/include/stdio.h:867,
                 from /nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include/lauxlib.h:13,
                 from src/options.c:7:
/nix/store/6gv97caz9j97bgq4kb7wjxs75znzd6bb-glibc-2.30-dev/include/bits/stdio2.h:36:10: note: '__builtin___sprintf_chk' output between 22 and 57 bytes into a destination of size 45
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/timeout.c -o src/timeout.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
unpacking sources
unpacking source archive /nix/store/f0az73f8fi7fp7cz55iapzwr0wh1kd93-luv-1.34.1-1.src.rock
copying path '/nix/store/7dgij5rsd2acxi2r66j7q5z45bzf2379-hook' from 'https://cache.nixos.org'...
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/io.c -o src/io.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
building '/nix/store/ym2cva5iwqg72dp5krqf7bg6c4s57v88-issue.drv'...
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
unpacking sources
building '/nix/store/p2blmd8v8h56z0896xpd6ivghzc8ssqr-luajit-2.1.0-beta3-env.drv'...
unpacking source archive /nix/store/f0az73f8fi7fp7cz55iapzwr0wh1kd93-luv-1.34.1-1.src.rock
created 16 symlinks in user environment
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/unix.c -o src/unix.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
building '/nix/store/ipf6j5xggx705pm74hpp4y7cdy7d7iii-nixos-version.drv'...
building '/nix/store/22qljv3s4fs9y3h7vavrzibjq8al3y9z-system-path.drv'...
gcc -shared -o socket/unix.so src/buffer.o src/auxiliar.o src/options.o src/timeout.o src/io.o src/usocket.o src/unix.o
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/luasocket.c -o src/luasocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/timeout.c -o src/timeout.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/buffer.c -o src/buffer.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/io.c -o src/io.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/auxiliar.c -o src/auxiliar.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/options.c -o src/options.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
src/options.c: In function 'opt_meth_setoption':
src/options.c:41:43: warning: '%.35s' directive writing up to 35 bytes into a region of size 25 [-Wformat-overflow=]
   41 |         sprintf(msg, "unsupported option `%.35s'", name);
      |                                           ^~~~~
In file included from /nix/store/6gv97caz9j97bgq4kb7wjxs75znzd6bb-glibc-2.30-dev/include/stdio.h:867,
                 from /nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include/lauxlib.h:13,
                 from src/options.c:7:
/nix/store/6gv97caz9j97bgq4kb7wjxs75znzd6bb-glibc-2.30-dev/include/bits/stdio2.h:36:10: note: '__builtin___sprintf_chk' output between 22 and 57 bytes into a destination of size 45
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/inet.c -o src/inet.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
created 16963 symlinks in user environment
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/except.c -o src/except.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/select.c -o src/select.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/tcp.c -o src/tcp.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
building '/nix/store/7pf2ip9cn7jfpl21f8jfggk379zhq6yr-dbus-1.drv'...
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/udp.c -o src/udp.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -shared -o socket/core.so src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/usocket.o
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/buffer.c -o src/buffer.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/auxiliar.c -o src/auxiliar.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/options.c -o src/options.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
src/options.c: In function 'opt_meth_setoption':
src/options.c:41:43: warning: '%.35s' directive writing up to 35 bytes into a region of size 25 [-Wformat-overflow=]
   41 |         sprintf(msg, "unsupported option `%.35s'", name);
      |                                           ^~~~~
In file included from /nix/store/6gv97caz9j97bgq4kb7wjxs75znzd6bb-glibc-2.30-dev/include/stdio.h:867,
                 from /nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include/lauxlib.h:13,
                 from src/options.c:7:
/nix/store/6gv97caz9j97bgq4kb7wjxs75znzd6bb-glibc-2.30-dev/include/bits/stdio2.h:36:10: note: '__builtin___sprintf_chk' output between 22 and 57 bytes into a destination of size 45
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/timeout.c -o src/timeout.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/io.c -o src/io.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))

Done. You may now enter directory
luv-1.34.1-1/luv-1.34.1-1
and type 'luarocks make' to build.
source root is ./luv-1.34.1-1/luv-1.34.1-1
setting SOURCE_DATE_EPOCH to timestamp 1579323846 of file ./luv-1.34.1-1/luv-1.34.1-1/src/work.c
patching sources
configuring
building
installing

luv 1.34.1-1 depends on lua >= 5.1 (5.1-1 provided by VM)
Warning: unmatched variable LUA_LIBDIR
-- The C compiler identification is GNU 9.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found LIBUV: /nix/store/w89ndqsb7ig22mw5hk7k7zfvxmhx44xb-libuv-1.34.2/lib/libuv.so
-- Lua: using information from luarocks
-- LUA_LIBDIR:
-- LUA_INCDIR: /nix/store/1m8vh1byjnjmjkpdidcqc37cykgsqjap-luajit-2.1.0-beta3/include/luajit-2.1
-- LUA: /nix/store/1m8vh1byjnjmjkpdidcqc37cykgsqjap-luajit-2.1.0-beta3/bin/luajit
-- Lua library: LUA_LIBRARIES-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /build/luv-1.34.1-1/luv-1.34.1-1/build.luarocks
Scanning dependencies of target luv
[ 50%] Building C object CMakeFiles/luv.dir/src/luv.c.o

Done. You may now enter directory
luv-1.34.1-1/luv-1.34.1-1
and type 'luarocks make' to build.
source root is ./luv-1.34.1-1/luv-1.34.1-1
setting SOURCE_DATE_EPOCH to timestamp 1579323846 of file ./luv-1.34.1-1/luv-1.34.1-1/src/work.c
patching sources
configuring
building
installing

luv 1.34.1-1 depends on lua >= 5.1 (5.1-1 provided by VM)
Warning: unmatched variable LUA_LIBDIR
-- The C compiler identification is GNU 9.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc
-- Check for working C compiler: /nix/store/1kn7fi3hhi33jms3113riyzwyn2yqpqd-gcc-wrapper-9.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
building '/nix/store/9rc57n7mwq9mdif6sbxg79wcgp2rypd8-unit-polkit.service.drv'...
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/serial.c -o src/serial.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found LIBUV: /nix/store/w89ndqsb7ig22mw5hk7k7zfvxmhx44xb-libuv-1.34.2/lib/libuv.so
-- Lua: using information from luarocks
-- LUA_LIBDIR:
-- LUA_INCDIR: /nix/store/1m8vh1byjnjmjkpdidcqc37cykgsqjap-luajit-2.1.0-beta3/include/luajit-2.1
-- LUA: /nix/store/1m8vh1byjnjmjkpdidcqc37cykgsqjap-luajit-2.1.0-beta3/bin/luajit
-- Lua library: LUA_LIBRARIES-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /build/luv-1.34.1-1/luv-1.34.1-1/build.luarocks
gcc -shared -o socket/serial.so src/buffer.o src/auxiliar.o src/options.o src/timeout.o src/io.o src/usocket.o src/serial.o
Scanning dependencies of target luv
building '/nix/store/ihahbh857b7gl1qz73f19yjkcmwk3wsp-unit-dbus.service.drv'...
gcc -O2 -fPIC -I/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/include -c src/mime.c -o src/mime.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
[ 50%] Building C object CMakeFiles/luv.dir/src/luv.c.o
building '/nix/store/iwkkfip878g59zn5c4ljbyrsaiy0pqym-unit-dbus.service.drv'...
gcc -shared -o mime/core.so src/mime.o
building '/nix/store/zd1grhk58pl7h21myklqhz071npdakjw-unit-systemd-fsck-.service.drv'...
building '/nix/store/hzxx0x14im8lyx627bzanfmpskcgn9y0-user-units.drv'...
No existing manifest. Attempting to rebuild...
luasocket 3.0rc1-2 is now installed in /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2 (license: MIT)

post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2
shrinking /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/lib/lua/5.2/mime/core.so
shrinking /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/lib/lua/5.2/socket/serial.so
shrinking /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/lib/lua/5.2/socket/core.so
shrinking /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/lib/lua/5.2/socket/unix.so
strip is /nix/store/ffi3j388c39qbbskfqg1zw0x2lmbzhnk-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/lib
patching script interpreter paths in /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/tcp-getoptions: interpreter directive changed from "/usr/bin/env lua" to "/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/bin/lua"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/find-connect-limit: interpreter directive changed from "/usr/bin/env lua" to "/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/bin/lua"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/cgi/cat: interpreter directive changed from "/bin/sh" to "/nix/store/1iaxkm0941nj1m4m5g4fxgg4cq5jckf0-bash-4.4-p23/bin/sh"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/cgi/cat-index-html: interpreter directive changed from "/bin/sh" to "/nix/store/1iaxkm0941nj1m4m5g4fxgg4cq5jckf0-bash-4.4-p23/bin/sh"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/cgi/query-string: interpreter directive changed from "/bin/sh" to "/nix/store/1iaxkm0941nj1m4m5g4fxgg4cq5jckf0-bash-4.4-p23/bin/sh"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/cgi/redirect-loop: interpreter directive changed from "/bin/sh" to "/nix/store/1iaxkm0941nj1m4m5g4fxgg4cq5jckf0-bash-4.4-p23/bin/sh"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/cgi/env: interpreter directive changed from "/bin/sh" to "/nix/store/1iaxkm0941nj1m4m5g4fxgg4cq5jckf0-bash-4.4-p23/bin/sh"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/cgi/request-uri: interpreter directive changed from "/bin/sh" to "/nix/store/1iaxkm0941nj1m4m5g4fxgg4cq5jckf0-bash-4.4-p23/bin/sh"
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/udp-zero-length-send: interpreter directive changed from "/usr/bin/lua" to "/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/bin/lua"
[100%] Linking C shared library libluv.so
/nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2/luasocket-3.0rc1-2-rocks/luasocket/3.0rc1-2/test/udp-zero-length-send-recv: interpreter directive changed from "/usr/bin/lua" to "/nix/store/dmsnsn318cpbzdx3c2cbp0bslhq5gfd8-lua-5.2.4/bin/lua"
[100%] Built target luv
checking for references to /build/ in /nix/store/hbq3z7vvk953y570kingryfsqgwh0ny1-lua5.2-luasocket-3.0rc1-2...
[100%] Built target luv
Install the project...
-- Install configuration: ""
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so.1.34.1
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so.1
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/pkgconfig/libluv.pc
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/luv.h
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/util.h
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/lhandle.h
-- Installing: /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/include/luv/lreq.h
cp: cannot stat '/nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so.1': No such file or directory

Error: Failed copying /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/luv-1.34.1-1-rocks/luv/1.34.1-1/lib/libluv.so.1 to /nix/store/xbkg5195c34l60736cm8y06kvy295y29-luajit-2.1.0-beta3-luv-1.34.1-1/lib/lua/5.1/libluv.so.1
[100%] Linking C shared module luv.so
builder for '/nix/store/8kvhvsifpmi1b0l37njwm355b8z755vf-luajit-2.1.0-beta3-luv-1.34.1-1.drv' failed with exit code 1
error: build of '/nix/store/8kvhvsifpmi1b0l37njwm355b8z755vf-luajit-2.1.0-beta3-luv-1.34.1-1.drv' on 'ssh://hexa@phoibe.cysec.de' failed: builder for '/nix/store/8kvhvsifpmi1b0l37njwm355b8z755vf-luajit-2.1.0-beta3-luv-1.34.1-1.drv' failed with exit code 1
builder for '/nix/store/8kvhvsifpmi1b0l37njwm355b8z755vf-luajit-2.1.0-beta3-luv-1.34.1-1.drv' failed with exit code 1
cannot build derivation '/nix/store/qn7dwxkkq8badi1m45pq9bisgdmw3xk8-neovim-unwrapped-0.4.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z4ax249prsjdndbrasq4v295sm7m221w-neovim-0.4.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ykgkzg32jxc0hd54w5fyza2cqjg3hjb5-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/chhz1brblci05a0yjz1smvzddnfard69-home-manager-generation.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/9yl697djccv0d3hngx6wp0npvj49xhcv-activate-hexa.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m5abw8ypzwmjqby008mghivhg4l38p6l-unit-home-manager-hexa.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xpynlf0aa28xlyjriil9n5dyzppn64wv-system-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1g0j4cr4y6m5jv6gbr6jxgvq7mbk3mrq-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z2w7fsq9g578z7jfvgy73lj5pndj8fqm-nixos-system-nyx-20.09.git.7aee5b838b2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/z2w7fsq9g578z7jfvgy73lj5pndj8fqm-nixos-system-nyx-20.09.git.7aee5b838b2.drv' failed
</code>
</details>
