### ISSUE TITLE
nixos-unstable: postgresql cannot open postgresql.conf permission denied

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#8451]
After rebooting today postgresql could not be started and gave me this error: 

```
Jun 21 23:44:26 nixos postgres[9337]: FATAL:  the database system is starting up
Jun 21 23:44:26 nixos postgres[9337]: LOG:  database system was interrupted; last known up at 2015-06-21 12:00:04 GMT
Jun 21 23:44:26 nixos postgres[9337]: FATAL:  could not open file "/nix/store/zc56v89gqvgmibfhqqp5c71s827ayhmw-postgresql.conf": Permission denied
Jun 21 23:44:26 nixos postgres[9337]: LOG:  startup process (PID 9349) exited with exit code 1
Jun 21 23:44:26 nixos postgres[9337]: LOG:  aborting startup due to startup process failure
Jun 21 23:44:26 nixos systemd[1]: postgresql.service: main process exited, code=exited, status=1/FAILURE
Jun 21 23:44:26 nixos postgresql-post-start[9338]: /nix/store/sl792mpfp7fml43gn9v5x1g7i0134nh6-unit-script/bin/postgresql-post-start: line 3: kill: (9
Jun 21 23:44:26 nixos systemd[1]: postgresql.service: control process exited, code=exited status=1
Jun 21 23:44:26 nixos systemd[1]: Failed to start PostgreSQL Server.
Jun 21 23:44:26 nixos systemd[1]: Unit postgresql.service entered failed state.
Jun 21 23:44:26 nixos systemd[1]: postgresql.service failed.
```

My system:

``` bash
$ nixos-version
15.06pre64030.e1af50c (Dingo)
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
```

I'm only using the minimal arguments for the postgresql service: 

``` nix
    services.postgresql = {
      enable  = true;
      package = pkgs.postgresql;
    };
```

Contents of `/var/db/postgresql`:

``` bash
# ls -la
total 64
drwx------ 14 postgres postgres 4096 Jun 21 23:44 .
drwxr-xr-x  4 root     root     4096 Jun 10 21:41 ..
drwx------  8 postgres postgres 4096 Jun 21 13:54 base
drwx------  2 postgres postgres 4096 Jun 21 13:56 global
drwx------  2 postgres postgres 4096 Apr  3 15:06 pg_clog
drwx------  4 postgres postgres 4096 Apr  3 15:06 pg_multixact
drwx------  2 postgres postgres 4096 Jun 21 23:44 pg_notify
drwx------  2 postgres postgres 4096 Apr  3 15:06 pg_serial
drwx------  2 postgres postgres 4096 Apr  3 15:06 pg_snapshots
drwx------  2 postgres postgres 4096 Jun 21 21:57 pg_stat_tmp
drwx------  2 postgres postgres 4096 Apr  3 15:06 pg_subtrans
drwx------  2 postgres postgres 4096 Apr  3 15:06 pg_tblspc
drwx------  2 postgres postgres 4096 Apr  3 15:06 pg_twophase
-rw-------  1 postgres postgres    4 Apr  3 15:06 PG_VERSION
drwx------  3 postgres postgres 4096 Apr  3 15:06 pg_xlog
lrwxrwxrwx  1 root     root       59 Jun 21 23:44 postgresql.conf -> /nix/store/zc56v89gqvgmibfhqqp5c71s827ayhmw-postgresql.conf
-rw-------  1 postgres postgres   75 Jun 21 23:44 postmaster.opts
```

Permissions of the file that could not be opened:

``` bash
# ls -la /nix/store/zc56v89gqvgmibfhqqp5c71s827ayhmw-postgresql.conf 
-r--r--r-- 1 root nixbld 182 Jan  1  1970 /nix/store/zc56v89gqvgmibfhqqp5c71s827ayhmw-postgresql.conf
```

I have tried to remove the postgresql service, ran `nixos-rebuild switch`, clean the store with `nix-collect-garbage` and `sudo nix-collect-garbage -d`, then finally enabling postgresql service and running `nixos-rebuild switch`. To see whether the config files would be created anew and the permission problem could be solved. That did not solve the problem however. 

I can read the file in question as a normal user.

**Comment by dezgeg** [comment]
Maybe https://wiki.postgresql.org/wiki/May_2015_Fsync_Permissions_Bug is related?

**Comment by calvinchengx** [comment]
Ran into the same problem

**Comment by wkennington** [comment]
It's fixed in master.

**Comment by calvinchengx** [comment]
which commit was that?

**Comment by calvinchengx** [comment]
Ok, git cherry picking this commit https://github.com/NixOS/nixpkgs/commit/c66be6378d8bbcea271b2d2102741fdda87ec8fe solved my problem on nixos-unstable. Thanks for letting me know it's fixed in master.

**Comment by calvinchengx** [comment]
A new problem surfaced. While postgresql does work and start up properly the first time it is installed, I am getting the same error if I shutdown my nixos instance and boot it up.

And to resolve that, I have to delete the entire `/var/db/postgresql` directory and reinstall postgresql again.  So the problem isn't solved. I am surprised we are not getting more bug reports from other users, who are using postgresql on NixOS.

**Comment by wkennington** [comment]
Works when rebuilding / rebooting for me

**Comment by seagreen** [comment]
Fixed for me in unstable.

**Comment by xor-xor** [comment]
@calvinchengx and @wkennington: same situation here - I had to delete `/var/db/postgresql` dir and reinstall postgresql to make it work after restart.
```
$ nixos-version
16.03pre71289.7ae05ed (Emu)
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
```
Relevant part from `/etc/nixos/configuration.nix`:
```
services.postgresql = {
  enable = true;
  package = pkgs.postgresql;
};
```

**Comment by flosse** [comment]
I just enabled the `postgresql` on NixOS `16.03.767.d3456dc (Emu)` and it doesn't work (`could not create lock file "/tmp/.s.PGSQL.5432.lock": Permission denied`). 
How can I fix that?

```
warning: the following units failed: postgresql.service

● postgresql.service - PostgreSQL Server
   Loaded: loaded (/nix/store/dq5z1svjvsryy44n73rbxzam6zn4s365-unit-postgresql.service/postgresql.service; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fr 2016-05-13 01:08:26 CEST; 19ms ago
  Process: 3587 ExecStartPost=/nix/store/4s64g4clks7h5sbnkf1b111m5kim61gv-unit-script/bin/postgresql-post-start (code=exited, status=1/FAILURE)
  Process: 3586 ExecStart=/nix/store/q59q1zaxkj84wg8hqgg5k8i87kblafj8-unit-script/bin/postgresql-start (code=exited, status=1/FAILURE)
  Process: 3581 ExecStartPre=/nix/store/yrvcywfydwaa7f26z787lafkb85y81zx-unit-script/bin/postgresql-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 3586 (code=exited, status=1/FAILURE)

Mai 13 01:08:26 flosse postgresql-start[3586]:     postgres -D /var/db/postgresql
Mai 13 01:08:26 flosse postgresql-start[3586]: or
Mai 13 01:08:26 flosse postgresql-start[3586]:     pg_ctl -D /var/db/postgresql -l logfile start
Mai 13 01:08:26 flosse postgresql-start[3586]: FATAL:  could not create lock file "/tmp/.s.PGSQL.5432.lock": Permission denied
Mai 13 01:08:26 flosse systemd[1]: postgresql.service: Main process exited, code=exited, status=1/FAILURE
Mai 13 01:08:26 flosse postgresql-post-start[3587]: /nix/store/4s64g4clks7h5sbnkf1b111m5kim61gv-unit-script/bin/postgresql-post-start: Zeile 3: kill: (3586) - No such process
Mai 13 01:08:26 flosse systemd[1]: postgresql.service: Control process exited, code=exited status=1
Mai 13 01:08:26 flosse systemd[1]: Failed to start PostgreSQL Server.
Mai 13 01:08:26 flosse systemd[1]: postgresql.service: Unit entered failed state.
Mai 13 01:08:26 flosse systemd[1]: postgresql.service: Failed with result 'exit-code'.

```

**Comment by spinus** [comment]
With https://github.com/NixOS/nixpkgs/pull/22655 should be easier to test with multiple postgresql versions. If you know how to reproduce this bug, we could add this to the test case.

**Comment by Ekleog** [comment]
(triage) is this still happening to anyone?

**Comment by mherzl** [comment]
@Ekleog yes it is happening to me. I just came across this thread after running into the issue. Am still trying to exhaust my options in troubleshooting it.

**Comment by mherzl** [comment]
For me, the issue was resolved by changing my `system.stateVersion` (described [here](https://nixos.wiki/wiki/PostgreSQL)) from 17.03 to 17.09 in my `/etc/nixos/configuration.nix`.

I had previously upgraded `postgresql` from 9.4 to 9.5+, carefully dumping and restoring my data as described [here](https://stackoverflow.com/questions/51688193/how-to-upgrade-postgresql-in-nixos).

**Comment by Ekleog** [comment]
So it sounds like this issue was fixed between 17.03 and 17.09 (postgresql upgrades being blocked on `stateVersion`).

As a consequence, I guess it's time to close this issue?

Thank you for your feedback, @mherzl!
