### ISSUE TITLE
python-gevent broken on Darwin

### ISSUE THREAD

**Issue by dmalikov** [NixOS/nixpkgs#8569]
```
these derivations will be built:
  /nix/store/c9jdfph8wmyjm83748bm99bb5djcdw4l-python2.7-gevent-1.0.2.drv
  /nix/store/i0vr126729q5w2zcy775jz66hbpy4hq9-python2.7-geventhttpclient-1.1.0.drv
  /nix/store/hspbwcmfrdah3q72rxqj0qrjrfwxhi82-python2.7-dulwich-0.10.1a.drv
  /nix/store/brl2n8ljrghzkld26lr1840wy6ng830r-python2.7-hg-git-0.8.1.drv
  /nix/store/pmcgjc1nn78vcdp7zs2300v5zzb8nkg3-mercurial-3.3.3.drv
  /nix/store/p354mipadfp533p05zwm84i5f3664wfq-nix-prefetch-scripts.drv
  /nix/store/z2kxfgmh5c9brsany50ky3fw2p7nxh9a-cabal2nix-20150531.drv
building path(s) ‘/nix/store/s04p3634mpqv5gxsadsza74bx7ca1byy-python2.7-gevent-1.0.2’
unpacking sources
unpacking source archive /nix/store/m0k8dcbg5q952x3qxs9ngm0spz0fbvr6-gevent-1.0.2.tar.gz
source root is gevent-1.0.2
patching sources
configuring
building
running build
running build_py
creating build
creating build/lib.macosx-10.7-x86_64-2.7
creating build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/_ssl2.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/_sslgte279.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/_threading.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/backdoor.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/baseserver.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/coros.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/event.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/fileobject.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/greenlet.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/hub.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/local.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/lock.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/monkey.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/os.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/pool.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/pywsgi.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/queue.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/resolver_ares.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/resolver_thread.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/select.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/server.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/socket.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/ssl.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/subprocess.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/thread.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/threading.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/threadpool.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/timeout.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/util.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/win32util.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
copying gevent/wsgi.py -> build/lib.macosx-10.7-x86_64-2.7/gevent
running build_ext
Running '/bin/sh /private/var/folders/4z/wrr232f910s5lk_j2zmn3y1m0000gn/T/nix-build-python2.7-gevent-1.0.2.drv-0/gevent-1.0.2/libev/configure > configure-output.txt' in /private/var/folders/4z/wrr232f910s5lk_j2zmn3y1m0000gn/T/nix-build-python2.7-gevent-1.0.2.drv-0/gevent-1.0.2/build/temp.macosx-10.7-x86_64-2.7/libev
building 'gevent.core' extension
creating build/temp.macosx-10.7-x86_64-2.7/gevent
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U__llvm__ -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.macosx-10.7-x86_64-2.7/libev -Ilibev -I/nix/store/m15dqpcqyvfh1hmfgx3wwh05ikgf8lsf-python-2.7.10/include/python2.7 -c gevent/gevent.core.c -o build/temp.macosx-10.7-x86_64-2.7/gevent/gevent.core.o
In file included from gevent/gevent.core.c:249:
In file included from gevent/libev.h:2:
libev/ev.c:483:48: warning: '/*' within block comment [-Wcomment]
/*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                               ^
libev/ev.c:1029:42: error: '_Noreturn' keyword must precede function declarator
  ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                         ^~~~~~~~~~~~
  _Noreturn 
libev/ev.c:832:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
libev/ev.c:1625:31: warning: 'extern' variable has an initializer [-Wextern-initializer]
  EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                              ^
libev/ev.c:1796:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);
      ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:1807:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);
  ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:1934:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);
      ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
In file included from gevent/gevent.core.c:249:
In file included from gevent/libev.h:2:
In file included from libev/ev.c:2484:
libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);
  ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
In file included from gevent/gevent.core.c:249:
In file included from gevent/libev.h:2:
In file included from libev/ev.c:2490:
libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);
      ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:3648:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                       ~~~~~~~~~~^~~~~~~~~~~~~ ~
libev/ev.c:3648:34: note: place parentheses around the '&' expression to silence this warning
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                 ^
                       (                      )
libev/ev.c:3687:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);
  ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4367:5: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);
    ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4407:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);
  ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4445:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_check *, checks, checkmax, checkcnt, EMPTY2);
  ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4592:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);
  ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4675:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);
  ^
libev/ev.c:1758:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
14 warnings and 1 error generated.
error: command 'clang' failed with exit status 1
builder for ‘/nix/store/c9jdfph8wmyjm83748bm99bb5djcdw4l-python2.7-gevent-1.0.2.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/hspbwcmfrdah3q72rxqj0qrjrfwxhi82-python2.7-dulwich-0.10.1a.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/pmcgjc1nn78vcdp7zs2300v5zzb8nkg3-mercurial-3.3.3.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/p354mipadfp533p05zwm84i5f3664wfq-nix-prefetch-scripts.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/z2kxfgmh5c9brsany50ky3fw2p7nxh9a-cabal2nix-20150531.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/z2kxfgmh5c9brsany50ky3fw2p7nxh9a-cabal2nix-20150531.drv’ failed
/Users/m/.nix-profile/bin/nix-shell: failed to build all dependencies
```

**Comment by lethalman** [comment]
Should be fixed by staging merge, 616ed6ee152ac16dd617fbbab2ee275e2e36d401

**Comment by aflatter** [comment]
Seems to work for me.

**Comment by boj** [comment]
This is occurring when I try to install cabal2nix.

**Comment by ecyrb** [comment]
In pkgs/top-level/python-packages.nix, I changed gevent's "platforms = platforms.linux;" to "platforms = platforms.unix;" and it seemed to work.

**Comment by dmalikov** [comment]
Actually, this issue is still reproducing for me. I'm on b2588ad

What should I check first?

**Comment by stillzhl** [comment]
@dmalikov try this

CFLAGS='-std=c99' pip install gevent

see https://github.com/gevent/gevent/issues/656

**Comment by gorjuce** [comment]
using the CFLAGS works, thanks.
