### ISSUE TITLE
System switching overwrites user-set autorepeat

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#9364]
I’ve had this occur some times now, that if you do a `nixos-rebuild switch` it resets your autorepeat speed (set in `displayManager.sessionCommands` with `xset r rate <int> <int>`).

**Comment by jb55** [comment]
This is constant source of annoyance for me as well, anyone have a good way to deal with this? Right now I `writeScript` my sessionCommands into a script that I re-run after rebuilds. Not ideal...

**Comment by Profpatsch** [comment]
When I last looked, I could not find what caused this. I have no idea how to find out, either.

**Comment by puffnfresh** [comment]
This is pretty annoying for me too. It's also annoying to use `sessionCommands`, can we write a NixOS configuration for the repeat speeds?

**Comment by puffnfresh** [comment]
I wrote a small service to set the rate, which seems to be working: https://github.com/puffnfresh/nixpkgs/commit/ea313026bc3d6fae622cae4b0ac42c5870ba539e

I'll run it for a while before submitting a pull request.

**Comment by Profpatsch** [comment]
It seems to work well.

Hm, autorepeat is always enabled, right? So do we need an `enable` option at all? It will just fall back to implicit X11 defaults then, which is hella implicit. We could leave that out and just set it to the X11 defaults.

**Comment by dezgeg** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=601853#c12 suggests that the X server could be started with e.g. `-ardelay 200 -arinterval 30` parameters. That'd probably be the best since I presume that would affect hotplugged keyboards as well.

**Comment by Profpatsch** [comment]
Does `xset` not change the settings for hotplugged keyboards? Because if not it is probably the safest way to apply that configuration (without having to restart the server and all dependencies/programs), right?

**Comment by dezgeg** [comment]
Yeah, `xset r` applies only to currently plugged in devices, and newly plugged in devices still get the initial repeat rate (`setxkbmap` and `xmodmap` work the same way).

X.Org sucks :/

**Comment by Profpatsch** [comment]
@puffnfresh I’ve been using your patches for quite a while now, and it’s been working flawlessly. I’d suggest we merge them and document that it can still be improved, because keyboards that are plugged in after the fact are probably not affected.

**Comment by puffnfresh** [comment]
@Profpatsch I had problems where it wouldn't work at startup - it only worked upon a switch. Have you noticed any problems around that?

**Comment by Profpatsch** [comment]
Hm, I reboot too seldomly. :P
let me try.

**Comment by Profpatsch** [comment]
You are right, here’s my log (reversed, sorry):

```
Feb 25 15:33:17 katara systemd[1]: autorepeat.service: Failed with result 'exit-code'.
Feb 25 15:33:17 katara systemd[1]: autorepeat.service: Unit entered failed state.
Feb 25 15:33:17 katara systemd[1]: Failed to start Keyboard autorepeat rate.
Feb 25 15:33:17 katara systemd[1]: autorepeat.service: Main process exited, code=exited, status=1/FAILURE
Feb 25 15:33:17 katara audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=autorepeat comm="systemd" exe="/nix/store/44pk6l5hcj0g97l1zifvkkxlyn9m7ijq-syst
Feb 25 15:33:17 katara xset[854]: /nix/store/pmw54459nrxwq333iay8jpxsiz9rw033-xset-1.2.3/bin/xset:  unable to open display ":0"
```

It’s the old xserver stuff. It needs the `DISPLAY` envvariable set.

**Comment by puffnfresh** [comment]
The service I wrote has:

```nix
{
   after = [ "display-manager.service" ];
}
```

So I don't know why it can't open the display. :disappointed:

**Comment by Profpatsch** [comment]
Wow, that was easier than expected. Thanks for the lead, @dezgeg.

**Comment by zimbatm** [comment]
I'm having a similar issue where `setxkbmap` options get reset.

**Comment by rasendubi** [comment]
(triage) still an issue?

I can't reproduce with `setxkbmap` + `nixos-rebuild`

**Comment by Profpatsch** [comment]
Hm, it looks like it was fixed! Will reopen should it happen again.

**Comment by Profpatsch** [comment]
Just happened again on switch. For reference, these things were restarted/reloaded:

```
removing user ‘avahi’
restarting systemd...
reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, sys-kernel-debug.mount
restarting the following units: polkit.service, sshd.service, systemd-logind.service
starting the following units: alsa-store.service, audit.service, cups.service, kmod-static-nodes.service, network-local-commands.service, network-manager.service, network-setup.service, nix-daemon.service, nscd.service, ntpd.service, rngd.service, rtkit-daemon.service, systemd-journald.service, systemd-modules-load.service, systemd-sysctl.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd.service, systemd-vconsole-setup.service, tlp.service, udisks2.service, upower.service, wpa_supplicant.service
the following new units were started: NetworkManager-dispatcher.service, systemd-hostnamed.service
```

**Comment by cstrahan** [comment]
Fixed by #19143

**Comment by Profpatsch** [comment]
Reopening, because it still overwrites user-set settings on switch. @cstrahan do you know what causes this?

**Comment by Profpatsch** [comment]
(triage) this still happens

**Comment by Profpatsch** [comment]
Still happening. I guess I learned to live with it.

**Comment by masaeedu** [comment]
This isn't actually fixed,would you mind just leaving this issue open @Profpatsch?
